### ISSUE TITLE
Feature request: Reset event

### ISSUE THREAD

**Issue by KrekoG** [mengxiong10/vue2-datepicker#101]
In my project I use vue2-datepicker to select a date-range filter. This works great, but I also have other components modifying the same filter. This leads to multiple sources of change. What would be a nice to have, is to emit an event when the component's reset button is clicked, as to have an easier time identifying there the update came from.

**Comment by mengxiong10** [comment]
you can replace v-model with 'value' and 'input'
``` html
    <date-picker lang="en"
      :value="value"
      @input="changeDate"/>
```
