### ISSUE TITLE
change fixed shortcuts 

### ISSUE THREAD

**Issue by 7ben** [mengxiong10/vue2-datepicker#105]
you know when mounted page, shortcuts is fixed 
ex) before 1hour => start, end time is current time, but when i will click date-picker input box after 2 hour,  this shortcuts is not right
i want to change fixed shortcuts when mx-datepicker-popup css changed display 
plz help me

**Comment by 7ben** [comment]
<<scriptscrip >
import DatePicker from 'vue2-datepicker'

export default {
  components: { DatePicker },
  data() {
    return {
      time1: '',
      time2: '',
      shortcuts: [
        {
          text: 'before 1 hour',
            start: new Date(Date.now() - 3600 * 1000 * 1),
            end: new Date(Date.now())
        }
      ]
    }
  }
}
</script>

<template>
  <div>
    <date-picker v-model="time1" :first-day-of-week="1"></date-picker>
    <date-picker v-model="time2" range :shortcuts="shortcuts"></date-picker>
  </div>
</template>

if i click shortcuts of before 1 hour after 3hour, date time is not right 
so i want to change shortcuts when i will click to input box (date-picker)

**Comment by mengxiong10** [comment]
You can listen the change event to change the shortcuts.
```html
<date-picker @change="changeShout"></date-picker>
  methods: {
    changeShortcuts (date) {
      this.shortcuts = [
        {
          text: 'before 1 hour',
          start: new Date(date.getTime() - 3600 * 1000),
          end: new Date(date.getTime())
        }
      ]
    }
  }

```

**Comment by 7ben** [comment]
thank you
