### ISSUE TITLE
Add types for Typescript

### ISSUE THREAD

**Issue by ChristianStornowski** [mengxiong10/vue2-datepicker#107]
I wrote my own vue2-datepicker.d.ts because I'm using vuejs with typescript. It is official supported. So could it be possible to add:

```
declare module "vue2-datepicker" {
    import {Component} from "vue/types/options";

    interface IShortcuts {
        text: string;
        start: Date;
        end: Date;
    }

    interface ITimePickerOptions {
        start: string;
        step: string;
        end: string;
    }

    interface ILang {
        days: Array<string>;
        months: Array<string>;
        pickers: Array<string>;
        placeholder: {
            date: string;
            dateRange: string;
        }
    }

    const Datepicker: Component<any, any, any, {
        type?: string;
        range?: boolean;
        format?: string;
        lang?: string | ILang;
        clearable?: boolean;
        confirm?: boolean;
        editable?: boolean;
        disabled?: boolean;
        placeholder?: string;
        width?: number|string;
        notBefore?: string|Date;
        notAfter?: string|Date;
        disabledDays?: Array<number|string>|((date: Date) => Array<Date>);
        shortcuts?: boolean|Array<IShortcuts>
        timePickerOptions?: Array<ITimePickerOptions>|(() => Array<ITimePickerOptions>);
        minuteStep?: number;
        firstDayOfWeek?: number;
        inputClass?: string;
        inputName?: string;
        confirmText?: string;
        rangeSeparator?: string;
    }>;
    export = Datepicker;
}
```
as an official typescript definition for this project?

**Comment by mengxiong10** [comment]
Don't understand it too much. 
There is no plan to use ts.

**Comment by ChristianStornowski** [comment]
My problem with no types is this import statement:

```
<template>
    ...
</template>

<script lang="ts">
    import DatePicker from "vue2-datepicker";
    import Vue from "vue";

    export default Vue.extend({
        name: "MyComponent"
    });
</script>

<style lang="scss">
    ...
</style>

```

If i have no types for vue2-datepicker i get a typescript compiler warning.

**Comment by ChristianStornowski** [comment]
That's not possible because typescript needs node_modules to resolve other types from other libraries.

**Comment by mengxiong10** [comment]
You can exclude /node_modules\/vue2-datepicker/

**Comment by mengxiong10** [comment]
fyi
```js
{
  test: /\.tsx?$/,
  loader: 'ts-loader',
  exclude: /node_modules/,
  options: {
    appendTsSuffixTo: [/\.vue$/],
  }
}
```

**Comment by ChristianStornowski** [comment]
It's not the intension of typescript. I could use @ts-ignore. But it would be nice of you could add this type definition. If you don't like this, I could create a subrepo in https://github.com/DefinitelyTyped/DefinitelyTyped and everybody can install tjose types if they want to use them.

**Comment by mengxiong10** [comment]
I don't good at typescript yet. I need to spend time learning it.

If you can do that it's good.

**Comment by MartinYounghoonKim** [comment]
@ChristianStornowski 
I'v spent a lot of time to find vue2-datepicker.d.ts, and finally I found yours. 
Thanks.

**Comment by Finrod927** [comment]
Thanks @ChristianStornowski for the types :)

I was wondering why you did set some attributes to mandatory in the `Lang` interface, as they all have default values?

I would like to use this interface to define translated labels, but without redefining all other values and functions.

**Comment by ChristianStornowski** [comment]
Here are my current types https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vue2-datepicker/index.d.ts for vue2-datepicker.
