### ISSUE TITLE
Span in shortcuts

### ISSUE THREAD

**Issue by Julia-Lavrova** [mengxiong10/vue2-datepicker#110]
Hi! Thank you for this lib! It is great! 
But I have some problems.
Why did you use `span` element in shortcuts? It will be better to use  `<button type="button"></button>` 

I can make PR with changing.

**Comment by mengxiong10** [comment]
^_^, you are right.
I'll change next version.
You can change it by slot 'header'

**Comment by Julia-Lavrova** [comment]
Cool! Also, you use <td> as a date. It isn't correct too. Clickable element needs using a clickable tag. 
It will be good if you will use button in td tag

**Comment by mengxiong10** [comment]
I change the shortcus element `span` to `button`
