### ISSUE TITLE
Period in input not translated

### ISSUE THREAD

**Issue by Julia-Lavrova** [mengxiong10/vue2-datepicker#111]
I have one more problem. I use lang attribute, but period does not translate? I think it is not correct.  May be I do something wrong? 
  
![image](https://user-images.githubusercontent.com/18362544/41772767-9dbd8b78-7622-11e8-81c6-25d790044c5b.png)

**Comment by mengxiong10** [comment]
the lang don't translate the format text.
I can open an interface to translate it by yourself.

**Comment by Julia-Lavrova** [comment]
Why not? You can translate date in calendars, but you can't translate date in input. Sounds weird.

**Comment by mengxiong10** [comment]
You are right. I'll translate it default.

**Comment by Julia-Lavrova** [comment]
Yep! Thank you!

**Comment by Julia-Lavrova** [comment]
When can I use this updates? I am waiting for them so much :)

**Comment by mengxiong10** [comment]
In v2.x. I use the 'fecha' to format date.
The project has merged some default language.
If I translate it  will make everyone add unnecessary files.
You can translate it temporarily.
Next I will separate the translation file and  file.

```js
import DatePicker from 'vue2-datepicker'

// Customize by yourself
DatePicker.fecha.i18n.monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
```

```js
// the feach i18n
fecha.i18n = {
	dayNamesShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat'],
	dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
	monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
	monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
	amPm: ['am', 'pm'],
	// D is the day of the month, function returns something like...  3rd or 11th
	DoFn: function (D) {
		return D + [ 'th', 'st', 'nd', 'rd' ][ D % 10 > 3 ? 0 : (D - D % 10 !== 10) * D % 10 ];
    }
}

```

**Comment by Julia-Lavrova** [comment]
I like it :) But I think, that it is not simple. And I cannot use this updates soon. :(

**Comment by mengxiong10** [comment]
same as #261.
v3.0 in default.
