### ISSUE TITLE
Not seeing the datePicker at all - What is missing?

### ISSUE THREAD

**Issue by AngularOne** [mengxiong10/vue2-datepicker#112]
I have download the all project, but for some reason opening the input will not show any date to select. Only the month/year is displayed. What I did wrong?

Also, there are files written as Vue component, but are .js files and not .vue files (date.js, month.js ...).
Why is that?

Did anyone has the same problem?

![ps](https://user-images.githubusercontent.com/7720825/41783444-8984c1c6-7645-11e8-90ad-8f33efeeb4a5.png)

**Comment by mengxiong10** [comment]
I use jsx in the project.
Show me the error info.Maybe I can help you.
