### ISSUE TITLE
scope-slot is missing

### ISSUE THREAD

**Issue by AngularOne** [mengxiong10/vue2-datepicker#114]
if I add a slot template with my own confirm button for example, I can't run the confirm methods.
If you add scope-slot we will.

**Comment by mengxiong10** [comment]
Thanks for the suggestion, it has been added in v2.0.2

```html
 <template slot="footer" slot-scope="{confirm}">
     <button @click="confirm">OK</button>
 </template>

```

**Comment by AngularOne** [comment]
Thanks for adding it, but I think the footer need access also to "confirmText". What about other props or merhods you may want to run from your own footer or header. I'm adding "ref" for this to work, but the scope slot is cleaner approch

**Comment by mengxiong10** [comment]
Just replace the prop `confirmText` with data
```html
<template slot="footer" slot-scope="{confirm}">
     <button @click="confirm">{{confirmText}}</button>
 </template>

<script>
export default {
  data () {
     return {
        confirmText: ''
     }
  }
}
<script>

```

**Comment by AngularOne** [comment]
For some reason this is not working:

```
 <template slot="footer" slot-scope="{confirm}">
     <button @click="confirm">OK</button>
 </template>
```

```
> vue.js:584 [Vue warn]: Invalid handler for event "click": got undefined
> 
> found in
```
