### ISSUE TITLE
How to remove the delete/clear (x) icon?

### ISSUE THREAD

**Issue by AngularOne** [mengxiong10/vue2-datepicker#115]
Is there a way not to allow delete/clear selection, meaning there will be always a selection, never empty.

**Comment by AngularOne** [comment]
clearable="false"

**Comment by ronnievisser** [comment]
this returns a warning

Invalid prop: type check failed for prop "clearable". Expected Boolean, got String.

**Comment by FPTSonPM3** [comment]
> @ronnievisser
> v-bind:clearable="false"

thanks

**Comment by mchelombitkopax8** [comment]
> @ronnievisser v-bind:clearable="false"

thanks a lot

**Comment by MarcinPasynczuk** [comment]
> @ronnievisser v-bind:clearable="false"

Thanks.
