### ISSUE TITLE
Selecting shortcut like "Last 7 days", you will get range of date and time when the page loaded

### ISSUE THREAD

**Issue by AngularOne** [mengxiong10/vue2-datepicker#118]
Think you loaded the page yesterday, and now using the date/time picker, the shortcut will not get you the current date or time, it is the date and time when page loaded.

Can this be fixed fast?

Another strange thing  is when you select shourtcut, the date/time selected updated in the input field above, although  you did not click on "CONFIRM/OK" button yet. Clicking on "CANCEL" will not cancel this change.

**Comment by mengxiong10** [comment]
v2.0.3 fixed it.
And the confirm don't effect shortcuts.
