### ISSUE TITLE
wrong date returned

### ISSUE THREAD

**Issue by ronnievisser** [mengxiong10/vue2-datepicker#119]
Hi,

I have the following code 

<date-picker v-model="selected_date" lang="en" v-bind:clearable="false"></date-picker>

when I select a date, let's say tomorrow, it returns 2018-06-27T22:00:00.000Z while it should be 2018-06-28 so it's basically a day behind (or some hours).

Is there anything I can do about this?

thanks

**Comment by mengxiong10** [comment]
It's a timezone problem.
You get a locale date.

**Comment by ronnievisser** [comment]
is there anything i can do to get this work correctly?

**Comment by mengxiong10** [comment]
It's right. 
The string 2018-06-27T22:00:00.000Z is a UTC date.
`getTimezoneOffset()`  returns the time zone difference.

```html
<date-picker v-model="value"></date-picker>
```
```js
// UTC time
value.toISOString()
// local time
value.toLocaleString()
// Convert to UTC
new Date(value.getTime() - value.getTimezoneOffset() * 60 * 1000)
```

**Comment by irufus** [comment]
By default the `format` property defaults to `YYYY-MM-DD`. Just specify your `value-type` property to `format`

```html
<date-picker v-model="value" value-type="format"></date-picker>
```
