### ISSUE TITLE
Invalid Date in fecha.format

### ISSUE THREAD

**Issue by mdeprezzo** [mengxiong10/vue2-datepicker#120]
In which way, i must to pass the value stored in my db to the component in order to be a valid date ?

**Comment by vegenera** [comment]
Try this, If you use **unixtime**(maybe works and for others) format:

```javascript
this.datepicker_model = new Date(this.db_unixtime * 1000);
```

**Comment by mengxiong10** [comment]
What's your value in db.

**Comment by mdeprezzo** [comment]
simple timestamp field, something like 2018-06-30 22:29:00
