### ISSUE TITLE
manually entering a date does not format using the format property

### ISSUE THREAD

**Issue by robfromcornell** [mengxiong10/vue2-datepicker#121]
`<date-picker v-model="myDate" lang="en" editable format="MM/DD/YYYY"></date-picker>`

works fine for clicking and selecting a date, but if I try to type in 07/03/2018 manually, the date converts to 06/30/1900.  It doesn't seem to take my above format into account.

I am using version 1.9.8.

**Comment by mengxiong10** [comment]
Please upgrade to 2.x, it is compatible with your code.

**Comment by robfromcornell** [comment]
After upgrading to 2.0.3, I can now manually type in dates. However, I now get a new error when the value in myDate above is in the format of '07/03/2018'.  It does works if there is no initial value and myDate = '' or null. The error is:

Invalid Date in fecha.format

**Comment by mengxiong10** [comment]
It's a bug when value is a string.
I fixed it in v2.0.4
