### ISSUE TITLE
Using the datepicker calendar to display a date

### ISSUE THREAD

**Issue by andrewhl** [mengxiong10/vue2-datepicker#122]
Is it possible to have the calendar display the date, without the input, in a readonly way? In other words, I have a date I want to display to the user, and I'd like to display it AS a calendar, rather than a date input field or a date string. But I don't want the user to be able to edit the date. 

I'm not sure how to do this with this component.

Thank you!

**Comment by mengxiong10** [comment]
set `editable` false
```
<date-picker v-model="time" :editable="false"></date-picker>
```
