### ISSUE TITLE
Formated v-model value

### ISSUE THREAD

**Issue by VitaliyM24** [mengxiong10/vue2-datepicker#129]
Is it possbile to make v-model return value in YYYY-MM-DD instead of Wed Mar 25 2015 02:00:00 GMT+0200 ?

**Comment by mengxiong10** [comment]
format="MMM DD YYYY HH:mm:ss 'GMT'ZZ"

**Comment by mengxiong10** [comment]
https://github.com/taylorhakes/fecha

**Comment by VitaliyM24** [comment]
Attribute formate, formatting only "input placeholder" but not the value of v-model.
