### ISSUE TITLE
New feature: month / year picker

### ISSUE THREAD

**Issue by dermansi** [mengxiong10/vue2-datepicker#130]
Hey,

I have some use cases where I want to select just a month and a year, but no day at all. Is it possible to implement a prop which allows me to skip the selection of days, like I can already with the selection of time?

Someone already made a pull request for this kind of use case: #125 

Thank you and kind regards
dermansi

**Comment by mengxiong10** [comment]
v2.1.0 added it

**Comment by jonalxh** [comment]
How to achieve it?

**Comment by mengxiong10** [comment]
@jonalxh https://mengxiong10.github.io/vue2-datepicker/index.html
type="year"
