### ISSUE TITLE
v-model="value"里设置的默认value在ios机器上的常见浏览器失效

### ISSUE THREAD

**Issue by crydear** [mengxiong10/vue2-datepicker#132]
你好，这个时间框里，我设置的默认值为当前时间，在安卓设备均显示正常，但是在ios设备上，用了几款常见的浏览器测试，发现这个设定的值没有生效

**Comment by mengxiong10** [comment]
可以展示下你的代码么

**Comment by crydear** [comment]
<template>
<date-picker v-model="value" type="datetime" :lang="lang" format="YYYY-MM-DD hh:mm a" @change="Datechange" confirm :not-before='Getdataa()'></date-picker>
</template>
export default {
data() {
    return {
      value: null,
}
}
mounted() {
    this.value = this.Getdate();
}
this.Getdate()是一个获取当前时间的方法，return出来一个值，这里就不附上来了

**Comment by mengxiong10** [comment]
你可以` this.value = new Date()` 看看

**Comment by crydear** [comment]
哦，我不是这个意思，我的意思是，我们写法都没问题，只是兼容性好像不大支持ios系统的浏览器，我在pc端调试和安卓手机上，这个value的值都正常显示出来了，但是在ios的浏览器上，不显示

**Comment by mengxiong10** [comment]
我用ios浏览器测试了我的demo页面，是可以显示。你的不显示只是初始值不显示还是整个功能不能用？
![tim 20180727180134](https://user-images.githubusercontent.com/14135808/43314998-3c67050a-91c7-11e8-9404-9205c1ef07c6.jpg)

**Comment by mengxiong10** [comment]
可能是你的value的字符串格式`new Date()` chrome支持Safari不支持，
