### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by RauppRafael** [mengxiong10/vue2-datepicker#138]
The input's autocomplete attr should be set to false to prevent this behaviour:

![bug](https://user-images.githubusercontent.com/14304799/43680555-f0fb569a-9813-11e8-9eb2-ea28e8e05384.png)

**Comment by mengxiong10** [comment]
tks. V2.2.0 set the autocomplete off

**Comment by ShmidtAlex** [comment]
Because of google remove autocomplete prop from API, it doesn't work at all. Every time when user put cursor into input, google chrome shows autocomplete form.
