### ISSUE TITLE
Trigger the datepicker opening with a condition

### ISSUE THREAD

**Issue by DrJaxx** [mengxiong10/vue2-datepicker#144]
Hello !

I was wondering if it was possible to trigger the opening of the date-picker manually, with a prop or a function.

Thanks in advance

François

**Comment by mengxiong10** [comment]
```html
<date-picker ref="datepicker"  v-model="value1" lang="en" ></date-picker>
```

```js
export default {
  methods: {
    open () {
      this.$refs.datepicker.showPopup()
    }
  }
}

```

**Comment by DrJaxx** [comment]
Thank you ! 

Maybe should you add it to the doc, I think it is not displayed

**Comment by kcgirondeveloper** [comment]
HI @mengxiong10 , this is working when calendar is outside a v-for. But when it is inside, a v-for loop, an error appears

Object doesn't support property or method 'showPopup'

**Comment by mengxiong10** [comment]
@kcgirondeveloper  You can use `open` in v3.x.   https://mengxiong10.github.io/vue2-datepicker/index.html#ControlOpen
