### ISSUE TITLE
Set Format

### ISSUE THREAD

**Issue by George2215** [mengxiong10/vue2-datepicker#145]
how I can set format (YYYY-MM-DD) in the v-model of the component?

my component
<date-picker  v-model="dob" lang="es" type="date">   </date-picker>

my v-model receive this
dob:Tue Aug 21 2018 00:00:00 GMT-0500

I want to get this:
dob: 2018-08-21

I appreciate the help...

**Comment by mengxiong10** [comment]
The v-model value is Date Object.
You can use a computed value.
```js
import DatePicker from 'vue2-datepicker'

export default {
  data () {
    return {
      date: ''
    }
  },
  computed: {
    dateText () {
      return this.date ? DatePicker.methods.stringify(this.date, 'YYYY-MM-DD') : ''
    }
  }
}
```

**Comment by George2215** [comment]
thank you
