### ISSUE TITLE
Unable to handle any datepicker events

### ISSUE THREAD

**Issue by renelopez** [mengxiong10/vue2-datepicker#146]
Hi!
I have this datepicker declaration in my code and Im unable to capture neither change or input-error events from the control. Is there any issue on it or an example that I can look around?

`<date-picker v-model="expiryDate" lang="en"
                               :first-day-of-week="1"
                               class="datepicker-nocontrols"
                               :not-before="notBefore"
                               :not-after="notAfter"
                               :input-class="expiryDateClass"
                               @input-error="dateChanged">
                  </date-picker>
`

**Comment by bribar** [comment]
Does expiryDate exist and have a value when created?

**Comment by mengxiong10** [comment]
The `input-error` event just be fired by the user input.
