### ISSUE TITLE
Input text is not updated on error

### ISSUE THREAD

**Issue by WisienDot** [mengxiong10/vue2-datepicker#149]
When the calendar pop-up is hidden and user type the wrong date then the text is not updated (v-model != input value). 

For example:
With option :not-after="new Date()" I can enter the date from future. 
![image](https://user-images.githubusercontent.com/7932803/44989685-e5c65f80-af8e-11e8-8e4d-0e598aee7a07.png)

When the calendar pop-up is visible then the text is updated to the previous value.

**Comment by mengxiong10** [comment]
Yes, Because the input value is wrong, so the date don't update.
It'll trigger an `input-error` event when the input value is wrong.
You can listen the event to do something.

**Comment by WisienDot** [comment]
Hi and thanks for your answer.
Isn't it a bit inconsistent? Wrong value gets updated only when the popup is opened and it remains unchanged when it's closed.

I already tried to implement a workaround using "input-error" event to update the text via "value" prop, but unfortunately without any success (yet 😄 ).

**Comment by mengxiong10** [comment]
In fact, the Date value don't update when the popup is opened, just the input text updated.
It's only updated when the input element `change` event is triggered.
If you want change the value when the input text is error.
https://jsfiddle.net/mengxiong/znvc5am2/9/

**Comment by WisienDot** [comment]
I think it's just wrong to have different data in the model and in the input. I still think you should keep those values in sync. 
![image](https://user-images.githubusercontent.com/7932803/45018780-0b08ab80-b02b-11e8-90c8-1b620232fa0f.png)

My current ugly workaround:
`onError(){
            let datePicker = this.$children.find((item) => {
                return item.$options._componentTag === 'date-picker'
            });
            this.$set(datePicker, 'userInput', this.yearAndMonthFormatted);
}`

**Comment by bubgdgnanh** [comment]
@mengxiong10 
Please let me know if you can how to change the value when the input text is error.
I cannot access your link https://jsfiddle.net/mengxiong/znvc5am2/9/.

I try as below but doesn't resolve.
event.target.value = "";
this.$emit('input', null);

Thank you so much.

**Comment by mengxiong10** [comment]
@bubgdgnanh 
```html
 <date-picker :not-after="new Date()" v-model="value" @input-error="handleInputError" />
```
```js
export default {
  components: { DatePicker },
  data() {
    return {
      today: new Date(),
      value: ''
    };
  },
  methods: {
   // text is the input value
    handleInputError (text) {
       this.value = ''
    }
  }
};

```
