### ISSUE TITLE
Global options setting

### ISSUE THREAD

**Issue by a0902m51** [mengxiong10/vue2-datepicker#150]
Hi!
I use your package as a plugin in my app. Then I need to setup global options for all input after.
But I can't find anything guide me.
Please guide me to make it!
Thanks

**Comment by mengxiong10** [comment]
What options do you want to set?
If you want to do something after all `change`  event.
You need to change the code inner.
```js
import DatePicker from 'vue2-datepicker'

DatePicker.methods.updateDate = function() {
  DatePicker.methods.updateDate();
  // do your things
}

```

**Comment by a0902m51** [comment]
Longtime wait for a reply....

**Comment by mengxiong10** [comment]
```js
import DatePicker from 'vue2-datepicker'

DatePicker.props.format="MM-YYYY"

```

**Comment by oscar21** [comment]
This works for me:

DatePicker.props.lang = process.env.VUE_APP_I18N_LOCALE;//es
DatePicker.props.format.default = Constants.General.DATE_FORMAT;//DD-MM-YYYY
Vue.component('date-picker', DatePicker);

**Comment by acirinelli** [comment]
This works for me as well, slightly changed:
> DatePicker.props.format.default = "MM-DD-YYYY"
> Vue.component('date-picker', DatePicker); // or Vue.use(DatePicker)
