### ISSUE TITLE
Date Issue with different same time zone

### ISSUE THREAD

**Issue by Hrddk** [mengxiong10/vue2-datepicker#152]
Date `10 Sept, 2018 06:00 AM` with Timezone `UTC-08:00 (Pacific Time (US & Canada)) or UTC-07:00 (Arizona)` automatically changes to day before to `9 Sept, 2018`.

Date `10 Sept, 2018 07:00 AM ` with Timezone UTC-08:00  remains same `10 Sept, 2018`.

I'm not getting why this happening. please help me on this.

**Comment by arvenom** [comment]
got the same issue and an example how to fix it would be nice :)

**Comment by mengxiong10** [comment]
@arvenom show your code plz.

**Comment by mengxiong10** [comment]
timezone issue
ref: #232 #233
