### ISSUE TITLE
Time picker with steps: can it close the popup with a click?

### ISSUE THREAD

**Issue by kgusihin** [mengxiong10/vue2-datepicker#154]
Hello, is there a way to close the timepicker just like the datepicker does, when the option with steps is selected? It would be nice to pick time without having to close the popup with an OK button or a click outside?

**Comment by mengxiong10** [comment]
It's a good idea.  When used the `time-picker-options`, it should be closed.

**Comment by mengxiong10** [comment]
v2.4.3

**Comment by raimund-schluessler** [comment]
When you don't use `time-picker-options` it could also be closed after selecting both hours and minutes (or seconds as well if available).

**Comment by KonradDeskiewicz** [comment]
+1 for closing after all lowest granulation time element is clicked (minutes or seconds depends on options)

**Comment by HapLifeMan** [comment]
That could be a nice feature ✌🏻
