### ISSUE TITLE
Time in dropdown is not formatting

### ISSUE THREAD

**Issue by deep0410** [mengxiong10/vue2-datepicker#155]
### in the demo you have used this..
```
 <date-picker v-model="value4" lang="en" type="datetime" format="YYYY-MM-DD hh:mm:ss a" :time-picker-options="{ start: '00:00', step: '00:30', end: '23:30' }"></date-picker>
```

### I am trying to use this
`<date-picker
                                        v-model="startTime"
                                        lang="en"
                                        type="time"
                                        format="hh:mm a"
                                        width="inherit"
                                        placeholder="Select Time"
                                        :time-picker-options="{
                                                               start: '00:00',
                                                               step: '00:30',
                                                               end: '23:30'
                                                               }"
                                    >
                                    </date-picker>`

### but it doesn't give me this format:
![toshowwwwwwww](https://user-images.githubusercontent.com/33726731/45511307-a6f09080-b76a-11e8-9b4e-7adb4b7e855e.PNG)

### it gives me this instead
![image](https://user-images.githubusercontent.com/33726731/45511409-ec14c280-b76a-11e8-8014-5e50713b5297.png)

**Comment by mengxiong10** [comment]
Please upgrade to the latest version
