### ISSUE TITLE
no way to change the header

### ISSUE THREAD

**Issue by deep0410** [mengxiong10/vue2-datepicker#157]
![image](https://user-images.githubusercontent.com/33726731/45555740-9b06dc00-b807-11e8-9adb-85632460dd66.png)

`<date-picker
                                        v-model="startTime"
                                        lang="en"
                                        type="time"
                                        format="hh:mm a"
                                        width="inherit"
                                        placeholder="Select Time"
                                        :time-picker-options="{
                                                               start: '00:00',
                                                               step: '00:30',
                                                               end: '23:30'
                                                               }"
                                        date-format="Select Time"
                                    >
                                    </date-picker>`

Last time I forgot to mention that this is some great work. I love it.

I just wanted to know if there was a way to change the header

**Comment by mengxiong10** [comment]
Change the source code.
```js
import DatePicker from 'vue2-datepicker'

const calendar = DatePicker.components.CalendarPanel

calendar.computed.timeHeader = function () {
  return 'your code'
}
```

**Comment by deep0410** [comment]
```
const calendar = DatePicker.components.CalendarPanel

calendar.computed.timeHeader = function () {
  return 'your code'
}
```
I put that mounted() property for vue and it seems to not have any effect. I am on v2.4.1

**Comment by mengxiong10** [comment]
Not in the mouted.
```js
import DatePicker from 'vue2-datepicker'

const calendar = DatePicker.components.CalendarPanel

calendar.computed.timeHeader = function () {
  return 'your code'
}

```

**Comment by mitjarobic** [comment]
Does this still work? I tried:
```
const { CalendarPanel } = DatePicker;
CalendarPanel.computed.timeHeader = function () {
    return 'your code'
}
```
