### ISSUE TITLE
Click handler when picking YYYY-MM

### ISSUE THREAD

**Issue by titpetric** [mengxiong10/vue2-datepicker#158]
I would love to have a click handler when navigating between months or years. I need to issue AJAX calls to some API that will return me enabled days in the chosen month. There is already a `disabled-days` function that lets me do this, but I can't hook into some event that would let me update the values responsively, because no click event is exposed as a prop.

Also, the disabled days function is called for disabling months or years, but there's no additional info available in the callback (I want to disable days, but there's no difference between 2018/01/01 for day or month or year check). Could you add a parameter for the type of check?

**Comment by mengxiong10** [comment]
Your needs are very special, you can modify the source code to do it.
```js
import DatePicker from 'vue2-datepicker'

const calendar = DatePicker.components.CalendarPanel

// change the selectYear methods 
calendar.methods.selectYear = function (year) {
  this.changeCalendarYear(year)
 // request your data
  Promise.resolve().then(() => {
    this.showPanelMonth()
  })
}


```

**Comment by titpetric** [comment]
I used [vuejs-datepicker](https://github.com/charliekassel/vuejs-datepicker) which provides a wide set of events out of the box, and doesn't require hacks like the above extension. Thanks for the effort however :)
