### ISSUE TITLE
How do I init it opened? 

### ISSUE THREAD

**Issue by dbelintani** [mengxiong10/vue2-datepicker#159]
Hi!
I'm kinda beginner in vueJs, but I am immersed myself in reading and testing codes in the last hours.
I loved your component and how you wrote it. It have been really usefull debugging it. 

Is that possible to open a view component and see both calendars opened, without clicking in the input? I used to do that in the old jQuery justing giving focus on the input.

I tried some methods such as 'showPopup()', but the console says it's not a method/functions. I'm still trying to understand exactly how this inheritance of index.js and calendar.js works and why I could not invoke these events.

Thank you,

**Comment by mengxiong10** [comment]
<date-picker ref="datepicker" />
this.refs.datepicker.showPopup()
