### ISSUE TITLE
Is there any way to set the first day of week?

### ISSUE THREAD

**Issue by TebanCL** [mengxiong10/vue2-datepicker#16]
By default the first day it's "Sunday", but Is there any way to set the first day of week to "Monday"?

**Comment by mengxiong10** [comment]
Added a prop 'first-day-of-week', you can set it to 1
```
<date-picker v-model="time" :first-day-of-week="1"></date-picker>
```

**Comment by karimation** [comment]
The first-day-of-week is not working, 
There is not first-day-of-week props in the index.vue
I think this should be fixed ASAP.
https://github.com/mengxiong10/vue2-datepicker/blob/master/src/index.vue

**Comment by mengxiong10** [comment]
@karimation 
It's working by the `$attrs` not `prop`. Upgrade your `vue` version >=2.4.0

**Comment by decadence** [comment]
@mengxiong10 this doesn't work. Sunday is first day of week whatever `first-day-of-week` is.

```html
<date-picker v-model="request.creation_date"
             value-type="format"
             format="YYYY-MM-DD HH:mm:ss"
             type="datetime"
             :first-day-of-week="1"
>
</date-picker>
```

What am I doing wrong?

**Comment by decadence** [comment]
Got it. Need to

```javascript
import ru from 'vue2-datepicker/locale/ru';
```

And pass it to lang prop.
