### ISSUE TITLE
CalendarPanel props not being set in render function

### ISSUE THREAD

**Issue by roelVerdonschot** [mengxiong10/vue2-datepicker#160]
I'm using the datepicker via the render function but the firstDayOfWeek prop is not being passed to the CalendarPanel. 

My render function:
`return h(
                'date-picker',
                {
                    props: {
                        value: this.date,
                        lang: this.lang,
                        firstDayOfWeek: 1,
                        // 'first-day-of-week': 1,
                        format: 'DD-MM-YYYY',
                        type: 'date'
                    },
                    on: {
                        input: event => {
                            console.log(event)
                            this.date = event
                        }
                    },
                    class: {
                        'is-invalid': this.state === false
                    },
                }
            )`

**Comment by mengxiong10** [comment]
You should set the `firstDayOfWeek` to `attrs`.
```js
{
   attrs: {
    'first-day-of-week': 1
  }
}
```

**Comment by roelVerdonschot** [comment]
Thx for the feedback, it's working now!
