### ISSUE TITLE
Change day's title

### ISSUE THREAD

**Issue by CovaliIrina** [mengxiong10/vue2-datepicker#161]
Hi!
First of all thank you a lot for awesome job!

As I still need to add little extra customization to the component, could you please advise if there is a possibility to change default date's title?

![title](https://user-images.githubusercontent.com/43413234/45759178-01d52c80-bc30-11e8-890c-6d42e031ec2b.png)

Thank you in advance!

**Comment by mengxiong10** [comment]
You can use the prop `format` or `date-format`

**Comment by CovaliIrina** [comment]
I need to change the title for specific dates, for example disabled weekends will show `weekend` instead of a date on hover. Is it possible?

**Comment by mengxiong10** [comment]
Unless you modify the default method.
```js
import DatePicker from 'vue2-datepicker'

DatePicker.components.CalendarPanel.components.PanelDate.methods.getCellTitle = function ({ year, month, day }) {
  return 'weekend'
}
```

**Comment by CovaliIrina** [comment]
It worked! Thank you!

**Comment by rrd108** [comment]
Is it still available?

**Comment by mengxiong10** [comment]
@rrd108 
You can simply set `title-format` to achieve it in v3.x.
I'll update the docs.
```
<date-picker title-format="YYYY/MM/DD">
```
