### ISSUE TITLE
Is there a way to show only certain months when type="month"

### ISSUE THREAD

**Issue by vvtense** [mengxiong10/vue2-datepicker#162]
I have a datepicker with type="month" and range as pictured below

![monthpicker](https://user-images.githubusercontent.com/8485457/45840653-89c93e00-bce5-11e8-90ba-2c7b758e2bf2.png)

Is there a way to only enable quarter months, i.e.: I only wish to enable:

- Mar
- Jun
- Sep
- Dec

everything else should be **disabled**. I cannot figure out how to accomplish this in the current version of vue2-datepicker. Any help would be appreciated, thank you.

**Comment by mengxiong10** [comment]
use the `disabledDays`
```html
<date-picker v-model="value" type="month" :disabledDays="disabledDays" format="YYYY-MM" ></date-picker>
```

```js
methods: {
    disabledDays (date) {
      const month = new Date(date).getMonth() + 1
      if (month % 3 === 0) {
        return false
      }
      return true
    }
}
```

**Comment by vvtense** [comment]
Thank you very much. This is an excellent library, by the way. Very useful and well-made
