### ISSUE TITLE
Always set datepicker to open downwards

### ISSUE THREAD

**Issue by chippison** [mengxiong10/vue2-datepicker#163]
Would it be possible to always set the datepicker to open downwards?

Currently it depends on the amount of space on top or bottom... If space on top is greater than bottom, it opens up... But I want to let it open downwrds always...

Thanks

**Comment by mengxiong10** [comment]
ref #18

**Comment by augnustin** [comment]
Shouldn't there be a prop `position`, which defaults to `auto` with the current behavior but can be overridden and set programmatically?

**Comment by mengxiong10** [comment]
@augnustin  use the `popup-style`
```html

<date-picker   :popup-style="{ top: 0; left: 0 }"    />
```

**Comment by augnustin** [comment]
Doesn't work for me as the popup appears at the top left of my screen.

It appears `append-to-body` is set to `true` by default, I tried to change this to `false`, without success.

Anyway, a `position` prop would be much simpler and elegant to handle.

**Comment by mengxiong10** [comment]
@augnustin 
```html
<date-picker v-model="value" :popup-style="{ top: '100%', left: 0}" :append-to-body="false" />
```

**Comment by kkauper** [comment]
> @augnustin
> 
> ```
> <date-picker v-model="value" :popup-style="{ top: '100%', left: 0}" :append-to-body="false" />
> ```

This worked for me perfectly.

**Comment by maximkompaneev** [comment]
@mengxiong10 
when I set append-to-body: false clicking on date does not close the date panels (it actually triggers close and open event, instead of just closing) 
is this intentional and is there a way to avoid it ?

**Comment by mengxiong10** [comment]
> @mengxiong10 when I set append-to-body: false clicking on date does not close the date panels (it actually triggers close and open event, instead of just closing) is this intentional and is there a way to avoid it ?

`append-to-body: false` will not affect  `open`. 
There may be a problem with the click event
