### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by Sakthi002** [mengxiong10/vue2-datepicker#165]
it is showing "[Vue warn]: Error in nextTick: "TypeError: Object doesn't support property or method 'from'"
![date](https://user-images.githubusercontent.com/35330401/45943615-a8407980-c004-11e8-8bc0-2c3d0248e40a.PNG)
"

**Comment by mengxiong10** [comment]
Yes, It's a problem. 
I fixed it in v2.4.2
