### ISSUE TITLE
In time mode hours change without click

### ISSUE THREAD

**Issue by mxmvshnvsk** [mengxiong10/vue2-datepicker#168]
When I change value of minutes or seconds, value of hours change too. If I understand this issue right, you set it with Date() and at this moment hours set too by my timezone.
For example I have default value 00:00:00 and timezone +4. When I click on minutes, then hours change to 4.

**Comment by bubgdgnanh** [comment]
Dear mengxiong10, I got this problem but don't know to resolve it although I read your comment.

If you can, please let me know more detail.
Thank you so much.

**Comment by mengxiong10** [comment]
fyi
https://jsfiddle.net/mengxiong/hmu75ay2/

**Comment by mengxiong10** [comment]
It's a bug. I fixed it in v2.10.2. Thanks

**Comment by bubgdgnanh** [comment]
Thank you so much for quickly supports.

It works well.
