### ISSUE TITLE
Wrong format input

### ISSUE THREAD

**Issue by AlexanderBelkevich** [mengxiong10/vue2-datepicker#170]
I have a variable. Format 'DD.MM.YYYY HH:mm', but calendar automatical change in format 'MM.DD.YYYY HH:mm'
http://prntscr.com/kzok9v
http://prntscr.com/kzokdh
http://prntscr.com/kzokju

**Comment by mengxiong10** [comment]
Can you show your code detail.

Can't reproduce

**Comment by AlexanderBelkevich** [comment]
This happens when using the moment.
newPointDate = moment().format("DD.MM.YYYY HH:mm") // 04.10.2018

<date-picker :lang="propsCalendar.lang" :minute-step="1" v-model="data.newPointDate" type="datetime" confirm  :not-after="new Date()" use-utc="true" format="DD.MM.YYYY HH:mm" input-class="monitoring-element-add-element__input"></date-picker> // 10.04.2018

**Comment by mengxiong10** [comment]
The `v-model` value should be a Date Object.
If you need a String.
You can use a computed value.
I'll add a prop feature to select the value type later.

**Comment by donnie24** [comment]
Hi, any solution for this issue? I've encounter same issue. thanks

**Comment by mengxiong10** [comment]
use it like this


```html
<date-picker :lang="propsCalendar.lang" :minute-step="1" v-model="date" type="datetime" confirm :not-after="new Date()" format="DD.MM.YYYY HH:mm"></date-picker>

```
```js
data() {
  return {
    date: null;
  }
}

computed: {
  newPoinitDate() {
    return moment(this.date).format("DD.MM.YYYY HH:mm")
}

```

**Comment by mengxiong10** [comment]
v2.8.0 add the prop `valueType` to format the binding value.
You can set it to 'format' to solved it.
