### ISSUE TITLE
Using DatePicker as a birthday picker

### ISSUE THREAD

**Issue by alataknet** [mengxiong10/vue2-datepicker#174]
Hello
How to use vue2-datepicker as a birthday picker, ie: the order of the panels would be Year, Month, and then day ?

**Comment by mengxiong10** [comment]
You need to change the source code.
```js

import DatePicker from 'vue2-datepicker'

const init = DatePicker.components.CalendarPanel.methods.init

DatePicker.components.CalendarPanel.methods.init = function () {
  init.call(this)
  this.panel = 'YEAR'
}

```

**Comment by alataknet** [comment]
Hello,
Thank you.
I use the date picker also as a normal date picker.
I tried with Vue.nextTick, but I did not find the correct way of doing it

**Comment by alataknet** [comment]
Thank you very much. Works perfect
