### ISSUE TITLE
Timestamp format

### ISSUE THREAD

**Issue by azriel46d** [mengxiong10/vue2-datepicker#177]
The underlying library fecha does not support 'X' or 'x' similar to momentJS and other libararies and so the formatting does not work properly

**Comment by Tusko** [comment]
+1

**Comment by mengxiong10** [comment]
I'll add a prop to return the value to formatted text or `timestamp`.
Now you can do this with computed.
```html
<date-picker  v-model="value" />

```
```js

  computed: {
    timestamp: {
      get() {
        return new Date(this.value).getTime()
      },
      set(val) {
        this.value = new Date(val)
      }
    }
  }

```

**Comment by mengxiong10** [comment]
v2.8.0 added a prop `valueType`
when `valueType` is 'timestamp' ,
the binding value will be a timestamp number
