### ISSUE TITLE
How to set different :time-picker-options in range picker?

### ISSUE THREAD

**Issue by therakib7** [mengxiong10/vue2-datepicker#178]
Hello, 
First I would like to thanks for your great DateTime picker. But I have a problem.
In range picker if I set :time-picker-options="" both are same in  range (from and to). Like the folliwng:

`<date-picker v-model="value5" range type="datetime" lang="en" format="YYYY-MM-DD HH:mm:ss" :time-picker-options="{ start: '00:00', step: '00:30', end: '23:30' }"></date-picker>`

I want different :time-picker-options="" in range picker for from datetime and to datetime.

Advance Thanks

**Comment by mengxiong10** [comment]
I have not considered this requirement. But you can implement it in the following way.
```html
<date-picker ref="datepicker" v-model="value5" range type="datetime" lang="en" format="YYYY-MM-DD HH:mm:ss"  >`

```

```
mounted () {
    this.$refs.datepicker.$children[0].timePickerOptions = { start: '00:00', step: '00:30', end: '23:30' }
    this.$refs.datepicker.$children[1].timePickerOptions = { start: '06:00', step: '00:30', end: '20:30' }
 }
```

**Comment by therakib7** [comment]
Thanks for quick response and solution.
