### ISSUE TITLE
change position of datepicker

### ISSUE THREAD

**Issue by DeepakAryal** [mengxiong10/vue2-datepicker#18]
is it possible to change the position of datepicker? since i have used it in table, it covers all my table data. so i want to change its position to top side of table. is it possible?

**Comment by mengxiong10** [comment]
there is a function named "displayPopup" to control the position. you can rewrite it like this:
```
import DatePicker from '../datepicker/index.vue'

DatePicker.methods.displayPopup = function () {
  this.position = {
    left: 0,
    bottom: '100%'
  }
}
```

**Comment by DeepakAryal** [comment]
It works. thank you.
