### ISSUE TITLE
下载你的源码， optionsSchema.definitions.output = undefined

### ISSUE THREAD

**Issue by zgbbiao** [mengxiong10/vue2-datepicker#183]
npm run dev 的时候，  项目报错， 然后找到 config-yargs.js 里面 引入的 const optionsSchema = require("webpack/schemas/WebpackOptions.json");   中   optionsSchema.definitions.output // 打印出来是undefined

**Comment by mengxiong10** [comment]
这个应该是依赖的问题, 具体是怎么样我也不太清楚, 我建议你删了package-lock.json 后 再重新安装下依赖.

**Comment by zgbbiao** [comment]
这个操作试了几遍 还是不行

**Comment by mengxiong10** [comment]
https://github.com/webpack/webpack/issues/8082
看看这个是不是你的问题

**Comment by zgbbiao** [comment]
对的  就是这个问题，   谢谢大神
