### ISSUE TITLE
date-picker is not closing on click or selection

### ISSUE THREAD

**Issue by khrono-angel** [mengxiong10/vue2-datepicker#184]
After a couple of Hours dealing with this issue, I figured out that the component is not closing the calendar when this is located inside a html label. i.e.
```html
<label>
    <strong>some caption</strong>
    <date-picker v-model="value1" lang="en"></date-picker>
</label>
``` 
How I solve it was to set the `append-to-body` atribuye to `true`. i.e.
```html
<label>
    <strong>some caption</strong>
    <date-picker v-model="value1" lang="en" append-to-body></date-picker>
</label>
``` 
This workaround solve the problem, but I think there should be other way. 

Is there any conflict with this nesting of elements in the code ?

Regards,

**Comment by mengxiong10** [comment]
I should prevent the popup click event propagation.
I fixed it in v2.6.1.
