### ISSUE TITLE
Disabling days dynamically

### ISSUE THREAD

**Issue by mrdigitalau** [mengxiong10/vue2-datepicker#185]
Hi,

Thank you very much for your plugin, it is fantastic work.
I have a problem I can't seem to solve with vue2-datepicker.

I need to disable days based on criteria.

For example, If the time now is past 5 pm, I want the next available day that can be chosen to be 2 days time.

AND

If today is Friday, then the next available date I can choose is Monday.

There are about 5 different rules I need to apply.

Is there a way to do this with the disabledDates function? I can't figure it out, it's killing me.
I was able to do it in jquery with datepicker but I really do not want to use Jquery with Vue.

Thanks very much.
Sean

**Comment by marcosdipaolo** [comment]
Is this documented? cannot find the option disabledDays in the docs

**Comment by mengxiong10** [comment]
@marcosdipaolo `disabledDate`
