### ISSUE TITLE
Create new event when month selection changes

### ISSUE THREAD

**Issue by olivertappin** [mengxiong10/vue2-datepicker#187]
From the docs, we have the following events (which are extremely non-descriptive):

Name | Description | Callback Arguments
-- | -- | --
change | When the value change | the currentValue
input | When the value change | the currentValue
confirm | When click 'OK' button | the currentValue
clear | When click 'clear' button |  
input-error | When user type a invalid Date | the input text
panel-change | When change the panel | panel, oldPanel

However, the `panel-change` event doesn't seem to do what I expect. Every time the month selection changes (from say October to November), the event does not fire. I need to pick it up as an event, so I can manipulate the calendar contents. In my case, I need to add prices below each of the dates in the month view. I am having to inject this with JavaScript since the calendar provides very little custom functionality, but I would at least expect an event when the data changes. Currently I see no way of doing this.

Please can I request a few feature of an event for when any content on the calendar changes, such as changing month? Either in the form of a new event, or updating the existing event: `panel-change`.

**Comment by mengxiong10** [comment]
Do you mean you want to listen an event for the calendar changes, when the `type` is `date`?
I can emit a `calendar-change` event for it.
The `panel-change` is for the view changes.

**Comment by olivertappin** [comment]
Yes that's correct. That would be great if you could add that as an event.

**Comment by mengxiong10** [comment]
I added a `calendar-change` event in v2.6.2.
```html
<date-picker @calendar-change="handleCalendarChange"  v-model="value" />
```

```js
{
   methods: {
      handleCalendarChange (value, oldValue) {
          const month = value.getMonth()
          const year = value.getFullYear()
          const oldMonth = oldValue.getMonth()
          const oldYear = oldValue.getFullYear()
      }
   }
}

```

**Comment by olivertappin** [comment]
Thank you very much for such a quick turn around.
