### ISSUE TITLE
vue2-datepicker在safari中用v-model="startTime的方式设置时间不生效

### ISSUE THREAD

**Issue by yaowangmx** [mengxiong10/vue2-datepicker#196]
`vue2-datepicker在safari中用v-model="startTime的方式设置时间不生效，在苹果电脑的谷歌浏览器中有效
`<date-picker 
                                    class="date" 
                                    v-model="startTime" 
                                    type="datetime" 
                                    format="YYYY-MM-DD HH:mm" 
                                    :minute-step="noSecond" lang="zh" 
                                    :not-after="endTime == '永久'? new Date('2099-12-10 12:12:12'):endTime" 
                                    :editable="isEditable"
                                    confirm
                                    @panel-change="changePanel" 
                                    @backToDate="changeToDate" 
                                    @confirmDate="closeNow"
                                    @changeValue="getChangeValue"
                                    >
                                    <template slot="footer" slot-scope="scope">
                                        <div class="mx-datepicker-footer">
                                            <button 
                                                class="backDateBtn"
                                                v-if="panelName == 'TIME'"
                                                @click="back">返回日期</button>
                                            <button 
                                                class="whiteBtn" 
                                                @click="nowDate">现在</button>
                                            <button 
                                                class="blueBtn" 
                                                @click="scope.confirm">确定</button>
                                        </div>
                                    </template>
                                </date-picker>`

``

**Comment by mengxiong10** [comment]
你是指not-after不生效是吧
safari 不支持 `new Date('2099-12-10 12:12:12')`这种写法.
中间要加一个T `new Date('2099-12-10T12:12:12')`

**Comment by yaowangmx** [comment]
> 你是指not-after不生效是吧
> safari 不支持 `new Date('2099-12-10 12:12:12')`这种写法.
> 中间要加一个T `new Date('2099-12-10T12:12:12')`

v-model="startTime"我从数据库获取了一个值需要写进去，但是在safari里面显示是空的

**Comment by mengxiong10** [comment]
en 建议检查下 startTime 的格式

**Comment by yaowangmx** [comment]
> en 建议检查下 startTime 的格式

加上T会不会影响其他的浏览器呢》比如谷歌，IE等

**Comment by mengxiong10** [comment]
加T才是标准的写法, 是都支持的.

**Comment by yaowangmx** [comment]
> 加T才是标准的写法, 是都支持的.

感谢你的解答，你的插件做的真的很棒
