### ISSUE TITLE
Date problem

### ISSUE THREAD

**Issue by travis5491811** [mengxiong10/vue2-datepicker#198]
How should date be handled? if i set a default date with new Date() and then select today date manually in a different date field, they both end up with different dates. Why is this?

Why is new Date(), a different date (off by a day or so) than selecting todays date in the tool?

How do i fix this so that no matter what, both cases have correct date?

**Comment by mengxiong10** [comment]
Can you show your code plz.

**Comment by travis5491811** [comment]
sorry, i found the problem while trying to make a simplified code example to post here.
