### ISSUE TITLE
Error: Couldn't find preset "latest"

### ISSUE THREAD

**Issue by blackpuppy** [mengxiong10/vue2-datepicker#2]
Thanks for creating the component!

I am using it with Vue.js 2 and got the following error:

```
...
 error  in ./~/vue2-datepicker/src/datepicker/index.vue

Module build failed: Error: Couldn't find preset "latest" relative to directory ".../node_modules/vue2-datepicker"
...
```

Bug reproduction can be found [here](https://github.com/blackpuppy/vue2-datepicker-demo).  I am using Node v6.10.1, and npm 4.2.0.

**Comment by mengxiong10** [comment]
@blackpuppy  Thank you for your feedback, I have fixed it. You can  delete the file "/node_modules/vue2-datepicker/.babelrc" or run the npm again
``` bash
npm install vue2-datepicker --save
```

**Comment by blackpuppy** [comment]
@mengxiong10 I got the update and verified the fix.  Thanks!
