### ISSUE TITLE
Wrong header if type set to 'time'

### ISSUE THREAD

**Issue by david-mart** [mengxiong10/vue2-datepicker#205]
If you set `type="time"`, the header is just displaying plane format string 

<img src="https://user-images.githubusercontent.com/20728627/48750182-c5737c00-ec32-11e8-8deb-7789de37f9a0.png" width="200" />

I believe this is related to this part of your component 

https://github.com/mengxiong10/vue2-datepicker/blob/60798f77a087241d0008ce29b44f47e52402fb0c/src/calendar.vue#L173-L178

Looks like you are just returning the format string itself without parsing the date

It should be
```
    timeHeader () {
      if (this.type === 'time') {
        return this.value && formatDate(this.value, this.dateFormat || this.$parent.format)
      }
      return this.value && formatDate(this.value, this.dateFormat)
    }
```

This will also make sure that you can use a different format for the time picker header (for example if you want to show the date or currently selected time)

I will create a PR for this bug soon

**Comment by mengxiong10** [comment]
v3.0 refactored the time picker.
The header is not displayed by default.
The header can be customized by `show-time-header` and `time-title-format`.
