### ISSUE TITLE
Broken CSS from closed suggestion

### ISSUE THREAD

**Issue by travis5491811** [mengxiong10/vue2-datepicker#206]
https://github.com/mengxiong10/vue2-datepicker/issues/204#issuecomment-440301166 made another problem.

`append-to-body` hides the date-picker. Datepicker is used in a <b-modal>. The date-picker shows up behind the model.

How can i use append-to-body without it hiding the datepicker? Where to put z-index change?

**Comment by mengxiong10** [comment]
use the `popupStyle` prop to set zIndex.

**Comment by travis5491811** [comment]
thanks, 
```
append-to-body
style="width: 100%;" //for input box
:popupStyle="{'z-index': 84474}"
```
worked. number probably doesn't need to be that high but that's just full example.

**Comment by ugurcanalyuz** [comment]
@mengxiong10 Thanks!
