### ISSUE TITLE
Is it possible to show the popup on focus and close it on blur?

### ISSUE THREAD

**Issue by DineshSrisrimal** [mengxiong10/vue2-datepicker#207]
<no-ssr>
            <date-picker
              :ref="datepicker"
              @focus="$refs[`datepicker`][0].showPopup()"
              @blur="$refs[`datepicker`][0].closePopup()"
              v-model="year"
              type="year"
              format="YYYY"
              placeholder="Year"
              :not-after="new Date()"
              :not-before="new Date('1970')"
            </date-picker>
          </no-ssr>

The @focus and @blur method don't seem to work? I checked the events of the date-picker and found that we don't have blur and focus. Any suggestions on how to achieve it?

**Comment by mengxiong10** [comment]
```html
<date-picker 
  v-model="value2" 
  @focusin.native="$refs.datepicker.showPopup" 
  @focusout.native="$refs.datepicker.closePopup" 
  ref="datepicker" >
</date-picker>'
```

**Comment by DineshSrisrimal** [comment]
The above code works perfectly for the type year. When the type is set to month, the popup closes when clicked on side arrows. Is it possible to focus out only when the tab key is pressed and not when by clicking the arrows to change year?
```
    <no-ssr>
        <date-picker
          :ref="datepicker"
          @focusin.native="$refs.datepicker.showPopup" 
         @focusout.native="$refs.datepicker.closePopup" 
          v-model="year"
          type="month"
          format="MMM-YYYY"
          placeholder="Year"
          :not-after="new Date()"
          :not-before="new Date('1970')"
        </date-picker>
      </no-ssr>
```

**Comment by mengxiong10** [comment]
V2.10.0 supports this feature by default.

**Comment by bubgdgnanh** [comment]
Hi mengxiong10,\

It works well when changing focus. But when clicking, this issue still happens

I checked on v2.10.0, v2.10.1, v2.10.2
If you can please help me check it.

Thanks

**Comment by mengxiong10** [comment]
What's the problem?
```html
<date-picker v-model="value2" / >
```
v2.10.0 will show the popup on focus and close it on blur by default. 
Don't need `@focusin.native="$refs.datepicker.showPopup" `

**Comment by bubgdgnanh** [comment]
Yes, it's ok when changing focus, but when clicking, this issue still happens.

Below is my case:
I have 2 date-picker in a page.
The first, I clicked date-picker A, the popup A displays as normally.
After that, moving cusor and click on date-picker B, the popup B displays and popup A didn't dismiss.

**Comment by mengxiong10** [comment]
@bubgdgnanh 
It's a feature for somebody.
Because the date-picker prevent the click event.

**Comment by bubgdgnanh** [comment]
Thanks for your feedback.
If you can, please let me know how to display only one date-picker at the moment.

**Comment by mengxiong10** [comment]
@bubgdgnanh 
```html
<date-picker @blur="handleBlur" ref="datepicker" v-model="value" lang="en" />
```
```js
handleBlur () {
   this.$refs.datepicker.closePopup()
}

```

**Comment by HapLifeMan** [comment]
Is it expected that the popup of a field doesn't disappear when clicking in another datepicker field?

**Comment by mengxiong10** [comment]
@HapLifeMan yes.

**Comment by HapLifeMan** [comment]
Ok, do you have any solution to prevent it? (especially when fields are one below the other)

**Comment by mengxiong10** [comment]
https://github.com/mengxiong10/vue2-datepicker/issues/207#issuecomment-473268772

**Comment by bubgdgnanh** [comment]
@mengxiong10 
Your example code to work with my case but cannot set value when selecting date.
If you have another way, please let us know.

Thank you so much.

**Comment by HapLifeMan** [comment]
> @bubgdgnanh
> 
> ```
> <date-picker @blur="handleBlur" ref="datepicker1" v-model="value" lang="en" />
> ```
> 
> ```js
> handleBlur () {
>    this.$refs.datepicker1.closePopup()
> }
> ```

This is working fine to display one at a time!
But it is now impossible to click into the popup because it's closing the current one 🤔

**Comment by bubgdgnanh** [comment]
@HapLifeMan 
You can use as below.
@focusout.native="handleBlur($event)"

handleBlur(event) {
            if(event.relatedTarget != null) {
                this.$refs.datepicker.closePopup();
            }
        },

**Comment by bubgdgnanh** [comment]
Now I have issue related with it. 
Steps to reproduce:
- Open time popup after that change time but done close it.
- Click to other time/date 
=> 2 popup are displayed.

@mengxiong10 Do you have free time or any opinion for my case.
If you have please help to take a look and let me know.

Thank you so much.
