### ISSUE TITLE
Open calendar on a default date other then today

### ISSUE THREAD

**Issue by alataknet** [mengxiong10/vue2-datepicker#208]
Hello
Thank you very much for your plugin, it is fantastic work.

Is it possible to open the calendar on a specific date other than today ?

**Comment by mengxiong10** [comment]
```html
<date-picker v-model="value">
```
Just set the `value` to the specific date you want.

**Comment by alataknet** [comment]
Hello

Yes, it is correct, but in that case the date is already preselected. I would like that the date is not preselected, but the calendar opens on the first available date which in my case can  some months after today

**Comment by mengxiong10** [comment]
https://github.com/mengxiong10/vue2-datepicker/issues/94

**Comment by alataknet** [comment]
Hello,

Ok got it. thank  you.
