### ISSUE TITLE
Feature request: date range optional range 

### ISSUE THREAD

**Issue by alfonsobries** [mengxiong10/vue2-datepicker#211]
Sometimes we want to add a range but allow the user to only set the first date (or only the second) Will be great to add an option to the user doesn't need to complete the range to the range input could be filled

**Comment by mengxiong10** [comment]
In this case, it is best to use two components(not range) to achieve this feature just like the way the component implements the `range` feature internally..

**Comment by alfonsobries** [comment]
@mengxiong10 Totally understand but don`t you think that sometimes (as an option) had a single date range is preferable? For example, I`m using it for a datatable filter so this input is in a date column (other columns has a text input), the user can set the full range or only one limit.

I forked the package to add this function and use that branch in my project, also made a PR, probably the PR is not usable anymore because I needed to add the lib folder so I can use the branch in my project, but in case you consider to add that functionality maybe its useful:

https://github.com/mengxiong10/vue2-datepicker/pull/212

thanks

**Comment by glemiron** [comment]
@mengxiong10 This feature really helpful for me. Can I help somehow to add it?

**Comment by mengxiong10** [comment]
```html
      <date-picker v-model="begin" lang="en" :not-after="end"></date-picker>
      <date-picker v-model="end" lang="en" :not-before="begin"></date-picker>
```

**Comment by glemiron** [comment]
![image](https://user-images.githubusercontent.com/22412236/52846769-7ea2fe80-311b-11e9-90df-12db084c9caf.png)
If I use this solving I'll get two inputs and user have to click more times for getting range.

**Comment by mengxiong10** [comment]
a hack
```js

import DatePicker from 'vue2-datepicker'

DatePicker.methods.selectStartDate = function (date) {
  this.$set(this.currentValue, 0, date)
  this.updateDate()
}

DatePicker.methods.selectEndDate = function (date) {
  this.$set(this.currentValue, 1, date)
  this.updateDate()
}

DatePicker.methods.isValidRangeValue = function (value) {
  return Array.isArray(value) && value.length === 2
}

```

**Comment by glemiron** [comment]
Thanks!!

**Comment by Pajicc** [comment]
Guys any news about this? Can we allow half range or at least (in case of using 2 components) to have an option to define "highlighted" dates so that we can show all selected dates in the 2nd component?

**Comment by suresh444** [comment]
Nay update on selecting half-range-values

**Comment by mengxiong10** [comment]
You can use two components to have this feature in v3.x.
 
https://codesandbox.io/s/date-range-optional-range-z06gv?file=/src/App.vue
