### ISSUE TITLE
tabindex not working/available!

### ISSUE THREAD

**Issue by bilgino** [mengxiong10/vue2-datepicker#214]
Hi,
How can I set the tabindex="-1"? Should I access the input element manually through the api? My Goal is to use the Datepicker in a Form but it should not be tabable! Of course the following example does not work, but that is what i need kind of! `<date-picker  tabindex="-1"  v-model="value1"></date-picker>`

**Comment by mengxiong10** [comment]
#207

**Comment by bilgino** [comment]
Thank you! 
Can you please update the docs with "how to use the slot to change the calendar icon"? I cant find a example of how to change the datepicker calendar icon!

**Comment by mengxiong10** [comment]
```html
<date-picker v-model="value">
  <i  slot="calendar-icon">your icon</i>
</date-picker>

```
