### ISSUE TITLE
Only show popup on calendar icon click

### ISSUE THREAD

**Issue by algil** [mengxiong10/vue2-datepicker#215]
Hi!

How can I disable opening the popup when the input has focused? I only want to open the picker popup on calendar click.

BTW, When I click on the calendar button/icon the input should get the focus, Is this possible?

Thanks!

**Comment by mengxiong10** [comment]
```html
<date-picker ref="picker" v-model="value" lang="en" ></date-picker>

```

```js
  mounted () {
    const datePicker = this.$refs.picker
    const input = datePicker.$refs.input
    input.addEventListener('click', (event) => {
      event.stopPropagation()
    })
  }

```

**Comment by algil** [comment]
Hi!

But I also have needed `event.preventDefault()`.

About input focus when click on the calendar icon. I've solved using `icons` slot and manage `@click.native` event.

Regards!
