### ISSUE TITLE
Hide year navigation from datepicker

### ISSUE THREAD

**Issue by algil** [mengxiong10/vue2-datepicker#219]
Hi!
How can I hide the year navigation arrows from datepicker, but not in year and moth pickers?

Remove from here:

![image](https://user-images.githubusercontent.com/520071/50536732-b946dc80-0b57-11e9-929d-d4789ccf85bd.png)

But not from here:

![image](https://user-images.githubusercontent.com/520071/50536749-edba9880-0b57-11e9-8aea-bdd3bfa347d4.png)

![image](https://user-images.githubusercontent.com/520071/50536782-63266900-0b58-11e9-8a9b-0c37940ec1e0.png)

Thanks!

**Comment by mengxiong10** [comment]
You can use the `panel-change` prop to do it.
```html
<date-picker @panel-change="handlePanelChange" v-model="value" lang="en" ></date-picker>
```
```js
handlePanelChange (panel, oldPanel) {
  if (panel === 'DATE') {
    document.querySelector('.mx-icon-last-year').style.display = 'none'
    document.querySelector('.mx-icon-next-year').style.display = 'none'
  } else if (panel !== 'TIME') {
    document.querySelector('.mx-icon-last-year').style.display = 'block'
    document.querySelector('.mx-icon-next-year').style.display = 'block'
  }
}

```

**Comment by algil** [comment]
This solution doesn't work if there are various datepicker elements.

**Comment by doctorsirius** [comment]
Would be easier, even for CSS styling if the component would add an attribute or class to the parent element mx-calendar indicating the different modes; date, year, month, time.

**Comment by mengxiong10** [comment]
Yes, add class will be better.
I'll do it later.
@algil Now it can work by adding different ids.
```html
<date-picker id="datepicker" @panel-change="handlePanelChange" v-model="value" lang="en" ></date-picker>
```
```js
handlePanelChange (panel, oldPanel) {
  const datepicker = document.getElementById('datepicker');
  if (panel === 'DATE') {
    datepicker.querySelector('.mx-icon-last-year').style.display = 'none'
    datepicker.querySelector('.mx-icon-next-year').style.display = 'none'
  } else if (panel !== 'TIME') {
    datepicker.querySelector('.mx-icon-last-year').style.display = 'block'
    datepicker.querySelector('.mx-icon-next-year').style.display = 'block'
  }
}

```

**Comment by doctorsirius** [comment]
Any hope we can see mode classes anytime soon? Btw, another good thing for styling would be allow to specify a class to the confirmation button, so you can take approach of your own button classes (very common; like btn-primary, and so) instead of repeat styles.

**Comment by mengxiong10** [comment]
@doctorsirius 
You can use the `footer` slot.
```html
<date-picker>
   <template slot="footer" slot-scope="{ confirm }>
      <button type="button"
            class="btn-primary"
            @click="confirm">OK</button>
  </template>
</date-picker>

```

**Comment by doctorsirius** [comment]
Cool! Thanks!

**Comment by mhdyahiya** [comment]
Thanks, @mengxiong10

**Comment by FPTSonPM3** [comment]
![image](https://user-images.githubusercontent.com/40652135/72138514-874d9480-33bf-11ea-9d08-999b94996677.png)
I want to install like this, thanks to everyone for help

**Comment by FPTSonPM3** [comment]
![image](https://user-images.githubusercontent.com/40652135/72138696-f1fed000-33bf-11ea-913c-3339a6247e3d.png)
I want to install like this, thanks to everyone for help

**Comment by FPTSonPM3** [comment]
![image](https://user-images.githubusercontent.com/40652135/72138792-23779b80-33c0-11ea-8daf-d78b432bfece.png)
I want to install like this, thanks to everyone for help

**Comment by FPTSonPM3** [comment]
![image](https://user-images.githubusercontent.com/40652135/72138838-3d18e300-33c0-11ea-9a86-c06b41dcd691.png)
I want to install like this for the red circle - change it to the previous month and the next month, thanks to everyone for help

**Comment by mengxiong10** [comment]
@FPTSonPM3 
use css.
```css
.mx-calendar-panel-year .mx-icon-double-right::before,
.mx-calendar-panel-year .mx-icon-double-left::before {
  display: none;
}

```

**Comment by FPTSonPM3** [comment]
I'm trying css for the header, is there any way to customize the number for the switch to the previous month, the switch to the next month?

**Comment by yakovcohen4** [comment]
> I'm trying css for the header, is there any way to customize the number for the switch to the previous month, the switch to the next month?

@ghost 
Did you manage to turn the sides of the arrows?
And if yes, how ?
