### ISSUE TITLE
How to change format header

### ISSUE THREAD

**Issue by lequy1010** [mengxiong10/vue2-datepicker#221]
![image](https://user-images.githubusercontent.com/7949193/50633942-9cf3d700-0f7f-11e9-9615-c81ee686b4f2.png)
default format header: 1月 2019
now i want to change format: 2019/1 , Please confirm how to change it?

**Comment by mengxiong10** [comment]
Don't have prop to change it.
You just can change the language.

**Comment by mengxiong10** [comment]
You can switch position of year and months by css #223.  But cann't format now.

**Comment by lequy1010** [comment]
> You can switch position of year and months by css #223. But cann't format now.

Thank you, it's worked. but if you update to allow format is OK.

**Comment by mengxiong10** [comment]
v3.0.
You can set it by lang.
```html
<date-picker  :lang="locale" />
```
```js
// import defalut locale.
import 'vue2-datepicker/locale/zh-cn';

export default {
  date() {
    return {
      locale: {
        yearFormat: 'YYYY /',
        monthFormat: 'M',
        monthBeforeYear: false,
      },
    };
  },
};```
