### ISSUE TITLE
Picker not working undefined date

### ISSUE THREAD

**Issue by nattyluke** [mengxiong10/vue2-datepicker#222]
![1](https://user-images.githubusercontent.com/23554225/50678285-41b4f980-0ffe-11e9-92f0-2a7a7f5d54e6.png)
When i open datepicker, it looks good, but when i change year/month i just get "undefined" like you see on the picture, any ideas?

**Comment by mengxiong10** [comment]
It looks like the prop `lang`'s problem.
Can you show your code .

**Comment by mengxiong10** [comment]
write an example https://jsfiddle.net/
