### ISSUE TITLE
Feature Request - time picker option separate select for minutes and hours

### ISSUE THREAD

**Issue by brianlmerritt** [mengxiong10/vue2-datepicker#227]
I love the plugin, just one minor tweak would be great.  My timePickerOptions are set to a step of 00:05, which results in a lot of scrolling when selecting the time.

Could you have the option of two selects, one for the hour, one for the minutes?  I suppose if the step is 00:00:nn then it would be 3 selects.

ps - if the step is stupidly set to 00:00 then that is not detected and the browser just gets in an infinite loop trying to get from 00:00 to 24:00 in steps of 00:00

**Comment by brianlmerritt** [comment]
Thanks - that results in just one long selection box, not separate one column for hours and one for minutes.

I had already got that result with 

`timePickerOptions:{
                    start: '00:00',
                    step: '00:05',
                    end: '23:55'
                },`

Is there a way to get just two columns (no seconds) and have the minutes select be every 5 minutes?

**Comment by mengxiong10** [comment]
set the `minute-step` 5 instead of setting the `timePickerOptions`

**Comment by brianlmerritt** [comment]
Cool - that works fine.  Closing now.  Don't forget that check for zero step  -> infinite loop :D

**Comment by Dual-Ice** [comment]
I have a similar problem... 
I want to use 
timePickerOptions:{ start: '09:00', end: '18:00' }, 
with 
minute-step="10"
and have in result two colums 
one with hours from 09 to 18 
and second with minutes from 00 to 50 with step of 10
Is it real?

**Comment by mengxiong10** [comment]
@Dual-Ice 
I add a prop `time-select-options` in v2.12.0.
You can use it like this.
```html
<date-picker  :time-select-options="{ hours: [9,10,11,12,13,14,15,16,17,18], minutes: [0,10,20,30,40,50], seconds: []  }" />

```
