### ISSUE TITLE
Feature request: Allow to define our own stringify function

### ISSUE THREAD

**Issue by skjnldsv** [mengxiong10/vue2-datepicker#229]
Hello and thanks for your awesome component!
Could it be possible to define our own `stringify` function?
Just to change the display but not the data itself. Recent 2.8.0 added a `value2date` function, but it's also used in the `handleValueChange` function and therefore preventing us to use it since it is also completely changing the selected value.

Thanks a lot
Cheers

**Comment by mengxiong10** [comment]
try this.
```js
import DatePicker form 'vue2-datepicker'

DatePicker.methods.stringify = function(date) {}

```

**Comment by skjnldsv** [comment]
@mengxiong10 Thats' what I do for now, but this is really *hackish*. A prop would be better for that I think :)

**Comment by mengxiong10** [comment]
v2.9.0.

Yes, I release v2.9.0 to supports custom `format`.
You can use it like this.
```html
<date-picker v-model="value" lang="en" :format="myFormat"></date-picker>
```

```js
  data () {
    return {
      myFormat: {
        stringify: (date) => {
          return date ? moment(date).format('LL') : null
        },
        parse: (value) => {
          return value ? moment(value, 'LL').toDate() : null
        }
      }
    }
  }

```

**Comment by skjnldsv** [comment]
You're awesome!! :D
