### ISSUE TITLE
可支持range选择的时候,能否支持只选年和只选月的

### ISSUE THREAD

**Issue by haryzxw** [mengxiong10/vue2-datepicker#23]
有没有比较方便的属性可以设置的

**Comment by mengxiong10** [comment]
@haryzxw 
我不打算开发这个功能，因为不涉及到时间选择。会比较简单，我建议你根据自己的需求封装一个。

**Comment by haryzxw** [comment]
@mengxiong10  感谢回复！这个功能我自己已经实现啦！
