### ISSUE TITLE
Time shift when value is empty

### ISSUE THREAD

**Issue by dranik** [mengxiong10/vue2-datepicker#231]
When using datepicker solely as a timepicker, I stumbled upon a strange behaviour: it shiftsthe time I pick by three hours by default.
Even when I go to the samples page at https://mengxiong10.github.io/vue2-datepicker/demo/index.html this artifact is present regardless of which browser I am using.

**Comment by dranik** [comment]
Upon closer inspection, It seems to shift time by whatever timezone offset is on a given machine.

**Comment by mengxiong10** [comment]
set the `value-type` is 'format' to get the string value.
