### ISSUE TITLE
Time Panel bug

### ISSUE THREAD

**Issue by HandsomeHan515** [mengxiong10/vue2-datepicker#237]
当type=time时，先选择分或者秒会导致小时选项跳到8上，原因是 time.js中 date=new Date(this.value)，初始时this.value为空，new Date(this.value)会返回Thu Jan 01 1970 08:00:00 GMT+0800 (中国标准时间)，中国人就不发英文了

**Comment by mengxiong10** [comment]
现在可以设置 value-type这个值.
如果你的value 是字符串 设置 value-type='format'.
如果你希望value 是个时间对象. 你可以把 value设置为 new Date().setHour(0, 0, 0, 0)
