### ISSUE TITLE
Feature Request: Allow modification to the look of the next/last month/year

### ISSUE THREAD

**Issue by joeycf** [mengxiong10/vue2-datepicker#238]
Current Issue: While using this plugin we don't support whatever is currently being used as those icons so it displays in an odd way. We can't just modify it directly in the node_modules directory as that is periodically reset in the build. 

Solution: Allow us to change the last/next month/year icons (<< < > >>) manually.

**Comment by mengxiong10** [comment]
try this.
```js

mounted () {
    document.querySelector('.mx-icon-last-year').innerHTML = '<<'
}

```

**Comment by joeycf** [comment]
This workaround works! Thanks!

**Comment by mrcoulter45** [comment]
If you are doing a time range with 2 calendar instances, you will need something like:
```
var style_list = ['.mx-icon-last-year', '.mx-icon-next-year', '.mx-icon-last-month', '.mx-icon-next-month'];
var arrow_chars = ['<<', '>>', '<', '>'];
for (var i = 0; i < 4; i += 1) {
  var matches = document.querySelectorAll(style_list[i]);
  for (var match of matches) {
    match.innerHTML = `<font size="3">${arrow_chars[i]}</font>`;
    match.style.fontFamily = "Trebuchet MS,Charcoal,sans-serif";
  }
}
```

**Comment by xolott** [comment]
Why no leave this as a slot. In my case, I want to use vuetify's icon component instead of the default ones.
