### ISSUE TITLE
Bug: not-before can default to a disabled time.

### ISSUE THREAD

**Issue by joeycf** [mengxiong10/vue2-datepicker#239]
This relates to #27 and #73.

Scenario:

If you have a `calendar` AND a `timeFormat` (separate) and they are both linked to the same model. If you added a `not-before:` in both to the current date with `timePickerOptions`
start at 00:00 
step 01:00
end: 23:00

If the current time was todays date at [at any time after 00:00], and you select todays date in the calendar the `timeFormat` will still be at the defaulted 00:00 (which isdisabled). This should point to the closest enabled time.

**Comment by mengxiong10** [comment]
V3.0 refactored this behavior.
If the default time is disabled, It will not select any time by default
