### ISSUE TITLE
Panel does not close

### ISSUE THREAD

**Issue by MidnightP** [mengxiong10/vue2-datepicker#241]
Hi! :wave: 

Somehow the panel does not close anymore.

Is there some way I can force it to close after an `input` or `change` event occurs?

I've looked at the docs (https://www.npmjs.com/package/vue2-datepicker#panel) but can't find what I ned to do.

Thanks!

**Comment by mengxiong10** [comment]
```html
<date-picker 
  v-model="value" 
   ref="datepicker"
  @change="handleChange" 
   >
</date-picker>
```
```js
handleChange () {
  this.$refs.datepicker.closePopup()
}

```

**Comment by MidnightP** [comment]
`Cannot read property 'closePopup' of undefined"`

The
