### ISSUE TITLE
Show calendar with closest possible date

### ISSUE THREAD

**Issue by David-111** [mengxiong10/vue2-datepicker#242]
It's not a bug, but hopefully an improvement.

We've configured the option "not-before" with the date for tomorrow.
For today "tomorrow" is february the 1st.
So the user has to select a date from february or later.
The wierd thing is, that the calendar shows january (today is january the 31st), but no date in january is selectable.
So our suggestion is display the month, "not-before" is set to.

![bugticket_datepicker](https://user-images.githubusercontent.com/47214840/52056071-83838200-2561-11e9-92ea-61c384b19bbd.png)
As you can see within the attached screenshot, the left calendar is shown. The calendar on the right side should be shown.

**Comment by ikristher** [comment]
This is really a great suggestion. I am also struggling on how I can achieve this setting

**Comment by mengxiong10** [comment]
v2.10.0 add a prop `default-value`.
https://github.com/mengxiong10/vue2-datepicker/issues/94#issuecomment-462621925
