### ISSUE TITLE
Bug: Confirm not working correctly with range

### ISSUE THREAD

**Issue by aeacusvol** [mengxiong10/vue2-datepicker#243]
Can be seen on the demo page https://mengxiong10.github.io/vue2-datepicker/demo/index.html

On the single date picker if you click off the calendar without clicking okay the date label isn't updated, however if you select dates in the range picker then click off without clicking okay the labels are updated but the v-model is not updated.

**Comment by mengxiong10** [comment]
The last demo need to confirm. It's OK.

**Comment by aeacusvol** [comment]
Created a fiddle to make sure my code wasn't breaking something. It seems that using the shortcuts to change the date range doesn't require you to confirm. Is this expected?
https://jsfiddle.net/jxLfdwo0/
