### ISSUE TITLE
Clear date with value-type format sets date to 1970-01-01

### ISSUE THREAD

**Issue by matthijsbreemans** [mengxiong10/vue2-datepicker#244]
When using the new feature to set the value to the format with the value-type property causes the value to be set to 1970-01-01 when clearing the input box. 

When not using the value-type="format" it works as intended

Example jsfiddle: http://jsfiddle.net/u8rgb73e/

**Comment by mengxiong10** [comment]
Thank you for your feedback.
I fixed it in v2.9.1

**Comment by matthijsbreemans** [comment]
Great! Thanks for the fast fix!
