### ISSUE TITLE
Year range in the date select dialog is always one year ahead of the available options

### ISSUE THREAD

**Issue by j-ed** [mengxiong10/vue2-datepicker#245]
I've been asked by the Nextcloud team to report that problem here because they're using the vue2-datepicker function in their Contacts app software which causes the described problem: [Nextcloud Issue:](https://github.com/nextcloud/contacts/issues/911#issuecomment-460158560). 

## Expected behavior
The displayed year range in the date select dialog should reflect the available options.

## Current behavior
The displayed year range in the date select dialog is always one year ahead of the available options.

![20190203_nc_contacts_date_selector](https://user-images.githubusercontent.com/2572764/52179272-5ab8f200-27d8-11e9-956c-7e63e054ed42.png)

**Comment by mengxiong10** [comment]
Yes, It should be 1940 ~ 1949

**Comment by mengxiong10** [comment]
v2.9.2 fixed it.
