### ISSUE TITLE
showPopup dont working

### ISSUE THREAD

**Issue by mailok** [mengxiong10/vue2-datepicker#247]
Hi, I have the version installed 2.4.1and showPopup it works very well, but in the version 2.9.1dont working.

```
<date-picker ref="datepicker" ......
```

```
 get datepicker(): HTMLFormElement {
        return this.$refs.datepicker as HTMLFormElement;
    }

 mounted() {
        this.datepicker.showPopup();
    }
```

**Comment by mengxiong10** [comment]
You may need to check the value `this.datepicker` by the computed or use `this.$refs.datepicker` in mounted.

I've tried it. It's ok.

http://jsfiddle.net/mengxiong/2rz0apfy/5/

**Comment by vmihailenco** [comment]
See http://jsfiddle.net/Le96mytn/ - clicking on "Show" button used to show the datepicker.

**Comment by mengxiong10** [comment]
Now outside click events need to stop propagation
http://jsfiddle.net/ub81xLw4/
```html

<button @click.stop="showPopup">Show</button>

```
