### ISSUE TITLE
Using focusout.native to close panel on blur causes the panel to to close before it can register a click.

### ISSUE THREAD

**Issue by fidgetwidget** [mengxiong10/vue2-datepicker#248]
I saw in #207 you suggested the use of @focusin.native and @focusout.native to cause the panel to show/hide on focus/blur, but when I tried it, the focusout closing the panel caused all use of the calendar panel to not register, as the panel was closed by the focusout before the click on the panel could be registered. 
I even tried wrapping the close in a nextTick, but even that was triggered before any clicks on the panel were picked up.

Is it possible a recent change caused this to break?
perhaps commit 054758e ?

**Comment by mengxiong10** [comment]
Because  the input is blurred, when a mousedown event (before click event) on the panel.
You can try this.
```
<div
  tabindex="-1"
  @focusin="$refs.datepicker.showPopup" 
  @focusout="$refs.datepicker.closePopup" >
  <date-picker ref="datepicker" v-model="value" />
</div>

```

**Comment by fidgetwidget** [comment]
That works to a degree, but by adding the tabindex to the parent elm, it gets focus when selecting a date via the calendar. 
It breaks the accessibility, which is what I am trying to add to your component. Perhaps I should just open a different issue about the underlying problem rather than the issues that are coming up as I try and work around it.

**Comment by mengxiong10** [comment]
v2.10.0 show the popup on focus and close it on blur.
