### ISSUE TITLE
Entering a date value via the input doesn't trigger the input or change event.

### ISSUE THREAD

**Issue by fidgetwidget** [mengxiong10/vue2-datepicker#249]
I was trying to find a way to make the component accessible, so those who with limited vision could still type in a valid date or datetime and have it work.

However, you aren't emitting change or input on keyboard entry, and trying to capture the value on focus change (using focusin and focusout) lead to other issues (#248).

Is there any plan to add keyboard input handling to the component, or would I need to fork it and do that work for you (I just won't have time to do that in the near term, as the feature I am working on's deadline is fast approaching).

**Comment by joelpro2** [comment]
is this fixed?
i need to access the userInput data property on input event and not on change

**Comment by anorudes** [comment]
It is very strange that the issue is simply closed without comment. Why?

**Comment by mengxiong10** [comment]
use the event propagation

```html
<div @input="handleInput"><date-picker><date-picker/></div>

```

```
export default {

methods: {
   handleInput(evt) {}
}


}

```
