### ISSUE TITLE
Could you please add an option to alter the background color for the calender icon like this.

### ISSUE THREAD

**Issue by mhdyahiya** [mengxiong10/vue2-datepicker#252]
Could you please add an option to alter the background color for the calender icon like this, now there is white color as bg.

![image](https://user-images.githubusercontent.com/30796088/52699214-41176780-2f9b-11e9-9ac9-5812ae3854b1.png)

now i have altered your css with my own like this.

![image](https://user-images.githubusercontent.com/30796088/52699308-7754e700-2f9b-11e9-89bf-dd4dc09b9e2d.png)

I dont know if there already a possible way to do it. If there please help me ...

**Comment by mhdyahiya** [comment]
I have already passed a font awesome icon through the `calendar-icon` slot, but there is white bg along with that. my input box is grey.

**Comment by mengxiong10** [comment]
I'll remove the icon background-color

**Comment by mhdyahiya** [comment]
or you make an element to alter the background color for the users it may be perfect like the` input-class` bg color

**Comment by mengxiong10** [comment]
The background-color is redundant.
