### ISSUE TITLE
Is there any option to dynamically change the input-class value

### ISSUE THREAD

**Issue by mhdyahiya** [mengxiong10/vue2-datepicker#253]
Is there any option to dynamically change the `input-class` value???

![image](https://user-images.githubusercontent.com/30796088/52700776-c4868800-2f9e-11e9-8c15-6490a25a6e18.png)

I cant use `class` instead of `input-class` 

![image](https://user-images.githubusercontent.com/30796088/52700897-fe578e80-2f9e-11e9-94a8-0bf6510b7d17.png)
 
this will be the response for above code

![image](https://user-images.githubusercontent.com/30796088/52700961-1deeb700-2f9f-11e9-83c1-482e8bef8bc6.png)

**Comment by mengxiong10** [comment]
??
`:input-class`="computedClass"

**Comment by mhdyahiya** [comment]
`computedClass` is just a dynamic class variable from my script. I need to dynamically change the `input-class` according to my computed property value. But whenever I bind the `input-class` it shows an error, saying `input-class` is already defined like that

**Comment by mengxiong10** [comment]
just remove the second `input-class="appear..."`

**Comment by mhdyahiya** [comment]
Yeah, this thing can works, if you return the whole class to the `input-class` through the computed property. But i think it's not good to return common class items each time.

Vuejs class binding works like this,

```
<date-picker :input-class="ComputedClass">

export default {
computed: {
ComputedClass() {
if(!error) {
return 'appearance-none border border-grey-lighter block w-full bg-grey-lighter text-black text-xs rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-grey';
} else {
return 'appearance-none border border-red block w-full bg-grey-lighter text-black text-xs rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-grey';
}
}
}
}
```

you see the bulk class items i need to return each time when the computed works. this isnt a good way

```
<date-picker 
:input-class="ComputedClass"
input-class="appearance-none border  block w-full bg-grey-lighter text-black text-xs rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-grey>

export default {
computed: {
ComputedClass() {
if(!error) {
return 'border-grey-lighter';
} else {
return 'border-red';
}
}
}
}
```

why cant we bind class like this upper on

**Comment by mengxiong10** [comment]
It's Vue's problem.
```js

computedClass () {
  const commonClass = "appearance-none border  block w-full"
  return [!error ? 'border-grey-lighter' : 'border-red', commonClass]
}

```
