### ISSUE TITLE
Enable way to customize entire input format display

### ISSUE THREAD

**Issue by jacobg** [mengxiong10/vue2-datepicker#259]
The stringify override only allows you to change format of the date. I'd like to be able to format the entire display. For example, I want to prepend the custom shortcut text to the date range displayed in the input box, as well as change format based on the period, like this:
`This Month: 2019-02-01 ~ 2019-02-28`
or
`Last Week: 2019-02-17 ~ 2019-02-23`

Is there a way now to do that?

**Comment by mengxiong10** [comment]
No such feature.
Maybe you can use an external element to display the label.Then Let it look inside the input box via css.
```html
<span>{label}</span>
<date-picker v-model="value" range lang="en" ></date-picker>
```
```js
data () {
  return {
    value: []
  }
},
computed:{
  label () {
    if(value[0] === ? && value[1] === ?) {
       return 'This Month'
    }
  }
}


```

**Comment by jacobg** [comment]
Ok thanks
