### ISSUE TITLE
Range picker with one calendar

### ISSUE THREAD

**Issue by ghost** [mengxiong10/vue2-datepicker#260]
Is there a range picker with one calendar? I have multiple ranges that need to be picked for comparation. And using 2 per range takes a lot of screen, is there a way to use one calendar for range?

**Comment by mengxiong10** [comment]
No such feature. But you can use two components(not range) to achieve a range
```html
      <date-picker v-model="begin" lang="en" :not-after="end"></date-picker>
      <date-picker v-model="end" lang="en" :not-before="begin"></date-picker>
```

**Comment by mengxiong10** [comment]
in v3.x.
https://codesandbox.io/s/range-picker-with-one-calendar-jvv5s?fontsize=14
