### ISSUE TITLE
Custom localization (lang) is not used for date formatting

### ISSUE THREAD

**Issue by Raiondesu** [mengxiong10/vue2-datepicker#261]
I need to set a custom russian localization for my users. In Russia, dates are formatted differently, so I have to use the `format` prop.

Unforutnately, this prop formats dates using English locale only, resulting in the following language mess, which will result in a bad user experience:
![image](https://user-images.githubusercontent.com/19854420/53739355-99f36500-3ea2-11e9-86d1-8afad75948b4.png)

Notice the cyrillic russian language everywhere except the input field.

---
## P.S. Thank you for the most comprehensive calendar out there, tho!

**Comment by mengxiong10** [comment]
Thanks for your feedback.
Fix it requires a breaking change version, you can temporarily use it like this.
https://github.com/mengxiong10/vue2-datepicker/issues/111#issuecomment-399625732

**Comment by mengxiong10** [comment]
When I release v3.0, I'll close it.

**Comment by Raiondesu** [comment]
Thank you for the response! Your workaround helped.

I'll keep this issue open for task-tracking purposes then.

**Comment by mengxiong10** [comment]
fixed it in v3.0
