### ISSUE TITLE
Date picker does not opens the popup on selecting the value in it.

### ISSUE THREAD

**Issue by riddhiparekh** [mengxiong10/vue2-datepicker#262]
The date picker popup is opened only sometimes when the chosen value is selected. Hence it allows the user to type any invalid data other than date in it.

![ddd](https://user-images.githubusercontent.com/45178176/54010386-9a3a7b80-4194-11e9-8234-e96bb6ecc74b.png)

![d2](https://user-images.githubusercontent.com/45178176/54010284-31530380-4194-11e9-8b9d-f6580a05c10c.png)

Also the date picker gets closed automatically if another date picker popup is opened on the page which is not the case that is seen on the demo page.I think the picker should stay open even if the user clicks on another date picker.

![d3](https://user-images.githubusercontent.com/45178176/54010397-a32b4d00-4194-11e9-9dfe-d5ac840bade1.png)

![d4](https://user-images.githubusercontent.com/45178176/54010292-387a1180-4194-11e9-893b-0482708f54ca.png)

**Comment by mengxiong10** [comment]
Try to upgrade to the latest version
