### ISSUE TITLE
special characters visible when the projects compressed with gzip

### ISSUE THREAD

**Issue by munnabhaims** [mengxiong10/vue2-datepicker#263]
![image](https://user-images.githubusercontent.com/44765659/54119647-dd5a5000-441b-11e9-885f-3885e5e8c1f4.png)

when the war/tomcat  compressed with gzip, vu2 date pciket is having the special characters on header. please, find attached screenshot

**Comment by mengxiong10** [comment]
This seems to be a compatibility issue for entity characters.
I changed the entity character to entity number in v2.10.1.

**Comment by munnabhaims** [comment]
the issue still persisted

**Comment by mengxiong10** [comment]
set it by yourself. #238

**Comment by munnabhaims** [comment]
Thanks. It worked.
