### ISSUE TITLE
prop "name" should be propagated to input.

### ISSUE THREAD

**Issue by KonradDeskiewicz** [mengxiong10/vue2-datepicker#265]
Right now name is generated base on v-model. It would be nice to have an option to override this.
I've got some dynamic form one page that is "legacy" form page and such option would be live-saver :)

**Comment by mengxiong10** [comment]
use `inputAttr`
```html
<date-picker :input-attr={ name: 'legacy' } />
```

**Comment by KonradDeskiewicz** [comment]
Tried but "name" is not working (id, required etc. are working fine)

**Comment by mengxiong10** [comment]
use `input-name`
```html
<date-picker :input-name="formPrefix + 'date.value'" />
```
