### ISSUE TITLE
Problem typing a date in the input in version 2.10.1

### ISSUE THREAD

**Issue by FelipeBohnertPaetzold** [mengxiong10/vue2-datepicker#266]
After the update package for version 2.10.1, when entering the date in the input, the value is not updated.
![datepickerbug](https://user-images.githubusercontent.com/15256199/54307713-137a0a00-45ab-11e9-99e8-9ec935ece95f.gif)

The value is expected to be filled in the input as in previous versions

**Comment by mengxiong10** [comment]
Because it's an invalid date.

**Comment by FelipeBohnertPaetzold** [comment]
@mengxiong10 the format used is DD/MM/YYYY, was informed to the component, so it is valid

**Comment by mengxiong10** [comment]
Yes, you need type `10/10/2010`

**Comment by FelipeBohnertPaetzold** [comment]
@mengxiong10 in version 2.9.1 it is not necessary to enter the date with the mask, the component already understands.

this gif shows the operation in version 2.9.1:
![funcionando](https://user-images.githubusercontent.com/15256199/54353692-70b99e00-4633-11e9-9fe6-32602daa4e13.gif)

**Comment by mengxiong10** [comment]
Thanks, It's a bug In some case. 
I'll fix it soon.

**Comment by FelipeBohnertPaetzold** [comment]
@mengxiong10 thanks

**Comment by mengxiong10** [comment]
v2.10.3 fixed it.

**Comment by FelipeBohnertPaetzold** [comment]
@mengxiong10 Thanks man. It's working.
