### ISSUE TITLE
Error when i choose smaller date then start date

### ISSUE THREAD

**Issue by mstfdmr** [mengxiong10/vue2-datepicker#268]
Hello,
On the date range mode, when i choose a date from left side, the right side must be disable, because on the left side i choose a date smaller than right side month of date view. I think it must be same month with left side month because i cant choose a smaller date then starting date.

You can see it on picture below
Image URL is here (edited)
[https://pasteboard.co/I5mjErR.png
](https://pasteboard.co/I5mjErR.png
)

> And i need to tell you month names in Turkish :) And "Nis" means 'April' and "Mar" means "March"

**Comment by mengxiong10** [comment]
No picture. What's the problem?

**Comment by mstfdmr** [comment]
> No picture. What's the problem?

Hello.
Post has been edited

**Comment by mengxiong10** [comment]
Do you mean that this arrow should be disabled?
![image](https://user-images.githubusercontent.com/14135808/54669687-f904db00-4b2c-11e9-867b-a7ed61b44b14.png)

**Comment by bsormagec** [comment]
No i understood, 
he said;
in the right screen all fields has been disabled. When all fields disabled, it can be automatically change page to next month. Because we can't choose any date. 
So when all fields disabled in screen it must be go next month.

**Comment by mstfdmr** [comment]
Hello, @mengxiong10
Do you have an advice?

**Comment by mengxiong10** [comment]
There is an API  that supports two window interactions. #137
But its scope of action is very limited, so it is not on the document. 
I need to adjust it to make it easy for your scene.
Welcome for any suggestions

**Comment by dawid-karnacewicz** [comment]
@mengxiong10 any advice when user use on panel-change event ?

**Comment by mengxiong10** [comment]
@dawid-karnacewicz 
I'll release v3.0.0 this week.
It will solve this problem by default

**Comment by mengxiong10** [comment]
Minimum one month between two calendar in v3.x.
