### ISSUE TITLE
限定可选时间段？

### ISSUE THREAD

**Issue by SLRXXX** [mengxiong10/vue2-datepicker#27]
首先非常感谢作者，这个组件用起来非常方便，满足了我的大部分需求，且没发现什么坑。
有一个可能比较小众的场景，比如进行数据查询的时候，限制可以选择的时间长度（尤其是精确到每分种的时候，需要限制可选长度为几小时），也就是说需要可选范围随着初始、结束时间的选择而动态变化。
不知是否考虑支持这种功能

**Comment by mengxiong10** [comment]
not-before, 和not-after 可以满足你的需求，比如 :not-before="new Date()" , 当前时间以前都是不可选择的

**Comment by arunrreddy** [comment]
This doesn't work when you just select the date and click ok. Suppose the current time 1:00 pm today and you select today as the date and press ok and your :not-before="new Date()", the selected date will be today's date with the time as 12:00 AM(this time is actually disabled). Technically it should select the current time or the closest time interval in the future(i.e. 1:00 PM or 1:15 PM).
