### ISSUE TITLE
Vue warns: $attrs, $listeners, props...

### ISSUE THREAD

**Issue by rkvtsn** [mengxiong10/vue2-datepicker#270]
I have Vue (v2.6.9) warns in console:

- [Vue warn]: $attrs is readonly.
- [Vue warn]: $listeners is readonly.
- [Vue warn]: Avoid mutating a prop directly...

Is it normal ?

**Comment by spencerfrost** [comment]
I'm also having this warning. Using version 3.11.0

`[Vue warn]: $attrs is readonly.`
`[Vue warn]: $listeners is readonly.

Using the Datepicker like so:

```
<Datepicker
    :value="value"
    @input="onInput"
    :type="type"
    :valueType="format"
    :range="range"
    inline
    prefix-class="eci"
/>
```
