### ISSUE TITLE
ie11下v-model绑定的data值发生改变，视图却没变，要点一下控件才发生改变。chrome下正常。不是new Date()传参的问题。

### ISSUE THREAD

**Issue by nieyt** [mengxiong10/vue2-datepicker#271]

**Comment by mengxiong10** [comment]
展示下你的代码, 暂时没有发现这个问题

**Comment by nieyt** [comment]
templete:
`<date-picker placeholder="请选择时间" type="time" format="HH:mm:ss" confirm v-model="rule.GotoworkTime" :disabled="UserRole != 2"></date-picker>`
data里的定义:
`  data: function () {
    return {
      rule: {
        GotoworkTime: new Date(),
        ...
     }
}}}`
刚才试了一下发现，直接设置会变，但延时一些就不会变了。因为我之前写是需要拿接口的数据，会有延时，所以就没发生改变。edge下没有这个问题。ie11有，11以下没有测过。
直接设置：
`this.$set(this.rule, 'GotoworkTime', new Date(2019,3,18,8,30,0))`
延时设置：
` setTimeout(() => {
          this.$set(this.rule, 'GotoworkTime', new Date(2019,3,18,8,30,0))
         console.log("hhhh") //已经log出来了，但视图始终不发生改变。除非点一下控件
        }, 2000)`

**Comment by mengxiong10** [comment]
下面是我实验的代码, 在IE11上是OK的

```html
  <date-picker v-model="rule.value" lang="en"  type="time" format="HH:mm:ss"></date-picker>
  <button @click="reset">reset</button>
  <button @click="set">set</button>
  <button @click="timeoutSet">timeoutSet</button>
  <button @click="set2">$set</button>
  <button @click="timeoutSet2">timeout$Set</button>
```
```js
data () {
  return {
    rule: {
        value: new Date()
      },
    }
  },
  methods: {
    reset() {
    	this.rule.value = new Date()
    },
    set() {
       this.rule.value = new Date().setHours(8,30,0,0)
    },
    timeoutSet() {
       setTimeout(() => {
       	this.set()
       }, 1000)
    },
    set2() {
    	this.$set(this.rule, 'value', new Date().setHours(8,30,0,0))
    },
    timeoutSet2() {
       setTimeout(() => {
       	this.set2()
       }, 1000)
    }
  }

```

**Comment by nieyt** [comment]
是版本问题，我升级到最新版本就好了。之前用的是2.6.2
