### ISSUE TITLE
Dont allow popup when readonly

### ISSUE THREAD

**Issue by joshrobertson92** [mengxiong10/vue2-datepicker#273]
Hi,

Would it be possible to disable the popup when the input has been made readonly?

Thanks,
Josh

**Comment by mengxiong10** [comment]
set `disabled`

**Comment by joshrobertson92** [comment]
@mengxiong10 disabled works fine for this, however i have other fields on my form that are readonly, and therefore can be tabbed to and can be focused, but with disabled this isn't possible.

**Comment by mengxiong10** [comment]
Do you want it to be focused but not allow popup?
The easiest way is to set css.
```html
<date-picker v-model="value"  :popup-style="{ visibility: 'hidden' }" :editable="false" />
```

**Comment by joshrobertson92** [comment]
That worked, thanks.
