### ISSUE TITLE
please add an option like custom range to enable the calender

### ISSUE THREAD

**Issue by Waynezhi** [mengxiong10/vue2-datepicker#276]
We often use the shortcut to select range, it could be cool to have an option to disable calender, and when we select custom range (from shortcut), the calender turns to be visible.

**Comment by mengxiong10** [comment]
set `disabled`
```html
<date-picker disabled />
```

**Comment by Waynezhi** [comment]
ok, want to have an option to select range directly from shortcuts of date-picker but with calender non visible. but its not the subject here.
thanks anyway
