### ISSUE TITLE
Negative years

### ISSUE THREAD

**Issue by dinhtq** [mengxiong10/vue2-datepicker#277]
Is there a way to not only have dates disabled, but to not even show the dates? Foe example, I would like to not let the user toggle back to year < 0.

**Comment by mengxiong10** [comment]
You can implement the formatting function by yourself.
https://github.com/mengxiong10/vue2-datepicker/issues/232#issuecomment-459177746

**Comment by dinhtq** [comment]
Would I just return `null` then?

**Comment by mengxiong10** [comment]
```html
<date-picker :format="format" />
```

```js
format: {
        stringify: (date) => {
          return date ? moment(date).format('Y-MM-DD') : null
        },
        parse: (value) => {
          return value ? moment(value, 'Y-MM-DD').toDate() : null
        }
      }

```

**Comment by mengxiong10** [comment]
the moment 'Y' can be year < 0
