### ISSUE TITLE
Clearing the date or choosing a date has no effect

### ISSUE THREAD

**Issue by sam26880** [mengxiong10/vue2-datepicker#278]
I just downloaded this today and using it in my project. Everything seems to work where I see it displaying my date from the v-model. However, when choosing a date, it doesn't change the value in the text box.

Also, clicking on "x" doesn't clear the value and show placeholder

![image](https://user-images.githubusercontent.com/4713069/55243675-149b7000-5216-11e9-85b9-878204cfd5e1.png)

I'm displaying this text inside a client table from vue-tables-2

**Comment by sam26880** [comment]
Here's how I'm using it btw

<DatePicker 
                v-model="props.row.DueDate" 
                lang="en" 
                format="MM-DD-YYYY" 
                :not-before="new Date()" 
                placeholder="Select a Date" 
                input-class="form-control"
                @change="selectDate"
                append-to-body>
              <i class="glyphicon glyphicon-th" slot="calendar-icon" />
            </DatePicker>

Also, I just realized that when clicking on "x" icon it's actually calling the CHANGE event where my function "selectDate" is getting called with an invalid date of course. This doesn't make any sense. Any idea why this may be happening?

**Comment by mengxiong10** [comment]
Because you cann't v-model the props.

**Comment by sam26880** [comment]
I don't understand what that means....props is coming from a SLOT

Here's how the slot works inside the vue-tables-2 library I'm using
<v-client-table v-if="dataToDisplay.length > 0" :data="dataToDisplay" :columns="columnsDatatable" :options="optionsDatatable">

<div slot="DueDate" slot-scope="props">
            <DatePicker 
                :id="'date-'+props.row.id"
                v-model="props.row.DueDate" 
                lang="en" 
                format="MM-DD-YYYY" 
                :not-before="notBefore" 
                placeholder="Select a Date" 
                input-class="form-control"
                @change="updateTaskDueDate"
                append-to-body>
              <i class="glyphicon glyphicon-th" slot="calendar-icon" />
            </DatePicker>
 </div>
</v-client-table>

Are you saying I can't do **"v-model="props.row.DueDate"?**

**Comment by mengxiong10** [comment]
yes

**Comment by mengxiong10** [comment]
You need a local data to bind the v-model

**Comment by sam26880** [comment]
But it does grab the value from it and is displaying it just fine on the page load. Only when I change the date, it doesnt' seem to be saving it or remembering it...it just resets it back to what it was when the page loaded.

can you provide an example of how I'd do that?

**Comment by mengxiong10** [comment]
Because Vue can't change the prop in child component.
You can change the `v-model` to `value` and `Input`.
```html
<date-picker :value="props.row.DueDate" @input="changeDate(index, $event)" />
```
```js
changeDate(index, date) {
  this.dataToDisplay[index].DueDate = date
}

```

**Comment by sam26880** [comment]
very helpful...thanks..that works 👍

**Comment by sam26880** [comment]
actually..i think I spoke too quickly....everything is working now except clicking on "x" icon is causing the CHANGE event to fire which is calling my function and saves an invalid date of 12/31/1969

**Comment by mengxiong10** [comment]
Because when you click the clear button. the date is null.
You cann't to use the value like new Date(null).

**Comment by sam26880** [comment]
So what do you suggest?

**Comment by mengxiong10** [comment]
Show your code plz.

**Comment by sam26880** [comment]
Ok. Here's how I'm displaying it

<v-client-table v-if="dataToDisplay.length > 0" :data="dataToDisplay" :columns="columnsDatatable" :options="optionsDatatable">

<div slot="DueDate" slot-scope="props">
            <DatePicker 
                :id="'date-'+props.row.id"
                :value="props.row.DueDate" 
                lang="en" 
                format="MM-DD-YYYY" 
                :not-before="notBefore" 
                placeholder="Select a Date" 
                input-class="form-control"
                **@input="setDueDate(props.row.id,$event)"
                @change="updateTaskDueDate(props.row.id,$event)"**
                append-to-body>
              <i class="glyphicon glyphicon-th" slot="calendar-icon" />
            </DatePicker>
          </div>
</v-client-table>


Here's my data

```
data() {
   notBefore: new Date(),
}

methods: {
      setDueDate(taskID, dueDate) {      
          this.tasks.find(m => m.id === taskID).DueDate = moment(dueDate).format('MM/DD/YYYY');
    },

    updateTaskDueDate(taskID, dueDate) {      
      let taskToUpdate = {
        taskID : taskID,
        task : {
          DueDate : new Date(dueDate),
        }
      };
      console.log('Updating task:' + JSON.stringify(taskToUpdate));
    },
}
```

**Comment by mengxiong10** [comment]
```js

setDueDate(taskID, dueDate) {      
          this.tasks.find(m => m.id === taskID).DueDate = dueDate && moment(dueDate).format('MM/DD/YYYY');
    }
```

**Comment by sam26880** [comment]
I guess what I'm trying to understand is what is the desirable outcome here. When I click the "x" icon, it should just clear the textbox correct?

Right now, It seems to be calling my  @change event with an empty date which of course is invalid and that's why the update fails.

How do I prevent the @change from being called and just set the textbox to clear? Or are you saying that it SHOULD call the @change and then in my function, I have to detect whether the date is empty and then not do any api call to update the task due date?

**Comment by mengxiong10** [comment]
Then input event and change event is the same. Just listen one.
The value of the input box depends on the value you bound.
```
:value="props.row.DueDate"
```
when the props.row.DueDate is `null` or '', the input box is clear.
```js
setDueDate(taskID, dueDate) {
      // when you click X, the dueDate is null, so you need to set props.row.DueDate = null, then the input box is clear.
          this.tasks.find(m => m.id === taskID).DueDate = dueDate && moment(dueDate).format('MM/DD/YYYY');
    }
```

**Comment by sam26880** [comment]
I did as you suggested. Now the date picker looks like this

```
<DatePicker 
                :id="'date-'+props.row.id"
                :value="props.row.DueDate" 
                lang="en" 
                format="MM-DD-YYYY" 
                :not-before="notBefore" 
                placeholder="Select a Date" 
                input-class="form-control"
                
                @change="updateTaskDueDate(props.row.id,$event)"
                append-to-body>
              <i class="glyphicon glyphicon-th" slot="calendar-icon" />
            </DatePicker>
```

as you can see, I did as you suggested and rather than keeping both INPUT and CHANGE event, I only kept CHANGE

Here's my change function

```
updateTaskDueDate(taskID, dueDate) {      
      this.tasks.find(m => m.id === taskID).DueDate = dueDate && moment(dueDate).format('MM/DD/YYYY');   
      
      let taskToUpdate = {
        taskID : taskID,
        task : {
          DueDate : new Date(dueDate),
        }
      };
      console.log('Updating task:' + JSON.stringify(taskToUpdate)); //eslint-disable-line
     this.updateTask(taskToUpdate); // calling my API to update the task in DB
```

Now when I click on the "X" icon, it's calling my change function with invalid date. Console log prints out this
`Updating task:{"taskID":"Spz5qBU96PCKSBiolme1","task":{"DueDate":"1970-01-01T00:00:00.000Z"}}`

I don't want it to call my API when someone clicks "x". I just want it to reset the textbox so that the user can then select another date. Only then (when a new date is picked) I want the API call to be called

**Comment by mengxiong10** [comment]
```js  
    this.tasks.find(m => m.id === taskID).DueDate = dueDate && moment(dueDate).format('MM/DD/YYYY');  
     // when you click x, dueDate is null. just return
      if (!dueDate) {
        return
       }
      let taskToUpdate = {
        taskID : taskID,
        task : {
          DueDate : new Date(dueDate),
        }
      };
      console.log('Updating task:' + JSON.stringify(taskToUpdate)); //eslint-disable-line
     this.updateTask(taskToUpdate); // calling my API to update the task in DB

```

**Comment by sam26880** [comment]
Great! That works 👍
