### ISSUE TITLE
How do I get the id of the input element where the date was changed?

### ISSUE THREAD

**Issue by sam26880** [mengxiong10/vue2-datepicker#279]
I have a table with multiple rows and each row has a datepicker. When a date is changed, how do I know which input element the date was changed for?

@change event only gives me the new value that was selected.

**Comment by mengxiong10** [comment]
```html
<date-picker v-model="value1" @Change="handleChange(1, $event)"  />
<date-picker v-model="value2" @Change="handleChange(2, $event)"  />
```
```js
methods: {
    handleChange (index, date) {
      console.log(index, date)
    }
}

```

Why you want to know that?
You can listen the diffrent change event.

**Comment by sam26880** [comment]
This is not working. I have a thread going on stackoverflow about this. What am I doing wrong? All I'm getting from the change event is the date that was selected...nothing about the event

<DatePicker 
                :id="'date-'+props.row.id"
                v-model="props.row.DueDate" 
                lang="en" 
                format="MM-DD-YYYY" 
                :not-before="notBefore" 
                placeholder="Select a Date" 
                input-class="form-control"
                @change="updateTaskDueDate"
                append-to-body>

and then in my function

updateTaskDueDate(event) {
      console.log(event);
      console.log(event.target.id);
}

here's what I get.

![image](https://user-images.githubusercontent.com/4713069/55331895-43a62180-5462-11e9-8b62-eb011610fdb9.png)

**Comment by sam26880** [comment]
I even tried it like this

<DatePicker 
                :id="'date-'+props.row.id"
                v-model="props.row.DueDate" 
                lang="en" 
                format="MM-DD-YYYY" 
                :not-before="notBefore" 
                placeholder="Select a Date" 
                input-class="form-control"
                @change=**"updateTaskDueDate($event)"**
                append-to-body>

but no difference....why is the $event not being passed in....how do I read **BOTH the date that was selected AND the $event?**

**Comment by mengxiong10** [comment]
the $event will be the Date value.
```html
<DatePicker
@change="updateTaskDueDate('date-'+props.row.id, $event)"
>
```
```js

updateTaskDueDate(id, date) {
  console.log(id, date)
}
```

**Comment by sam26880** [comment]
Aah! ok. That makes sense and it works now. Thanks so much 👍 

However, I still have an issue where clicking on the "x" doesn't clear the textbox value but it actually is calling the @change event again. Any ideas?
