### ISSUE TITLE
minute-step is incompatible with AM/PM format

### ISSUE THREAD

**Issue by HapLifeMan** [mengxiong10/vue2-datepicker#280]
Hi there, this datepicker is very nice, great job! ✌🏻

I wonder if it is possible that the AM/PM format can work with the `minute-step` option?
It can be very useful and I didn't find a way to have them together.

Thanks!

**Comment by mengxiong10** [comment]
Do you mean add a column to select 'AM/PM'
![image](https://user-images.githubusercontent.com/14135808/55324038-76c4d100-54b3-11e9-8044-7c5ac4ac80ff.png)

**Comment by HapLifeMan** [comment]
I see two ways to do it:
- A new column as you said with `AM / PM` (but there would be 4 columns with seconds)
- Modify the hour column like this `...  10 AM / 11 AM / 12 AM / 1 PM / 2 PM ...`

I don't know which is the best but it's a relevant feature I think 😊

**Comment by mengxiong10** [comment]
added In v3.0
