### ISSUE TITLE
Bad behaviour with not-before and time-list

### ISSUE THREAD

**Issue by HapLifeMan** [mengxiong10/vue2-datepicker#281]
Hi,

I found an unexpected behaviour when using the `not-before` option with `new Date()`.

It is currently 17h57 and when the time picker is displayed, the hour `17` and minute `57` are both `actived` and `disabled`.

![Capture d’écran 2019-03-30 à 17 55 20](https://user-images.githubusercontent.com/1854141/55279201-27956980-5316-11e9-867e-1c54e237a3a6.png)
![Capture d’écran 2019-03-30 à 17 58 19](https://user-images.githubusercontent.com/1854141/55279204-35e38580-5316-11e9-889a-20e5c6c104ad.png)

When I click on the minute `58` for example, the `disabled`class disappear for the hour and now the `actived` is used (what it is expected by default).

![Capture d’écran 2019-03-30 à 17 58 41](https://user-images.githubusercontent.com/1854141/55279216-5dd2e900-5316-11e9-888e-c8b12dbdf90a.png)
![Capture d’écran 2019-03-30 à 17 58 32](https://user-images.githubusercontent.com/1854141/55279205-39770c80-5316-11e9-8892-018c4789c966.png)

I temporarily fixed this by using `!important` on properties in the `actived` class but this is not a long-term solution...

I think this is a bug, what do you think about that?

**Comment by mengxiong10** [comment]
Yes.
Because the value of this not-before new Date() is constantly changing
You'd better bind a constant value.

```html
<date-picker :not-before="notBefore" />

```
```js
  data () {
    return {
      notBefore: new Date(),
    }
  }

```

**Comment by HapLifeMan** [comment]
Unfortunately I need to have a `not-before` dynamic date in order to have a date-range with two fields...

**Comment by mengxiong10** [comment]
Yes, you can.
I mean you can't write new Date() directly in the template, you have to use a variable to store.
```
<date-picker :not-after="end" v-model="start" />
<date-picker :not-before="start" v-model="end" />

```

**Comment by HapLifeMan** [comment]
That's what I did and I don't know why it doesn't work 🤔

**Comment by mengxiong10** [comment]
https://codesandbox.io/embed/6yrnkmr26r

**Comment by HapLifeMan** [comment]
Ok I found the bug! => https://codesandbox.io/s/q7y8y64894
With a `not-before` and `minute-step` > 1, the next available minute is not selected by default.

**Comment by namnnh** [comment]
same issue @HapLifeMan , any solution for it ?

**Comment by HapLifeMan** [comment]
I don't have any solution, but maybe @mengxiong10 can solve this.

**Comment by mengxiong10** [comment]
@HapLifeMan 
set the minutes of `notBefore` to be one of  the minute list.
```
notBefore: new Date().setMinutes(45),
```

**Comment by eaionov** [comment]
Does anyone knows how to set time range, for example, from 08:15 to 13:25? I tried to use "not-before" and "not-after" properties, "not-after" works perfectly, but "not-before" doesn't allow me to chose time before 09:00.

**Comment by mengxiong10** [comment]
@eaionov 
I think you need a fixed time list to select. https://mengxiong10.github.io/vue2-datepicker/index.html#FixedTimeList

**Comment by mengxiong10** [comment]
v3.x.  Use a function `disabledTime` to achieve `not-before` .
And the `defaultValue` is valid for time.
You should set the `defaultValue` is not disabled.
```html
<date-picker
  v-model="value"
  type="time"
  format="HH:mm"
  // is always valid
  :default-value="new Date(new Date().getTime() + 60000)"
  :disabled-time="disabledTime"
></date-picker>
```

```js
export default {
  data() {
    return {
      value: null,
    };
  },
  methods: {
    disabledTime(date) {
      return new Date() > date;
    }
  }
};

```

**Comment by mengxiong10** [comment]
The problem is that the default time is always 00:00:00 in v2.x.
You can change the default time by `defaultValue` in 3.x.

**Comment by suresh444** [comment]
not-before and  not-after are not working ....How to disable before  the start date and after the end date  ??

**Comment by danstoian07** [comment]
In "vue2-datepicker": "^3.8.1", not-before and not-after are not working.
I got back to version 2, but there the "name" attribute is not working.
I hope you can fix this! :)

**Comment by mengxiong10** [comment]
@danstoian07  use `disabledDate`.https://mengxiong10.github.io/vue2-datepicker/index.html#DisabledDateTime
```html
<date-picker :disabledDate="disabledDate" />
```
```js

  methods: {
    disabledDate(date) {
      const notBefore = new Date();
      cosnt notAfter = new Date(Date.now() + 24 * 3600 * 1000)
      return date < notBefore || date > notAfter;
    },
}

```
