### ISSUE TITLE
datepicker minus one day

### ISSUE THREAD

**Issue by musman92** [mengxiong10/vue2-datepicker#282]
when i enter date manually or copy/paste the date, 
the datepicker minus the it by one day

like i paste 15/06/2020 
it become 14/06/2020

**Comment by mengxiong10** [comment]
Can you show your code plz.

**Comment by mengxiong10** [comment]
set the valueType="format" to solve the timezone problem. #43

**Comment by chemoral87** [comment]
Yes it works, but if i want to set date YYYY-MM-DD and display input DD-MMM-YYYY, how can i achieve it?? 

// input set YYYY-MM-DD (ok) but i need to display input picker DD-MMM-YYYY
<date-picker :input-class="'form-control'" format="YYYY-MM-DD" lang="es" v-model="edit_userrole.start_date"></date-picker>

I read advance value-type, but i dont have an example
 {
  value2date: (value: any) => Date,  // transform the binding value to calendar Date Object
  date2value: (date: Date) => any   // transform the calendar Date Object to binding value
}

**Comment by mengxiong10** [comment]
https://codesandbox.io/s/ovo5699okq?fontsize=14
```html
<datePicker lang="en" v-model="date" format="DD-MMM-YYYY" :value-type="valueType"></datePicker>
```
```js
  data() {
    const valueType = {
      value2date: value => {
        // transform String to Date
        return value ? moment(new Date(value), "YYYY-MM-DD").toDate() : null;
      },
      date2value: date => {
       // transform Date to String
        return date ? moment(date).format("YYYY-MM-DD") : null;
      }
    };
    return {
      valueType,
      date: null
    };
  }
```
