### ISSUE TITLE
Suggestion: Disabled state - no hover icon change

### ISSUE THREAD

**Issue by KonradDeskiewicz** [mengxiong10/vue2-datepicker#283]
Hi,

Current behavior of date indicator that change to "remove" indicator on hover is fine, 
however it shouldn't happened if element is disabled, as this can be confusing for users.

Icon change somehow suggest that input is still active but "broken"

**Comment by mengxiong10** [comment]
Which version do you use?

**Comment by KonradDeskiewicz** [comment]
2.10.3
My bad. Disabled state was controlled dirtectly on <input> in DOM. I haven't spot that at the time so this is what caused unexpected behavior. Once old code was removed and replaced with proper "Vue" props all works fine :) Closing now :)
