### ISSUE TITLE
Control not clearing date when text is removed inside the textbox

### ISSUE THREAD

**Issue by trsiddiqui** [mengxiong10/vue2-datepicker#284]
How to reproduce:
1. Put an instance of the control with v-model set to a variable.
2. Select or type a valid date and move to another field. Confirm that the variable is set to the selected/typed date.
3. Focus on the date field again, remove the text and move to another field. 
4. The variable is still set to the date typed/selected before while the text box and the calendar that appears on focusing on the textbox shows no selected date.

A simple watch on the input value where its checked for empty would suffice. Thanks.

**Comment by mengxiong10** [comment]
use the `clear` event ?

**Comment by trsiddiqui** [comment]
How do i hook on to the text clear event of the control?

**Comment by mengxiong10** [comment]
```html
<date-picker @clear="handleClear" />
```

**Comment by mengxiong10** [comment]
when the text is clear, the value is null.
