### ISSUE TITLE
display format for year buddhist (Thai year)

### ISSUE THREAD

**Issue by mahadoang** [mengxiong10/vue2-datepicker#285]
Thai-year uses Buddhist-Era (B.E.) that is 543 years greater than Christian-Era (C.E.).

**Comment by mengxiong10** [comment]
Sorry, I don’t understand what you mean. what can I do for you?

**Comment by mahadoang** [comment]
How to Format display for Thai year because  Thai-year uses Buddhist-Era (B.E.) that is 543 years greater than Christian-Era (C.E.).
Example.
**2019-01-31** format for Thai year  **2562-01-31**

Thanks you.

**Comment by mengxiong10** [comment]
try this
```html
<date-picker v-model="value" lang="en" :format="myFormat" ></date-picker>
```

```js
  data() {
    return {
      myFormat: {
        stringify: (date) => {
          return date ? moment(date).add(543, 'y').format('[Thai year] YYYY-MM-DD') : null
        },
        parse: (value) => {
          return value ? moment(value, '[Thai year] YYYY-MM-DD').subtract(543, 'y').toDate() : null
        }
      },
      value: null 
    };
  }

```

**Comment by mahadoang** [comment]
Thank you.

**Comment by ucyaka** [comment]
@mengxiong10 Can you help me to change years on the  mx-calendar-header to Buddhist year + 543

Thx

**Comment by mengxiong10** [comment]
@ucyaka 
```html
<date-picker v-model="buddhistDate" />
```

```js
data() {
  return {
     date: new Date()
   }
},
computed: {
  buddhistDate: {
    get() {
       if (this.date) {
         const date = new Date(this.date)
         date.setFullYear(date.getFullYear() + 543)
          return date
       }
      return null
    },
    set(value) {
    if (value ) {
     const date = new Date(value)
     date.setFullYear(date.getFullYear() - 543)
     this.date =  date
    }
   this.date = null


   }
  }
}


```

**Comment by ucyaka** [comment]
Thx @mengxiong10 
Now My calendar header show correctly
but mx-calendar-content can't show properly

**Comment by mengxiong10** [comment]
@ucyaka 
Do you mean you just need to change the year in header + 543?
I think you can use a custom element to cover it.
```html
<date-picker v-model="value" />
<div :style="position: absolute; top: ..., left: ...">{{ value.getFullYear() + 543 }}</div>
```

**Comment by ucyaka** [comment]
No
I mean 23/05/2022 is Monday not Thursday
![image](https://user-images.githubusercontent.com/91123717/169768589-1bc1b8f2-debc-44c0-820e-1447243a70a0.png)
![image](https://user-images.githubusercontent.com/91123717/169768826-3142783a-4c4b-4fcc-85fe-ba3e0025cf45.png)

**Comment by mengxiong10** [comment]
@ucyaka This function don't supports now, only can change the input text.
https://github.com/mengxiong10/vue2-datepicker/issues/285#issuecomment-479479552

**Comment by ucyaka** [comment]
@mengxiong10 Thx so must
