### ISSUE TITLE
calendar-change event not firing

### ISSUE THREAD

**Issue by handrej** [mengxiong10/vue2-datepicker#286]
Event `select-time` seems to be firing when changing dates in the newest releases instead of `change-calendar`.

**Comment by mengxiong10** [comment]
the `calendar-change` is fired.
https://codesandbox.io/s/6yrnkmr26r?fontsize=14

**Comment by handrej** [comment]
Odd, maybe it's on my end but those are the events which are being emitted, after selecting a date in your link. I also don't get the alert for `handleChangeCalendar`.

![image](https://user-images.githubusercontent.com/8639175/55482327-8fa0c400-5624-11e9-8023-4efbd27594e3.png)

**Comment by mengxiong10** [comment]
Can you show your code plz

**Comment by handrej** [comment]
I was using your https://codesandbox.io/s/6yrnkmr26r?fontsize=14 in Chrome with the Vue.js Extension for Events.

**Comment by mengxiong10** [comment]
the `calendar-change` is fired when you change the calandar. ie: click the >

**Comment by handrej** [comment]
Oooh my bad, i see now, sorry for the misunderstanding. I used it in prior versions to capture events if the date was changed, maybe I'm using it wrong actually.

Thanks for the clear up.
