### ISSUE TITLE
Missing configuration of context

### ISSUE THREAD

**Issue by cichy380** [mengxiong10/vue2-datepicker#287]
Clicking outside the `.mx-datepicker` element will close the calendar-popup. Event **clickoutside** has listener on `document`.

part of code of clickoutside directive:
```
document.addEventListener('click', el['@clickoutside'], false)
```

 But when I want to use the datepicker on element inside the element with `clickEvent.stopPropagation()` then clickoutside procedure will not work!

For example, when I want to use datapicker inside the Bootstrap Modal I had a problem :/

For me.. in configuration is missing context (root, parent) html element which datepicker will be append to. Clickoutside should looks:
```
var context = context || document
context.addEventListener('click', el['@clickoutside'], false)
```

**Comment by mengxiong10** [comment]
I have modified the implementation of clickoutside, now it can be used when `clickEvent.stopPropagation()`
