### ISSUE TITLE
confirm: value doesn't change on "OK", if only year and/or month were changed

### ISSUE THREAD

**Issue by caugner** [mengxiong10/vue2-datepicker#290]
The month and year of a date cannot currently be changed alone (using the UI).

## Steps to reproduce
0. `<date-picker v-model="value" confirm />`
1. Choose a date, e.g. 2019-04-07.
2. Choose a different year, e.g. 2020, and press "OK".
3. Date is still 2019-04-07.
4. Choose a different month, e.g. 05, and press "OK".
5. Date is still 2019-04-07.

## Expected result
It should be possible to change ...
1. the month without having to choose the day again.
2. the year without having to choose the month (and the day) again.

## Actual result
The changes are ignored unless day or month and day are chosen.

**Comment by mengxiong10** [comment]
v2.11.0 added `select-year` and `select-month`.
```html
<date-picker @select-year="handleSelectYear" @select-month="handleSelectMonth" v-model="value" lang="en" ></date-picker>
```
```js

    handleSelectYear (year) {
      if (this.value) {
        this.value = new Date(new Date(this.value).setFullYear(year))
      }
    },
    handleSelectMonth (month) {
      if (this.value) {
        this.value = new Date(new Date(this.value).setMonth(month))
      }
    }
```

**Comment by mengxiong10** [comment]
The `select-year` event will only be triggered by selecting the year. 
The `calendar-change` event will be triggered by clicking the arrow too. 
The `confirm` event will only be triggered by clicking the `OK` button.
You can achieve what you need by https://github.com/mengxiong10/vue2-datepicker/issues/290#issuecomment-481237289

**Comment by caugner** [comment]
> The confirm event will only be triggered by clicking the OK button.

However, if I select a year and then click the `OK` button, the payload of the confirm event does still include the old year.

**Comment by mengxiong10** [comment]
https://codesandbox.io/s/9812vnx124?fontsize=14

**Comment by caugner** [comment]
> https://codesandbox.io/s/9812vnx124?fontsize=14

If I add `confirm` (https://codesandbox.io/s/8287rwol7j), the date changes before I press `OK`.

**Comment by mengxiong10** [comment]
If you need to confirm the `select-year`
https://codesandbox.io/s/vvz89oqno3

**Comment by caugner** [comment]
I respect that you don't agree with me, so I'm closing this issue and will suggest your proposed solution/workaround in https://github.com/nextcloud/nextcloud-vue/issues/137.

PS: I still think it's a pity that I need to handle two events *and* call a method on the instance to get a behaviour that I would expect by default (being consistent with the UX of other datepickers). For example, Android's [DatePicker](https://developer.android.com/reference/android/widget/DatePicker) allows setting a `minDate` and a `maxDate` and still allows changing the year on it's own; the `OnDateChangedListener` is only called with dates that adhere to these constraints.

**Comment by caugner** [comment]
Let me add:
Thank you for developing this library, taking the time to respond and providing a solution!
And sorry for my insistence in this matter.

**Comment by caugner** [comment]
> https://codesandbox.io/s/9812vnx124?fontsize=14

Unfortunately, there is a problem with your suggested workaround: If year **and** month are changed in one go, only the month is changed upon confirmation:

![](https://media.giphy.com/media/h534Poz84yG2ObWdXr/giphy.gif)
(Source: https://github.com/nextcloud/contacts/issues/1196)

Do you have a tip how to fix this?

**Comment by mengxiong10** [comment]
```js
    handleSelectYear(year) {
      let value = this.$refs.datepicker.currentValue;
      if (value) {
        value = new Date(new Date(value).setFullYear(year));
        this.$refs.datepicker.selectDate(value);
      }
    },
    handleSelectMonth(month) {
      let value = this.$refs.datepicker.currentValue;
      if (value) {
        value = new Date(new Date(value).setMonth(month));
        this.$refs.datepicker.selectDate(value);
      }
    }

```

**Comment by caugner** [comment]
Thanks a lot, @mengxiong10.

**Comment by mengxiong10** [comment]
I added a prop `partial-update`  implement this feature in ^3.0.2.
https://codesandbox.io/s/partial-update-kc4k1?fontsize=14&hidenavigation=1&theme=dark
