### ISSUE TITLE
calendar-icon slot is overlapped by close icon

### ISSUE THREAD

**Issue by pravdinalex** [mengxiong10/vue2-datepicker#297]
I add some calendar icon in the right:
```
                    <template slot="calendar-icon">
                        <font-awesome-icon
                            icon="calendar-check"
                            class="text-success"
                        ></font-awesome-icon>
                    </template>
```
when `:clearable="true"`, and component is hovered, I got this:

![image](https://user-images.githubusercontent.com/2210640/56423312-27a0dd80-62b4-11e9-9124-c306f62c711f.png)

(background set to `inherit` - otherwise if input is disabled calendar icon is on white background on gray input. Ok, we can set solid background, but then problem arises when calendar icon is bigger than close ison...)

Maybe hide calendar-icon slot when close icon is shown? otherwise I shoul do some CSS hacks

**Comment by mengxiong10** [comment]
Which Version?

**Comment by pravdinalex** [comment]
```
"vue2-datepicker": {
      "version": "2.10.0",
      ...
    }
```

**Comment by mengxiong10** [comment]
v2.10.2 had solved it

**Comment by pravdinalex** [comment]
really, sorry, thank you!

**Comment by Aiba0** [comment]
How did you decide? I have the same problem (

**Comment by mengxiong10** [comment]
@Aiba0 which version?

**Comment by HamzaAdam** [comment]
<img width="196" alt="Screenshot 2023-05-11 at 2 23 12 PM" src="https://github.com/mengxiong10/vue2-datepicker/assets/17048792/4f81751b-e367-47aa-879d-6ad79a388b0a">
I am having this issue clear icon is overlapping text & user is unable to recognised what is it
