### ISSUE TITLE
Datepicker always in open mode 

### ISSUE THREAD

**Issue by dhruvalviradiya** [mengxiong10/vue2-datepicker#298]
Hello,
Is there any way to keep this date picker in open mode.

**Comment by mengxiong10** [comment]
You can prevent closePopup
```html
<date-picker v-model="value" ref="datepicker" @panel-change="handlePanelChange"/>
```
```js
methods: {
  handlePanelChange (panel) {
    if (panel === 'NONE') {
      this.$refs.datepicker.showPopup()
    }
  }
},
mounted () {
  this.$refs.datepicker.showPopup()
},

```

**Comment by dhruvalviradiya** [comment]
@mengxiong10 ,
Thanks for you answer. but it is not exact as i am looking for.
For your better understanding i am attaching few images.
first one is what i get after applying your solution and second one is what i actually need.

![Screenshot 2019-04-25 at 4 55 41 PM](https://user-images.githubusercontent.com/25316354/56732646-aea1fa00-677b-11e9-9dc1-2adadbb9f42b.png)
![Screenshot 2019-04-25 at 4 56 52 PM](https://user-images.githubusercontent.com/25316354/56732655-b2358100-677b-11e9-8399-07759d8abc49.png)

 

Waiting for your response.
Thanks in advance.

**Comment by mengxiong10** [comment]
https://github.com/mengxiong10/vue2-datepicker/issues/181#issuecomment-433781799

**Comment by dhruvalviradiya** [comment]
Thanks @mengxiong10 .
It's working for me.

**Comment by JoaoPedroAS51** [comment]
Hi @dhruvalviradiya , I'm not sure if you still needing help, but I've been working on this feature and if you want, you can use my fork https://github.com/JoaoPedroAS51/vue2-datepicker/tree/feat/add-static-option :)

#### Usage:
```
<date-picker v-model="value" static />
```
