### ISSUE TITLE
Selecting Shortcut while confirm is true does not close the calendar panel

### ISSUE THREAD

**Issue by timothymarois** [mengxiong10/vue2-datepicker#299]
When confirm is on, you must select "OK" to change the date range and close the calendar panel popup. But if you select the shortcut link, it changes the calendar date range (confirming) automatically but does not close the calendar panel. 

This should either, 

1) close the calendar panel automatically on the shortcut link.

or 

2) change the date range, but the user must confirm first. 

I think 1 is best because it is a shortcut link, but right now the user must close the calendar panel manually by clicking OK, **which ends up loading ajax twice.**

**Comment by mengxiong10** [comment]
I think the first suggestion is very good, I will implement it in the next version.

**Comment by mengxiong10** [comment]
v2.11.1 fix it.
