### ISSUE TITLE
时区的问题怎么解决呀？

### ISSUE THREAD

**Issue by wesleyqiwei** [mengxiong10/vue2-datepicker#3]
在中国和美国显示的日期不一致，我用了很多方法都不管用。

**Comment by blackpuppy** [comment]
我用[moment-timezone](https://momentjs.com/timezone/):

```
moment(this.filterDateRange[0]).tz('Asia/Shanghai').format('YYYY-MM-DD');
```

**Comment by wesleyqiwei** [comment]
我把YYYY-MM-DD 改成了YYYY/MM/DD 结果时间就固定了，也不知道有没有弊端，加上了start-time和end-time，moment-timezone:我没使用过。

**Comment by mengxiong10** [comment]
@wesleyqiwei 这个问题, 我可能没看明白. 显示不一致? new Date() 是显示的当地时间.  这个需求是选择日期后显示的UTC时间吗?
