### ISSUE TITLE
suggest add valueType as default demo, it's important.

### ISSUE THREAD

**Issue by 016** [mengxiong10/vue2-datepicker#301]
首先作为中文用户很感谢你能写出这样的插件，非常非常好用，我试用了好多个这个是最帅的， 最顺手的一个，加油。

please try add valueType="format" to the first demo on introduce page, because the date value back to v-model value is not format, and it's not very easy to found the solution(I spent about 2 hours on it, it's just a config 2 mins work at max), and I guess the valueType="format" will cover 90% use condition, no one want return a date object I think.

so plz do this it will be more friendly to new use.

if I didn't search git issues, I may direct use moment to do the format, it's definitely double work.

again thx for ur work, it's amazing..

**Comment by mengxiong10** [comment]
Thanks for the suggestion. It had been added to the demo
