### ISSUE TITLE
date pick not display lang month

### ISSUE THREAD

**Issue by chemoral87** [mengxiong10/vue2-datepicker#305]
<date-picker format="MMM-YYYY" input-class="form-control" lang="es" type="month" ></date>

I pick the date "Dic 2019" in Spanish, but the input says "Dec-2019" in english. I would expect the input text  "Dic-2019"

thanks

**Comment by mengxiong10** [comment]
duplicate of https://github.com/mengxiong10/vue2-datepicker/issues/111#issuecomment-399625732
