### ISSUE TITLE
clear button 报错

### ISSUE THREAD

**Issue by myclcs** [mengxiong10/vue2-datepicker#309]
![image](https://user-images.githubusercontent.com/49704546/57686313-f37acb80-766b-11e9-9f0f-8409098d2921.png)
![image](https://user-images.githubusercontent.com/49704546/57686343-01c8e780-766c-11e9-8340-09fadd16bf48.png)

选择一个时间后点击清除按钮时出现这个错误

<date-picker range format="YYYY-MM-DD" value-type="format"></date-picker>
目前发现当 range、format、value-type 同时存在时出现这个bug

**Comment by mengxiong10** [comment]
谢谢反馈.
v2.11.2 修复了这个bug.
