### ISSUE TITLE
To show the next month when the days of the current month are disabled 

### ISSUE THREAD

**Issue by kolosovvs** [mengxiong10/vue2-datepicker#311]
Is it possible to show the next month when all the dates of the current month are disabled?

**Comment by mengxiong10** [comment]
use the `default-value`

**Comment by kolosovvs** [comment]
![image](https://user-images.githubusercontent.com/37772988/58025008-287b9800-7b1c-11e9-8c5f-ebf1e4c0fde5.png)
in this case I need to show June

**Comment by mengxiong10** [comment]
<date-picker :default-value="new Date(2019, 5,1)" />

**Comment by kolosovvs** [comment]
Thanks
