### ISSUE TITLE
inline calendar 

### ISSUE THREAD

**Issue by Ali7862** [mengxiong10/vue2-datepicker#312]
There is no option without input.

**Comment by mengxiong10** [comment]
#181

**Comment by JoaoPedroAS51** [comment]
Hi @Ali7862, last week I sent a [PR](https://github.com/mengxiong10/vue2-datepicker/pull/307) that add this feature. If you want, you can use my fork https://github.com/JoaoPedroAS51/vue2-datepicker/tree/feat/add-static-option :D

#### Usage:
```
<date-picker v-model="value" static />
```

**Comment by CharlesOkwuagwu** [comment]
@JoaoPedroAS51 Please how can I use your version directly from `npm install`?

**Comment by JoaoPedroAS51** [comment]
Hi! Thank you for reach me out!

I guess you can use this command: `npm install  git://github.com/JoaoPedroAS51/vue2-datepicker.git#feat/add-static-option --save`

And if you find any bug, let me know!
________________________________
De: Charles <notifications@github.com>
Enviado: segunda-feira, 17 de junho de 2019 08:26
Para: mengxiong10/vue2-datepicker
Cc: João Pedro Antunes Silva; Mention
Assunto: Re: [mengxiong10/vue2-datepicker] inline calendar (#312)


@JoaoPedroAS51<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJoaoPedroAS51&data=02%7C01%7C%7Cbfc3fe87e7544d06ccff08d6f316b227%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636963676132045299&sdata=yiwKnJUQ9BGzzCUt8Q%2BTsDB3S%2Btdj4X6WgPmkzDhAcY%3D&reserved=0> Please how can I use your version directly from npm install?

**Comment by CharlesOkwuagwu** [comment]
This error comes:


 ERROR  Failed to compile with 1 errors                                                               5:55:55 PM

This dependency was not found:

* vue2-datepicker in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Reports.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save vue2-datepicker

**Comment by JoaoPedroAS51** [comment]
@CharlesOkwuagwu Sorry my mistake. This branch is only for merge, it doesn't have dist files. You can use `custom` branch. `npm install  git://github.com/JoaoPedroAS51/vue2-datepicker.git#custom --save`

**Comment by CharlesOkwuagwu** [comment]
works now, thanks

**Comment by mengxiong10** [comment]
v3.x add the inline feature.
```
<date-picker inline />
```
