### ISSUE TITLE
Input refocus after selecting a date

### ISSUE THREAD

**Issue by DragosPeta** [mengxiong10/vue2-datepicker#315]
Greetings, is there an elegant way to refocus the datepicker input after selecting a date only from the popup without reopening it?
It would be useful because i need to submit a form using the enter key too.
I understand that it might interfere with the popup functionality.

Thanks!

**Comment by mengxiong10** [comment]
Sorry, I may not fully understand what you need.
when the input box is in focus, to open the popup is a feature.

**Comment by DragosPeta** [comment]
Basically i wanted after selecting a date from the popup, to keep the input focused so that i can press enter to submit the form.

**Comment by mengxiong10** [comment]
Maybe you can try this.
```html
<form @submit="handleSubmit" >
  <date-picker v-model="value1" valueType="format" @change="handleChange"  />
  <input type="submit" ref="input" style="position: absolute; left: -9999px" />
</form>
```
```js
handleChange () {
   this.$refs.input.focus()
}
```

**Comment by DragosPeta** [comment]
Thanks!
