### ISSUE TITLE
Popup closes when shortcut is pressed when it should not.

### ISSUE THREAD

**Issue by alpha1d3d** [mengxiong10/vue2-datepicker#316]
There is a bug where if props are set to:
  - `confirm` ;
  - `range`; and 
  - `shortcuts` are in format `[{text, start, end}]`

e.g.
```
   <date-picker
          range
          confirm
          :shortcuts="[{text:' Today', start: new Date(), end: new Date()}]"
    />
```
Clicking on the shortcut will preemptively close the popup and not update the date.

This should not happen because `confirm` is set to `true`, instead it should just update the `currentValue` and not `closePopup`.

See below PR for fix.

**Comment by mengxiong10** [comment]
If you bind value with `v-model`, it'll update.
When confirm is set and click the shortcut, the value is not update In old version.
Many people think that shortcut operations should not need to be confirmed, so there is no need to confirm now.
