### ISSUE TITLE
range-separator is always using the default value

### ISSUE THREAD

**Issue by Jujaju** [mengxiong10/vue2-datepicker#318]
Hello, 

loving this datepicker so far, yet I have some difficulties to overwrite the range-seperator. Is this an known issue?

```
 <DatePicker v-model="dateYear"
                      placeholder="Jahr"
                      range-separator="-"
                      format="YYYY"
                      type="year"
                      lang="de"
                      :editable="dateYearEditable">
</DatePicker>
```

**Comment by mengxiong10** [comment]
https://codesandbox.io/s/gallant-euler-wz4j413z8?fontsize=14
```html
<datePicker lang="en" v-model="date" format="DD-MMM-YYYY" range range-separator="--"></datePicker>
```

**Comment by Jujaju** [comment]
Thanks - I somehow assumed that the range-separator will change the ~ in the header of the datepicker, too. Is there a chance to adapt this and make it consistent?

**Comment by Jujaju** [comment]
I stated a pull request considering this behaviour :) Greetings

**Comment by mengxiong10** [comment]
It can be change by css in ^3.0.2.
```css
.mx-calendar-decade-separator:after {
    content: "~";
}

```
