### ISSUE TITLE
Functional components without render functions

### ISSUE THREAD

**Issue by OwenMelbz** [mengxiong10/vue2-datepicker#32]
Hi guys,

Recently we've updated vue to `2.5.9`

Now when we compile we're getting 

![ideas_-_ideas_work](https://user-images.githubusercontent.com/1094740/33373636-bb1e74e4-d4fa-11e7-9f5c-4c7397dfce44.jpg)

Any suggestions as to how to fix this?

Thanks

**Comment by mengxiong10** [comment]
I try it with vue 2.5.9&& vue-loader 13.5.0. It's normal without error. 
The error should be from vue-loader. Or you use the functional option somewhere.
Can you give me more info.

**Comment by OwenMelbz** [comment]
Hmm, This is a dump of the versions we're using

```
├─ vue-hot-reload-api@2.2.4
├─ vue-loader@13.5.0
├─ vue-resize@0.4.3
├─ vue-style-loader@3.0.3
├─ vue-template-compiler@2.5.9
├─ vue-template-es2015-compiler@1.6.0
├─ vue@2.5.9
├─ vue2-datepicker@1.6.2
```

What other information would be helpful do you think?

Do you know what the functional options are?

**Comment by mengxiong10** [comment]
https://vuejs.org/v2/guide/render-function.html#Functional-Components
How do you use the Datepicker.
I think the problem is on vue-loader.
I suggest you copy the file directly, and then try to import them as a common component instead of  npm.
I consider packing them into js file.

**Comment by mengxiong10** [comment]
I removed the inner template tag. And publishd v1.6.3.
I am not sure if this will solve your problem
