### ISSUE TITLE
Format YYYY/MM not working on IE11

### ISSUE THREAD

**Issue by lequy1010** [mengxiong10/vue2-datepicker#320]
I want to format date YYYY/MM on IE11 but it's not working. on Chrome is OK.
Please help to verify it.
`<date-pickers v-model="model.searchYm"  :elementId="'searchYm'" :type="'date'" :format="'YYYY/MM'" maxlength="7" :input-class="'datepicker'" placeholder="YYYY/MM"/>`

**Comment by bubgdgnanh** [comment]
Hi @mengxiong10,
I met the similar issue, when setting format is "YYYY/MM". Data cannot display on IE. 

I try to using "YYYY-MM", it is OK.
I try to use jquery to set value for it as format "YYYY/MM" but not success.

If you have free time, please help to take a look.
Thank you so.

**Comment by mengxiong10** [comment]
@lequy1010 
What's the version you used.
I try it in IE11, It's ok.
And why you don't use the 'DD' in your format when you use the 'date picker' not 'month picker'.

**Comment by mengxiong10** [comment]
@bubgdgnanh 
Can you show your code. Why you don't set the type with month

**Comment by lequy1010** [comment]
@mengxiong10 thank you for reply soon.
I'm using IE11 as capture.
![image](https://user-images.githubusercontent.com/7949193/59080025-cfc83f80-8910-11e9-8dfa-bb8766da7a1e.png)

I used type="month" and it can show month but when click on it so it's not binding to input.
![image](https://user-images.githubusercontent.com/7949193/59080266-14080f80-8912-11e9-9609-7948817647c4.png)

**Comment by mengxiong10** [comment]
The lastest vue2-datepicker version is 2.11.2.
![image](https://user-images.githubusercontent.com/14135808/59080518-b2e53980-891b-11e9-8524-fe000da0fbae.png)

**Comment by lequy1010** [comment]
@mengxiong10 thank you so much,
I will try again with the latest version.

**Comment by bubgdgnanh** [comment]
@mengxiong10 Thank you so much. I updated lastest version but got issue as below:

I set '2019/06' for v-model in mounted but it doesn't display (aboth on chrome/IE). 
when selecting on pop-up, it's OK to display.

Please help to check again with lastest version
Thank you so much for quickly feedback.

**Comment by mengxiong10** [comment]
@bubgdgnanh Do you set the valueType 'format'.

**Comment by bubgdgnanh** [comment]
@mengxiong10 
No, I don't use it. 
Do you need to use it for this case? 
Please help to let me know how to use it if need.

**Comment by mengxiong10** [comment]
@bubgdgnanh you need set valueType 'format', then your value of `v-model` will be a formatted string(2019/06) not a Date Object.
```html
<date-picker value-type="format" v-model="value" />
```

**Comment by bubgdgnanh** [comment]
Thank @mengxiong10 for your feedback. I used value-type as your comment but this issue still happens, please help to take a look.

Below is my issue, I has just edited the content to easier understand:
When selecting on pop-up, it's OK to display (2019/06).
But if you set string('2019/06') for v-model in mounted, string(2019/06) will be displayed after that.

I hope you will reproduce this issue and have another way to resolve it.
Thank you so much.

**Comment by bubgdgnanh** [comment]
Please try to use type="'month'" for this case.

**Comment by mengxiong10** [comment]
Can you write a CodeSandbox.
https://codesandbox.io/s/range-separator-ip9wr

**Comment by bubgdgnanh** [comment]
Thanks @mengxiong10, this is my bad.

This issue is resolved.

Thank you so much again.
