### ISSUE TITLE
v-model errors

### ISSUE THREAD

**Issue by jsmera** [mengxiong10/vue2-datepicker#322]
With this:
`<date-picker v-model="query" lang="en" type="month" format="MMM YYYY"></date-picker>`

I am getting:
1. $attrs is readonly.
2. $listeners is readonly.
3. Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"

**Comment by mengxiong10** [comment]
update the `Vue` version

**Comment by jsmera** [comment]
I have 2.6.10 version

**Comment by mengxiong10** [comment]
Can you show your complete code?
The error was caused by your binding value of `v-model`.

**Comment by jsmera** [comment]
```
<template>
<date-picker v-model="query" lang="en" type="month" format="MMM YYYY"></date-picker>
</template>

<script>
import DatePicker from 'vue2-datepicker'

export default {
  components: {
    DatePicker
  },
  props: {
    initial_date: {
      type: Date,
      required: true
    }
  },
  data() {
    return {
      query: "",
    }
  },
  watch: {
    initial_date: {
      immediate: true,
      handler(value) {
        this.query = new Date(value)
      }
    }
  },
}
</script>
```
