### ISSUE TITLE
AutoClose Not Working

### ISSUE THREAD

**Issue by mintunitish** [mengxiong10/vue2-datepicker#326]
Auto Close of the datepicker popup is not triggered when using two date-pickers side by side.

**Comment by mengxiong10** [comment]
which version?
Can you show your code?

**Comment by r0hanc** [comment]
I'm using 
    "vue2-datepicker": "^2.12.0",
    "moment": "^2.24.0"

Having the same issue. Will try and create reproducible sandbox

**Comment by mengxiong10** [comment]
@r0hanc 
https://codesandbox.io/embed/6yrnkmr26r?fontsize=14

**Comment by mengxiong10** [comment]
fixed in lastest version.

**Comment by rolexta** [comment]
same issue with nuxt v2.15.4
