### ISSUE TITLE
Date in time panel will disappear when clear the time

### ISSUE THREAD

**Issue by humengchuan** [mengxiong10/vue2-datepicker#327]
in 2.11.2, datepicker type is datetime. I click clear button when pick the time. the date in time panel will disappear
![TIM截图20190717102412](https://user-images.githubusercontent.com/11323790/61342575-3bd98400-a87d-11e9-8a86-7a98da1ec1dc.png)
after clear the time
![TIM截图20190717102432](https://user-images.githubusercontent.com/11323790/61342584-43009200-a87d-11e9-8708-aef6e2202910.png)

**Comment by mengxiong10** [comment]
Thanks for your feedback.
Becase the date is null.
I think the panel should be closed when you click the clear button.

**Comment by mengxiong10** [comment]
v3.0.0,The panel will closed when click clear button.
