### ISSUE TITLE
Disable

### ISSUE THREAD

**Issue by sokolovdev** [mengxiong10/vue2-datepicker#328]
How to disable all dates until today?
Thanks.

**Comment by mengxiong10** [comment]
const today = new Date();

`:not-after="today"`

**Comment by Arjun3023** [comment]
> `:not-before="new Date()"`

Please add this in README.md as its not available there

**Comment by mengxiong10** [comment]
in v3.x. Replace it with `disabledDate`. 
[ChangeLog](https://github.com/mengxiong10/vue2-datepicker/blob/master/CHANGELOG.md).
[Demo](https://mengxiong10.github.io/vue2-datepicker/index.html#DisabledDateTime)
