### ISSUE TITLE
@notBefore not working as expected on time picker

### ISSUE THREAD

**Issue by walderpinheiro** [mengxiong10/vue2-datepicker#331]
When i'm using `@notBefore` for a time picker i can't choose a time in the same hour that my before date

Code: 
``` vue
<date-picker :notBefore="beforeData" type="time"/>
```
``` javascript
data () {
   return {
      beforeData: new Date('Mon Jul 22 2019 01:03:00 GMT-0300 (Horário Padrão de Brasília)')
   }
}
```

In this specific scenery i can't select another value on the same hour, however if my before date start in 00 minutes i can select any value

**Comment by mengxiong10** [comment]
The beforeData you need to set the day is today in time component.
 And you can set the default value is equal to beforeData. 
```html
<date-picker :notBefore="beforeData" v-model="value" type="time" format="HH:mm:ss"  />
```
```js
  data() {
    return {
      beforeData: new Date().setHours(1, 3, 0),
      value: new Date().setHours(1, 3, 0),
    };
  },

```

**Comment by walderpinheiro** [comment]
It did work

For don't mount the component with value or fill input after user select a 'beforeDate', i did wrap  in another component and set today date on focus

**Comment by danstoian07** [comment]
<date-picker
            v-model="delivery_date"
            type="date"
            format="DD-MM-YYYY"
            :first-day-of-week="1"
            :disabled-date="disabledBeforeToday"
 ></date-picker>

.....

Methods:

disabledBeforeToday(date) {
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      return date < today;
 },
