### ISSUE TITLE
 In ipad. Not show popup at the first time click

### ISSUE THREAD

**Issue by oanhkieu** [mengxiong10/vue2-datepicker#334]

**Comment by mengxiong10** [comment]
What's your datepicker version?
Whether you need to click twice?

**Comment by shv-z** [comment]
Reproducing this on ipad and iphone (chrome and safari).
datepicker 2.13.1
If date is set and editable === true you need to tap 2 times to open datepicker. After first tap you only get the input focused and the calendar icon changed to clear icon.

**Comment by mengxiong10** [comment]
Thanks for your feedback.
fixed it in v2.13.2.

**Comment by Igor-Tsoy** [comment]
same problem with "vue2-datepicker": "3.9.0"

**Comment by veverre** [comment]
the issue is still alive in `vue2-datepicker@3.9.0:`

**Comment by mengxiong10** [comment]
fixed it in v3.10.3
