### ISSUE TITLE
Request to add a popupClass option

### ISSUE THREAD

**Issue by TDola** [mengxiong10/vue2-datepicker#338]
It would be helpful to have a popupClass option to allow more exact targeting of the popup when using append-to-body and global scope css

```
    popupClass: {
      type: String
    }
```
and
```
    <div class="mx-datepicker-popup"
      :style="innerPopupStyle"
      :class="popupClass"
      v-show="popupVisible"
      @click.stop.prevent
```

Thank you

**Comment by mengxiong10** [comment]
use the `popupStyle`

**Comment by TDola** [comment]
How @mengxiong10  ?
like this?
:popupStyle="{left: 0, margin: 'auto', width: '100vw', **className: 'mobile-date-picker'**}"

**Comment by mengxiong10** [comment]
set the wrapper's  class.
```html
<date-picker class="your-class" />
```
``` css
.your-class .mx-datepicker-popup {
   color: red;
}
```
or set the popupStyle instandOf class

```html
<date-picker :popupStyle="{ color: 'red' }" />
```

**Comment by TDola** [comment]
I need to be able to apply a class to the outer body elements for the popup
![image](https://user-images.githubusercontent.com/30079906/63095504-0afa7680-bf31-11e9-9e54-1c403f1bf49c.png)
So that I can select them through a global CSS individually and set up different styles for Desktop, Mobile, and Tablet.

Adding a class to the date picker adds it to the div around the mx-input-wrapper div element, not the pop up element, and I can't apply styles through the popupStyle because I need to target child elements as well.

**Comment by mengxiong10** [comment]
It's really a problem when  `appentToBody` is true.
I'll add the prop `popupClass` in next version.
You can set it like this temporarily. 
```html
<date-picker v-model="value" ref="datepicker" appendToBody  lang="en" />
```
```js
mounted () {
    this.$refs.datepicker.popupElm.classList.add('popupClass')
}

```

**Comment by TDola** [comment]
Thank you

**Comment by FPTSonPM3** [comment]
@mengxiong10 I want the div mx-datepicker-popup tag to be displayed always centered on the page. Help me !

**Comment by mengxiong10** [comment]
@FPTSonPM3  Use the `popup-style`
```html
<date-picker
  v-model="value"
  :popup-style="{ left: '50%', top: '50%', transform: 'translate(-50%, -50%)' }"
></date-picker>

```
