### ISSUE TITLE
Events: How to get a last day of month in month range selector?

### ISSUE THREAD

**Issue by ajithsimon** [mengxiong10/vue2-datepicker#339]
Hi,

This is my datepicker implementation
`<date-picker v-model="customDate" :editable="false" @change="changeDate" @clear="clearCustomDate" placeholder="Select Month Range" value-type="format" range :shortcuts="false" type="month" format="DD-MM-YYYY" lang="en"></date-picker>`

If i select from Jan 2019 to Dec 2019 the values I'm getting are "01-01-2019 ~ 01-12-2019"
I just need to show the last day of the December instead of the first day. 

![TRAQADE   Demo Traqade](https://user-images.githubusercontent.com/8578458/63021238-c8e41d00-bebd-11e9-909a-11ca0aeb40af.png)

Please help me out with this.

Thanks.

**Comment by mengxiong10** [comment]
```js
    changeDate(val) {
      if (val && val[1]) {
        const date = moment(val[1], "DD-MM-YYYY").endOf("month").format("DD-MM-YYYY");
        this.value = [val[0], date];
      }
    }

```

**Comment by ajithsimon** [comment]
@mengxiong10  thank you so much. It's working now.. 💯
