### ISSUE TITLE
Setting a Min/Max time for datetime picker

### ISSUE THREAD

**Issue by matthayzon** [mengxiong10/vue2-datepicker#34]
Hello, I am using your datetime picker component to allow users to choose the date and time for an event that should not be scheduled earlier than 1pm. With the current date time picker there doesn't seem to be an option to set a min / max time.

This is my current implementation:

<date-picker v-model="value4" type="datetime" format="yyyy-MM-dd HH:mm" :minute-step="10" lang="en"></date-picker> 

For the example above, we'd like to hide all hours prior to 1pm from the time picker step. Second, we'd like to have the option to display non-military time with am/pm in the time step (1pm instead of 13). I appreciate any suggestions on how to accomplish this.

Thanks in advance!

**Comment by mengxiong10** [comment]
The component does not have this feature yet, I will add a prop to achieve it tomorrow

**Comment by mengxiong10** [comment]
@matthayzon  I added a prop(time-picker-options) to implement it. And You can set the format prop lowercase 'hh' as below. to display non-military time with am/pm.
```
<date-picker v-model="time" type="datetime" format="YYYY-MM-dd hh:mm:ss a" :time-picker-options="{start: '00:00', step: '00:30',end: '13:00'}"></date-picker>
```

**Comment by matthayzon-sk** [comment]
hey @mengxiong10 ,

Thanks for adding that! I've updated my vue2-datepicker to version 1.8.0 although as you can see in the screenshots below, the start and end and non-military time isn't being applied. Any idea why this is?
```

<date-picker
                            lang="en"
                            v-model="time"
                            type="datetime"
                            format="YYYY-MM-dd hh:mm:ss a"
                            :time-picker-options="{start: '00:00', step: '00:15',end: '13:00'}">
                    </date-picker>
```

<img width="756" alt="screen shot 2017-12-28 at 8 51 33 pm" src="https://user-images.githubusercontent.com/31517632/34420207-fff7a978-ec10-11e7-8f8f-3857be4ffa65.png">
<img width="295" alt="screen shot 2017-12-28 at 8 51 24 pm" src="https://user-images.githubusercontent.com/31517632/34420209-00455ea2-ec11-11e7-80dd-df49c3b9eae1.png">

**Comment by mengxiong10** [comment]
you can see in the screenshots below. I use the same code as you in v1.8.0.
Please check the version again in /node_modules/vue2-datepicker/package.json.
Or try to change the time-picker-options to timePickerOptions.
If it still does not work please let me know
![image](https://user-images.githubusercontent.com/14135808/34432666-5ecf3382-ecb4-11e7-9717-c5f51c805dc5.png)

**Comment by matthayzon-sk** [comment]
Hi @mengxiong10,

I've confirmed I'm on version 1.8.0 and I am getting the same unsuccessful outcome as before. I am not getting the same screenshot as you've shown. 

I am getting the following warning: 
`
Invalid prop: type check failed for prop "timePickerOptions". Expected Object, got String.
`

And using the following code:
```

<date-picker
                            lang="en"
                            v-model="time"
                            type="datetime"
                            format="YYYY-MM-dd hh:mm:ss a"
                            :time-picker-options="{start: '00:00', step: '00:15',end: '13:00'}">
                    </date-picker>
```

**Comment by mengxiong10** [comment]
@matthayzon-sk 
as the warning, you should use a Object for the prop. But the code you show is Object not String. Maybe other reasons make it invalid. You can try below.
```
v-bind:time-picker-options="options"

  data () {
    return {
      options: {
        start: '00:00',
        step: '00:15',
        end: '13:00'
      }
    }
  }
```

**Comment by matthayzon-sk** [comment]
Hey @mengxiong10, that didn't work for me either. Can you set up a working fiddle or codepen example?

**Comment by mengxiong10** [comment]
@matthayzon-sk 
https://jsfiddle.net/mengxiong/0yxwh58q/

**Comment by matthayzon-sk** [comment]
@mengxiong10, thanks for the help! All is working now :D

**Comment by matthayzon-sk** [comment]
Hey @mengxiong10,

I'd like to detect the changing of a date-picker component input value, what would be the best way to accomplish this? I tried adding a @change event listener, although it doesn't seem to fire. 

```

 <date-picker
                                v-model="cool"
                                @change="changeFoo"
                                lang="en"
                                type="datetime"
                                width="480"
                                input-class="date-time-picker"
                                format="MM/DD/YYYY hh:mm A"
                                :confirm="true"
                                :not-before="cool"
                                :time-picker-options="{
                                     start: '12:00',
                                     step: '00:15',
                                     end: '23:45'
                                     }"
                        >
                        </date-picker>
```

I appreciate any suggestions on how to accomplish this.

**Comment by mengxiong10** [comment]
@matthayzon-sk 
You can watch the value 'cool' or @confirm event listener to accomplish this.

**Comment by imbidhu** [comment]
Hi,
I am using this plugin but thing is i want to show only time picker not date with time picker. What all setting i have to do in this plugin?

**Comment by mengxiong10** [comment]
@imbidhu v2.4.0 support it.
Set the type `time`.
```html
<date-picker v-model="value12" lang="en" type="time" format="HH:mm:ss" placeholder="Select Time"></date-picker>

```

**Comment by deep0410** [comment]
@mengxiong10 I can't seem to get the 12 hour format
```
<date-picker
                                        v-model="startTime"
                                        lang="en"
                                        type="time"
                                        format="hh:mm a"
                                        placeholder="Select Time"
                                        :time-picker-options="{
                                             start: '00:00',
                                             step: '00:30',
                                             end: '23:30'
                                             }"
                                      >
                                      </date-picker>
```

**Comment by aalfredrdz** [comment]
@mengxiong10 how can i make it in 12h format like this? 
![image](https://user-images.githubusercontent.com/34704635/54334349-afb21880-4660-11e9-8604-9d62cffa19d8.png)

**Comment by AmitVSH** [comment]
is there any way to make 12 hours picker?

**Comment by mengxiong10** [comment]
v3.0.0 will supports it.
