### ISSUE TITLE
Always make date picker visible? 

### ISSUE THREAD

**Issue by havietduc91** [mengxiong10/vue2-datepicker#343]
Firstly, congrats for the great effort you've put in vue2-datepicker 

Can I set the calendar in a div? to always show, not by click.

Thank you first!

**Comment by mengxiong10** [comment]
https://github.com/mengxiong10/vue2-datepicker/issues/181#issuecomment-433781799

**Comment by havietduc91** [comment]
Thank you for a quick response and workaround solution!
