### ISSUE TITLE
Support two ranges in one date picker

### ISSUE THREAD

**Issue by havietduc91** [mengxiong10/vue2-datepicker#344]
Firstly, congrats for the great effort you've put in vue2-datepicker!

How we can make date picker with two ranges?
One range for `set time frame` with `yellow color (#FEF2E5)`
and two range for `compare time frame` with `green color (#E9F6FE)`

could you please see the below image to know more!

![Screenshot (44)](https://user-images.githubusercontent.com/4966192/63563206-7627f680-c58a-11e9-8f23-35c5770c8c96.png)

Thank you in advance!

**Comment by mengxiong10** [comment]
This feature is not available in v2.x.
I am refactoring v3.0, then you may implement this feature through some new interfaces.

**Comment by havietduc91** [comment]
I'm really impressed to hear that, thanks a lot!

**Comment by mengxiong10** [comment]
https://codesandbox.io/s/support-two-ranges-in-one-date-picker-bdoee?fontsize=14

**Comment by havietduc91** [comment]
yeah, thank you a lot for your effort, I will close this issue right away
