### ISSUE TITLE
Only show popup on calendar icon click broke

### ISSUE THREAD

**Issue by DragosPeta** [mengxiong10/vue2-datepicker#345]
Hello!

This issue was already solved in #215 , I tried that method with the last version of vue2-datepicker and it didn't worked. I downgraded to v2.6.3 version and it worked with the same code. I personally don't need this, it's just an observation.

Thank you!

**Comment by mengxiong10** [comment]
It's a problem to config how to show the popup.
I'll add the featrue to next version.

**Comment by mengxiong10** [comment]
v3.0.0 add prop `open` to control the state of popup.

**Comment by mengxiong10** [comment]
```html
<date-picker :open="open"  @close="open = false"  @click.native="handleClick" />
```
```js
export default {
  data() {
    return {
      open: false,
    };
  },
  methods: {
    handleClick(evt) {
      if (evt.target.tagName !== 'INPUT') {
        this.open = true;
      }
    },
  },
};


```
