### ISSUE TITLE
TabIndex is lost while using append-to-body

### ISSUE THREAD

**Issue by DragosPeta** [mengxiong10/vue2-datepicker#346]
Hello!

How to replicate:
1. In my situation i have a date picker using append to body and an input near it
2. Click on the date picker and select a date from the popup
3. Press tab key from keyboard and the focus should move on the input next to it, but it doesn't.

This works fine when i'm not using append-to-body.

**Comment by mengxiong10** [comment]
When you click on popup, datepicker lose the focus.
```html
<date-picker ref="datepicker" @change="handleChange" />

```
```js
handleChange() {
   this.$refs.datepicker.focus()
}

```

**Comment by DragosPeta** [comment]
Thanks for the response.
Your solution works fine ( this.$refs.datepicker.$el.getElementsByTagName('input')[0].focus() ), i thought this could be done somehow behind the curtains for that specific use case, but it's not a problem.
Have a great day!
