### ISSUE TITLE
Double click on the calendar icon causes an error

### ISSUE THREAD

**Issue by MoNSTRiKcom** [mengxiong10/vue2-datepicker#347]
```
inject.js:496 Uncaught TypeError: target.className.indexOf is not a function
    at HTMLDocument.triggerTranslation (inject.js:496)
```

**Comment by mengxiong10** [comment]
Can you show your code. 
I can't reproduce this bug in demo page.

**Comment by MoNSTRiKcom** [comment]
Test demo page:
Opera v62
[Screen](http://dl4.joxi.net/drive/2019/08/28/0023/3404/1555788/88/41ab95a9ae.jpg)

**Comment by mengxiong10** [comment]
the error is not in the `vue2-datepicker`.

It may be issued by some browser plugins.

**Comment by MoNSTRiKcom** [comment]
I confirm.
