### ISSUE TITLE
Responsive desing

### ISSUE THREAD

**Issue by iulian34** [mengxiong10/vue2-datepicker#35]
Hello, 
Any possibility to make this date picker responsive?

**Comment by mengxiong10** [comment]
@iulian34  
Do you mean the input box or calendar?
For the input box, you can change the css by yourself to make it responsive.

**Comment by iulian34** [comment]
@mengxiong10
I refer to calendar, if you view from mobile, is going outside the edges.

**Comment by mengxiong10** [comment]
@iulian34 
When set the range, the canlendar is hard to show in the mobile.
I suggest using two input boxes instead of range.
```
    <date-picker v-model="startDate" :not-after="endDate"></date-picker>
    <date-picker v-model="endDate" :not-before="startDate"></date-picker>
```

**Comment by Tusko** [comment]
@mengxiong10 

```
@media screen and (max-width: 567px) {
  .mx-datepicker-popup {
    .mx-shortcuts-wrapper {
      display: none;
    }
    .mx-range-wrapper {
      max-width: 100vw;
      .mx-calendar {
        float: none;
        .mx-calendar-content {
          width: auto;
        }
      }
    }
  }
}
```
