### ISSUE TITLE
How to close the datepicker after selecting date range?

### ISSUE THREAD

**Issue by ajithsimon** [mengxiong10/vue2-datepicker#351]
I have tried change-calendar and panel-change events, it wasn't working. Please help me with it.

**Comment by HuanVo** [comment]
you can using
`this.$refs.datepicker.closePopup();`
to close it.

**Comment by ajithsimon** [comment]
tried it, not working.

**Comment by mengxiong10** [comment]
You can watch the value then close the popup when it is changed.

```html
<date-picker v-model="value" ref="datepicker" range ></date-picker>
```
```js
watch: {
   value (newDate, oldDate) {
        this.$refs.datepicker.closePopup()
   }
}
```

**Comment by ajithsimon** [comment]
Thank you so much @mengxiong10 .
