### ISSUE TITLE
How to set input type?

### ISSUE THREAD

**Issue by HuanVo** [mengxiong10/vue2-datepicker#352]
I want to set type for input. i used  
`input-attr="{type: 'tel}"`
But it not working.
please hepl me!
thanks!

**Comment by mengxiong10** [comment]
```html
<date-picker ref="datepicker" />
```
```js
mounted () {
  this.$refs.datepicker.$refs.input.type = 'tel'
}

```
you can use `input-attr="{type: 'tel}"` in v3.0.0.

**Comment by HuanVo** [comment]
thanks to you @mengxiong10 . It's working very well.
