### ISSUE TITLE
negative year/month.

### ISSUE THREAD

**Issue by lequy1010** [mengxiong10/vue2-datepicker#354]
Please confirm to fix to not allow use input or click prev to choose a negative year/month 
![image](https://user-images.githubusercontent.com/7949193/65212270-aef4b600-dacb-11e9-9d49-cc3184a4e9a8.png)

**Comment by mengxiong10** [comment]
I think should allow the negative, but the current format for negative is error. I'll fix it in v3.0.0.

**Comment by mengxiong10** [comment]
in v3.x
You can use the token `Y` to display a negative year.
```js
<date-picker  format="Y-MM"    />
```

**Comment by lequy1010** [comment]
> in v3.x
> You can use the token `Y` to display a negative year.
> 
> ```js
> <date-picker  format="Y-MM"    />
> ```

Good, thank you!
