### ISSUE TITLE
Not able to change Calendar icon

### ISSUE THREAD

**Issue by krishnad10** [mengxiong10/vue2-datepicker#355]
Not able to change Calendar icon using Props. 

**I'm able to change the icon with below code.** 
<template slot="calendar-icon">
       <i class="material-icons">calendar_today</i>
</template>

It would be nice if we have Props for changing the icon. Like calendar-icon="calendar_today"

Just a suggestion.

**Link for material icons :** 
https://material.io/resources/icons/?icon=calendar_today&style=baseline

**Comment by mengxiong10** [comment]
use slot.
```html
<date-picker v-model="value">
   // your icon
   <i slot="calendar-icon"></i>
</date-picker>
```

**Comment by ajaymarathe9** [comment]
> use slot.
> 
> ```
> <date-picker v-model="value">
>    // your icon
>    <i slot="calendar-icon"></i>
> </date-picker>
> ```

@mengxiong10 I don't know why but slot not working, what if I want to change the icons, i mean where is the list of icons, from where i can choose one.

**Comment by mengxiong10** [comment]
@ajaymarathe9 the name is 'icon-calendar' in v3.x.
```html
<date-picker v-model="value">
   // your icon
   <i slot="icon-calendar"></i>
</date-picker>
```

**Comment by Tech-49** [comment]
```
       <date-picker
            v-model="time"
            type="time"
            format="HH:ss"
            placeholder="Select Time"
          >
            <i slot="icon-calendar">
              <font-awesome-icon icon="clock" />
            </i>
        </date-picker>
