### ISSUE TITLE
Remove 13 from Icon Calendar

### ISSUE THREAD

**Issue by franmazanet** [mengxiong10/vue2-datepicker#360]
I know 13 is lucky in Chinese but you have to be universal.

How to get rid of 13 from icon?

**Comment by mengxiong10** [comment]
use the slot.
``` html
<date-picker>
  // your icon
  <i slot="calendar-icon"></i>
</date-picker>
```

**Comment by mengxiong10** [comment]
The calendar number will be removed in next version.

**Comment by franmazanet** [comment]
The 13 is gone and so is the calendar icon. Really wanted the calendar icon to stay.

**Comment by franmazanet** [comment]
Dude: I think you are a very smart person and I appreciate the product you produced but you really need to be less Chinese and more universal if you want your talents to be appreciated world-wide. Just sayin ... #FreeHK

**Comment by mengxiong10** [comment]
@franmazanet the number just is the current day. It changed every day.

**Comment by mengxiong10** [comment]
v2.13.0 removed the icon day.
