### ISSUE TITLE
How to display calendar inline?

### ISSUE THREAD

**Issue by mrosminin** [mengxiong10/vue2-datepicker#362]
without showing input box?
is it possible?
like this

![2019-10-28_13-03-58](https://user-images.githubusercontent.com/46540893/67670150-5515c480-f984-11e9-92db-eacec0954913.png)

**Comment by mengxiong10** [comment]
same as https://github.com/mengxiong10/vue2-datepicker/issues/181#issuecomment-433781799
And v3.0.0 will add the feature soon.

**Comment by mengxiong10** [comment]
v3.0 add inline feature.
```html
<date-picker inline />
```
