### ISSUE TITLE
default-value props doesnt change dynamically? 

### ISSUE THREAD

**Issue by dawid-karnacewicz** [mengxiong10/vue2-datepicker#364]
Hello,
Im writing because i have one small problem - when i have two date pickers DateFrom and DateTo

1. I Change DateFrom value
2. Assing Date From Value (v-model) to DateTo "**default-value**" props
3. Open DateTo datepicker - Nothing changes
4. Close DateTo datepicker
5. Open DateTo datepicker (again) - Everything is okey - "**default-value**" props is equal to DateTo Value (v-model)
 
Default value of DateTo datepicker should change in point number 3 not 5. I need to open and close and once again open to default-value props refresh

Is this bug?

**Comment by mengxiong10** [comment]
The `default-value` is just to initialize the calendar when the `value` is null.

**Comment by dawid-karnacewicz** [comment]
@mengxiong10 Shall you provide the approximate date of release of the version?

**Comment by mengxiong10** [comment]
Can you show your code?
I'm not sure if your question is what I think.

**Comment by mengxiong10** [comment]
fixed it in v2.13.3
