### ISSUE TITLE
Panel is not opening to first selectable date while using not-before prop

### ISSUE THREAD

**Issue by akki-jat** [mengxiong10/vue2-datepicker#365]
### Issue
When I use not-before prop, give any future dates and open the date picker it opens the current date / month / year. So I use to manually go to first seletable date.

### What to expect
When is there is future date in not-before prop then datepicker panel should be open at first selectable date / month / year.

### Repoduction Link
[https://codesandbox.io/embed/vue2-datepicker-notbefore-prop-error-u3qww](https://codesandbox.io/embed/vue2-datepicker-notbefore-prop-error-u3qww)

**Comment by mengxiong10** [comment]
You can use the prop `default-value` to control it.

**Comment by akki-jat** [comment]
ok @mengxiong10. But would be great if it is done by default because there is no use to open calendar where user can't select anything.
