### ISSUE TITLE
Icon is off when using date-picker inside table

### ISSUE THREAD

**Issue by kimegenes** [mengxiong10/vue2-datepicker#367]
The example at the top is inside table and the icon is off, the example at the bottom is inside a div and works fine
![image](https://user-images.githubusercontent.com/2052292/68092519-61ba8100-fe8c-11e9-840d-f4c76d881901.png)

![image](https://user-images.githubusercontent.com/2052292/68092507-3cc60e00-fe8c-11e9-83df-7203c779eac6.png)

Any hints to how I might resolve this? Did try to override css class .mx-calendar-icon { height: auto !important; } but no luck...

Appreciate your work, thanks alot
Cheers

**Comment by mengxiong10** [comment]
Maybe It's a height bug.
You can try this. 
```css
.mx-input-append {
  height: 34px;
}

```

**Comment by jowi24** [comment]
Can't this be included in master? This fixed the issue also for me.

**Comment by mengxiong10** [comment]
v3.x doesn't have this issue.

**Comment by jowi24** [comment]
Great, good idea. Thanks :-)
