### ISSUE TITLE
Clear Current Date

### ISSUE THREAD

**Issue by dennisc9** [mengxiong10/vue2-datepicker#37]
There is no way to clear the current date chosen.

**Comment by mengxiong10** [comment]
@dennisc9  when you hover the icon, it should show the clear icon. 
This is not really obvious, then I will change to show the clear icon when hover the input box.
![image](https://user-images.githubusercontent.com/14135808/34403123-44110e54-ebe1-11e7-9e1e-ae499c5f9ad8.png)

**Comment by dennisc9** [comment]
Programmatically speaking how can i clear the fields? Is there a clear function i can evoke?

**Comment by mengxiong10** [comment]
It's easy to do
```
<date-picker v-model="time" :first-day-of-week="1"></date-picker>
data
clear () {
 this.time = ''
}
```

**Comment by bhavinjr** [comment]
@dennisc9  you can do something like that when pressing on a clear icon
```
<date-picker v-model="time" @clear='(clear)=>{time=null}'></date-picker>
```
