### ISSUE TITLE
Maybe return [null,null] instead of null when clear the range type date picker

### ISSUE THREAD

**Issue by kentkwan** [mengxiong10/vue2-datepicker#370]
`
:value="[$v.scheduledNotice.start.$model,$v.scheduledNotice.end.$model]"
@change="[$v.scheduledNotice.start.$model,$v.scheduledNotice.end.$model]=$event||[null,null]"
`

It will cause npe if not use $event||[null,null]

**Comment by mengxiong10** [comment]
Yes, thanks for feedback.

**Comment by mengxiong10** [comment]
fixed in v3.0.2

**Comment by kentkwan** [comment]
Thanks a lot.
