### ISSUE TITLE
JS errors opening a daterange picker

### ISSUE THREAD

**Issue by matteomelotti** [mengxiong10/vue2-datepicker#371]
I get 'Cannot read property 'monthBeforeYear' of undefined at VueComponent.t' and 'Injection "locale" not found' during opening a daterange picker

**Comment by mengxiong10** [comment]
Can you show your code?

**Comment by mengxiong10** [comment]
Need to upgrade version of vue >= 2.5.

**Comment by matteomelotti** [comment]
> Need to upgrade version of vue >= 2.5.0

it works, thanks!
