### ISSUE TITLE
de locale has sunday as first day

### ISSUE THREAD

**Issue by sahaAcat** [mengxiong10/vue2-datepicker#373]
Hi there,

we are using the date picker with 'en' and 'de' locale and this is working fine except that for the de locale the first day of the week is Sunday - customarily in German speaking countries Monday is the first day of the week though... is this something it would be possible to change?

Or is there a way i can use the internal 'de' locale settings and just amend the first day of week?
if i just do 
```
:lang="{
  formatLocale: {
    firstDayOfWeek: 1,
  },
}"
```
of course i would need to set all translations for weekdays etc manually...

Thanks for the help in advance!

**Comment by mengxiong10** [comment]
the firstDayOfWeek is Sunday in `en` and is Monday in `de` by default.

You can change the default global locale like this.
```js
import DatePicker from 'vue2-datepicker'
import de from 'vue2-datepicker/locale/de'

de.formatLocale.firstDayOfWeek = 0

```

**Comment by mengxiong10** [comment]
If you are importing two locales. You can set a locale like this.

```js

<date-picker lang="de" />
```

**Comment by sahaAcat** [comment]
thanks for the quick reply!

I probably should have mentioned that im still on version 2 (sorry) so the proposed solution did not work for me 

then i tried to update to v3 however this broke other things for me so i had to revert for now until i have more time - but just in case someone else is reading this - i found now that it can be set as prop directly `:first-day-of-week="1"` (again - this is for v2 at least!)

again - thanks anyway!

**Comment by sahaAcat** [comment]
just one more thing...

> the firstDayOfWeek is Sunday in en and is Monday in de by default.

at least for version 2 this was not true for me unfortunately

![image](https://user-images.githubusercontent.com/51696862/68879038-03ea2c80-0709-11ea-815d-518fdd234170.png)
![image](https://user-images.githubusercontent.com/51696862/68879092-182e2980-0709-11ea-808d-76931c12ceb3.png)

but of course maybe this is just for version 2...apologies if this was fixed already anyway!
