### ISSUE TITLE
inputClass should allow object syntax

### ISSUE THREAD

**Issue by jantajov** [mengxiong10/vue2-datepicker#374]
Property inputClass should allow object syntax as described in [docs](https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax).
```
    inputClass: {
      type: [String, Array, Object],
      default: 'mx-input'
    },
```
It is broken in 2.13 release. Not tested in 3.0 release. Anyway could you fix it and release patch, please?

**Comment by mengxiong10** [comment]
v3.0 is OK. I'll release patch in 2.x.

**Comment by jantajov** [comment]
Hello @mengxiong10 , will there be a branch for 2.x? You could make it from https://github.com/mengxiong10/vue2-datepicker/commit/72024440d744457c6e9f41042d0d9c9c7e7cb626.

**Comment by mengxiong10** [comment]
v2.13.4 fixed it.
