### ISSUE TITLE
[Bug] Panel doesn't close after selecting time

### ISSUE THREAD

**Issue by BaptisteLemarcis** [mengxiong10/vue2-datepicker#378]
**Vue2-datepicker version**: 3.1.0 (was here in 3.0.2)
**Vue version**: 2.6.10
**Browser**: firefox, chrome, edge, ie

**Steps to reproduce**
Follow the link to the reproduction

**Reproduction Link or Source Code**
https://jsfiddle.net/jh7cmpg4/7/

**Expected behavior**
The time panel should close after I selected the time

**Actual behavior**
The time panel stays open

**Comment by mengxiong10** [comment]
fyi: https://jsfiddle.net/6c8om4ft/4/

**Comment by mengxiong10** [comment]
fixed in 3.1.1.

**Comment by geeksilva97** [comment]
How can I close a inline datepicker?

**Comment by mengxiong10** [comment]
@geeksilva97 
`Inline` means that the input box is not displayed and the calendar is always displayed.
You can use `v-show` or `v-if` to hide datepicker.

**Comment by geeksilva97** [comment]
> @geeksilva97
> `Inline` means that the input box is not displayed and the calendar is always displayed.
> You can use `v-show` or `v-if` to hide datepicker.

I did it. Thanks!
By the way, this project is awesome!
