### ISSUE TITLE
I like range type V2 mode, can add prop to go back

### ISSUE THREAD

**Issue by hcwhan** [mengxiong10/vue2-datepicker#379]
range mode in V2
if want change `2019-10-01 ~ 2019-11-01` to `2019-10-01 ~ 2019-12-01`, I only click once
but in V3
when I click one time, start time and end time is clear, click time is not start time and end time, I must choose another one, even though if I only modify one value, poor user experience

**Comment by mengxiong10** [comment]
FYI:  https://codesandbox.io/s/range-picker-v2x-mode-9co63?fontsize=14&hidenavigation=1&theme=dark.

I will consider this feature built in by default.

**Comment by hcwhan** [comment]
It's work, very thankful
