### ISSUE TITLE
time picker component

### ISSUE THREAD

**Issue by taylorchu** [mengxiong10/vue2-datepicker#38]
It is nice to have a separate component for pure time picker if there is no date to pick.

If you have some plans for this in the future, please let me know.

@mengxiong10

**Comment by mengxiong10** [comment]
v2.4.0 support it.
Set the prop `time`
```html
<date-picker v-model="value12" lang="en" type="time" format="HH:mm:ss" placeholder="Select Time"></date-picker>
```
