### ISSUE TITLE
[Feature request] Default to previous popup-style if no popup-style prop exists

### ISSUE THREAD

**Issue by jayporta** [mengxiong10/vue2-datepicker#381]
**What problem does this feature solve?**
The unpleasant surprise of noticing the UI of the date picker on your site is suddenly broken

**What does the proposed API look like?**
popup-style: { type: Object, default: defaultStyleThatExistedBeforeThisUIBreakingChange }

**Comment by mengxiong10** [comment]
The default `popup-style` is `{ left: number; top: number }`.
What does  `previous popup-style`  mean.

**Comment by jayporta** [comment]
Before the update, it looked like this:

<img width="247" alt="Screen Shot 2019-11-25 at 12 25 16 PM" src="https://user-images.githubusercontent.com/15250836/69512375-c7c39100-0f7e-11ea-9169-382af9317a91.png">

After the update it looks like this:

<img width="253" alt="Screen Shot 2019-11-25 at 12 24 56 PM" src="https://user-images.githubusercontent.com/15250836/69512381-ce520880-0f7e-11ea-9184-c031a0def206.png">

So, "previous popup-style" means the style in the first photo.

**Comment by mengxiong10** [comment]
Do you update the v3.x?
You need to import style separately.
```js
import 'vue2-datepicker/index.css';
```

**Comment by mengxiong10** [comment]
https://github.com/mengxiong10/vue2-datepicker/releases/tag/v3.0.0

**Comment by jayporta** [comment]
Ok, that's a cool solution to the problem, thanks for that, but why should the user be responsible for importing default style in this way? That's why I submitted this as a feature request, not a bug report.

**Comment by mengxiong10** [comment]
Because you can customize the style more conveniently.
If you use `scss`.
```
$default-color: #555;
$primary-color: #1284e7;

@import '~vue2-datepicker/scss/index.scss';

```
