### ISSUE TITLE
[Feature request] - Week Number Callback

### ISSUE THREAD

**Issue by byronferguson** [mengxiong10/vue2-datepicker#382]
**What problem does this feature solve?**
We use a different week numbering system for business that we would like to display. For example, Week 1 for 2021 begins on January 3rd, so the 1st and 2nd belong to week 53 of 2020.

**What does the proposed API look like?**
`getWeekNumber(date: Date): number`
Essentially provide a hook that the would override the default week number based on a the user-defined week for any given date.

**Comment by mengxiong10** [comment]
override global.
```js
import datepicker from 'vue2-datepicker';

const defaultLocale = datepicker.locale();

defaultLocale.formatLocale.firstWeekContainsDate = 3

```
override component.
```html
<datepicker  :lang="{ formatLocale: { firstWeekContainsDate : 3 }  }" />
```

**Comment by byronferguson** [comment]
[date-fns Locale](https://date-fns.org/v2.8.1/docs/Locale)

From looking at your dependencies I see you are using this package to handle dates. My concern with using this override is that is a locale dependent rule rather than a business one. This year the first week started on the 7th, so changing it statically won't work for the "retail week".

**Comment by mengxiong10** [comment]
I use `date-format-parse`

**Comment by byronferguson** [comment]
```
  "dependencies": {
    "date-fns": "^2.0.1",
    "date-format-parse": "^0.2.5"
  },
```

I am not criticizing you. I have not used this module long, but I appreciate it. My use-case is business-focused rather than regionally focused, which is why I having the option to override the `locale` defaults is needed.

**Comment by mengxiong10** [comment]
I see.  Just do it like this.
```html
<date-picker  :lang="{ formatLocale: { firstWeekContainsDate : 3 }  }" />
```

**Comment by byronferguson** [comment]
https://slack-files.com/T0D11T59P-FQZ4B7L7J-3796f744e1

Week 1 of 2020 should start on 2020.01.05

**Comment by byronferguson** [comment]
https://slack-files.com/T0D11T59P-FQML0ETC3-3417777b9a

Week 1 of 2021 should start on 2021.01.03

So the hard-coded solution won't work for me

**Comment by mengxiong10** [comment]
Do you need different start dates for different years

**Comment by byronferguson** [comment]
Yes. I need different start dates for different years, and there will be 53 weeks most years

**Comment by mengxiong10** [comment]
OK. I can consider prop `getWeekNumber` by user-defined.

**Comment by byronferguson** [comment]
That's awesome. Thank you so much.

**Comment by mengxiong10** [comment]
Prop `format` can customize format and parse now, I will add `getWeek` in it.
```html

<date-picker  :format="customFormat" />
```

```js
data() {
  return {
     customFormat: {
        getWeek(date) {  return 1 }
     }
  }
}

```

**Comment by mengxiong10** [comment]
v3.2.0 added it.
