### ISSUE TITLE
[Bug] Incompatible with custom css properties

### ISSUE THREAD

**Issue by lucianholt97** [mengxiong10/vue2-datepicker#383]
**Vue2-datepicker version**:
^3

**Steps to reproduce**
override `$primary-color` with custom css property
sass building will fail because of the mix method in index.scss on line 265

**Expected behavior**
Line 265 should depend on a scss variable which can be overridden

**Actual behavior**
build fails

**Comment by mengxiong10** [comment]
Can you show your code ?
FYI: https://codesandbox.io/s/custom-css-oj0wq?fontsize=14&hidenavigation=1&theme=dark

**Comment by lucianholt97** [comment]
Sorry for answering late. In the index.scss file, you use the `mix(#fff, $primary-color, 10%);`. Therefor setting `$primary-color: var(--primary-color);` to a css custom property results in compilation errors, because `mix()`can't handle those. Instead I'd suggest adding `$todayColor: mix(#fff, $primary-color, 10%);` to the variables, to you can override this variable instead of overriding the `.today` class. 
```
.mx-table-date {
  td,
  th {
    height: 32px;
    font-size: 12px;
  }

  .today {
    color: mix(#fff, $primary-color, 10%);
  }
  .cell.not-current-month {
    color: #ccc;
  }
}
```

**Comment by mengxiong10** [comment]
Yes, It's a improvement.
