### ISSUE TITLE
[Bug] :disabled-time disables time starting from next hour

### ISSUE THREAD

**Issue by plakhin** [mengxiong10/vue2-datepicker#384]
**Vue2-datepicker version**: 3.1.1
**Vue version**: 2.6.10
**Browser**: Chrome 78

**Steps to reproduce**
`:disabled-time="(date) => date < new Date()"`

**Expected behavior**
Lets suppose current time is `15:33:03`
User should be able to select `15:33:04` and later

**Actual behavior**
User can able to select `16:00:00` and later.

**Comment by mengxiong10** [comment]
You can set  `default-value= new Date()`.

**Comment by plakhin** [comment]
Thanks for response, but how it will help?
I have a field with value already inserted from database. I need an option to forbid dates and time in past. `disabled-time` seems what I need, but it disables time during current hour.
Adding `default-value` seems to give no affect in my case.

**Comment by mengxiong10** [comment]
If your value is null, You should set the `default-value`. let the `default-value` is valid.
If your value from database is invalid. Maybe you should give a message and not bind the value.
Can you write a CodeSandbox link.

**Comment by plakhin** [comment]
https://jsfiddle.net/mfw2L3co/

Please try to select time 1 minute from now(). It is not possible.
I.e. if now() is 12:33:00 the nearest time possible to select is 13:00:00

**Comment by mengxiong10** [comment]
You should set a `default-value`. 
But the `default-value` is invalid when `type === datetime`. 
I'll fix it.

**Comment by plakhin** [comment]
I've updated to last version, but still no result, or I just can't understand how to use `default-value`.

Can you edit my jsfiddle please and paste the link here?
I just need working example with past dates/time inselectable.

**Comment by mengxiong10** [comment]
v3.2.1.
https://jsfiddle.net/aqw3ypLo/9/

**Comment by mengxiong10** [comment]
```
disabledTime = date < '2019-12-03 14:30:30';
```
1. the initial value is `2019-11-29 12:00:00`.
2. when you select `2019-12-04`,  the value will be `2019-12-04 12:00:00` (retain the time).
3. when you select `2019-12-03`. the value will be `2019-12-03 12:00:00`, but the value is disabled. So You can set a `default-value="2019-12-03 14:30:31", then the value will be `2019-12-03 14:30:31`.

**Comment by mengxiong10** [comment]
Set the `default value` to fall back when the value is disabled

**Comment by mengxiong10** [comment]
Suppose`disabled-time = date < '2019-12-03 16:30:30'`.
Because the default time is '00:00:00', the time `16:00:00` is disabled cause the hour `4` cann't be selected.
When you set the default value is '16:30:31', then the hour `4` can be selected, because '16:30:31' isn't disabled.

**Comment by plakhin** [comment]
Finally, works and now it's clear about `default-value`

**Comment by plakhin** [comment]
@mengxiong10 please check https://jsfiddle.net/tvaz230r/3/

I changed format  from `"YYYY-MM-DD HH:mm:ss"` to `format="YYYY-MM-DD HH:mm"` and now it's broken again. Can you help please?

**Comment by mengxiong10** [comment]
`:default-value="now.getTime() + 1000 * 60"`

**Comment by plakhin** [comment]
Thanks! This works in example. But I have more complicated actual use case.
Can you please check https://jsfiddle.net/plakhin/tjx4cL2m/8/

I'll really appreciate. Can not understand what I'm doing wron.

**Comment by plakhin** [comment]
@mengxiong10 can you help please?

**Comment by mengxiong10** [comment]
@plakhin When select the date, you should check the time.

**Comment by mengxiong10** [comment]
```html
 <time-panel
       :value="slotProps.value < new Date() ? new Date(Date.now() + 60 * 1000) : slotProps.value"
  ></time-panel>
```



```

**Comment by plakhin** [comment]
Works perfect! Thanks!
