### ISSUE TITLE
[Bug] Disabled date inside range

### ISSUE THREAD

**Issue by nikeddarn** [mengxiong10/vue2-datepicker#385]
Vue2-datepicker version: 3.1.1
Vue version: 2.6.10
Browser: Chrome Version 78.0.3904.108 (Official Build) (64-bit)

Steps to reproduce
:disabled-date="(date) => date.getDate() === 4;"
Then select range from 2 to 6 for example

Expected behavior
Cant select range that has disabled date or time inside.

Actual behavior
Range selected as usual.

**Comment by nikeddarn** [comment]
it will be not hard to set disabled all days after disabled date (time) and before previous disabled date(time) when first date selected . I can't to do that via :disabled-date because i haven't event like "first date selected"

**Comment by mengxiong10** [comment]
It's a good idea to add the second parameter (the current selected value) to the `disabled-date` function

**Comment by nikeddarn** [comment]
And to disabledTime(date, currentValue) also

**Comment by mengxiong10** [comment]
v3.2.0 added it.

**Comment by nikeddarn** [comment]
Hi. I wrote code for disabled dates and times using current values with whole usability. It's not optimally without some events like 'CurrentValueChanged' and 'ShowingMonthChanged' but working fine.

Why do you remove passing those parameters to disabled-date and disabled-time in newest version ? I cant upgrade.

**Comment by daaner** [comment]
its working good! Thanks!
```
:disabled-date="(date) => date <= disabledBefore"

disabledBefore: this.$moment("31-12-2019", "DD-MM-YYYY"),
```

**Comment by Matvej17** [comment]
Hi guys, I cant apply this issue conversation for solve my problem, but i think, it is same.

For example:
I have set disable days (13.1, 14.1, 15.1) in January
When I picked a range, for example from 10.1 to 20.1 I expected the selection to fail, but no. I can do this selection.

I try work with currentValue but without succes

Can u help me ?

**Comment by mengxiong10** [comment]
@Matvej17 

```js
disabledDate(date, currentValue) {
  // when one date is chosen
  const d13 = // new Date(...).getTime()
  const d14 = ...
  const d15 = ...
  if (currentValue.length === 1) {
      const firstDate = currentValue[0]
      if (firstDate.getTime() <  d13) {
         return date.getTime() > d13
      }
  }
  return [d13, d14, d15].indexOf(date.getTime()) !== -1
  ...
}

```
