### ISSUE TITLE
how to disregard time zone and always use UTC?

### ISSUE THREAD

**Issue by RudyOnRails** [mengxiong10/vue2-datepicker#388]
Hi @mengxiong10,

I understand this question may be best for stackoverflow, which I've posted [there](https://stackoverflow.com/questions/59162751/can-you-make-vue2-datepicker-disregard-timezone-and-always-think-in-utc), but I am a little under pressure. Feel free to answer there and I'll give you internet points :)

I get my time in UTC from server, and vue2-datepicker adjusts the time on both display/get and set/@input event. How do I make it so that when I get UTC from server, it displays UTC in component, and send UTC time back to server?

Do I need some sort of computed property with getter and setter (that does some special stuff) or are there some props that can help me? I see you've made many advancements from the version I am on, 2.6.2.

**Comment by RudyOnRails** [comment]
@mengxiong10 also thank you for making this component, it is pretty sweet!

**Comment by mengxiong10** [comment]
```html
<date-picker v-model="date" type="datetime" @change="handleChange" format="YYYY-MM-DD HH:mm:ss" />
```

```js
export default {
  data() {
    return {
      value: new Date('2019-12-06T16:00:00.000Z')
    };
  },
  computed: {
    date: {
      get() {
        const value = new Date(this.value)
        const offset = value.getTimezoneOffset();
        return new Date(value.getTime() + offset * 60 * 1000);
      },
      set(val) {
        const offset = new Date().getTimezoneOffset();
        this.value = new Date(val.getTime() - offset * 60 * 1000)
      }
    }
  },
  methods: {
    handleChange() {
      console.log(this.value, this.value.toISOString());
    }
  }
};



```

**Comment by mengxiong10** [comment]
The component select the locale date default. 
If you want use the UTC date, you need to transform by computed.

**Comment by RudyOnRails** [comment]
Ahh, I see what you are doing! Thank you so VERY much for taking the time to guide me @mengxiong10 👍
