### ISSUE TITLE
Show range on hover

### ISSUE THREAD

**Issue by 4spen** [mengxiong10/vue2-datepicker#392]
Would be nice to have option to show range you selecting while hovering over calendar for date selection.

**Comment by fevzican** [comment]
I agree, it would be nice.

**Comment by mortezasabihi** [comment]
I am also looking for this feature.

**Comment by Aristamo** [comment]
Same here this would give the user a better feel for the selection.

**Comment by mengxiong10** [comment]
I'll add it in next version
