### ISSUE TITLE
disabled in range calendar start date and end date

### ISSUE THREAD

**Issue by JohnAragon** [mengxiong10/vue2-datepicker#393]
Hi.
How can I use a specific date to start and end for disabling in a range calendar?. It means, for example the range of 2019-12-01 to 2020-01-10 have to be available and the rest of calendar doesn't.

**Comment by mengxiong10** [comment]
use `disabled-date`.

```html
<date-picker :disabled-date="disabledDate" />
```


```js

disabledDate(date) {

 return date > new Date(2019, 11, 1) && date < new Date(2020, 0, 10)
}
```

**Comment by icemountainzappel** [comment]
is it working @JohnAragon ? im facing the same problem. if i understand correctly you want to enable only a specific range of dates in the calendar, but the solution above seems to be doing the opposite - enabling the rest of the dates and disabling the range wanted. tried reverting the more/less than arrows and still not working.

**Comment by mengxiong10** [comment]
@icemountainzappel 
```js
disabledDate(date) {
 return date < new Date(2019, 11, 1) || date > new Date(2020, 0, 10)
}
```
