### ISSUE TITLE
[Feature request] Open datepicker with year selection

### ISSUE THREAD

**Issue by augnustin** [mengxiong10/vue2-datepicker#394]
I randomly found about the possibility to select the year by clicking on it, showing this screen:

![image](https://user-images.githubusercontent.com/1970156/70529536-106b7480-1b51-11ea-80c9-f698ced765c3.png)

Is it possible to open the datepicker with this view by default with props?

Indeed, when it is about birth dates, having to click back to 30-50 years is a wonderful pain while this screen makes it acceptable.

Couldn't find any reference in the doc for this.

**Comment by mengxiong10** [comment]
I'll add prop to support it.

**Comment by augnustin** [comment]
Looking forward! Do you want me to PR this? As for me the sooner the better. :smile:

**Comment by mengxiong10** [comment]
PR welcome.

**Comment by mengxiong10** [comment]
v3.3.0 add the `default-panel`.
```html
<date-picker default-panel="year" />
```

**Comment by augnustin** [comment]
You rock my world!

**Comment by mrkaluzny** [comment]
We should add it to documentation!
