### ISSUE TITLE
[Feature request] Slot for each date

### ISSUE THREAD

**Issue by lucianholt97** [mengxiong10/vue2-datepicker#396]
**What problem does this feature solve?**
- Option to individualize the look of each date and highlight special areas with background colors (like vacations)
- Option to hint for events at a given date with dots beneath the number

**What does the proposed API look like?**
```
<date-picker v-model="time1" valueType="format">
  <template v-slot:myDate>
    <!-- Custom html/components here -->
  </template>
</date-picker>
```

**Alternative Approach**
An alternative would be to define delegate functions like:
`getBackgroundColorForDate()` or `getNumberOfEventsForDate()`.

**Comment by mengxiong10** [comment]
Infact, there is a prop named `get-classes` to set the classes of date. 
```html
<date-picker  v-model="value" :get-classes="getClasses" />
```
```js
  methods: {
    getClasses(date) {
      if (date.getMonth() === 11 && date.getDate() === 25) {
        return 'Christmas';
      }
      return '';
    },
  },

```
