### ISSUE TITLE
@change="handleChange" -> type undefined

### ISSUE THREAD

**Issue by nunob87** [mengxiong10/vue2-datepicker#398]
hello, when I click hours, minutes, seconds or always type undefined

handleChange(value, type)

<template>
  <div>
    <date-picker
      v-model="value"
      value-type="format"
      type="time"
      :open.sync="open"
      placeholder="Select time"
      @change="handleChange"
    ></date-picker>
  </div>
</template>

<script>
export default {
  name: 'ControlOpen',
  data() {
    return {
      value: null,
      open: false,
    };
  },
  methods: {
    handleChange(value, type) {
console.log(type);
      if (type === 'second') {
        this.open = false;
      }
    },
  },
};
</script>

**Comment by mengxiong10** [comment]
check your version. It should be > v3.0.0

**Comment by nunob87** [comment]
thanks
