### ISSUE TITLE
[Bug] Date/Datetime selection element does not display well with modals

### ISSUE THREAD

**Issue by vcayetano** [mengxiong10/vue2-datepicker#399]
**Vue2-datepicker version**:
**Vue version**:
**Browser**:

**Steps to reproduce**
Create A Bootstrap Modal
Insert target element in Modal body
Display Modal

**Reproduction Link or Source Code**
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                  <div class="row mb-3">
                      <div class="col-lg-6">
                          <div class="form-group">
                              <label class="form-check-label">Starts</label>
                              <div class="col-lg-12">
                                  <date-picker v-model="start_at" type="datetime" placeholder="Select datetime"></date-picker>
                              </div>
                              
                              
                              <span class="text-danger" v-if="form.errors.has('start_at')"
                                    v-text="form.errors.get('start_at')"></span>
                          </div>
                      </div>

                      
                      <div class="col-lg-6">
                          <div class="form-group">
                              <label class="form-check-label">Ends</label>
                              <div class="col-lg-12">
                                  <date-picker v-model="end_at" type="datetime" placeholder="Select datetime"></date-picker>
                                  
                              </div>
                              <span class="text-danger" v-if="form.errors.has('end_at')"
                                    v-text="form.errors.get('end_at')"></span>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
              </div>
            </div>
          </div>
        </div>

**Expected behavior**
Date/time selection elements should be positioned above the modal to be selected

**Actual behavior**
Date time section elements get covered by the modal therefore hindering selection of a date or time

**Comment by Gerley** [comment]
Set css below:
<code css>
.mx-datepicker-popup {
  z-index: 1060;
}
</code>

**Comment by vcayetano** [comment]
@Gerley Thank you,  .mx-datepicker-popup { z-index: 1060 !important; } worked.
