### ISSUE TITLE
How to customize input style?

### ISSUE THREAD

**Issue by blackpuppy** [mengxiong10/vue2-datepicker#4]
I put <date-picker> inside a Boostrap toolbar, like this:

```
<template>
    <div class="filter-bar pull-left">
        <div class="form-inline">
            <div class="form-group">
                ...
                <div class="input-group">
                    <label class="input-group-addon">交易时间:</label>
                    <date-picker :class="'form-control'" v-model="filterDateRange"
                        range width="220" @keyup.enter="doFilter"
                        placeholder="开始日期 ~ 结束日期"
                    ></date-picker>
                </div>
                ...
            </div>
        </div>
    </div>
</template>
...
```

But it looks like this:

<img width="322" alt="image" src="https://cloud.githubusercontent.com/assets/439069/26517011/8d423c38-42c2-11e7-99d0-9d2c0f3f703c.png">

This is because inside vue2-datepicker, css class `input` is used, and there is no way to change it.

```
<template>
  <div class="datepicker"
       :style="{'width': width + 'px','min-width':range ? '210px' : '140px'}"
       v-clickoutside="closePopup">
    <input readonly
          class="input"
...
```

Is it possible to customize the <input> style?

Thanks!
Zhu Ming

**Comment by mengxiong10** [comment]
@blackpuppy   你现在的问题最简单的方法是去掉'form-control' 这个class , 因为我里面的 input class 和这个几乎一样.  接下来我会尽量把input 的样式 给到datepicker , 这样就能修改了.

**Comment by blackpuppy** [comment]
@mengxiong10 谢谢！原来是个简单的CSS问题，我还在想如何改变`input` class来达到目的呢，的确去掉`form-control`就可以了。
