### ISSUE TITLE
disabled-days option is not working 

### ISSUE THREAD

**Issue by yugandhargangu** [mengxiong10/vue2-datepicker#40]
I have integrated date picker with my vue2 app.
I pass an array to  disabled-days option in below formats. But it is not disabling those dates.
Array = ['2017-01-14','2017-01-15']  ==> Not working
Array = [new Date('2017-01-14'), new Date('2017-01-15')]  ==> Not working
Array = [1,3]  ==> Not working (as index of days)

Can you let me know how to use this option if My way of usage is wrong

**Comment by mengxiong10** [comment]
As added TimePicker, it should add '00:00:00'.
I'll fix this bug next version, then it can work with '2018-01-13'
thanks for your feedback
```
<date-picker v-model="value" lang="en" :disabled-days="['2018-01-13 00:00:00']"></date-picker>
```

**Comment by mengxiong10** [comment]
Ok, V1.8.1 has fixed it.
Array = ['2017-01-14','2017-01-15'] ===> OK
Array = [new Date('2017-01-14'), new Date('2017-01-15')]  ===> Ok
