### ISSUE TITLE
[Bug] Cannot use shortcuts with range

### ISSUE THREAD

**Issue by denilsonsa** [mengxiong10/vue2-datepicker#400]
**Vue2-datepicker version**: 3.2.2
**Vue version**: 2.6.10 (doesn't matter)
**Browser**: Chrome 78 (doesn't matter)

**Steps to reproduce**

1. Enable the `range` prop.
    * Now, instead of one single date, this component works with an array of two elements.
2. Generate a list of shortcuts, each one with `onClick` returning a list of two elements.
3. Doesn't work. :(

**Reproduction Link or Source Code**

It should be reproducible with a code similar to this one (note: untested code snippet):

```
  <VueDatePicker
    type="datetime"
    range
    value-type="format"
    format="YYYY-MM-DD HH:mm:ss"
    v-model="foobar"
    :shortcuts="makeShortcuts"
  />
…
    makeShortcuts() {
      return [
        {
          text: 'Last hour',
          onClick: () => [new Date(Date.now() - 60 * 60 * 1000), new Date()],
        },
      ];
    },
```

It would be nice to add to [the demo page](https://mengxiong10.github.io/vue2-datepicker/index.html) one example using both shortcuts and range: 

**Expected behavior**

If the shortcut returns an array of two dates, it should set the range to the returned array.

(Bonus!) If the shortcut returns only one date, then it could behave as if the user clicked on that date on the calendar; i.e. it would select either the start or the end of the range. This way, it would be possible to have a list of "key" dates and let the user click on them to set an arbitrary range between those dates. (When I say "date", please also consider the other types, such as datetime.)

**Actual behavior**

When the shortcut returns an array, the [`handleSelectShortcut`](https://github.com/mengxiong10/vue2-datepicker/blob/v3.2.2/src/date-picker.vue#L379-L386) function does nothing, because it checks if the value is a date before emitting it. In other words, this function does not support ranges.

However, if the shortcut returns a single date (even though the component is in `range` mode), that function blindly calls [emitValue](https://github.com/mengxiong10/vue2-datepicker/blob/v3.2.2/src/date-picker.vue#L345-L353), which will emit the single date instead of the expected array, which will then break code outside of the component.

**Comment by mengxiong10** [comment]
I'll fixed it soon.

**Comment by mengxiong10** [comment]
v3.3.0 fixed it.
