### ISSUE TITLE
[Bug] Not able to call function on calender icon click

### ISSUE THREAD

**Issue by raghuvarbisht** [mengxiong10/vue2-datepicker#405]
**Vue2-datepicker version**: 3.3.0
**Vue version**: "^2.5.16"
**Browser**: chrome 

**Steps to reproduce**
1-Click on the calendar icon not calling onFocusStartDate method. I want to call this method when the user click on the calendar icon.

**Reproduction Link or Source Code**
https://codesandbox.io/s/vue2datepicker-disabled-uj2u1

**Expected behavior**
When clicking on the calendar icon it should call the same function which we are calling on input focus.
**Actual behavior**
When clicking on the calendar icon it showing calendar but not making a call for function.

**Comment by raghuvarbisht** [comment]
Is there any way we can call a function from calendar icon click?

**Comment by mengxiong10** [comment]
1.
```html
<date-picker @click.native="handleClick" />
```
```js
  methods: {
    handleClick(evt) {
      const target= evt.target;
      if (target.className === 'mx-icon-calendar') {
        // do something
      }
    },
  },
```
```css
.mx-icon-calendar svg {
  pointer-events: none;
}
```
----
2.
```html
<date-picker  />
```
```js
  mounted() {
    const icon = document.querySelector('.mx-icon-calendar');
    icon.addEventListener('click', () => {
      // do something
    });
  },

```
---
3. Use the custom icon.
```html
      <date-picker
        v-model="value"
        placeholder="Select date"
      >
        <i slot="icon-calendar" @click="handleClick">
          // your icon
        </i>
      </date-picker>
```

**Comment by raghuvarbisht** [comment]
Thanks mengxiong really appreciate quick response now above solution working for me perfectly.
