### ISSUE TITLE
offsetX - Why right aligned?

### ISSUE THREAD

**Issue by sanderbongers** [mengxiong10/vue2-datepicker#406]
In vue2-datepicker/src/util/dom.js function getRelativePosition(), it says to align the popup on the right side of the input field, in case the width and left margin of the input field is more than the 50% screen width:

```
  if (dw - relativeRect.left < targetWidth && relativeRect.right < targetWidth) {
    left = offsetX - relativeRect.left + 1;
  } else if (relativeRect.left + relativeRect.width / 2 <= dw / 2) {
    left = offsetX; /* left aligned */
  } else {
    left = offsetX + relativeRect.width - targetWidth; /* right aligned */
  }
```
Why is this? I have forms that are aligned on the right half of the page, but they are the same markup as other forms. The text is also aligned on the left, and the input fields are relatively wide. So now when you open the datepicker popup, it opens all the way on the right, way right of the input's placeholder text.

I would prefer it to always open on the left side of the input field, so `offsetX = window.pageXOffset + relativeRect.left`.

**Comment by mengxiong10** [comment]
set the `popup-style`
```html

<date-picker  :popup-style="{ top: '100%', left: 0}" :append-to-body="false" />
```

**Comment by sanderbongers** [comment]
Sorry, didn't know about this option. Resolved, thanks!
