### ISSUE TITLE
set language dynamically?

### ISSUE THREAD

**Issue by saraha33** [mengxiong10/vue2-datepicker#407]
Hi,

it might be my lacking knowledge however would you eventually have advice on how to set the datepicker language dynamically?

Currently i am doing this: 

```js
  async mounted() {
    // if the language is not english - import from correct locale from datepicker
    if (this.language !== 'en') {
      // eslint-disable-next-line global-require
      const x = await import(`vue2-datepicker/locale/${this.language}`);
      this.langObject = x.default;
    }
  },
```

```html
<datepicker :lang="langObject" />
```

However that seems awfully hacky...

just doing `import('vue2-datepicker/locale/${this.language}\')` (as it would make sense to me) did unfortunately not have any effect (lang remains english)

As mentioned - it might be my lack in understanding how to use import - but any help would be appreciated!

**Comment by mengxiong10** [comment]
You can import the locale files which you need, then change the prop `lang`.
```html
<date-picker :lang="lang" />
```

```js
import 'vue2-datepicker/locale/en';
import 'vue2-datepicker/locale/zh-cn';

export default {
  data() {
    return {
       lang: 'zh-cn'
    }
  },
  methods: {
     changeLocale() {
       this.lang = this.lang === 'zh-cn' ? 'en' : 'zh-cn'
     }
  }
}

```

**Comment by saraha33** [comment]
Sorry for taking a while to get back on this, but ok I see - I was hoping there was a more generic way but I guess this will have to do for now.

 thanks for your answer anyway!
