### ISSUE TITLE
[Feature request] Support timezone

### ISSUE THREAD

**Issue by ansidev** [mengxiong10/vue2-datepicker#408]
**What problem does this feature solve?**
Can you support timezone picker?

**What does the proposed API look like?**

**Comment by mengxiong10** [comment]
what's the timezone picker like?

**Comment by ansidev** [comment]
I think a select box is good enough.

Ref link: https://baseweb.design/components/timezone-picker/

**Comment by mengxiong10** [comment]
I think this is not a feature of this library, other libraries should be used
