### ISSUE TITLE
[Feature] Adjust Z-Index of popups to account for Bootstrap modals

### ISSUE THREAD

**Issue by camper2020** [mengxiong10/vue2-datepicker#412]
Version 3.0.0+ of DatePicker does not _appear_  to show the popup on BS Modals. The popup does show but the **z-index** CSS property of **.mx-datepicker-popup** is set to 1000 which is behind BS Modal.

Could the default **z-index** be changed to **2000** to put it in front of these modals (and potentially other popups)

Marking this as a feature and not a bug, as there is nothing wrong with the DatePicker popup functionality and the CSS property can also be easily overridden in applications. Only suggesting it as it may cause confusion when the popup _appears_ to not show.

Thanks for making such a helpful component!

**Comment by mengxiong10** [comment]
Good advice

**Comment by digEmAll** [comment]
I second this request and I'd suggest to make the z-index a scss variable.

**Comment by mengxiong10** [comment]
v3.3.1
