### ISSUE TITLE
OK button is active even though only one date is selected

### ISSUE THREAD

**Issue by single-page** [mengxiong10/vue2-datepicker#413]
OK button (confirm) is active even though only one date is selected (((

Fix please

![image](https://user-images.githubusercontent.com/48788140/72278990-cdb02700-363d-11ea-934e-69b9c6a53553.png)

**Comment by mengxiong10** [comment]
The prop `confirm` is not recommended in v3.x.
When you click `OK` button, It'll emit the last valid date.
