### ISSUE TITLE
[Bug] CalendarPanel and TimePanel issues

### ISSUE THREAD

**Issue by plakhin** [mengxiong10/vue2-datepicker#415]
**Vue2-datepicker version**: 3.3.0
**Vue version**: 2.6.0
**Browser**: Chrome, Firefox (latest stable versions)

**Steps to reproduce**
Select date and time. 

**Reproduction Link or Source Code**
https://jsfiddle.net/plakhin/b9Luwp5m/6/

**Expected behavior**
Select date, selected date should be highlighted. Select time, selected time should be highlighted. 
Selected date and time should go to input box.

**Actual behavior**
Selected date goes to input element but is not highlighted and doesn't affect TimePanel. Selecting time flashes the date back, selected time is not highlighted.

I Believe this code was working some time ago when I just found it in some issues here.

If you remove ```<template>``` slot inside ```<date-picker></date-picker>``` it works as expected.

**Comment by mengxiong10** [comment]
You losed the prop `value`.

`:value="slotProps.value"`

```html
              <calendar-panel
                    @select="slotProps.emit"
                    :value="slotProps.value"
                ></calendar-panel>
                <time-panel
                    format="HH:mm"
                    show-time-header
                    @select="slotProps.emit"
                    :value="slotProps.value"
                ></time-panel>

```

**Comment by plakhin** [comment]
Wonderful!
Thank you!
