### ISSUE TITLE
[Feature request] Ignore whitespace around separator on manual range input

### ISSUE THREAD

**Issue by doits** [mengxiong10/vue2-datepicker#416]
**What problem does this feature solve?**

If I have a range-input with separator `<space>~<space>` (like the default), I can manually enter the range with the keyboard exactly like this:

```
2015-12-12 ~ 2016-12-31
```

When I omit the spaces on manual input though, it does not work, for example like this: 

```
2015-12-12~2016-12-31
```

Or if I add multiple spaces by accident:

```
2015-12-12 ~   2016-12-31
```

It would be nice if the spaces around the range separator do not have any impact when the user enters values manually, because users sometimes type like this.

**Comment by mengxiong10** [comment]
OK, This is a good improvement.

**Comment by mengxiong10** [comment]
v3.4.0 added it.

**Comment by doits** [comment]
Thank you for implementing it! I will test it out as soon as I can, thank you!

I looked at the commit though and I am wondering if there might be a problem now with `-` separator? Eg. if the separator is `-`, can it parse `2020-02-02 - 2020-03-03` or will it split on each `-` and then fail?

I think before this feature if separator `<space>-<space>` was used, this was no problem because the spaces were taken into account. Or am I wrong?

**Comment by mengxiong10** [comment]
@doits thanks for feedback, It's bug. I need to fix it soon.

**Comment by mengxiong10** [comment]
I released v3.4.1 to fix the bug

**Comment by doits** [comment]
:+1: good job, really fast fix. Now `<space>-<space>` should work again, which some people might use.

I still think though that the separator `-` (without spaces) does not work if the user enters `2020-02-02 - 2020-03-03` or even `2020-02-02-2020-03-03` (but this maybe makes no sense to enter it like this).

And on the other hand even if separator is `<space>-<space>`, if the user enters `2020-02-02- 2020-03-03` (no or only spaces on on side) it will break, too.

Maybe this feature is more complicated than it looked like at first, at least if the separator can be part of the date with all this edge cases ... sorry for the work you have with it!

**Comment by mengxiong10** [comment]
Yes, this feature is complicated now.
It may be improved in the future. Using 2 input element or other parsing methods
