### ISSUE TITLE
[Feature request] Add opportunity to highlight array of specific dates

### ISSUE THREAD

**Issue by DmitriyKurto** [mengxiong10/vue2-datepicker#417]
**What problem does this feature solve?**
I has array of specific dates when some events happend. Would be nice to have opportunity to show for users these dates by highlighting all of them at the same time (not like range)

**What does the proposed API look like?**

```
<datepicker :highlighted="highlighted"/>

...
data () {
  return {
    highlighted: [
     new Date(1579018009116),
     new Date(1578018009116),
    ]
  }
}
...

**Comment by mengxiong10** [comment]
Infact, there is a prop named get-classes to set the classes of date.
```html
<date-picker  v-model="value" :get-classes="getClasses" />

```

```js
  methods: {
    getClasses(date) {
       if (this.highlighted.find(v => v.getTime() === date.getTime())) {  return  'highlight' }
       return ''   
    },
  },
```
```css
.highlight {

}

```

**Comment by NShulzhenko** [comment]
get-classes prop does not add any class for <td> with class 'cell' for me. I hoped to find cell highlighted but there are no any. I am sure handler for prop returns string as class.

**Comment by mengxiong10** [comment]
https://codesandbox.io/s/highlight-pyjew?file=/src/App.vue
