### ISSUE TITLE
Change "calendar" icon

### ISSUE THREAD

**Issue by vvelkovski** [mengxiong10/vue2-datepicker#42]
Would be nice if we could customize the icon displayed in with the text-input.
I personally do not like the current one.

Just a "nice to have" idea.

**Comment by mengxiong10** [comment]
You can change the css backgroundImage for the icon 
![image](https://user-images.githubusercontent.com/14135808/34968976-6eadbb6a-faa7-11e7-8b73-56e836951f6a.png)

**Comment by vvelkovski** [comment]
Wont that be replaced back after I do npm install?

**Comment by mengxiong10** [comment]
@vvelkovski 
you can replace ".mx-input-icon__calendar" in you css file

**Comment by mengxiong10** [comment]
2.0 added slot
