### ISSUE TITLE
[Bug] date picker behind modals

### ISSUE THREAD

**Issue by orizzz** [mengxiong10/vue2-datepicker#422]
**Vue2-datepicker version 3.3.0**:
**Vue version **:
**Browser**:

**Steps to reproduce**

**Reproduction Link or Source Code**

**Expected behavior**

**Actual behavior**

Date picker behind the modals, i already try to using style with z-index to fix it but stil doest change anything

is there any way to fix this ?

![image](https://user-images.githubusercontent.com/41751653/74716917-04dbae80-5262-11ea-9656-4c395c064252.png)

**Comment by DiegoCuevas** [comment]
I have the same problem, what do you do about this bug?

**Comment by mengxiong10** [comment]
@DiegoCuevas `appendToBody` false

**Comment by DiegoCuevas** [comment]
I fix this problem, changing the ```z-index``` in my modal. Thanks!
