### ISSUE TITLE
[Feature request] Change the months to show in range

### ISSUE THREAD

**Issue by AlxZb** [mengxiong10/vue2-datepicker#425]
**What problem does this feature solve?**
To show the prev and current month when the disabled dates beginning in the next to current day, ex. is Febraury 18 and the calendar showme current and next month but after 18th are disabled, and I want to show the prev (Jan) and current month.... it's possible?

**What does the proposed API look like?**
Current view
![Captura de pantalla 2020-02-18 a la(s) 11 50 29](https://user-images.githubusercontent.com/13578327/74764469-617da000-5247-11ea-95bf-c35754008592.png)

Wanted view
![Captura de pantalla 2020-02-18 a la(s) 11 50 56](https://user-images.githubusercontent.com/13578327/74764590-9a1d7980-5247-11ea-9337-18328daf6def.png)

**Comment by mengxiong10** [comment]
You can set the `defaultValue`.
```
:default-value="new Date(2020, 0, 1)"
```

**Comment by AlxZb** [comment]
Thanks dude!, I was think that it was more complicated hahahaha.
