### ISSUE TITLE
[Bug] Sticky rendering in Firefox

### ISSUE THREAD

**Issue by kelunik** [mengxiong10/vue2-datepicker#427]
**Browser**: Firefox ([version](https://hg.mozilla.org/releases/mozilla-release/rev/816e7f29478180f322fb4731df776d3b7854f0f8))

**Steps to reproduce**

 - Focus date input
 - Scroll while keeping focus

**Reproduction Link or Source Code**

 - https://mengxiong10.github.io/vue2-datepicker/index.html

**Expected behavior**

 - Date dialog stays right below / above input field

![vue2-datepicker-nonsticky](https://user-images.githubusercontent.com/2743004/75193691-ff490180-5756-11ea-8de7-e9b408449fb0.gif)

**Actual behavior**

 - Date dialog is displayed sticky and stays at a fixed position

![vue2-datepicker-sticky](https://user-images.githubusercontent.com/2743004/75193604-d9236180-5756-11ea-83ce-0a88298cc547.gif)

**Comment by kelunik** [comment]
The cause for this seems to be that the scrolling element isn't `body` or `html`, but an inner `div` next to the popup. Not sure why it works in Chrome.

**Comment by mengxiong10** [comment]
v3.4.0 fixed it.

**Comment by kelunik** [comment]
Fix confirmed, thanks!
