### ISSUE TITLE
[Feature request] Emit selected event on DatePicker

### ISSUE THREAD

**Issue by lucianholt97** [mengxiong10/vue2-datepicker#428]
**What problem does this feature solve?**
Listen/ react to first click when selecting a range.
This would allow to create an optional range picker without needing the second click when selecting a single day.
Alternatively the input event could be fired on both clicks with [Date, null] on the first click.

**What does the proposed API look like?**
The selected event only needs to be bubbled from the Panel components.

**Comment by mengxiong10** [comment]
same as #429
