### ISSUE TITLE
[Feature request] Range picker should emit event on first selected date

### ISSUE THREAD

**Issue by colq2** [mengxiong10/vue2-datepicker#429]
**What problem does this feature solve?**

It is not possible to listen to the `select` event which is emitted by `CalendarPanel` in `CalendarRange`. It would be awesome to get this possibility.

**Use case**

For example we have a range picker, but it is possible to have a same-day range. A UX  would be if the user could only pick once and we can add a computed property for the end date. Which would be by default the same date as the start date.

**What does the proposed API look like?**

1. Approach 
Also emit the input event on the first date pick with `[start_date, null]`

2. Approach
Emit the select event delegated from `CalendarPanel` to `DatePicker`

Thank you for your great work!

**Comment by colq2** [comment]
Same as #428

**Comment by mengxiong10** [comment]
Yes, I'll add the feature in next version.

**Comment by mengxiong10** [comment]
It'll emit a `pick` event when the date is selected .

```html
<date-picker
  v-model="value"
  range
  placeholder="Select date range"
  @pick="handlePick"
></date-picker>
```
```js
methods: {
  handlePick(value) {
    // the first select
    if (!isNaN(value[0]) && isNaN(value[1])) {
      this.value = [value[0], new Date(value[0].getTime() + 30 * 24 * 3600 * 1000)];
    }
  },
},


```

**Comment by mengxiong10** [comment]
v3.4.0 added it.
