### ISSUE TITLE
Dynamically check selected date range within 1 month

### ISSUE THREAD

**Issue by ahyong83** [mengxiong10/vue2-datepicker#430]
I wish to have my date picker to have validation as below;
1. Always blocked the date not after today. I can get this working with disabled-date.
2. Dynamically check selected date range is same or less than 30 days. If selected range is exceed then raise an error. I dun know how to use or trigger the @input-error event. 

Anyone can please show me a working example with scenario above? 
Thanks.

**Comment by mengxiong10** [comment]
```html
<date-picker @change = 'handleChange' />

```
```js

    handleChange(date) {
      if (date[1].getTime() - date[0].getTime() > 30 * 24 * 3600 * 1000) {
        ///
      }
    },


```

**Comment by sumy7** [comment]
I have the same question. After selecting a date, dates over 30 days will be disabled. Is there a way to do this? Thanks.

我也有同样的需求，例如限制选择30天，在选择第一个日期后，与第一个日期距离超过30天的日期将被自动禁用。不知道目前能否实现此功能？

@mengxiong10

**Comment by mengxiong10** [comment]
@sumy7 

The second parameter of the disabledData function is the selected date.

```html
<date-picker  :disabled-date="disabledDate" />

```

```js
disabledDate(date, currentValues) {
  // one date is selected;
  if (currentValues.length === 1) {
    return date.getTime() - currentValues[0].getTime() > 30 * 24 * 3600
  }

  return false;
}

```

**Comment by sumy7** [comment]
> @sumy7
> 
> The second parameter of the disabledData function is the selected date.
> 
> ```
> <date-picker  :disabled-date="disabledDate" />
> ```
> 
> ```js
> disabledDate(date, currentValues) {
>   // one date is selected;
>   if (currentValues.length === 1) {
>     return date.getTime() - currentValues[0].getTime() > 30 * 24 * 3600 * 1000
>   }
> 
>   return false;
> }
> ```

It solved my problem.
Thx.
