### ISSUE TITLE
Change the current date[Feature request]

### ISSUE THREAD

**Issue by FPTSonPM3** [mengxiong10/vue2-datepicker#431]
Change the current date
For example, today is February 27, but I would like the current date on the board to be February 26 and the dates from February 27 onwards are disabled.

**Comment by FPTSonPM3** [comment]
Is tomonth refreshing okay?

**Comment by mengxiong10** [comment]
```html
      <date-picker
        v-model="value1"
        format="YYYY-MM-DD"
        :disabled-date="disabledDate"
        type="date"
        placeholder="Select date"
      ></date-picker>

```
```js
  data() {
    const yesterday = new Date(new Date().getTime() - 24 * 3600 * 1000);
    return {
        value: yesterday  
    };
  }, 
  methods: {
    disabledDate(date) {
      return date.getTime() > new Date().getTime() - 24 * 3600 * 1000;
    },
  }
```

**Comment by FPTSonPM3** [comment]
@mengxiong10  
I see,
I can disable it as I like, but I can't consider the "today" date to go back, I need to do css with the "today" class.
".mx-table-date .today"

**Comment by mengxiong10** [comment]
@FPTSonPM3 https://github.com/mengxiong10/vue2-datepicker/issues/496#issuecomment-661513918
