### ISSUE TITLE
Datepicker Not Showing Default Value

### ISSUE THREAD

**Issue by papakay** [mengxiong10/vue2-datepicker#437]
**Vue2-datepicker version**:  3.4.1
**Vue version**: 2.6.11
**Browser**: Google Chrome

**Steps to reproduce**
I have a datepicker component in a form as below

```
<date-picker
                  v-model="user.dob"
                  id="dob"
                  v-validate="'required'"
                  data-vv-as="Date of Birth"
                  name="dob"
                  lang="en"
                  type="date"
                  input-class="form-control"
                  placeholder="Date of Birth"
                  :not-after="new Date()"
                ></date-picker>
```

`user.dob` has a default value of "2014-01-19" but this default value doesn't show in the datepicker input field.

Please see the screenshot below.

![Screenshot 2020-03-09 at 00 39 21](https://user-images.githubusercontent.com/5013738/76173375-5b704480-619f-11ea-9dc8-51196a503b8f.png)

Please i need help on this.

**Comment by Algeneralo** [comment]
@papakay how did you solve the issue?

**Comment by papakay** [comment]
Hello @Algeneralo I was able to resolve it by specifying `value-type` option to correspond with the date format.

**Comment by Algeneralo** [comment]
@papakay could you please show an example of code?
also after that, the value will appear in the text input, right ?
Thanks!

**Comment by papakay** [comment]
@Algeneralo see below

```
<date-picker
                  v-model="user.dob"
                  id="dob"
                  v-validate="'required'"
                  data-vv-as="Date of Birth"
                  name="dob"
                  lang="en"
                  type="date"
                  input-class="form-control"
                  value-type="format"
                  format="YYYY-MM-DD"
                  placeholder="Date of Birth"
                  :not-after="new Date()"
                ></date-picker>
```

**Comment by Algeneralo** [comment]
@papakay thanks so far for responding.
I think my issue is different, I set the default-value, but it's not showing in the input field

**Comment by papakay** [comment]
@Algeneralo the snippet above also track current dob set by the user and display it in the input field. Could you share how you're doing this?

**Comment by Algeneralo** [comment]
```
<date-picker v-model="alumniYear" value-type="format" input-class="form-control"
                                             :input-attr="{name:'alumni_year',required:'required'}"
                                             format="YYYY"
                                             :default-value="new Date(1990)"
                                             type="year"></date-picker>
```

**Comment by papakay** [comment]
@Algeneralo since you're using format `YYYY`, and value-type as `format` then the default value should just be `1990` and not `new Date(1990)`.

**Comment by Algeneralo** [comment]
@papakay I tried that also, it's not working for some reason

**Comment by mengxiong10** [comment]
@Algeneralo `default-value` is just as default calendar.
```html
<date-picker v-model="dateWithDefault" />
```

```js
  computed: {
    dateWithDefault: {
      get() {
        return this.alumniYear || new Date(1990, 0);
      },
      set(val) {
        this.alumniYear = val;
      }
    }
  },

```
