### ISSUE TITLE
Get end date & time of the month if :type is 'month' or 'year'  

### ISSUE THREAD

**Issue by Aniket-Kale** [mengxiong10/vue2-datepicker#439]
I have `Start Date` & `End Date` fields. [DEMO LINK](https://stackblitz.com/edit/vue2-datepicker?file=index.html).

If the date type `month`: 
- Select `Start Date` as `Jan 2020` and see the selected date & time on the right side of the field. it is `2020-01-01 12:00:00 am` and it's correct.

- Select `End Date` as `Feb 2020` and see the selected date & time on the right side of the field. it is `2020-02-01 12:00:00 am`. **I want this date to be the end date and time of the selected month**. i.e. `2020-02-29 23:30:00 pm`

If the date type `year`:
- `Start Date` is correct
- `End Date` should be the end date of dec month and time.

Is there any way to give a date point. i.e. `start`, `end`, etc? OR any other way to handle this manually? Thanks; Not sure if it's already implemented.

Note: I am not using the `range` picker.

**Comment by mengxiong10** [comment]
You can change the `v-model` to `:value & @input`.
```html
<date-picker
  :value="value"
  type="month"
  format="YYYY-MM-DD HH:mm:ss"
  @input="handleChange"
></date-picker>
```
```js
data() {
  return {
    value: null,
  };
},
methods: {
  handleChange(date) {
    // if you use `valueType = 'format'`, you should parse it to date, then format it.
    this.value = date ? endOfMonth(date) : date;
  },
},

```

**Comment by Aniket-Kale** [comment]
Thanks, @mengxiong10. I'm able to solve this with [date-fns](https://date-fns.org/). I've used [endOfMonth](https://date-fns.org/v2.10.0/docs/endOfMonth) & [setMonth](https://date-fns.org/v2.10.0/docs/setMonth).

```js
if (this.type.value === 'month') {
  endDate = endOfMonth(new Date(endDate));
} else if (this.type.value === 'year') {
  const date = setMonth(new Date(endDate), 11);
  endDate = endOfMonth(date);
}
console.log('endDate: ', endDate)
```
