### ISSUE TITLE
select birthday

### ISSUE THREAD

**Issue by nunob87** [mengxiong10/vue2-datepicker#441]
hello, to use the calendar for the selection of a birthday for people over 18, without having to see the age of 18 until the current date, and have the placeholder visible, without having the date selected

thanks

**Comment by mengxiong10** [comment]
What's the problem?

**Comment by nunob87** [comment]
not practical for selecting birthdays

I should be able to hide the last 18 years from the list

**Comment by mengxiong10** [comment]
You can use `disabled-date`.

```html
<date-picker
  v-model="value"
  :disabled-date="disabledDate"
  :default-value="eighteenYearsAgo"
></date-picker>
```

```js

data() {
  const eighteenYearsAgo = new Date();
  eighteenYearsAgo.setFullYear(eighteenYearsAgo.getFullYear() - 18);
  return {
    eighteenYearsAgo,
  };
},
methods: {
  disabledDate(date) {
    return date > this.eighteenYearsAgo;
  },
},
```


```

**Comment by nunob87** [comment]
thanks
