### ISSUE TITLE
[Bug]No date display on the device IOS- iphone

### ISSUE THREAD

**Issue by FPTSonPM3** [mengxiong10/vue2-datepicker#442]
![90045993_496022324620317_7536805948141076480_n](https://user-images.githubusercontent.com/40652135/76920568-5ed1a180-68fe-11ea-8841-414e7ce11513.jpg)

![image](https://user-images.githubusercontent.com/40652135/76920658-92acc700-68fe-11ea-94bd-5bfa84c6d6f2.png)

<date-picker
         v-model="month"
         type="month" format="YYYY年M月"
          :lang="lang" 
          :editable='false' 
          v-bind:clearable="false" :disabled-date="(date) => date > disabledBefore">
</date-picker>

data() {
            return {
                lang:{
                    days:['日','月','火','水','木','金','土'],
                    months: ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'],
                    monthsShort: ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'],
                    // the calendar title of year
                    yearFormat: 'YYYY 年',
                    // the calendar title of month
                    monthFormat: 'M 月',
                    // the calendar title of month before year
                    monthBeforeYear: false,
                },
                month: new Date(),
                disabledBefore : new Date(),
                // popupElm : null
            }
        },

I have set up like this, when testing on a device reponsive mode for mobile devices, this error does not occur, but when testing on a device device - ios - iphone, the error does not display like this. Above are 2 photos taken on phones and pc

**Comment by mengxiong10** [comment]
What's the error?

**Comment by FPTSonPM3** [comment]
![image](https://user-images.githubusercontent.com/40652135/77867650-4ea4b500-7262-11ea-8450-b52bb83e5a45.png)
here !

**Comment by FPTSonPM3** [comment]
![76920568-5ed1a180-68fe-11ea-8841-414e7ce11513](https://user-images.githubusercontent.com/40652135/77867668-68de9300-7262-11ea-8183-b66d69dcb60a.jpg)
here !
It happens when I access using iOS devices, such as Iphone

**Comment by mengxiong10** [comment]
I think the error is the value.
![Uploading image.png…]()
