### ISSUE TITLE
Do you support Shortcuts like in ElementUI?

### ISSUE THREAD

**Issue by FreddyCrugger** [mengxiong10/vue2-datepicker#446]
Hello,

I would like to know if you support shortcuts like the ones in ElementUI please:
![shortcuts](https://user-images.githubusercontent.com/6231274/77554942-ff9ffe00-6eb6-11ea-8150-9ec1689d5fb8.png)

Thank you.

**Comment by mengxiong10** [comment]
https://mengxiong10.github.io/vue2-datepicker/index.html#Shortcut
