### ISSUE TITLE
:disabled-date set to hide previous and next date as desired

### ISSUE THREAD

**Issue by FPTSonPM3** [mengxiong10/vue2-datepicker#447]
For example, today is 1/4
I want to hide March 31 from the previous days and April 2 and the following days
I'm using :disabled-date, but It only accepts one function
@mengxiong10

**Comment by FPTSonPM3** [comment]
https://mengxiong10.github.io/vue2-datepicker/index.html

**Comment by mengxiong10** [comment]
return date < 3.31 || data > 4.2
