### ISSUE TITLE
How to apply vee-validate on datepicker input?

### ISSUE THREAD

**Issue by anburocky3** [mengxiong10/vue2-datepicker#449]
Here is my code:
```html
<validation-provider
  name="DOB"
  :rules="{ required: true }"
  v-slot="validationContext"
>
  <b-form-group id="DOB" label="Date of Birth:" label-for="DOB">
    <date-picker
      id="DOB"
      v-model="form.dob"
      value-type="format"
      placeholder="1970-12-06"
      :state="getValidationState(validationContext)"
    ></date-picker>
    <b-form-invalid-feedback>{{ validationContext.errors[0] }}</b-form-invalid-feedback>
  </b-form-group>
</validation-provider>
```

It doesn't work for datepicker, if i apply for normal input, its working..

I'm trying to apply `is-invalid` class when i press tab without selecting date-picker value.. How to accomplish it?

**Comment by mengxiong10** [comment]
https://github.com/mengxiong10/vue2-datepicker/issues/173#issuecomment-426246956

**Comment by anburocky3** [comment]
Hello, thanks for responding. I tried the above solution before itself.

I think, the validation works. But how to apply `is-invalid` if the validation failed?
