### ISSUE TITLE
Format Datetime after confirm on the calendar 

### ISSUE THREAD

**Issue by MJayJang** [mengxiong10/vue2-datepicker#45]
This code reads beginDateTimeValue as v-model  and saves date data when I click confirm.
But I'd like to format it to ISOString with specific timezone. What can I do?

```
<datepicker 
v-model="DateTimeValue"
type="datetime"
format="yyyy-MM-dd HH:mm:ss"
:time-picker-options="{start: '00:00', step: '00:30', end:'23:30'}" 
lang="en"
confirm>
</datepicker>
```

**Comment by mengxiong10** [comment]
@MJayJang 
I don't understand what you mean.
Maybe you can reference: https://github.com/mengxiong10/vue2-datepicker/issues/43

**Comment by MJayJang** [comment]
@mengxiong10 Thanks for helping!
