### ISSUE TITLE
Current open panel

### ISSUE THREAD

**Issue by makowy** [mengxiong10/vue2-datepicker#450]
after opening the popup, I need information about which panel is currently open. How can i do this?

**Comment by mengxiong10** [comment]
There is a className.

![image](https://user-images.githubusercontent.com/14135808/78955280-60634380-7b11-11ea-8ea4-4f9522181b5d.png)

**Comment by makowy** [comment]
I was thinking more about some function that returns like change-panel, but this solution is also good. Thank you
