### ISSUE TITLE
disabled-time not working as intended

### ISSUE THREAD

**Issue by nicolasbrigodiot** [mengxiong10/vue2-datepicker#451]
I have 2 datetime pickers, one for the start of a range and one for the end of a range. I cannot use the range feature because the 2 values are not set at the same time. I need the end to be after the start.

For a simpler example let's assume my start date is 2020 Apr. 4 at 15:30. My code is basically this:

```
:disabled-date="disableDate"  
:disabled-time="disableTime"
```

```
disableDate(date) {
    return date < new Date(2020, 3, 9);
},
disableTime(date) {
    return date < new Date(2020, 3, 9, 15, 30);
},
```

In the datetime picker, on the date selection, the earliest date I can pick is Apr. 9, which is correct. But then in the time picker, the earlier hour I can pick is 16, which is not correct. I should be able to select 15, and then the minutes should be disabled until 30.

![image](https://user-images.githubusercontent.com/5188344/78902189-bb495c00-7a79-11ea-938b-dd1b117067a2.png)

**Comment by mengxiong10** [comment]
You need to set a `default-value` which is not disabled.
```
:default-value="new Date(2020, 3,9, 15, 30)"
```

**Comment by nicolasbrigodiot** [comment]
Thank you, but doing this:
- sets a default value for time, which is not necessarily what I want
- sets the default value for any date you pick, not just the minimum date (i.e. in my example, you pick Apr. 20, and you get a default time of 15:30, that just makes very little sense)

Any chance that instead you could fix the behavior so that the minimum time is properly set based on disabled-date and disabled-time?

**Comment by mengxiong10** [comment]
Maybe the name of `default-value` should be `default-calendar`. 
Its role is to display which calendar should be displayed when the value is `null`. 
The defaultValue of `default-value` is `new Date()`.

Because the `default-date` is a function. We cannot know its minimum or maximum.

**Comment by nicolasbrigodiot** [comment]
Maybe I'm confused or I'm missing something but isn't the problem with `disabled-time` and not `default-value`?

I'll admit I haven't looked at the code but when you disable the hours based on `disabled-time`, isn't it just that you ignore the minutes component?

For example:
```
:disabled-time="disableTime"
```
```
disableTime(date) {  
    return date < new Date(2020, 3, 9, 15, 30);  
},
```

I'm guessing you go like:
- should I disable hour 14? disableTime for 14:00 returns true so yes
- should I disable hour 15? disableTime for 15:00 returns true so yes < problem
- should I disable hour 16? disbaleTime for 16:00 returns false so no

In theory I suppose you would have to test every minute of every hour (until you get a false) to know if an hour must be disabled...
- should I disable hour 15? disableTime for 15:00 returns true, for 15:01 as well, etc., but for 15:31 it returns false, so no 15 should not be disabled

But I understand how this does not sound great in terms of performance :(

If we assume that in the vast majority of cases people will not have discrete disabled times, you could get away with just testing minute 0 and minute 59:
- should I disable hour 15? disableTime for 15:00 returns true, but 15:59 returns false, so no

My workaround has heen to subtract 1 hour to the date I use in the `disableTime` function, so that in my case hour 15 becomes enabled ; not ideal because then you can pick any time before 15:30, which is not correct, which forced me to add form validation.

Sorry if I'm suggesting naive approaches, as I said haven't looked at the code, but just trying to help.

**Comment by mengxiong10** [comment]
For example:
```
:disabled-time="disableTime" v-model="value"
```
```
disableTime(date) {  
    return date < new Date(2020, 3, 9, 15, 30);  
},
```
This time always has a basic value. 
```
`the basic value` = value || defaultValue || new Date()
```
when the basic value is `new Date(2020,3,9, 0, 0, 0)`
- should I disable minute 0? disableTime for 00:00 returns true.
- should I disable minute 59? disbaleTime for 00:59 returns true.

when the basic value is `new Date(2020,3,9, 15, 30, 0)`
- should I disable minute 0? disableTime for 15:00 returns true
- should I disable minute 59? disbaleTime for 15:59 returns false.

So when the value is null, you should set a `defaultValue`.

**Comment by mengxiong10** [comment]
```html
<date-picker
  v-model="start"
  :default-value="end || new Date()"
  :disabled-date="disabledStartDate"
  :disabled-time="disabledStartTime"
  type="datetime"
></date-picker>
<date-picker
  v-model="end"
  :default-value="start || new Date()"
  :disabled-date="disabledEndDate"
  :disabled-time="disabledEndTime"
  type="datetime"
></date-picker>

```

```js
data() {
  return {
    start: null,
    end: null,
  };
},
methods: {
  disabledStartDate(date) {
    return this.end && date.setHours(0, 0, 0, 0) > new Date(this.end).setHours(0, 0, 0, 0);
  },
  disabledStartTime(date) {
    return this.end && date > this.end;
  },
  disabledEndDate(date) {
    return this.start && date.setHours(0, 0, 0, 0) < new Date(this.start).setHours(0, 0, 0, 0);
  },
  disabledEndTime(date) {
    return this.start && date < this.start;
  },
},


```

**Comment by suresh444** [comment]
How to disable before start Date date and after enddate?
I should be only able to select in between the given date range.


![image](https://user-images.githubusercontent.com/19501497/93177896-1aaa4700-f751-11ea-99ef-1665d61c1abf.png)

**Comment by mengxiong10** [comment]
@suresh444 
```html
<date-picker
        v-model="value1"
        :disabled-date="disabledBeforeTodayAndAfterAWeek"
      ></date-picker>

```

```js
    disabledBeforeTodayAndAfterAWeek(date) {
      const today = new Date();
      today.setHours(0, 0, 0, 0);

      return date < today || date > new Date(today.getTime() + 7 * 24 * 3600 * 1000);
    }

```
