### ISSUE TITLE
Date range enabled date for single datepicker

### ISSUE THREAD

**Issue by trdonnisedavid** [mengxiong10/vue2-datepicker#454]
Do you have any feature that you have date range that is only enabled?
What I want to achieve is when selecting a date, it should only have a date range option like minDate and maxDate:

![image](https://user-images.githubusercontent.com/46433499/79113633-e56d8780-7db3-11ea-8745-ece2e3a2943f.png)

As you can see in the image, I want the user to select only to 14 - 21.

**Comment by Be-Like** [comment]
You can do this:

`
<date-picker  v-model="selectedDates" type="date" range :disabled-date="selectableRange" />
`

`selectableRange(date) {
return (date < new Date(2020, 4, 14)) || (date > new Date(2020, 4, 21))
}`

**Comment by trdonnisedavid** [comment]
@Be-Like I dont want to use `range` for my date picker is there anything else?
