### ISSUE TITLE
[Bug] disabled dates not working in Firefox

### ISSUE THREAD

**Issue by AxelAndrian** [mengxiong10/vue2-datepicker#458]
**Vue2-datepicker version**: 1.6.2
**Vue version**: 2.6.10
**Browser**: Firefox 75.0

**Steps to reproduce**
- Focus datepicker

**Reproduction Link or Source Code**
https://mengxiong10.github.io/vue2-datepicker/index.html

**Expected behavior**
https://prnt.sc/s0fqir

**Actual behavior**
https://prnt.sc/s0fr0r

**Comment by mengxiong10** [comment]
firefox 75. It's ok.
![image](https://user-images.githubusercontent.com/14135808/79534406-0f24f800-80ad-11ea-9fae-a0231a92bac2.png)

**Comment by AxelAndrian** [comment]
yeah it's weird when i see your demo it's seems fine. But, after I'm implement to my projects that's not working

**Comment by AxelAndrian** [comment]
My component : 
https://prnt.sc/s0y8zd
My disabled date function : 
https://prnt.sc/s0y939

can you help me to find what's wrong in my code?

**Comment by AxelAndrian** [comment]
I find the problem, when i'm init specific `new Date('10-31-2020')` the output is `invalid date`. Just need change the format. Thanks 👍
