### ISSUE TITLE
How can i intercept payload from the Select event

### ISSUE THREAD

**Issue by makowy** [mengxiong10/vue2-datepicker#459]
Hi,
I need to receive date from select. Now it works that select push data into DatePicker, but i need to receive this data straight in my app.
I see that the event is emitted whenever a field is selected. The question is how could I get this payload? Because i want to output picked date(year,month,day) step by step.
Select-year and select-month were great solutions, but they were removed.

@calendar-change does not help me, because it also works after pressing the arrow.

you are doing a good job, thanks

![image](https://user-images.githubusercontent.com/43035202/79563351-f1f02980-80ac-11ea-9ddf-c8eeec8bdf85.png)

**Comment by mengxiong10** [comment]
use `change` event;

**Comment by mengxiong10** [comment]
I think I can add an argument for `calendar-change`.
`type: 'year' | 'month' | 'last-year' | 'next-year' | 'last-month' | 'next-month'`

```html
<date-picker  @calendar-change="handleCalendarChange" />

```

```js
handleCalendarChange(value, oldValue, type) {
 if (type === 'year') { // when select year }
 if (type === 'month') { // when select month }
}

```

**Comment by makowy** [comment]
this solution would be very helpful, thank you

**Comment by mengxiong10** [comment]
v3.5.0 added it.
