### ISSUE TITLE
Help Wanted. Date Picker not visible in IE11

### ISSUE THREAD

**Issue by anubhavpandey1995** [mengxiong10/vue2-datepicker#463]
Hi, 
Im using version 3.5.0. The Date Picker works fine in chrome, but not in IE11. Is there any polyfill I need to add in my webpack?

**Comment by mengxiong10** [comment]
Is there any error? And can you show the code?

**Comment by anubhavpandey1995** [comment]
sorry! I tried to change the styling of the Date picker with overrides, my bad. It works fine now. 
Thanks for the quick reply though.
