### ISSUE TITLE
[Feature request] Differentiate active classes for range

### ISSUE THREAD

**Issue by w00fz** [mengxiong10/vue2-datepicker#464]
**What problem does this feature solve?**
Currently, when a range is enabled, both start and end nodes share the same `active` class. This prevents any kind of specific custom styling.
A practical example would be desiring to style the start of the range `green` and the end of the range `blue`. This is not possible currently.

**What does the proposed API look like?**
Instead of `active` for both start/end range, a possible solution would be to have `active active-start` and `active active-end`. This would allow to target the cells via CSS.

Thanks!

**Comment by mengxiong10** [comment]
You can use the prop `get-classes` to add the classname.
```html
<date-picker  range :get-classes="getClasses" />
```
```js
  methods: {
    getClasses(cellDate, currentDates) {
      if (currentDates.length === 2) {
        if (cellDate.getTime() === currentDates[0].getTime()) {
          return 'active-start';
        }
        if (cellDate.getTime() === currentDates[1].getTime()) {
          return 'active-end';
        }
      }
      return '';
    },
  },

```

**Comment by w00fz** [comment]
Nice, that's exactly what I needed! I don't think I saw this in the docs, I should have checked the props list in general :)

Thanks,

**Comment by mengxiong10** [comment]
@w00fz I'll update the docs.

**Comment by kumarmeet** [comment]
Hey Mengxiong10, 
`blockDatesIterator(typeOfDate, array) {
      for (const blockDate of typeOfDate) {
        let d = blockDate.split("-").join(",");
        array.push(new Date(d));
      }
    },

    //get and show block dates and time highlighted for SP
    blockDatesHighlighted(date) {
      const bd = [];
      const bt = [];

      this.blockDatesIterator(this.gettingDates, bd);
      this.blockDatesIterator(this.gettingDatesOfTime, bt);

      if (bd.find((v) => v.getTime() === date.getTime())) {
        return "highlight";
      } else if (bt.find((v) => v.getTime() === date.getTime())) {
        return "timeHighlight";
      }
    },`

It working well in chrome and mozilla but when we use safari it is not adding classes in safari browser.

**Comment by mengxiong10** [comment]
@kumarmeet Please check this value of `array` for difference between  chrome and safari
```js
let d = blockDate.split("-").join(",");
array.push(new Date(d));
```

**Comment by kumarmeet** [comment]
@mengxiong10, thanks for ur suggestion, actually the array of dates is was not formatting correctly. Now its fixed.

Thanks
