### ISSUE TITLE
[Help Wanted] Can we disable the manual input of date/text input box?

### ISSUE THREAD

**Issue by sirlaughsalot** [mengxiong10/vue2-datepicker#466]
Hello, 

Can we disable the manual input in the box. I want to have a functionality where we only pick the date, and do not enter the date manually. I have been trying but couldn't achieve it. 
![image](https://user-images.githubusercontent.com/44025786/81207680-3a28aa80-8fce-11ea-9cdc-851c0a21446e.png)

**Comment by mengxiong10** [comment]
<date-picker :editable="false" />
