### ISSUE TITLE
set range value in mounted()

### ISSUE THREAD

**Issue by mvalitov** [mengxiong10/vue2-datepicker#467]
**Vue2-datepicker version**: 3.5.0
**Vue version**: 2.6.11
**Browser**: Google Chrome 81.0.4044.138

thanks for this plugin!

how to set initial value for date ranges in mounting process?

I try like this:

```
<date-picker
    v-model="dateRange"
    :placeholder="'Choose event period'"
    :type="'date'"
    :range="true"
    :value-type="'YYYY-MM-DD'"
    style="margin-left: 5px; margin-right: 5px;"
>
</date-picker>

...
data(){
   return {
       dateRange: [null, null],
   }
},
mounted(){
   this.dateRange = ['2020-05-13', '2020-05-13'];
}
```

but range in plugin empty

**Comment by mengxiong10** [comment]
I try it, it's ok. https://codesandbox.io/s/v2-test-1yzoc?file=/src/App.vue:135-154
Do you have some error?

**Comment by mvalitov** [comment]
thanks, I found my mistake.

```
...
this.dateRange[0] = "2020-05-13";
...
this.dateRange[1] = "2020-05-13";
```

vs 
`this.dateRange = ['2020-05-13', '2020-05-13'];`
