### ISSUE TITLE
[Bug]Datepicker Not Showing Default Value

### ISSUE THREAD

**Issue by Algeneralo** [mengxiong10/vue2-datepicker#468]
**Vue2-datepicker version**:latest
**Vue version**:latest

**Reproduction Link or Source Code**
```
<date-picker v-model="alumniYear" value-type="format" input-class="form-control"
                                             :input-attr="{name:'alumni_year',required:'required'}"
                                             format="YYYY"
                                             :default-value="new Date(1990)"
                                             type="year"></date-picker>
```

**Expected behavior**
Showing date in input filed
**Actual behavior**
input filed is empty

**Comment by MarkoKoval** [comment]
Try to set default value via v-model="my_default" value like that
<date-picker 
              v-model="value1" type="datetime" placeholder="Pick a day"
value-format="yyyy-MM-dd-hh-mm-ss"  format="YYYY-MM-DD-hh-mm-ss"   :lang="lang"
          min="2016-06-15-10-10-10"
>
</date-picker>                            
   ( maybe you know how to disable allowed selected date  before and after wished  dates ?)

**Comment by mengxiong10** [comment]
@Algeneralo `default-value` is just as default calendar.
```html
<date-picker v-model="dateWithDefault" />
```

```js
  computed: {
    dateWithDefault: {
      get() {
        return this.alumniYear || new Date(1990, 0);
      },
      set(val) {
        this.alumniYear = val;
      }
    }
  },

```
