### ISSUE TITLE
[Bug] touchstart event opens the popup while scrolling in mobile

### ISSUE THREAD

**Issue by tsguterres** [mengxiong10/vue2-datepicker#469]
**Vue2-datepicker version**:  3.5.0
**Browser**: chrome mobile

While scrolling the page in a mobile browser, everytime the 'touch' of the scrolling actions starts at the datepicker the popup is opened and in turn becomes very anoying to navigate in a page where there is multiples datepickers.

Is there any plans to fix this?

Thanks in advance

**Comment by mengxiong10** [comment]
Thanks for feedback, I'll fix it soon.

**Comment by mengxiong10** [comment]
Fixed it in v3.6.0

**Comment by Sergdan1992** [comment]
Hi! Thanks for best date-picker!

It's same bug in v3.10.1

Why do u return 'touchstart' event ?

**Comment by mengxiong10** [comment]
@Sergdan1992 v.3.11.1 fixed it.
