### ISSUE TITLE
Doesn't support the disabled attribute

### ISSUE THREAD

**Issue by theomails** [mengxiong10/vue2-datepicker#47]
To make the UI consistent, I want to use the same component to display disabled dates as well.
But, if I use this component, the date always becomes editable.

I tried putting a 'disabled' attribute on the component, but it still allows the date to be cleared or changed.

**Comment by mengxiong10** [comment]
It's a good attribute, I'll added 'disabled' next version. 
Now you can disable click by overlay it with extra element.

**Comment by mengxiong10** [comment]
v1.8.3 added.
