### ISSUE TITLE
[Bug] Set before and after dates not allowed to select in <date-picker> 

### ISSUE THREAD

**Issue by MarkoKoval** [mengxiong10/vue2-datepicker#470]

**Comment by mengxiong10** [comment]
https://mengxiong10.github.io/vue2-datepicker/index.html#DisabledDateTime

**Comment by frontender-ua** [comment]
> https://mengxiong10.github.io/vue2-datepicker/index.html#DisabledDateTime

there is samples about notBeforeDate OR notAfter, but for sure topicstarter means that it is not working together

when trying to set :disabled-date date < today && date > (today +14d) for example, it is  not working in such way

**Comment by frontender-ua** [comment]
> _No description provided._

use like below, for disable before and after limit
`disabledDates(date) {
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      const notLater = add(today, { days: 13 });
      return date < today || date > notLater;
    },`
