### ISSUE TITLE
Time picker 

### ISSUE THREAD

**Issue by laraketai** [mengxiong10/vue2-datepicker#473]
Thank you for best timepicker!

Please advice how to show only enabled times?
Or show on dropdown first enabled times?

<img width="240" alt="Снимок экрана 2020-05-15 в 17 52 39" src="https://user-images.githubusercontent.com/29000827/82047685-11429c80-96d5-11ea-95c4-c1d927d56d69.png">

**Comment by tsguterres** [comment]
I have not tried the timepicker yet but looking at the scss files I think that adding this will do the trick:

`.#{$datepicker-namespace}-time-item.disabled{
	display: none;
}`
