### ISSUE TITLE
[Bug]"disabled-time"  only set it after one hour

### ISSUE THREAD

**Issue by LiuYnag** [mengxiong10/vue2-datepicker#474]
```
<date-picker
              v-show="form.strategy==1"
              v-model="form.startTime"
              type="datetime"
              value-type="format"
              format="YYYY-MM-DD HH:mm"
              :clearable="false"
              :editable="false"
              :disabled-date="(date) => date < $moment().subtract(1, 'days')"
              :disabled-time="(date) => $moment().subtract(1, 'minutes').isAfter(date)"
              style="margin-left: 12px;"
              @open="showDate"
            />


startTime: this.$moment().format('YYYY-MM-DD HH:mm')
```
when i set the disable time，I find that I can only set it after one hour.
Then i set the disable time is last minute of current time,it's normal disabled time.
But when i wait 1minute later.
The disable time to automatically change to next hour.

Please, how can I do for that.

**Comment by mengxiong10** [comment]
set a `default-value="$moment().subtract(1, 'minutes')"`

**Comment by LiuYnag** [comment]
> set a `default-value="$moment().subtract(1, 'minutes')"`
My vue2-datepicker version is 3.5.0
```
<date-picker
            v-model="startTime"
            :default-value="$moment().subtract(1, 'minutes')"
            type="datetime"
            value-type="format"
            format="YYYY-MM-DD HH:mm"
            :clearable="false"
            :editable="false"
            :disabled-date="(date) => date < $moment().subtract(1, 'days')"
            :disabled-time="(date) => $moment().subtract(1, 'minutes').isAfter(date)"
            style="margin-left: 12px;"
          />
```
还是不行，加了这个default-value配置后禁用时间直接就变成1 小时之后了。
去掉这个default-value还能正常禁用当前时间之前；控件等待一分钟之后才会变为禁用1小时之后。

**Comment by mengxiong10** [comment]
这个 `default-value` 值作用是 当value 是空的时候, 下面的日历和时间怎么显示, 所以如果你设置过这个disabled-date/disabled-time, 你应该设置这个值不是被 disabled. 因为$moment() 是动态的, `$moment().subtract(1, 'minutes')` 两次的结果不一样, 你可以把 `:default-value="$moment().subtract(2, 'minutes')"`

**Comment by mengxiong10** [comment]
:default-value 可以接受的值是Date类型

**Comment by LiuYnag** [comment]
先这样吧
