### ISSUE TITLE
[Feature request] Option to disable animations

### ISSUE THREAD

**Issue by 7PH** [mengxiong10/vue2-datepicker#475]
**What problem does this feature solve?**

We need to minimize screen re-renders in our web app for technical reasons.

**What does the proposed API look like?**

I would suggest a flag such as `disable-animations` that when set to true, disables animations.

I am also interested in a work-around if any exists.

**Comment by 7PH** [comment]
I am using old-style browser import. I generate the `index.js` using `npm run build:index` (same for css). 
I was able to remove most of animations by manually removing the css `transition` properties, but this does not seem optimal, and does not remove all transitions (particularly the ones in the time picker when a new hour is selected and the content scrolls).
By the way, this component looks really nice, nice job!

**Comment by mengxiong10** [comment]
I can add a prop for the time picker to control animation.

**Comment by 7PH** [comment]
Thank you very much @mengxiong10 this will be very useful for our project. Do you know when you are planning to merge this to master?

**Comment by mengxiong10** [comment]
@7PH l'll release it this week and then close the issue.

**Comment by mengxiong10** [comment]
v3.6.0 added it.
