### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by ahsanzameer** [mengxiong10/vue2-datepicker#476]
**What problem does this feature solve?**
Right now there is no disable date option for a before and after in date range. Users can only disable one date (before or after) at a time based on today.  What if I have to disable the date before and after a specific period?

**What does the proposed API look like?**
Right now there is `:disabled-date` only. Can you please make it something like `:disabled-date-before` and `:disabled-date-after` so it will be easier and more flexible.

**Comment by mengxiong10** [comment]
```js
disabledDate(date) {
  return date < before || date > after
}

```
