### ISSUE TITLE
Error in render function: "TypeError: this.t is not a function"

### ISSUE THREAD

**Issue by josemorenoaguilera** [mengxiong10/vue2-datepicker#477]
The error is:
Error in render function: "TypeError: this.t is not a function"

I have unistalled and re install the component, import, and use on the html, when I try the input, in the console say the error.

**Comment by mengxiong10** [comment]
The version vue need > 2.5

**Comment by josemorenoaguilera** [comment]
What version I can use for Vue 2.3.4?

**Comment by josemorenoaguilera** [comment]
I solved my problem using the 3.2.0 version.

npm install vue2-datepicker@3.2.0 --save
