### ISSUE TITLE
Min/Max Date properties

### ISSUE THREAD

**Issue by cokuna-pavelkosolapov** [mengxiong10/vue2-datepicker#482]
May be needed to limit days in calendar, that may not be selectable. For example you need take some date in the future of today.

Would be great to have optional properties like `max-date`, `min-date` of type `Date`. The days out of that range should be disabled (not clickable and grey)
```
<date-picker 
  v-model="date" 
  :max-date="someMaxDate"
  :min-date="someMinDate"
</date-picker>
```
```
date() {
  return {
    someMaxDate: null,
    someMinDate: new Date()
  }
}
```

**Comment by mengxiong10** [comment]
https://mengxiong10.github.io/vue2-datepicker/index.html#DisabledDateTime

**Comment by cokuna-pavelkosolapov** [comment]
Thanks. It was not obvious to me, sorry
