### ISSUE TITLE
Adding quarter date type.

### ISSUE THREAD

**Issue by shadysherifsayed** [mengxiong10/vue2-datepicker#485]
**What does the proposed API look like?**
This can work in two ways:
1- the first one the same week date type is being handled, hovering over one day all the whole week is selected or being active, so for quarter hovering/selecting a month will select the quarter for this month.

2- The second one by having four options that represent the four quarters.

**Comment by mengxiong10** [comment]
No plan to add this feature.
If you want to get it. You can implement a inner component through various components that have been exported.

```html
    <date-picker v-model="value">
      <template v-slot:content="slotProps">
        <your-panel :value="slotProps.value" @select="slotProps.emit"></your-panel >
      </template>
    </date-picker>
```

**Comment by rxomidov** [comment]
> ```
> slotProps.emit
> ```

how to close popup then?
