### ISSUE TITLE
time autocomplete

### ISSUE THREAD

**Issue by frontender-ua** [mengxiong10/vue2-datepicker#486]
Hi and first of all thanks for very useful plugin. 

Is there any possibility or functionality already implemented to autocomplete manually entered time? For example, user enter 6 p - will proceed to 06:00 pm?

Maybe such feature already implemented but I don't get it from doc, will be glad for the advice

**Comment by mengxiong10** [comment]
You can get this function by `format`.
```html
<date-picker :format="format" />

```

```js
data() {
  return {
    format: {
      // Date to String;
      stringify(date) {
        return ''
      },
      // String to Date;
      parse(str) {
        return date;
      }
    }
  }
}

```
