### ISSUE TITLE
Set language i18n

### ISSUE THREAD

**Issue by MaxDiMart** [mengxiong10/vue2-datepicker#488]
Tell me how I can change the language of a component dynamically (for example, by pressing a button). Or bind componentization localization to the installed language i18n.

**Comment by mengxiong10** [comment]
```html

<date-picker :lang="lang" />

```

```js
import 'vue2-datepicker/locale/zh-cn';
import 'vue2-datepicker/locale/en';

export default {
  data() {
    return {
      lang: 'en'
    }
  },
  methods: {
    changeLang() {
      this.lang === 'en' ? 'zh-cn' : 'en'
    }
  }
}

```

**Comment by MaxDiMart** [comment]
Thank. Your code helped me.

**Comment by VictorPullzz** [comment]
@mengxiong10 Can you help?
How I can change globaly language, to change the language in all components.
Would be cool have global method ```$vue2Datepicker.setLang('en')``` - for example

**Comment by mengxiong10** [comment]
@VictorPullzz 
```js
import DatePicke from 'vue2-datepicker'

DatePicker.locale('en')

```

**Comment by VictorPullzz** [comment]
@mengxiong10 Thanks man!

**Comment by lightmyfire17** [comment]
@mengxiong10 Hey there! In my app I have more than 100 datepickers, is there any fancy way to change languange in all of them? I don't think that watching global languange and editing each datepicker is good idea :)

**Comment by mengxiong10** [comment]
@lightmyfire17 https://github.com/mengxiong10/vue2-datepicker/issues/488#issuecomment-863705168
