### ISSUE TITLE
[Bug] there's no way to replace the default input with a custom one and reproduce its logic

### ISSUE THREAD

**Issue by vdkrasny** [mengxiong10/vue2-datepicker#492]
**Vue2-datepicker version**: 3.6.0
**Vue version**: 2.6.11

**Steps to reproduce**
Use the `input` slot to replace the default input

**Reproduction Link or Source Code**
https://jsfiddle.net/dyw1puL0/

**Expected behavior**
I expect the `input` slot to be a [scoped slot](https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots) that provides all internal methods to use on my custom input.

**Comment by mengxiong10** [comment]
Why do you want to replace the default input ?

**Comment by vdkrasny** [comment]
I have a UI kit that I use in an app (it also includes a custom input). Without being able to change the default input, I have to maintain the styles of both components at the same time.

**Comment by mengxiong10** [comment]
```html
<date-picker>
 <template v-slot:input="slotProps">
 <input  type="text"  v-bind="slotProps.props" v-on="slotProps.events" />
</template>
</date-picker>

```

**Comment by mengxiong10** [comment]
v3.6.2 fixed it.
