### ISSUE TITLE
[Bug] Is there any way to highlight date ?

### ISSUE THREAD

**Issue by vaasav-kumar** [mengxiong10/vue2-datepicker#493]
**Vue2-datepicker version**: 3.5.0
**Vue version**: 2.6.11

**Steps to reproduce**
open date-picker -> append <input type="date" /> to calendar-content (by script) -> on changing date on appended input, I change :default-value of date-picker but the date is not highlighted in calendar

**Expected behavior**
on changing date on appended input, the corresponding date must be highlighted in calendar.

Is there any other way to directly highlight date on calendar ?

**Comment by mengxiong10** [comment]
Can you show your code ?

**Comment by mengxiong10** [comment]
Maybe you need: https://github.com/mengxiong10/vue2-datepicker/issues/496#issuecomment-661513918
