### ISSUE TITLE
[Bug]time picker doesn't show up

### ISSUE THREAD

**Issue by winterbreak99** [mengxiong10/vue2-datepicker#494]
**Vue2-datepicker version**:3.6.0
**Vue version**: 2.6
**Browser**:
Safari/Chrome
**Steps to reproduce**
Set  type  to time for date picker, click the input, popup show up but blank. If i changed the type to "date", it works fine, i didn't see any error in the console. Thanks!

**Comment by mengxiong10** [comment]
Can you show your code ?

**Comment by winterbreak99** [comment]
here it is
<DatePicker v-model="value4" type="datetime" value-type="DD/MM/YYYY" format="YYYY-MM-DD" />

**Comment by winterbreak99** [comment]
<DatePicker v-model="value4" type="datetime" value-type="DD/MM/YYYY" format="YYYY-MM-DD" />

**Comment by winterbreak99** [comment]
`   <DatePicker v-model="value4" type="datetime" value-type="DD/MM/YYYY" format="YYYY-MM-DD" />`

**Comment by winterbreak99** [comment]
I just went back check the code again, found the problem, thanks again!
