### ISSUE TITLE
[Feature request]Add position modal

### ISSUE THREAD

**Issue by VictorPullzz** [mengxiong10/vue2-datepicker#495]
**What problem does this feature solve?**
Hi! First I want to thank for your work! Indeed, this is the best minimalistic date plugin I've seen.

Could you add the ability to specify a popup position?

**What does the proposed API look like?**
Just sometimes I want to indicate this)

**Comment by mengxiong10** [comment]
use `popup-style`
```html

<date-picker :popup-style="{ left: 0, top: 0}" />

```

**Comment by VictorPullzz** [comment]
@mengxiong10  Wow, sorry , I miss this!
