### ISSUE TITLE
[Feature request] Ability to position calendar on datepicker (center, left, right and vertical offset)

### ISSUE THREAD

**Issue by virtualbjorn** [mengxiong10/vue2-datepicker#500]
**What problem does this feature solve?**
The mock up given to me has the calendar positioned in the center relative to the datepicker input.

**What does the proposed API look like?**
**Center**
![image](https://user-images.githubusercontent.com/19782129/87284304-cbfde800-c528-11ea-9413-5f5a02ef5440.png)

**Right**
![image](https://user-images.githubusercontent.com/19782129/87284592-1da67280-c529-11ea-80bb-996714d644a9.png)

**Left**
![image](https://user-images.githubusercontent.com/19782129/87284669-34e56000-c529-11ea-9e32-8bbe7dc7022e.png)

**Vertical Offset Top**
![image](https://user-images.githubusercontent.com/19782129/87284819-63fbd180-c529-11ea-88a2-1e962345b5a1.png)

**Vertical Offset Bottom**
![image](https://user-images.githubusercontent.com/19782129/87284884-74ac4780-c529-11ea-8011-657b1ee4bea7.png)

**Comment by mengxiong10** [comment]
try `popup-style`.
```html
<date-picker :append-to-body="false" :popup-style="{ left: 0, top: ' 100%', marginTop: '10px' }"  />

```

**Comment by tudor-sv** [comment]
Hi,
Great plugin!
It would be great if there was a solution to be able to position the popup explicitly, while keeping append-to-body true.
For example, I have a situation in which if I don't append it to the body, it gets cut off by an element with overflow: hidden.
