### ISSUE TITLE
Bundle size is big

### ISSUE THREAD

**Issue by igaloly** [mengxiong10/vue2-datepicker#501]
The problem is the dependence of `date-fns`

![image](https://user-images.githubusercontent.com/38460810/87392654-93582000-c5b5-11ea-9dec-df33d9001f70.png)
![image](https://user-images.githubusercontent.com/38460810/87392668-99e69780-c5b5-11ea-8fc3-5cc98cfc606f.png)

**Comment by mengxiong10** [comment]
If your `tree-shaking` is invalid. You can import 'vue2-datepicker/index.js'
