### ISSUE TITLE
[Feature request] Can you add start/end month for range picker

### ISSUE THREAD

**Issue by gribchic** [mengxiong10/vue2-datepicker#503]
**What problem does this feature solve?**
I need to start select select range from previous month to current. Now when I select picker I see 2 calendars: current month and next one
![image](https://user-images.githubusercontent.com/13151617/87802977-9aec2300-c85a-11ea-8718-1750a22d06ed.png)

**What does the proposed API look like?**
 ```
<date-picker
     v-model="requestedDate"
     range
     startMonth="new Date().getMonth()-1"
     endMonth="new Date().getMonth()"  />
```

**Comment by mengxiong10** [comment]
The prop `default-value`   is  for it.
```html
<date-picker :default-value="defaultValue" />
```
```js
data() {
 const   lastMonth =   new  Date();
 lastMonth.setMonth(lastMonth.getMonth() - 1)
 return {
    defaultValue: [lastMonth, new Date()]
  }
}

```
