### ISSUE TITLE
[Feature request] DateTime range

### ISSUE THREAD

**Issue by dlfmadmfeo** [mengxiong10/vue2-datepicker#505]
1. [Images attached]
![image](https://user-images.githubusercontent.com/68774812/88454734-7c1a0c00-ceac-11ea-8037-683d638d1ca6.png)

![image](https://user-images.githubusercontent.com/68774812/88454773-c00d1100-ceac-11ea-883d-6fa450e80971.png)

![image](https://user-images.githubusercontent.com/68774812/88454799-df0ba300-ceac-11ea-83ac-44e838aa4304.png)

![image](https://user-images.githubusercontent.com/68774812/88454816-fea2cb80-ceac-11ea-8498-71b8f934f140.png)

in last image, the current start time is 00:10 and end time is 01:00.
I wanted to change the end time to 00:30, but the time is disabled and cannot select it.
It seems that when the time difference between start time and end time is shorter than 1hour, end time (00) is disabled.
if (end - start) < 60(minutes) -> disabled,
if(end - start) >= 60(minutes) -> active.

How to solve this issue? 

Thank you.

**Comment by mengxiong10** [comment]
You can select the minute is 30, then the end time is '1:30:00', now you can select '0:30:00'.
