### ISSUE TITLE
How to set min/max date? 

### ISSUE THREAD

**Issue by bogdan-dubyk** [mengxiong10/vue2-datepicker#506]
**Vue2-datepicker version**: 3.6.1
**Vue version**: 2.6.11

How to set min/max date: for example I want my date picker min date to be 1970 : 01 : 01 and the max date is the current date minus 18 years. I found only feature to set min/max hours for time picker but do not see how tom set it for a calendar itself.

As an example in jquery date picker you can set it like:
      $('.datepicker').pickadate({
        min: new Date(1940, 1, 1),
        max: new Date(2001, 12, 31)
      });

**Comment by mengxiong10** [comment]
use `disabledDate`
