### ISSUE TITLE
[Bug] disabled date still allows to input dates in the disabled range

### ISSUE THREAD

**Issue by AyanamiSan** [mengxiong10/vue2-datepicker#508]
the bug is similar to https://github.com/mengxiong10/vue2-datepicker/issues/380 (and mentioned there in the comment), but here I am concerned about the logic instead of appearance. If this is intended behavior it would be nice to have an option to prevent selecting disabled date in this way.

Note that disabling manual input is not really a solution, as sometimes it is beneficial to allow manually entering dates, but prevent selecting some dates.

The workaround would be to use `:value="myDate"` and `@change="updateMyDate"` instead of `v-model="myDate", and manually implement validation logic, but this seems like something that should be handled by the date picker itself.

**Vue2-datepicker version**: 3.6.1
**Vue version**: 2.6.11
**Browser**: firefox

**Steps to reproduce**
set disabled date to something (e.g. `date => date < Date.now()`), then manually enter the date in the disabled range

**Reproduction Link or Source Code**
can be reproduced on the demo page: https://mengxiong10.github.io/vue2-datepicker/index.html

**Expected behavior**
After leaving the input field date reverts to what it was before (or any other behavior that will prevent setting date to the disabled one)

**Actual behavior**
Date is changed to the one specified manually.

**Comment by mengxiong10** [comment]
Thanks for feedback. It should not be changed when the date is in the disabled range.

**Comment by mengxiong10** [comment]
3.6.2 fixed it.
