### ISSUE TITLE
Changing lang globally when have several langs

### ISSUE THREAD

**Issue by AkhmedovSH** [mengxiong10/vue2-datepicker#509]
I wanna import all my languages and set it when user choose one, now it is always 1 language which i imported as last one
Example

import DatePicker from 'vue2-datepicker';
import ru from 'vue2-datepicker/locale/ru';
import en from 'vue2-datepicker/locale/en';
import uz from 'vue2-datepicker/locale/uz';

like below
let lang = localStorage.getItem('lang') // user selected lang
Vue.use(DatePicker, {'lang': lang});

or something like that
let lang = localStorage.getItem('lang') // user selected lang
var configuratedLang = {
  formatLocale: lang ,// user selected lang
  yearFormat: 'YYYY',
  monthFormat: 'MMM',
  monthBeforeYear: true
};
DatePicker.locale(configuratedLang );

**What does the proposed API look like?**
vee-validate package have same as i want there locales work like that
import { ValidationObserver, ValidationProvider, extend, localize } from 'vee-validate';
import en from "./locales/vee-validate/vee-en.json";
import ru from "./locales/vee-validate/vee-ru.json";
import uz from "./locales/vee-validate/vee-uz.json";

// Install messages
let lang = localStorage.getItem('lang') // user selected lang
localize(lang); // this set validations language, localize function imported from vee-validate package

**Comment by mengxiong10** [comment]
You can  use `DatePicker.locale` or `lang`.
```js
import DatePicker from 'vue2-datepicker';
import ru from 'vue2-datepicker/locale/ru';
import en from 'vue2-datepicker/locale/en';
import uz from 'vue2-datepicker/locale/uz';

DatePicker.locale('en')

```
------------------

```html
<date-picker  :lang="lang" />

```
```js

data() {
  return {
    lang: localStorage.getItem('lang') || 'en'
  }
}

```
