### ISSUE TITLE
[Bug]: Click event is registering when the whole component is in disabled state

### ISSUE THREAD

**Issue by praveendivekar** [mengxiong10/vue2-datepicker#511]
**Vue2-datepicker version**: 3.2.1
**Vue version**: 2.6.11
**Browser**: Chrome

**Steps to reproduce**: 
1. Pass the disabled prop as true to make the whole component in a disabled state
2. Click on the date picker input field
3. Click anywhere on the page

**Reproduction Link or Source Code**

**Expected behavior**: The picker pop-up is opening and letting the user select the date.

**Actual behavior**: The picker pop-up should not open up as the date-picker component is in a disabled state.

**Comment by mengxiong10** [comment]
Maybe you need the prop `:editable="false"` not `disabled`

**Comment by praveendivekar** [comment]
I tried with `:editable="false" `prop. unfortunately, it is also not working.

**Comment by mengxiong10** [comment]
The actual behavior is the popup not open up when `disabled=true`. So what do you want ?

**Comment by praveendivekar** [comment]
The expected behaviour is not to open the picker pop-up. However, with the mentioned steps in the bug, the pop-up is opened up on click anywhere on the page.

**Comment by mengxiong10** [comment]
I cann't show up the bug. what's the behavior in the demo? https://mengxiong10.github.io/vue2-datepicker/index.html#Disabled
