### ISSUE TITLE
datetime does not initialize empty value with :value [Bug]

### ISSUE THREAD

**Issue by Ksenia989** [mengxiong10/vue2-datepicker#513]
**Vue2-datepicker version**:
3.3.0
**Vue version**:
2.6.10
**Browser**:
Google chrome
**Steps to reproduce**
The problem is: there's no default empty value while creating datetime component:
I have such state variable:
```
producingPresentationClaim: {
        dateEvent: ''
}
```
and such datetime picker code:
```
<date-picker
    id="dateEventProducingPresentation"
    type="datetime"
    format="DD.MM.YY HH:mm"
    :value="new Date(producingPresentationClaim.dateEvent)"
    :confirm="true"
    :clearable="true"
    :input-class="'form-control'"
    :lang="lang"
    :popup-style="{'left': '0px'}"
    :append-to-body="false"
    :placeholder="'Выберите дату и время'"
    @input="updateDateTimeProperty($event, 'dateEvent')"
/>
```
But I'm getting such view when element is rendered (70th year suddenly):
![image](https://user-images.githubusercontent.com/25930885/92396244-60518900-f12d-11ea-8ad1-73bee4e0b1dd.png)

In the same time with just "date" component it works totally fine:
state:
```
contract: {
        dateStart: ''
}
```
and code:
```
 <date-picker
    id="startContractDate"
    type="date"
    format="DD.MM.YYYY"
    :placeholder="'Выберите дату'"
    :popup-style="{'left': '0px'}"
    :input-class="checkDateIsNotEmpty($v.contract.dateStart)"
    :value="new Date($v.contract.dateStart.$model)"
    :lang="lang"
    :clearable="false"
    :append-to-body="false"
    v-mask="'##.##.####'"
    @input="updateContractProperty($event, 'dateStart')"
/>
```
works just fine (empty by default and I can choose any date, starting with current date):
![image](https://user-images.githubusercontent.com/25930885/92396455-b0305000-f12d-11ea-9ce1-162ab82d2100.png)

It seems a bug for me, what do you think? Thanks in advance!

**Comment by mengxiong10** [comment]
`new Date(null)` is 70th year. I suggest you remove the `new Date` in value to use `value="producingPresentationClaim.dateEvent"`.
If you need the value is String, you can use `value-type`.

**Comment by Ksenia989** [comment]
> `new Date(null)` is 70th year. I suggest you remove the `new Date` in value to use `value="producingPresentationClaim.dateEvent"`.
> If you need the value is String, you can use `value-type`.

That's weird but this way does not display changed when I'm updating value (picking it from the calendar).
There's an empty date (OK)
![image](https://user-images.githubusercontent.com/25930885/92615640-ffa98400-f2c5-11ea-8a3b-1fb23b3b6c8d.png)
then I'm picking date and time and getting the same picture as above (but should be with date). Property was setted correctly but does not displaying in datetime picker
![image](https://user-images.githubusercontent.com/25930885/92615786-2a93d800-f2c6-11ea-9af9-fd282cddd1e7.png)

**Comment by mengxiong10** [comment]
Can you write a codesandbox?

**Comment by Ksenia989** [comment]
Yeah, https://codesandbox.io/s/vue-template-forked-usrsh?file=/src/App.vue

**Comment by Ksenia989** [comment]
> Yeah, https://codesandbox.io/s/vue-template-forked-usrsh?file=/src/App.vue

without confirm it works the same (incorrect)

**Comment by mengxiong10** [comment]
![image](https://user-images.githubusercontent.com/14135808/93566912-572faa00-f9c0-11ea-9bd9-afae59db0508.png)

**Comment by Ksenia989** [comment]
Thanks! It's working. Can you write this case to documentation, I suppose it might be common for some users
