### ISSUE TITLE
clearable not working when range is enabled

### ISSUE THREAD

**Issue by ee987** [mengxiong10/vue2-datepicker#514]
**Vue2-datepicker version**: 3.6.2
**Vue version**: 2.6.11
**Browser**: Firefox 80

**Steps to reproduce**
`<DatePicker v-model="time1" type="datetime" :clearable="true" range />`

**Expected behavior**
There should be a clear button to indicate no range was selected. As when range-property is not specified.

**Actual behavior**
No clear button visible

**Comment by mengxiong10** [comment]
https://mengxiong10.github.io/vue2-datepicker/index.html#Range
The clear button should be visibled when you hover the input and the value is not empty.
