### ISSUE TITLE
Time binds incorrectly

### ISSUE THREAD

**Issue by bribar** [mengxiong10/vue2-datepicker#517]
Here is a fiddle to show issue

https://jsfiddle.net/bribar/L6cj07br/

If you select 11:30 pm from the time picker the binded output will always be 12h format 11:30:00, where it should be 23:30:00. Am I not using the correct properties? Or is this a bug?

**Comment by mengxiong10** [comment]
`HH`.
Change  `value-type="YYYY-MM-DD hh:mm:ss"`  to `value-type="YYYY-MM-DD HH:mm:ss"
