### ISSUE TITLE
I was trying to put a date picker within my vue template, and i was wondering how to disable the automatically opened calender?  Because i when looked through the documentation, i cant  find any explanation on how to turn off the pop up date picker calender.

### ISSUE THREAD

**Issue by Airell98** [mengxiong10/vue2-datepicker#520]
**Vue2-datepicker version**:
**Vue version**:
**Browser**:

**Steps to reproduce**

**Reproduction Link or Source Code**

**Expected behavior**

**Actual behavior**

**Comment by mengxiong10** [comment]
use prop `open`. https://github.com/mengxiong10/vue2-datepicker/issues/518#issuecomment-694689739

**Comment by Airell98** [comment]
I've embeded the open props and set it to false but  the calender is still
there

**Comment by mengxiong10** [comment]
Check your version of vue2-datepciker and show your code ?
