### ISSUE TITLE
Disable Datepicker @change ?

### ISSUE THREAD

**Issue by Hajakutbudeen** [mengxiong10/vue2-datepicker#522]
Its that possible to disable datepicker @change using by id ?

**Comment by mengxiong10** [comment]
What's the change?

**Comment by Hajakutbudeen** [comment]
i found in vue2-datepicker only vue disable working if i use jquery disable thats not working its allow to click datepicker popup

**Comment by mengxiong10** [comment]
https://mengxiong10.github.io/vue2-datepicker/index.html#Disabled
