### ISSUE TITLE
[Bug] possible bug when trying to select week between years ? mode="week"

### ISSUE THREAD

**Issue by kurtn** [mengxiong10/vue2-datepicker#529]
**Vue2-datepicker version**: "vue2-datepicker": "^3.6.2",
**Vue version**: "vue": "2.6.10",
**Browser**: edge chromium, google chrome, safari, Firefox (Mac OS , windows, iPad, tablet)

**Steps to reproduce**
mode set to **week**:

**locale 1) default locale**
    import DatePicker from 'vue2-datepicker';
    import 'vue2-datepicker/index.css';

**locale 2) norwegian locale**
    import DatePicker from 'vue2-datepicker';
    import 'vue2-datepicker/index.css';
    import 'vue2-datepicker/locale/nb';

your private library "date-format-parse" is installed and loads (don't get any errors)

locale 1 and 2) above were all tested with the following settings:

\<date-picker v-model="date" type="week" value-type="YYYY-MM-DD" format="YYYY-MM-DD (YYYY ww)"></date-picker>
\<date-picker v-model="date" type="week" format="YYYY-MM-DD (YYYY ww)" show-week-number></date-picker>

the year returned depends on which date your mouse was pointing on when clicking to pick the week number.
doesn't seem to matter which day of the week January 1. starts, always gives some wrong year + week combination no matter which day of the week January 1. starts as long as the week is in both years.

**Reproduction Link or Source Code**

**Expected behavior**

for 52 week year (default locale)
on weeks with January 1. from first day of week to Thursday:
expecting week 1 and year of January when clicking on any of the days in that week
on weeks with January 1. from Friday to last day of the week:
expecting week 52 and year of December when clicking on any of the days in that week.

for 53 week year (in my case Norwegian locale)
on weeks with January 1. from first day of week to Thursday:
expecting week 53 and year of December when clicking on any of the days in that week
on weeks with January 1. from Friday to last day of the week:
expecting week 1 and year of January when clicking on any of the days in that week

I didn't go into depths of your getWeek method under date-format-parse library

**Actual behavior**
52 week default locale
 (Correct)
![Skjermbilde 2020-10-05 kl  10 36 02](https://user-images.githubusercontent.com/3510142/95057766-e3e3a300-06f6-11eb-85a4-9a8a40f4711e.png)
(Wrong)
![Skjermbilde 2020-10-05 kl  10 36 25](https://user-images.githubusercontent.com/3510142/95057771-e514d000-06f6-11eb-8898-32c51cd1d869.png)
53 week Norwegian locale
(Wrong)
![Skjermbilde 2020-10-05 kl  10 37 15](https://user-images.githubusercontent.com/3510142/95057772-e5ad6680-06f6-11eb-8ed0-e0cfe75fc4f8.png)
(Correct)
![Skjermbilde 2020-10-05 kl  10 37 40](https://user-images.githubusercontent.com/3510142/95057773-e645fd00-06f6-11eb-9454-4a4d8d9dab93.png)

or is there something I missed when using this module

**Comment by mengxiong10** [comment]
You can set `firstDayOfWeek  firstWeekContainsDate` of locale. the first week is base on `firstWeekContainsDate`.
https://github.com/mengxiong10/date-format-parse/blob/master/src/util.ts#L52
https://github.com/mengxiong10/date-format-parse/blob/master/src/locale/nb.ts.

If you think this algorithm is wrong, you can customize it `formatter`

```html
<date-picker :formatter="formatter" />

```


```js
data() {
  return {
   formatter:  {
    getWeek(date) { return ...}
   }
  }
}

```
