### ISSUE TITLE
[Bug] close time panel

### ISSUE THREAD

**Issue by orionchikby** [mengxiong10/vue2-datepicker#531]
Vue2-datepicker version: "vue2-datepicker": "^3.6.2",
Vue version: "vue": "2.6.10",
Browser: edge chromium, google chrome, safari, Firefox (Mac OS , windows, iPad, tablet)
**Steps to reproduce**
click title 

**Reproduction Link or Source Code**
https://mengxiong10.github.io/vue2-datepicker/index.html#ControlTimePanel

**Expected behavior**
close time panel

**Actual behavior**

if control showTimePanell then click title not work

![Screenshot (15)](https://user-images.githubusercontent.com/19212468/96267479-81c94e80-0fd0-11eb-9766-0ef2ff675c5e.png)

**Comment by mengxiong10** [comment]
Becase you should change value of `showTimePanel` to control it.

**Comment by orionchikby** [comment]
I do
And when I click on the date, nothing happens. Maybe there is an event that can be intercepted?

<date-picker
                v-model="dateTs"
                type="datetime"
                value-type="format"
                :disabled-date="notBeforeTodayAndAfterFinishTime"
                :show-time-panel="showDatePickerTimePanel"
                @pick="skipDateRange"
                @open="onDatePickerOpened()"
                :open.sync="openDatePicker"
                :lang="lang"
                :title-format="userFormat"
                :format="userFormat"
                :show-second="false"
                :minute-step="5"
                :input-class='inputCssClass'
            >
<i slot="icon-calendar">
                    <i class="far fa-calendar-alt"></i>
                </i>
                <template v-slot:footer>
                    <button v-if="showDatePickerTimePanel" class="mx-btn mx-btn-text pull-left" @click="showDatePickerTimePanel=false">
                        select date
                    </button>
                    <button v-else class="mx-btn mx-btn-text pull-left" @click="showDatePickerTimePanel=true">
                        select time
                    </button>
                    <button class="mx-btn mx-btn-text" @click="openDatePicker=false">
                        OK
                    </button>
                </template>
            </date-picker>

-----------


 methods: {
            onDatePickerOpened() {
                this.showDatePickerTimePanel = false
            },
            skipDateRange(date) {
                this.showDatePickerTimePanel = true
            },

**Comment by mengxiong10** [comment]
You can listen event `change` to know what you click.

**Comment by orionchikby** [comment]
https://jsfiddle.net/orion_by/syzfcxvw/2/
I don’t understand how this will help me?
Click events don't arrive.
Change events will not give what I need.
Can you help figure out the problem?

**Comment by mengxiong10** [comment]
Do you mean you need back to date picker when you click the title ?
![image](https://user-images.githubusercontent.com/14135808/99226745-369b9900-2825-11eb-8d8e-69d527dae294.png)

**Comment by orionchikby** [comment]
Yes

**Comment by mengxiong10** [comment]
I'll add an event in next version, then this code (`:show-time-panel.sync`)  will work.

**Comment by orionchikby** [comment]
Thank you so much

I think I found another bug
If russian language selected and  format is DD MMM YYYY HH:mm -> Date not selectable

https://jsfiddle.net/orion_by/31h84ty5/8/

**Comment by mengxiong10** [comment]
@orionchikby thanks, It's a date parse bug. You can set value-type="date" to avoid the bug.

**Comment by orionchikby** [comment]
thanks
i tried this before
https://jsfiddle.net/orion_by/31h84ty5/14/
If i set value-type="date" then input does not show default value
no matter what language is set.

**Comment by mengxiong10** [comment]
@orionchikby If the value-type is 'date', the value of `v-model` should be a Date not a string

**Comment by orionchikby** [comment]
@mengxiong10 thanks. I'll try

**Comment by mengxiong10** [comment]
v3.8.0 add the `show-time-panel.sync` and fix the parse error.
