### ISSUE TITLE
DatePicker Range formatting for the input

### ISSUE THREAD

**Issue by dnnsldr** [mengxiong10/vue2-datepicker#534]
I am using Luxon DateTime to get dates and manipulate those dates as necessary in my application.

Using the datepicker I using the range=true to have a date range picker. I am setting the range in my data as such:

```
data() {
        return {
             date_range      : [ Local.minus( { days: 10 } ).toFormat( 'MM/dd/yyyy' ), Local.toFormat( 'MM/dd/yyyy' ) ],
        }
}
```
The date range picker works as expected. On change of the range it is showing the input value as a string ' MM/DD/YYYY ~ MM/DD/YYYY' but then will change to 'MM/DD/YYYY'. Basically it will only show the this.date_range[0].

```
<date-picker
    v-mask="'##/##/####'"
    v-model="date_range"
   :format="'MM/DD/YYYY'"
    :value-type="'MM/DD/YYYY'"
    :editable="false"
    :clearable="false"
    :range="true"
    :disabled-date="(date) => date > new Date()"
    :confirm="false"
     :placeholder="date_range_placeholder"
     :append-to-body="false"
      :popup-style="{'height': '380px', 'top': '35px'}"
></date-picker>
```
I have tried different solutions for the format and the value-type but nothing seems to be working. I understand that right now with the format as it is above should only print out the string of 'MM/DD'YYYY'. Just not sure how to write the format function to get it to output 'MM/DD/YYYY ~ MM/DD/YYYY'. 

Any suggestions would be appreciated.

**Comment by dnnsldr** [comment]
This actually seems to be working every other time.

**Comment by mengxiong10** [comment]
I think you use chech the value of `date_range` when the input value is wrong.

**Comment by dnnsldr** [comment]
The date_range is showing correct such as:

[ 'Sat Oct 10 2020 11:26:23 GMT-0700 (Mountain Standard Time)', 'Tue Oct 20 2020 11:26:23 GMT-0700 (Mountain Standard Time)' ]

It only wants to grab the first and put that in the input value. If you click on the input again, the range is shown correctly. Just the input display is not showing the 'MM/DD/YYYY ~ MM/DD/YYYY'

**Comment by mengxiong10** [comment]
Can you write a codesandbox.
I don't understand what you mean.
