### ISSUE TITLE
[Bug] Slot #input do not bind it's value with a prop "text"

### ISSUE THREAD

**Issue by antonboltnev** [mengxiong10/vue2-datepicker#535]
**Vue2-datepicker version**: 3.6.0
**Vue version**: 2
**Browser**: Chrome

**Steps to reproduce** Place an input to slot #input. (custom or native does not matter)

**Reproduction Link or Source Code** 
`<date-picker
      :ref="'datepicker-' + _uid"
      v-bind="$attrs"
      v-on="$listeners"
      format: 'DDMMYYYY'
      :value-type="valueType"
      :disabled="disabled"
      v-model="$attrs.value"
    >
      <template #input>
        <ui-input
          v-model="$attrs.value"
          :mask="mask"
          v-on="$listeners"
          :label="label"
          :required="required"
          :placeholder="placeholder"
          :errors="errors"
          :disabled="disabled"
          :outline="$props.outline"
        />
      </template>
    </date-picker>`

**Expected behavior** Expect input value to be formatted as 'DDMMYYYY'

**Actual behavior** Get unformatted value instead. If i remove slot - everything is OK.

![date1](https://user-images.githubusercontent.com/38510677/96543822-e5dc6300-12ad-11eb-87c0-9a261515b27e.PNG)
![date2](https://user-images.githubusercontent.com/38510677/96543824-e70d9000-12ad-11eb-8704-54c81c703fa8.PNG)
![date3](https://user-images.githubusercontent.com/38510677/96543825-e70d9000-12ad-11eb-8059-7138d8bdc717.PNG)

**Comment by mengxiong10** [comment]
You can set `value-type="format"` in your case.

**Comment by antonboltnev** [comment]
> You can set `value-type="format"` in your case.

Yeah, but if so, i wont be able to send different formated to datepicker, like new Date(), or a timestamp. Why using your input it works fine, but with custom - no?

**Comment by mengxiong10** [comment]
Because you bind `$attrs.value` with  your input.
<template v-slot:input="slotProps">
			<input type="text"  v-bind="slotProps.props" v-on="slotProps.events"/>
		</template>
