### ISSUE TITLE
[Feature request] Add prop to allow listing only past dates or only future dates, or all

### ISSUE THREAD

**Issue by rianmartins** [mengxiong10/vue2-datepicker#539]
**What problem does this feature solve?**
Simplify front-end validation for inputs that allow only future dates or only past dates

**What does the proposed API look like?**
```
props: {
    min: {
        type: Date
        default: null
    }
    max: {
        type: Date
        default: null
    }
}
```

**User perspective**
- If passing `prop { min: new Date() }` the date picker would list only dates equal or greater than the current date
- Similar logic for `prop: { max: new Date() }`

**Comment by mengxiong10** [comment]
use `disabledDate`.
```html
<date-picker :disabledDate="disabledDate" />

```


```js
    disabledDate(date) {
      return date < min || date > max;
    },

```

**Comment by rianmartins** [comment]
Hello @mengxiong10 

Thanks for the quick reply, the disabledDate is cool, but it doesn't really does what I was expecting. If I have an initially empty value for `form.birthdate` and I use:

```
<date-picker v-model="form.birthdate" :disabledDate="disabledDate" ></date-picker>
```

```
disabledDate(date) {
      return date > new Date("2000");
},
```

The date picker still starts in the current year (2020) and I can still navigate to any future year - the dates would be correctly disabled, but it's not a good experience for the user. 

If I want to say that you can't select any day after the year 2000, why disable all future dates if I could not even bother to show them in the first place? Besides that, the user would need to guess or try all the years until he finds the first valid possible date to enter.

I still think the feature I suggested is necessary, but for now I would accept the `:disabledDate` if the date picker starts in first or last valid date.

Many thanks in advance 👍🏼

**Comment by mengxiong10** [comment]
You can set the `default-value` for the first calendar place.
```html
<date-picker  :default-value="new Date('2000')" />
```
