### ISSUE TITLE
split month when choosing

### ISSUE THREAD

**Issue by blogaster** [mengxiong10/vue2-datepicker#540]
This is the current version. If the period is one month, then it is shown on one half of the block.
![Screenshot_4](https://user-images.githubusercontent.com/30862584/98695933-411ce500-2384-11eb-9c29-ea7be95d503f.png)

In the older version, one month could be divided into two block screens.
![Screenshot_3](https://user-images.githubusercontent.com/30862584/98695944-437f3f00-2384-11eb-99a1-ff1988a29a62.png)

Is there a setting for this display now?

**Comment by mengxiong10** [comment]
It should use the custom component to get it.

https://codesandbox.io/s/range-in-datepicker2x-mode-hlzrg?file=/src/App.vue

**Comment by blogaster** [comment]
How to stop close panel after selected date?

**Comment by mengxiong10** [comment]
@blogaster you can change the type to `range`.
![image](https://user-images.githubusercontent.com/14135808/99209555-62575880-27fe-11eb-8199-33c72d161a21.png)
