### ISSUE TITLE
[Feature request] Timepicker endtime 24:00

### ISSUE THREAD

**Issue by jan-l** [mengxiong10/vue2-datepicker#543]
**What problem does this feature solve?**
When using two timepickers as a timerange, would be great to have support for hours between 00:00-24:00 and not only 00:00-23:00.

**What does the proposed API look like?**

**Comment by mengxiong10** [comment]
The end time is 23:59:59

**Comment by zhoums** [comment]
How to set end tiem 23:59:59? Prod includeEndDate is not work
