### ISSUE TITLE
[Bug] Clearing the text in the datepicker causes a console exception

### ISSUE THREAD

**Issue by bennyadam** [mengxiong10/vue2-datepicker#544]
**Vue2-datepicker version**: 3.8.0
**Vue version**: 2.6.11
**Browser**: Chrome 86.0.4240.198 

**Steps to reproduce**

1. Select a date from the datepicker.
2. Select the text in the input manually and hit backspace.

**Reproduction Link or Source Code**
Can just be reproduced on the official demo page:
https://mengxiong10.github.io/vue2-datepicker/index.html

**Expected behavior**
The text is cleared, no exception is emitted in the console.

**Actual behavior**
An exception is emitted in the console:
```
TypeError: Cannot read property 'stopPropagation' of undefined
    at a.handleClear (date-picker.js:335)
    at a.handleInputChange (date-picker.js:381)
    at a.handleInputKeydown (date-picker.js:414)
    at Ft (vue.runtime.min.js:6)
    at HTMLInputElement.n (vue.runtime.min.js:6)
    at HTMLInputElement.i._wrapper (vue.runtime.min.js:6)
```

There's a recent change introduction a `stopPropagation` call here:
https://github.com/mengxiong10/vue2-datepicker/blob/2eea21fe450df981ae45bd18e69394af4244619a/src/date-picker.js#L335
... while there's a call to `handleClear` without a related event in case the text changes and is empty afterwards:
https://github.com/mengxiong10/vue2-datepicker/blob/2eea21fe450df981ae45bd18e69394af4244619a/src/date-picker.js#L381

**Comment by mengxiong10** [comment]
v3.8.1 fixed it.
