### ISSUE TITLE
[Bug] Slot #input doesn't work properly with a custom input component

### ISSUE THREAD

**Issue by mrOrlando** [mengxiong10/vue2-datepicker#546]
**Vue2-datepicker version**: 3.8.0
**Vue version**: 2.6.11
**Browser**: Google Chrome v86.0.4240.198

**Steps to reproduce**
1. You need to pass the custom input to the input slot and use the variables from the scope (in my example I use `b-form-input` component from the [bootstrap-vue](https://bootstrap-vue.org/docs/components/form-input) library);
2. Try to enter a date manually;
3. An error will appear in the console.

**Reproduction Link or Source Code**
https://codesandbox.io/s/hopeful-bogdan-bpzuc

**Expected behavior**
If a string comes instead of an event in the `handleInputInput` method, then pass it to the `this.userInput` parameter.

**Actual behavior**
An error occurs because the custom component returns the entered value as a string and not an event. You can find this handler in the source code [here](https://github.com/mengxiong10/vue2-datepicker/blob/2eea21fe450df981ae45bd18e69394af4244619a/src/date-picker.js#L406).

**Comment by mengxiong10** [comment]
You can transfrom the input event.
![image](https://user-images.githubusercontent.com/14135808/100038119-6c044000-2e3e-11eb-97fb-08079e95023a.png)

**Comment by mrOrlando** [comment]
Thanks for the answer, however, it looks like a workaround, if you want I can create a pull request in this update, it is very simple, but it will help to avoid such problems in the future for other developers?

**Comment by mengxiong10** [comment]
v3.8.1 fixed it.
