### ISSUE TITLE
[Feature request] start date / end date etc. ?

### ISSUE THREAD

**Issue by LG0012** [mengxiong10/vue2-datepicker#547]
**What problem does this feature solve?**
:start-date="2020-11-01" :end-date="2020-12-01" allows you select days between those start/end dates?

**What does the proposed API look like?**

**Comment by mengxiong10** [comment]
https://mengxiong10.github.io/vue2-datepicker/index.html#DisabledDateTime

**Comment by LG0012** [comment]
const today = new Date();
      today.setHours(0, 0, 0, 0);

      return date < today || date > new Date(today.getTime() + 7 * 24 * 3600 * 1000);
    


Really? 😂
