### ISSUE TITLE
[Bug] xhtml document rendering breaks functionality of calendar click handler.

### ISSUE THREAD

**Issue by adjenks** [mengxiong10/vue2-datepicker#550]
**Vue2-datepicker version**: 	3.8.0
**Vue version**: 2.6.12
**Browser**: All

**Steps to reproduce**
Render page as an XHTML document by passing a "content-type" header with the value "application/xhtml+xml" from the server.

**Expected behavior**
Clicking on a date works

**Actual behavior**
Clicking on a date doesn't work.

in `handleCellClick` the function checks the tag name like so:
```
      if (target.tagName === 'DIV') {
        target = target.parentNode;
      }
```
The problem is that in an xhtml document tag names don't become capitalized on their object representation, they remain in whatever case they were written in, so for me `tagName` was "div" not "DIV". You can mitigate this by doing a simple `.toUpperCase()` or something like that.

**Comment by adjenks** [comment]
I noticed there were several places in the code that check the "tagName", they should probably all be made compatible with xhtml document quirks.

**Comment by adjenks** [comment]
See here for discussion about the issue: https://stackoverflow.com/questions/27223756/is-element-tagname-always-uppercase

**Comment by mengxiong10** [comment]
v3.8.1 fixed it.

**Comment by adjenks** [comment]
Thank you. You should get a bitcoin wallet and put up a QR code for that too.
