### ISSUE TITLE
[Bug] Input class with object syntax

### ISSUE THREAD

**Issue by kelunik** [mengxiong10/vue2-datepicker#552]
**Vue2-datepicker version**: 3.8.0
**Vue version**: 2.6.12
**Browser**: Firefox

**Steps to reproduce**

```
<date-picker
      :input-class="{
         'form-control': true,
         'is-invalid': hasErrors
      }"
      ...
```

**Expected behavior**

Classes are added conditionally like in Vue with `:class`

**Actual behavior**

```
class="[Object object]"
```

This is a regression of 3.8.0.

**Comment by mengxiong10** [comment]
3.8.2 fixed it

**Comment by kelunik** [comment]
Thanks! 😊
