### ISSUE TITLE
Values not being displayed when using Vuex

### ISSUE THREAD

**Issue by alexrafuse** [mengxiong10/vue2-datepicker#555]
**Vue2-datepicker version**:3.7.0
**Vue version**:2.5.17

The datepicker is not displaying my default or selected values. They are being loaded from the store (vuex) so I am using :value and events to bind.

My code:
```
<date-picker
     id="startDate"
     class="datepicker"
     @change="setStartDate"
     :value="startDate"
     :disabled-date="notAfterToday"
>
    {{ startDate }}
</date-picker>
```
I've tried it without {{ startDate }}, still nothing. When I click a date it changes in the Vue console but nothing is displayed in the input field. If I refresh the page, the startDate and endDate are loaded properly, but their respective datepickers are blank.

My getter:
```
computed: {
   startDate: {
      get() {
        return this.$store.state.startDate;
      },
      set(value) {
        this.$store.dispatch("startDate", value);
      },
    },
    endDate: {
      get() {
        return this.$store.state.endDate;
      },
      set(value) {
        this.$store.dispatch("endDate", value);
      },
    },
},
```

My setters:
```
methods: {
    setStartDate(date) {
      this.startDate = date;
    },
    setEndDate(date) {
      this.endDate = date;
    },
}.
```

**Comment by mengxiong10** [comment]
check the typeof `this.$store.state.startDate`

**Comment by alexrafuse** [comment]
It is coming back as a string, but I'm not setting it as one anywhere.

```const state = {
    startDate: new Date(),
    endDate: new Date(),
}```

**Comment by waleev** [comment]
I use `v-model` and `range` options, but there is nothing in datepicker input. Only placeholder.
When select new dates nothing changes in input value.

**Comment by mengxiong10** [comment]
It's the problem with app code not vue2-datepicker.
