### ISSUE TITLE
[Feature request] date range cell start/end CSS classes 

### ISSUE THREAD

**Issue by AlyZidanDev** [mengxiong10/vue2-datepicker#562]
it would be nice if we have costume  CSS classes for range cells like "active start" / "active end"
i am trying to achive the below picker look : 
![image](https://user-images.githubusercontent.com/74658208/101370828-a811b900-38b2-11eb-97a2-1f6f18b5dfcd.png)

i have tried something like below to give the first active cell css elements 

> .cell {
             &.active {
                   color: $calendar-active-color;
                   border: 2px solid red;
                    color: #000;
               &:nth-child(1) {
                  border: 2px solid green !important;
                 }
              }
            }
the problem with this approach it changes the first selected dates only , and whenever i change the range the cells colors goes to default .

**Comment by mengxiong10** [comment]
use `get-classes`.
```html
<date-picker :get-classes="getClasses" />
```
```js
methods: {
  getClasses(cellDate, currentDates) {
    if (currentDates.length === 2) {
      if (cellDate.getTime() === currentDates[0].getTime()) {
        return 'active-start';
      }
      if (cellDate.getTime() === currentDates[1].getTime()) {
        return 'active-end';
      }
    }
    return '';
  },
},

```
