### ISSUE TITLE
Static datapicker with disabled days

### ISSUE THREAD

**Issue by DariuszWalkiewicz** [mengxiong10/vue2-datepicker#565]
Very nice and usefull component. Thank you!

But what you think about possibility to display your datacpicker in static div (not as modal) and pass array with nonwork days / holidays? Datapicker can would be work in two mods - as datapicker and as small calendar. I think about solution simillar to https://vcalendar.io/ (from top part site)

Best regards

Darek

**Comment by mengxiong10** [comment]
```html
<date-picker inline />
```
-----------------------------------------
```html
<calendar-panel />

<script>
const CalendarPanel = DatePicker.CalendarPanel;
export default {
  components: {CalendarPanel }
}
</script>

```
