### ISSUE TITLE
Hide 2nd date picker on range mode

### ISSUE THREAD

**Issue by mick340** [mengxiong10/vue2-datepicker#567]
Is it possible to hide the 2nd date picker when using inline range mode?

Current situation
<img width="709" alt="Screenshot 2021-01-19 at 20 18 26" src="https://user-images.githubusercontent.com/8590308/105082266-9582c600-5a93-11eb-8dab-b0392d0d444f.png">

Situation i would like to create
<img width="491" alt="Screenshot 2021-01-19 at 20 19 57" src="https://user-images.githubusercontent.com/8590308/105082347-b6e3b200-5a93-11eb-8fc0-5b16e2ae84d1.png">

But i cant find a way to hide the 2nd date selector

**Comment by mengxiong10** [comment]
https://codesandbox.io/s/range-picker-with-one-calendar-jvv5s?file=/src/App.vue

**Comment by mick340** [comment]
Ty that fixed it

**Comment by aphavichitr** [comment]
@mengxiong10 I tried the same thing in your example, but I'm still getting 2 datepickers side by side. I'm on vue2-datepicker version 3.9.0. See screenshot.
<img width="579" alt="Screen Shot 2021-02-17 at 5 14 18 PM" src="https://user-images.githubusercontent.com/13293967/108289698-c2ce9c80-7143-11eb-9432-4e65273bc7c1.png">

**Comment by mengxiong10** [comment]
You can check the version of `vue`. If it supports `v-slot`.

```html
<template>
  <date-picker v-model="value" range :style="{ width: '200px'}">
    <template v-slot:content="slotProps">
      <calendar-panel :value="innerValue" :get-classes="getClasses" @select="handleSelect"></calendar-panel>
    </template>
  </date-picker>
</template>

<script>
import DatePicker from "vue2-datepicker";
import "vue2-datepicker/index.css";

const { CalendarPanel } = DatePicker;

function isValidDate(date) {
  return date instanceof Date && !isNaN(date);
}

export default {
  components: {
    DatePicker,
    CalendarPanel
  },
  data() {
    return {
      value: [],
      innerValue: [new Date(NaN), new Date(NaN)]
    };
  },
  methods: {
    getClasses(cellDate, currentDates, classes) {
      if (
        !/disabled|active|not-current-month/.test(classes) &&
        currentDates.length === 2 &&
        cellDate.getTime() > currentDates[0].getTime() &&
        cellDate.getTime() < currentDates[1].getTime()
      ) {
        return "in-range";
      }
      return "";
    },
    handleSelect(date) {
      const [startValue, endValue] = this.innerValue;
      if (isValidDate(startValue) && !isValidDate(endValue)) {
        if (startValue.getTime() > date.getTime()) {
          this.innerValue = [date, startValue];
        } else {
          this.innerValue = [startValue, date];
        }
        this.value = this.innerValue;
      } else {
        this.innerValue = [date, new Date(NaN)];
      }
    }
  }
};
</script>

<style>

.active1 {
  background: #ff0000;
}
.in-range1 {
  background: #ffaaaa;
}
.active2 {
  background: #00ff00;
}
.in-range2 {
  background: #aaffaa;
}
</style>



```

**Comment by aphavichitr** [comment]
> You can check the version of `vue`. If it supports `v-slot`.

Thanks! After updating vue to 2.6.12, this worked!
