### ISSUE TITLE
Disable list of days

### ISSUE THREAD

**Issue by nemanjazajk** [mengxiong10/vue2-datepicker#573]
**What problem does this feature solve?**
Is there a way to insert a list of days for a month that are unavailable and to disable them?
I know that there is "disable-date" , but I don't know how to use it for this problem?

**What does the proposed API look like?**
Provide a way to disable any day of a given year

**Comment by mengxiong10** [comment]
```js
disabledDate(date) {
  const day = date.getDate();
  const disabledList = [3,5,6];
  return disabledList.indexOf(day) !== -1;

}

```

**Comment by nemanjazajk** [comment]
> ```js
> disabledDate(date) {
>   const day = date.getDate();
>   const disabledList = [3,5,6];
>   return disabledList.indexOf(day) !== -1;
> 
> }
> ```

Ok but how can I disable certain days of a year so that it won't repeat in the next month? For example only ['11.02.2021','12.02.2021','17.02.2021']

**Comment by mengxiong10** [comment]
```js
disabledDate(date) {
  const pad = (v) => v < 10 ? `0${v}` : v;
  const day = date.getDate();
  const year = date.getFullYear();
  const month = date.getMonth();
  const text = `${pad(day)}.${pad(month + 1)}.${year}`
  const disabledList = ['11.02.2021','12.02.2021','17.02.2021'];
  return disabledList.indexOf(text) !== -1;

}


```

**Comment by nemanjazajk** [comment]
Thank you so much. I have one more question. How can I combine this with disable previous month with next month?

**Comment by runxc1** [comment]
So I just had the exact same question and didn't see it in any examples or documentation but this is exactly what I was looking for and a great feature to disable individual dates.

**Comment by fianbi** [comment]
How can I update de disabledDates?

**Comment by mengxiong10** [comment]
> How can I update de disabledDates? It works for the first load, but if I change the array with disabled dates it doesnt update the picker.

https://v2.vuejs.org/v2/guide/list.html#Array-Change-Detection
```js
data() {
   return {
      disabledDates = []
   }
}
```
