### ISSUE TITLE
[Feature request] Keep selection when changing range property

### ISSUE THREAD

**Issue by dartcafe** [mengxiong10/vue2-datepicker#575]
**What problem does this feature solve?**
I have a use case, where a user can select date options where he is able to decide between the selection of a single day, a day with time, a time range at the same day and a range spanning over multiple days (with or without time declaration). 

For example: 
* A moment: 2021-02-13 6:00 PM
* A Day: 2021-02-03 (24 hours)
* A time span at one day: 2021-02-13 6:00 PM- 7:00 PM (1hour)
* A day span over multiple days: 2021-02-13 - 2021-02-14 (a weekend)
* A time span over multiple days: 2021-02-13 6:00 PM - 2021-02-14 7:00 PM (25 hours)

## Use case A
It works as I expected with one problem. After selecting the date `currentValue` contains the selected day but ...
![grafik](https://user-images.githubusercontent.com/26707476/107856280-614abd00-6e27-11eb-871f-d6c77713b0d3.png)

... after changing the `range` prop to `true` the selection is lost. As a user I would expect the previously selected date as the first date of a range.
![grafik](https://user-images.githubusercontent.com/26707476/107856288-6d367f00-6e27-11eb-9568-5fd0ed046ae1.png)

## Use case B
User selects a date and then ...
![grafik](https://user-images.githubusercontent.com/26707476/107856280-614abd00-6e27-11eb-871f-d6c77713b0d3.png)

... switches to the timePanel and there ...
![grafik](https://user-images.githubusercontent.com/26707476/107856332-bab2ec00-6e27-11eb-8359-c153e185b005.png)

... he switches to range, the date falls back to `defaultValue`
![grafik](https://user-images.githubusercontent.com/26707476/107856350-dae2ab00-6e27-11eb-8dad-dd8db78388cf.png)

**What does the proposed API look like?**
Switching from 'single day selection' to `range` = `true` should transfer the selected (single) date to the first array item (`curentValue[0]`).

Aditionally: if no `due date` is selected, the day for the due date should be assumed to be the same day as the `from date`, when entering the timePanel. This because selecting a time span for one day, as a user I have to click twice on the wanted day to be able to selet a time span.

**Comment by mengxiong10** [comment]
You can set the value when you set the `range = true`.
```html
<date-picker v-model="valule" range="range" />
```
```js
data() {
  return {
    value: null,
    range: false
  }
},
methods: {
  setRange() {
   this.range = true;
   if(this.value) {
      this.value = [this.value, this.value]
    }
  ]
}



```

**Comment by dartcafe** [comment]
Not sure, if I miss something, but value doesn't get updated until submit. 
If I remove submit from the props, the value get's updated, but the calendar get's closed as soon as I select the first date (like in the fist screenshot. 

Maybe I can catch some events to get this working as expected, but that's a very heavy workaround....

**Comment by dartcafe** [comment]
@mengxiong10 Any hints, how get this working?
If made this fiddle, which works. like my implementation. As the value gets not updated, I have no idea, how to achieve this. 

https://jsfiddle.net/dartcafe/vxb06ksj/2/

**Comment by mengxiong10** [comment]
You need remove `confirm` and control the window by `open`. 

https://jsfiddle.net/ketgjqLm/18/

**Comment by dartcafe** [comment]
Thanks for your help. I got to manage the functionality. Needed some more logic to keep dates in sync, but finally...
