### ISSUE TITLE
detecting events?

### ISSUE THREAD

**Issue by vexsolutions** [mengxiong10/vue2-datepicker#58]
The component does not appear to respond to `@click` or `@change`, I need to trigger a method call on either of these events on the datepicker but it does not seem to work?

`<date-picker v-model="input.action_by_date" format="MM-dd-yyyy"
    lang="en" name="action_by_date" @click="input.errors.clear($event.target.name)">
</date-picker>`

**Comment by vexsolutions** [comment]
Not ideal but a viable workaround.

` watch: {
            'input.action_by_date': function() {
                this.input.errors.clear('action_by_date')
            }
        },`

**Comment by mengxiong10** [comment]
@change is supported
the callback is the value.

**Comment by FPTSonPM3** [comment]
@mengxiong10  You can make an example of no @change function

**Comment by mengxiong10** [comment]
@FPTSonPM3 
```
<date-picker  v-model="date"  @change="handleChange" @click.native="handleClick" />
```

**Comment by FPTSonPM3** [comment]
@mengxiong10 I am able to input the value into datepicker, how to stop it, I just want to use the value except the selection below.

**Comment by FPTSonPM3** [comment]
<date-picker v-model="date" type="date" format="YYYY年MM月DD日" editable='false'></date-picker>

**Comment by mengxiong10** [comment]
@FPTSonPM3 
change the `v-model` to `:value`
```html
< date-picker :value= "date" type= "date" format="YYYY年MM月DD日" editable='false'>< / date-picker >
```
