### ISSUE TITLE
How to castomize datepicker popup?

### ISSUE THREAD

**Issue by Ferym26** [mengxiong10/vue2-datepicker#580]
**Vue2-datepicker version**: 3.9.0
**Vue version**: 2.6.11
**Browser**: chrome 88.0.4324.182

that what i need https://s.mail.ru/DLzi/DHCyMZ6dc
how to insert "month" instead of "monthsShort" in header? the rest css i think

**Comment by mengxiong10** [comment]
`monthFormat`
```html
<date-picker :lang="{ monthFormat: 'MMMM'}" />

```
