### ISSUE TITLE
Ability to change icons of toggle buttons

### ISSUE THREAD

**Issue by Azema4ka** [mengxiong10/vue2-datepicker#581]
I would like to be able to change the icons of the buttons for turning the calendar. For example, through slots
![image](https://user-images.githubusercontent.com/50888444/110920176-222c6080-832e-11eb-9dd4-5ecc284cb62c.png)

**Comment by mengxiong10** [comment]
Change the css `.mx-icon-double-right`

**Comment by Azema4ka** [comment]
> Change the css `.mx-icon-double-right`

Well thank you
