### ISSUE TITLE
[Bug] Cant select single month without clicking twice.

### ISSUE THREAD

**Issue by jyotiSam** [mengxiong10/vue2-datepicker#582]
**Vue2-datepicker version**:3.9.0
**Vue version**: "vue": "^2.6.11",
**Browser**:chrome

**Steps to reproduce**
1. Open vue2 datepicker.
2. Select month tab.
3. Try to select one month by clicking once.
4. Cant select single month range without clicking twice.

Please see if this could be fixed. 

**Reproduction Link or Source Code**

we have used something like below:

  <DatePicker2
            v-model="monthVal"
            type="month"
            range
            format="YYYY-MM-DD"
            value-type="YYYY-MM-DD"
            :clearable="false"
            :disabled-date="disabledAfterToday"
            confirm
            :open.sync="openMonth"
            @change="dateFilterChange('month')"
          >

**Expected behavior**
User should be able to select single month without clicking twice.

**Actual behavior**
Cant select Single month without clicking twice

**Comment by mengxiong10** [comment]
#429 You need remove the `confirm`.

**Comment by jyotiSam** [comment]
Sorry but I cant remove confirm as we need to show confirm button to user. Is it possible to do it any other way?

**Comment by mengxiong10** [comment]
@jyotiSam https://github.com/mengxiong10/vue2-datepicker/issues/564#issuecomment-751602280

**Comment by jyotiSam** [comment]
Is it possible to work with type="month". I don't want to change the type to "date". 
With type month, it is not working.
