### ISSUE TITLE
[Feature request] - Should be able to display previous Month and current month in Range Date Picker -> Currently it shows current and next month in Range Date Picker

### ISSUE THREAD

**Issue by mayank-ps** [mengxiong10/vue2-datepicker#584]
Vue2-datepicker version:3.9.0
Vue version: "vue": "^2.6.11",
Browser:chrome

We have used something like below:

<DatePicker2
v-model="monthVal"
type="month"
range
format="YYYY-MM-DD"
value-type="YYYY-MM-DD"
:clearable="false"
:disabled-date="disabledAfterToday"
>

<DatePicker2
v-model="weekval"
type="week"
range
format="YYYY-MM-DD"
value-type="YYYY-MM-DD"
:clearable="false"
:disabled-date="disabledAfterToday"
>

**Expected behavior**
 When user selects range for type="month" or "year" -> Display to the user should be of current and previous months as well besides showing current and next month. Like currently by default it shows March and April.. It should also be able to show February and March.
This must also be taken care when user wants to select year range when type="year". 

**Current behavior**
Cant display previous month/year on 1st  and current month/year on 2nd. Currently it shows current month/year on 1st and next month/year on 2nd.

**Comment by mengxiong10** [comment]
use `default-value`.
```html
<date-picker :default-value="new Date().setFullYear(new Date().getFullYear() - 1)" />

```

**Comment by mayank-ps** [comment]
Thanks for a quick reply and solution @mengxiong10 . But In my case requirement is a bit different. 

What I want is that even after selection of dates in range(weekly/daily/monthly).. 
1. It must show previous and next month (in week/date type calendar)
2. It must show previous year and current year in (month type calendar)
3. Currently after selecting range of dates(in any weekly/daily/monthly) calendar-> it is showing current  year/month and next year/month. **Requirement says it must show previous and next year/month**

**Comment by mayank-ps** [comment]
@mengxiong10  Is my question clear to you ?

**Comment by mengxiong10** [comment]
You hack the method `updateCalendars`.
```js
import DatePicker from "vue2-datepicker";
import "vue2-datepicker/index.css";

const updateCalendars = DatePicker.CalendarRange.methods.updateCalendars;

DatePicker.CalendarRange.methods.updateCalendars = function (...args) {
  updateCalendars.apply(this, args);

  this.calendars = this.calendars.map((v) => {
    const next = new Date(v);
    next.setMonth(next.getMonth() - 1);
    return next;
  });

};
```

**Comment by maximkompaneev** [comment]
`import DatePicker from "vue2-datepicker";
import "vue2-datepicker/index.css";

const updateCalendars = DatePicker.CalendarRange.methods.updateCalendars;

DatePicker.CalendarRange.methods.updateCalendars = function (...args) {
  updateCalendars.apply(this, args);

  this.calendars = this.calendars.map((v) => {
    const next = new Date(v);
    next.setMonth(next.getMonth() - 1);
    return next;
  });

};
`

this way right panel's  'forward' clicking will be broken ('next-month' button)
possibly some other 'navigation' clicks which use updateCalendar

**Comment by mengxiong10** [comment]
@maximkompaneev 
Yes, you can judge according to the parameters of the function.

https://github.com/mengxiong10/vue2-datepicker/blob/master/src/calendar/calendar-range.js#L57
```js
import DatePicker from "vue2-datepicker";
import "vue2-datepicker/index.css";

const updateCalendars = DatePicker.CalendarRange.methods.updateCalendars;

DatePicker.CalendarRange.methods.updateCalendars = function (...args) {
  updateCalendars.apply(this, args);
  if (args.length === 1) {
      this.calendars = this.calendars.map((v) => {
        const next = new Date(v);
        next.setMonth(next.getMonth() - 1);
        return next;
      });
   }
};
```



```
