### ISSUE TITLE
Is there a way to show a close icon on the popup?

### ISSUE THREAD

**Issue by runxc1** [mengxiong10/vue2-datepicker#586]
I am triggering the calendar popup for multiple date selection and as the calendar stays up allowing the user to pick multiple days it's not exactly evident that you need to click off of the popup to get it to close.   In my scenario I don't display the text box with the dates but have them formatted with a button that says change days which then pops open the pop up.   Is there a way to put a button on the popup to have it close?

**Comment by mengxiong10** [comment]
use prop `open`. https://mengxiong10.github.io/vue2-datepicker/index.html#ControlOpen
And a button in footer slot.
```html
      <date-picker v-model="value3" range placeholder="Select date range" :open.sync="open">
        <template v-slot:footer="{ emit }">
            <button class="mx-btn mx-btn-text" @click="this.open = false">
              close
            </button>
        </template>
      </date-picker>

```

**Comment by runxc1** [comment]
Just what I was looking for

**Comment by solamichealolawale** [comment]
> use prop `open`. https://mengxiong10.github.io/vue2-datepicker/index.html#ControlOpen And a button in the footer slot.
> 
> ```
>       <date-picker v-model="value3" range placeholder="Select date range" :open.sync="open">
>         <template v-slot:footer="{ emit }">
>             <button class="mx-btn mx-btn-text" @click="this.open = false">
>               close
>             </button>
>         </template>
>       </date-picker>
> ```

Thank you @mengxiong10, just a little typo update, `this.open=false` should be updated to `open=false`
