### ISSUE TITLE
[Bug] Incorrect popup positioning in right to left layouts

### ISSUE THREAD

**Issue by asaff1** [mengxiong10/vue2-datepicker#589]
**Vue2-datepicker version**: 3.9
**Vue version**: 2.6
**Browser**: Chrome

**Steps to reproduce**
When toggling between `range=false / true`
Make sure to **extend the display area** so the initial rendering will render two panels in one row:
![image](https://user-images.githubusercontent.com/18662769/112629966-08b70880-8e46-11eb-89ba-82c8dbdc025a.png)
Then press the "Select month" button, this will set the datepicker to `range=false`

**Reproduction Link or Source Code**
https://codesandbox.io/s/winter-butterfly-phq4w?file=/src/App.vue

**Expected behavior**
Datepicker should be placed bellow the input

**Actual behavior**
![image](https://user-images.githubusercontent.com/18662769/112629835-d6a5a680-8e45-11eb-8798-a124f3b65a4f.png)

I've added some additional CSS to adjust the datepicker internal panel to RTL, however I believe this issue is caused by the popup behavior when it opens from right to left
https://github.com/mengxiong10/vue2-datepicker/blob/master/src/util/dom.js#L27

**Comment by mengxiong10** [comment]
Because the position is only calculated when the `visible` changes. 
I need to watch the width of popup.

**Comment by asaff1** [comment]
@mengxiong10 
As I see the range prop is the only one to change the datepicker width, right?
It should be possible to add a watch at the datepicker component https://github.com/mengxiong10/vue2-datepicker/blob/e872756fc3c8dc943953bb86052530568aab2f5a/src/date-picker.js#L204  for `range`,  and then to force re calculating the popup position.

Here is an example fix (a bit hack still):
https://codesandbox.io/s/vue2-datepicker-rtl-forked-plxtv

What do you think?

**Comment by mengxiong10** [comment]
You can update the key of component when you change the `range`.
```html
<date-picker  :range="range" :key="range ? 'range' : 'date' " />

```
