### ISSUE TITLE
Display received value in format DD/MM/YYYY

### ISSUE THREAD

**Issue by afandyng** [mengxiong10/vue2-datepicker#590]
Hi all, I'm trying to show the received value when the page render like in the first input. I would like to show it in format="DD/MM/YYYY" but it shows empty. How can I do this? Thanks
```vue
<template>
  <div>
    <date-picker v-model="time1" type="date" valueType="format"></date-picker>
    <date-picker v-model="time1" type="date" format="DD/MM/YYYY"></date-picker>
  </div>
</template>

<script>
import DatePicker from "vue2-datepicker";
import "vue2-datepicker/index.css";

export default {
  components: { DatePicker },
  data() {
    return {
      time1: "2020-11-25",
    };
  },
};
</script>

<style></style>
```
<img width="444" alt="Screen Shot 2021-03-26 at 5 41 10 PM" src="https://user-images.githubusercontent.com/42415152/112695470-884ed280-8e5a-11eb-86c0-de642be0c6c5.png">

**Comment by mengxiong10** [comment]
valueType="YYYY-MM-DD"
