### ISSUE TITLE
[Bug] Able to select disabled dates when in the range mode

### ISSUE THREAD

**Issue by runxc1** [mengxiong10/vue2-datepicker#592]
**Vue2-datepicker version**  3.9.0
**Vue version**: Latest
**Browser**: Firefox and others

**Reproduction Link or Source Code**
https://jsfiddle.net/runxc1/e6cLd1zo/11/

**Expected behavior**
If there are disabled dates then you should not be able to select them

**Actual behavior**
If there is a disabled day and you are using the range mode you can select that day by clicking the day before it and then clicking the day after it.  This selects a range including the day that is disabled.

**Comment by mengxiong10** [comment]
You can use the second arguments.
```js
disabledDate(date, currentSelectedDates) {
   if (currentSelectedDates.length === 1) {
      ....
  }
}

```

**Comment by runxc1** [comment]
Thanks I was able to calculate that out and use this to also accomplish a minimum and maximum number of dates you can select
