### ISSUE TITLE
Multiple datepickers for selecting multiple dates

### ISSUE THREAD

**Issue by whitewillow** [mengxiong10/vue2-datepicker#596]
**What problem does this feature solve?**
Select multiples dates (not range) over the span of 2 or more months, using the same v-model variable

**What does the proposed API look like?**

Almost got this working, but since the v-model forces change of "default-value" calandar month I get both datepickers showing the same month when picking a date.
So if possible - force a default value or way to switch calendar month/year regardless of v-model.

**Comment by mengxiong10** [comment]
<date-picker :multiple="true" type='date' />
