### ISSUE TITLE
[Bug] Can't properly choose time range within boundaries

### ISSUE THREAD

**Issue by SilverIrbis** [mengxiong10/vue2-datepicker#597]
**Vue2-datepicker version**: 3.9.0
**Vue version**:2.3.3
**Browser**:Electron 2.0.9

**Steps to reproduce**
I created a datetime picker with a range, so I need to select datetime in a specific spectre of time, from 13.11.2020 12:57:33 to 13.11.2020 13:18:31 and disable any other time, for example.
When I set disabled-date (or disabled-time as well) I face some problems with disabled "ending-time" of the picker for some reason.
I set default-value too, as a period [13.11.2020 12:57:33, 13.11.2020 13:18:30] (it doesn't help if I'm trying to add secong to the start and subtract second from the end just to be sure that default period inside enabled scope)

My code for now looks like:
```
<date-picker
      v-model="period"
      type="datetime"
      range
      format="DD.MM.YYYY HH:mm:ss"
      input-class="datetime"
      :default-value="periodDefault"
      :disabled-date="disableDays"
      value-type="date">
</date-picker>
```
```
disableDays(date) {
      let date0 = new Date(this.dateStart) //13.11.2020 12:57:33
      date0.setHours(0, 0, 0, 0) // need to set hours, minuts, etc in 0, otherwise picker can't display this one enabled date
      let date1 = new Date(this.dateEnd) //13.11.2020 13:18:30
      date1.setHours(0, 0, 0, 0)

      return date < date0 ||
        date > date1
    },
```

**Expected behavior**
I can choose any time aside disabled time period

**Actual behavior**
In the case with disabled-date only or with disabled-time too I'm facing that there is blocked hours before 13 in end-section of timepicker and after 12 in start-section (yet I should be able to choose time range inside 12 or 13 hour too).

This one is only with disabled-date (and I want to get period 12:57 - 12:59)
![321](https://user-images.githubusercontent.com/6632565/115543079-a8cb4a80-a2a9-11eb-8dff-920abe6c5651.png)
This one with disabled-time too (and I want to get period 12:57 - 12:59 or 13:10 - 13:11)
![123](https://user-images.githubusercontent.com/6632565/115543052-a23cd300-a2a9-11eb-938b-cfe8413aa135.png)

Help me, please. I've seen a lot of issues but still can't figure out how to make it works right

**Comment by mengxiong10** [comment]
It is very difficult for the current components to disable the minute and second.
You can change the disabled boundaries.

```html
<date-picker
  v-model="value4"
  type="datetime"
  range
  :default-value="start"
  :disabled-date="disabledDate"
  :disabled-time="disabledTime"
  @change="handleChange"
></date-picker>
```
```js
const start = new Date(2020, 10, 13, 12, 57, 33);
const end = new Date(2020, 10, 13, 14, 18, 30);

export default {
  data() {
    return {
      start,
      end,
      value4: [],
    };
  },
  methods: {
    handleChange(dates) {
      if (Array.isArray(dates)) {
        this.value4 = dates.map(v => {
          if (v < this.start) {
            return new Date(this.start);
          }
          if (v > this.end) {
            return new Date(this.end);
          }
          return v;
        });
      }
    },
    disabledDate(date) {
      return (
        date.getTime() < new Date(this.start).setHours(0, 0, 0, 0) ||
        date.getTime() > new Date(this.end).setHours(23, 59, 59, 999)
      );
    },
    disabledTime(date) {
      return (
        date.getTime() < new Date(this.start).setMinutes(0, 0, 0) ||
        date.getTime() > new Date(this.end).setMinutes(59, 59, 999)
      );
    },
  },
};

```
------------------------------

You can also disable it more finely. This should be controlled by the component and may be improved in the future.
```js
disabledTime(date, index) {
  const [startValue, endValue] = this.value4
  if (index === 0) {
    if (startValue.getHours() === this.start.getHours()) {
      return ...
    }
    if (startValue.getHours() === this.end.getHours()) {
      return ...
    }
  }
},

```

**Comment by Tofandel** [comment]
I have the same issue, I think this problem could easily be solved by retrying the function if the returned value is false with the last second of the range instead of providing them at the first (eg Check if first hour is disabled send 01:00:00 => returns false => check with 01:59:59 => returns true this hours shouldn't be disabled)

**Comment by Tofandel** [comment]
This is how I managed to implement the range solution super hackishly myself but it's less than ideal
```
      isDisabledTime(d) {
        let range = this.lastChecked ? d.getTime() - this.lastChecked : 360000;

        this.lastChecked = d.getTime();

        if (range < 0) {
          range = 60000;
        }

        if (range && d < this.minTime) {
          d = new Date(d);
          d.setMilliseconds(d.getMilliseconds() + range);
        }
        return d < this.minTime || d > this.maxTime;
      },
```
