### ISSUE TITLE
[Feature request] Add class to table when show-week-number is true

### ISSUE THREAD

**Issue by raimund-schluessler** [mengxiong10/vue2-datepicker#600]
**What problem does this feature solve?**

Having a class like `${prefixClass}-calendar-show-week-number` would allow to style the date table dependig whether the week number is visible or not. Currently, it is e.g. not possible to set a fixed width for the datepicker which takes into account the 8th row due to the week number and the picker is to narrow. See also https://github.com/nextcloud/nextcloud-vue/issues/1014.

**What does the proposed API look like?**

Adding a proper class when the week numbers are enabled to this line https://github.com/mengxiong10/vue2-datepicker/blob/master/src/calendar/table-date.vue#L2

**Comment by mengxiong10** [comment]
You can add a `popupClass` when `show-week-number` is true.
```
<date-picker :popup-class="{ 'showWeekNumberPopup': showWeekNumber }" />
```

**Comment by raimund-schluessler** [comment]
Thanks, that works well.
