### ISSUE TITLE
Trigger open/closed date picker inside Storybook

### ISSUE THREAD

**Issue by tidumarco** [mengxiong10/vue2-datepicker#604]
Hello everyone, I'm quite new to Vue.js development. Now I've implemented the datepicker inside Storybook but I really don't know how to trigger open/closed state when loading the page.

This is my code so far:

```
<template>
  <div class="box">
      <date-picker
        v-model="time1"
        format="YYYY-MM-DD"
        type="date"
        :open.sync= 'open'
        @change="handleChange"
      ></date-picker>
  </div>
</template>

<script>
import DatePicker from 'vue2-datepicker';
export default {
  components: { DatePicker },
  name: 'Default',
  data() {
    return {
      time1: null,
      open: false
    };
  },
  methods: {
    handleChange(value, type) {
      if (type === true) {
        this.open = true;
      }
    },
  },
};
```

At this point I know that when I'm changing the value of `open: false` to `open: true` inside `data()` function the date picker open twice, overlapping, otherwise of course just stays closed.

The method that I've put down was just for trying something, I know that is wrong.

Thanks everyone

**Comment by mengxiong10** [comment]
@tidumarco I don't know what it means to open twice, but I think you can use set open to true in async function.
```js

mounted() {
  setTimeout(() => { this.open = true }, 0)
}

```

**Comment by tidumarco** [comment]
It literally opens two times when I'm refreshing the page.

I will try it out now.

Thanks

Marco Tidu
Arranger, producer, songwriter
+358465839256

**Comment by tidumarco** [comment]
Just tried out, it didn't work.

**Comment by mengxiong10** [comment]
@tidumarco open twice?  Can you show you code ?

**Comment by tidumarco** [comment]
Now I've found another way, I'm quite new to Vue.js and Storybook but something seems to happen, at least I can see some changes in Storybook while modifying `mx-datepicker-popup`:

`<template>
  <div>
        <date-picker
        :class="modalOpen"
        v-model="value"
        value-type="format"
        type="date"

      ></date-picker>
  </div>
</template>

<script>
import DatePicker from 'vue2-datepicker';

export default {
    name: 'Default',
    components: { DatePicker },
    props: {
        open: {
            type: Boolean,
            default: true,
            required: false,
        },
    },

    computed: {
        modalOpen(){
        return {
            ['mx-datepicker-popup']:this.open
        }
        }
  },

  

    data() {
    return {
        value: null,
        
    };
    },
    
  
};

  
  

</script>

<style lang="scss">

@import 'vue2-datepicker/index.css';

.mx-icon-left:before, .mx-icon-right:before, .mx-icon-double-left:before, .mx-icon-double-right:before, .mx-icon-double-left:after, .mx-icon-double-right:after {
    content: "";
    position: relative;
    top: -1px;
    display: inline-block;
    width: 10px;
    height: 10px;
    vertical-align: middle;
    border-style: solid;
    border-color: currentColor;
    border-width: 2px 0 0 2px;
    border-radius: 1px;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    -webkit-transform-origin: center;
    transform-origin: center;
    -webkit-transform: rotate(-45deg) scale(0.7);
    transform: rotate(-45deg) scale(0.7)
}

.mx-icon-double-left:after {
    left: -4px
}

.mx-icon-double-right:before {
    left: 4px
}

.mx-icon-right:before, .mx-icon-double-right:before, .mx-icon-double-right:after {
    -webkit-transform: rotate(135deg) scale(0.7);
    transform: rotate(135deg) scale(0.7)
}

.mx-btn {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    line-height: 1;
    font-size: 14px;
    font-weight: 500;
    padding: 7px 15px;
    margin: 0;
    cursor: pointer;
    background-color: transparent;
    outline: none;
    border: 1px solid rgba(0, 0, 0, .1);
    border-radius: 4px;
    color: #73879c;
    white-space: nowrap
}

.mx-btn:hover {
    border-color: #1284e7;
    color: #1284e7
}

.mx-btn-text {
    border: 0;
    padding: 0 4px;
    text-align: left;
    line-height: inherit
}

.mx-scrollbar {
    height: 100%
}

.mx-scrollbar:hover .mx-scrollbar-track {
    opacity: 1
}

.mx-scrollbar-wrap {
    height: 100%;
    overflow-x: hidden;
    overflow-y: auto
}

.mx-scrollbar-track {
    position: absolute;
    top: 2px;
    right: 2px;
    bottom: 2px;
    width: 6px;
    z-index: 1;
    border-radius: 4px;
    opacity: 0;
    -webkit-transition: opacity .24s ease-out;
    transition: opacity .24s ease-out
}

.mx-scrollbar-track .mx-scrollbar-thumb {
    position: absolute;
    width: 100%;
    height: 0;
    cursor: pointer;
    border-radius: inherit;
    background-color: rgba(144, 147, 153, .3);
    -webkit-transition: background-color .3s;
    transition: background-color .3s
}

.mx-zoom-in-down-enter-active, .mx-zoom-in-down-leave-active {
    opacity: 1;
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
    -webkit-transition: opacity .3s cubic-bezier(0.23, 1, 0.32, 1), -webkit-transform .3s cubic-bezier(0.23, 1, 0.32, 1);
    transition: opacity .3s cubic-bezier(0.23, 1, 0.32, 1), -webkit-transform .3s cubic-bezier(0.23, 1, 0.32, 1);
    transition: transform .3s cubic-bezier(0.23, 1, 0.32, 1), opacity .3s cubic-bezier(0.23, 1, 0.32, 1);
    transition: transform .3s cubic-bezier(0.23, 1, 0.32, 1), opacity .3s cubic-bezier(0.23, 1, 0.32, 1), -webkit-transform .3s cubic-bezier(0.23, 1, 0.32, 1);
    -webkit-transform-origin: center top;
    transform-origin: center top
}

.mx-zoom-in-down-enter, .mx-zoom-in-down-leave-to {
    opacity: 0;
    -webkit-transform: scaleY(0);
    transform: scaleY(0)
}

.mx-datepicker {
    /* Text Field */

    position: static;
    width: 608px;
    height: 40px;
    left: 0px;
    top: 20px;

    border-radius: 3px;

    /* Inside Auto Layout */
    flex: none;
    order: 1;
    align-self: stretch;
    flex-grow: 0;
    margin: 4px 0px;
}

.mx-datepicker svg {
    width: 13,33px;
    height: 14,67px;
    top: 0,67px;
    left: 1,33px;
    vertical-align: -0.15em;
    fill: currentColor;
    overflow: hidden
}

.mx-datepicker-range {
    width: 320px
}

.mx-datepicker-inline {
    width: auto
}

.mx-input-wrapper {
    display: flex;
    flex-direction: row;
    align-items: center;
    padding: 9px;

    position: absolute;
    height: 38px;
    left: 0px;
    right: 1px;
    top: 1px;
    
}

.mx-input-wrapper .mx-icon-clear {
    display: none
}

.mx-input-wrapper:hover .mx-icon-clear {
    display: block
}

.mx-input-wrapper:hover .mx-icon-clear+.mx-icon-calendar {
    display: none
}

.mx-input {
    position: absolute;
    display: flex;
    flex-direction: row;
    align-items: center;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    height: 38px;
    left: 0px;
    right: 1px;
    top: 1px;
    padding: 9px;
    font-size: 14px;
    color: #fff;
    background-color: #392F55;
    border: 1px solid #ccc;
    border-radius: 4px;
}

.mx-input:hover, .mx-input:focus {
    border-color: #409aff
}

.mx-input:disabled, .mx-input.disabled {
    color: #ccc;
    background-color: #f3f3f3;
    border-color: #ccc;
    cursor: not-allowed
}

.mx-input:focus {
    outline: none
}

.mx-input::-ms-clear {
    display: none
}

.mx-icon-calendar, .mx-icon-clear {
    /* calendar_today_24px */

    position: absolute;
    width: 16px;
    height: 16px;
    right: 9px;
    top: 19px;
    color: #fff;


    /* Inside Auto Layout */
    flex: none;
    order: 2;
    flex-grow: 0;
    margin: 0px 4px;
}

.mx-icon-clear {
    cursor: pointer
}

.mx-icon-clear:hover {
    color: rgba(0, 0, 0, .8)
}

.mx-datepicker-main {
    font: 14px/1.5 "Helvetica Neue", Helvetica, Arial, "Microsoft Yahei", sans-serif;
    /*font-family: SF Pro Text;*/
    font-size: 14px;
    font-style: normal;
    font-weight: 400;
    line-height: 20px;
    letter-spacing: 0px;
    text-align: center;


    color: #fff;
    background-color: #29223D;
    border: 1px solid #4E4379;
    box-shadow: 0px 0px 1px 0px #091E424F;

    box-shadow: 0px 3px 5px 0px #091E4233;


}

.mx-datepicker-popup {
    position: absolute;
    margin-top: 1px;
    margin-bottom: 1px;
    -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, .175);
    box-shadow: 0 6px 12px rgba(0, 0, 0, .175);
    z-index: 2001
}

.mx-datepicker-sidebar {
    float: left;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    width: 100px;
    padding: 6px;
    overflow: auto
}

.mx-datepicker-sidebar+.mx-datepicker-content {
    margin-left: 100px;
    border-left: 1px solid #e8e8e8
}

.mx-datepicker-body {
    /*position: relative;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;*/
    position: static;
    width: 319px;
    height: 293px;
    left: 0px;
    top: 72px;
    
}

.mx-btn-shortcut {
    display: block;
    padding: 0 6px;
    line-height: 24px
}

.mx-range-wrapper {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex
}

@media(max-width: 750px) {
    .mx-range-wrapper {
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column
    }
}

.mx-datepicker-header {
    padding: 6px 8px;
    border-bottom: 1px solid #e8e8e8
}

.mx-datepicker-footer {
    padding: 6px 8px;
    text-align: right;
    border-top: 1px solid #e8e8e8
}

.mx-calendar {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    padding: 6px 12px;
    position: static;
    width: 319px;
    height: 293px;
    left: 0px;
    top: 72px;
}

.mx-calendar+.mx-calendar {
    border-left: 1px solid #e8e8e8
}

.mx-calendar-header, .mx-time-header {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    height: 34px;
    line-height: 34px;
    text-align: center;
    overflow: hidden
}

.mx-btn-icon-left, .mx-btn-icon-double-left {
    float: left
}

.mx-btn-icon-right, .mx-btn-icon-double-right {
    float: right
}

.mx-calendar-header-label {
    font-size: 14px
}

.mx-calendar-decade-separator {
    margin: 0 2px
}

.mx-calendar-decade-separator:after {
    content: "~"
}

.mx-calendar-content {
    position: relative;
    height: 224px;
    -webkit-box-sizing: border-box;
    box-sizing: border-box
}

.mx-calendar-content .cell {
    cursor: pointer;
    color: #958EAF
}

.mx-calendar-content .cell:hover {
    color: #fff;
    background-color: #392F55
}

.mx-calendar-content .cell.active {
    color: #fff;
    background-color: #392F55
}

.mx-calendar-content .cell.in-range, .mx-calendar-content .cell.hover-in-range {
    color: #73879c
}

.mx-calendar-content .cell.disabled {
    cursor: not-allowed;
    color: #ccc;
    background-color: #f3f3f3
}

.mx-calendar-week-mode .mx-date-row {
    cursor: pointer
}

.mx-calendar-week-mode .mx-date-row:hover {
    background-color: #f3f9fe
}

.mx-calendar-week-mode .mx-date-row.mx-active-week {
    background-color: #dbedfb
}

.mx-calendar-week-mode .mx-date-row .cell:hover {
    color: inherit;
    background-color: transparent
}

.mx-calendar-week-mode .mx-date-row .cell.active {
    color: inherit;
    background-color: transparent
}

.mx-week-number {
    opacity: .5
}

.mx-table {
    table-layout: fixed;
    border-collapse: separate;
    border-spacing: 0;
    width: 100%;
    height: 100%;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    text-align: center;
    vertical-align: middle
}

.mx-table th {
    padding: 0;
    font-weight: 500
}

.mx-table td {
    padding: 0
}

.mx-table-date td, .mx-table-date th {
    height: 32px;
    font-size: 12px
}

.mx-table-date .today {
    color: #fff;
    background: #392F55;
    border: 2px solid #AA74CE;
    box-sizing: border-box;
    border-radius: 3px
}

.mx-table-date .cell.not-current-month {
    color: #6F6994;
    background: none
}

.mx-time {
    -webkit-box-flex: 1;
    -ms-flex: 1;
    flex: 1;
    width: 224px;
    background: #fff
}

.mx-time+.mx-time {
    border-left: 1px solid #e8e8e8
}

.mx-calendar-time {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%
}

.mx-time-header {
    border-bottom: 1px solid #e8e8e8
}

.mx-time-content {
    height: 224px;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    overflow: hidden
}

.mx-time-columns {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    width: 100%;
    height: 100%;
    overflow: hidden
}

.mx-time-column {
    -webkit-box-flex: 1;
    -ms-flex: 1;
    flex: 1;
    position: relative;
    border-left: 1px solid #e8e8e8;
    text-align: center
}

.mx-time-column:first-child {
    border-left: 0
}

.mx-time-column .mx-time-list {
    margin: 0;
    padding: 0;
    list-style: none
}

.mx-time-column .mx-time-list::after {
    content: "";
    display: block;
    height: 192px
}

.mx-time-column .mx-time-item {
    cursor: pointer;
    font-size: 12px;
    height: 32px;
    line-height: 32px
}

.mx-time-column .mx-time-item:hover {
    color: #73879c;
    background-color: #f3f9fe
}

.mx-time-column .mx-time-item.active {
    color: #EEECF2;
    background-color: transparent;
    font-weight: 700
}

.mx-time-column .mx-time-item.disabled {
    cursor: not-allowed;
    color: #ccc;
    background-color: #f3f3f3
}

.mx-time-option {
    cursor: pointer;
    padding: 8px 10px;
    font-size: 14px;
    line-height: 20px
}

.mx-time-option:hover {
    color: #73879c;
    background-color: #f3f9fe
}

.mx-time-option.active {
    color: #1284e7;
    background-color: transparent;
    font-weight: 700
}

.mx-time-option.disabled {
    cursor: not-allowed;
    color: #ccc;
    background-color: #f3f3f3
}
</style>

`

I'm not using any async function.
