### ISSUE TITLE
How to hide red circle on the view (Date field) Date Picker

### ISSUE THREAD

**Issue by Polina121** [mengxiong10/vue2-datepicker#606]
Hello,
Is it possible to hide Red/Green circle on the date field view? (Date Picker control.

![image](https://user-images.githubusercontent.com/84388356/118649778-2ec4ad80-b7e4-11eb-85d5-475fa419cf5f.png)

**Comment by mengxiong10** [comment]
@Polina121 It's not in the `vue2-datepicker` component.
