### ISSUE TITLE
issue with shortcuts event fire

### ISSUE THREAD

**Issue by DeepakAryal** [mengxiong10/vue2-datepicker#61]
I have a method call on `@input` event. but while clicking the shortcuts, it throws same input event twice thats why my method get called twice. but i want to call my method only one time on shortcut click.

**Comment by mengxiong10** [comment]
According to the code should only emit input event once, I also tested only trigger once. Can you provide more code information.

**Comment by DeepakAryal** [comment]
have you tested it for shortcuts? when selecting the date from calendar panel, it emits one time but in the case of shortcuts twice.

**Comment by DeepakAryal** [comment]
`<date-picker
          @input="selectDateRange"
          :lang="locale"
          :placeholder="$t('stats.date_range.placeholder')"
          :shortcuts="false"
          format="dd MM yyyy"
          range
          ref="stats_date_range"
          v-model="stats.date_range"
          width="225">
        </date-picker>`

shortcuts define
`stats_date_range_shortcuts: [
        {
          text: this.$t('stats.date_range.shortcuts.prev_seven_days'),
          start: this.$moment().subtract(7, 'days'),
          end: this.$moment()
        },
        {
          text: this.$t('stats.date_range.shortcuts.prev_fourteen_days'),
          start: this.$moment().subtract(14, 'days'),
          end: this.$moment()
        },
        {
          text: this.$t('stats.date_range.shortcuts.this_month'),
          start: this.$moment().startOf('month'),
          end: this.$moment()
        },
        {
          text: this.$t('stats.date_range.shortcuts.this_year'),
          start: this.$moment().startOf('year'),
          end: this.$moment()
        }
      ]`

method call
`selectDateRange () {
      console.log('fire')
      this.init()
    }`

fire is logged in console twice while clicking on shortcuts.

**Comment by mengxiong10** [comment]
'v-model' and input is conflict.
You need to change the v-model to :value. And change the value in the selectDateRange method .

**Comment by DeepakAryal** [comment]
ok let me try this.

**Comment by DeepakAryal** [comment]
not works at all.
it still fires same event twice when clicking on shortcuts
