### ISSUE TITLE
[Bug] Vue Warn: The computed property "lang" is already defined as a prop

### ISSUE THREAD

**Issue by nikolaypronchev** [mengxiong10/vue2-datepicker#611]
**Vue2-datepicker version**: 3.9.0
**Vue version**: 2.6.10
**Browser**: Google Chrome 90.0.4430.212

**Steps to reproduce**
Vue warn is shown in browser console after component mounting :
> The computed property "lang" is already defined as a prop.
> found in
> ---> `<DatePicker>`

**Reproduction Link or Source Code**
```JavaScript
<template>
  <date-picker />
</template>

import DatePicker from 'vue2-datepicker';

export default {
  components: { DatePicker }
}
```

Is that expected behaviour?

**Comment by mengxiong10** [comment]
Maybe you have some global mixins

**Comment by nikolaypronchev** [comment]
> Maybe you have some global mixins

You are absolutely right, mixin with computed property 'lang' was attached to application globally. Thanks!
