### ISSUE TITLE
[Feature request] Open Date/Time ranges

### ISSUE THREAD

**Issue by m-mohr** [mengxiong10/vue2-datepicker#612]
**What problem does this feature solve?**

Our users need to be able to select a date/time range, which may be open-ended. 

So potential inputs that are allowed are:
2020-01-01 - 2020-12-31 (all days in 2020)
2020-01-01 - null (all days from the beginning of 2020)
null - 2020-01-01 (all days until the beginning of 2020)

**What does the proposed API look like?**

A new prop boolean "open-range" prop that is only available if the range prop is set to true. In this case, people are allowed to choose open-ended date and/or time ranges. This could enable two additional buttons below the calender which can be used to select that one of the sides is an open end.

**Comment by mengxiong10** [comment]
To use two component is better.

https://codesandbox.io/s/date-range-optional-range-z06gv?file=/src/App.vue

**Comment by mengxiong10** [comment]
To use two component is better.

https://codesandbox.io/s/date-range-optional-range-z06gv?file=/src/App.vue

**Comment by m-mohr** [comment]
I never happened to thank you for the code example. This was very helpful, thanks a lot!
