### ISSUE TITLE
[Bug] Dynamically changing type `date` to `month` does not update panel

### ISSUE THREAD

**Issue by cmitz** [mengxiong10/vue2-datepicker#613]
**Vue2-datepicker version**: 3.9.0
**Vue version**: 2.6.12
**Browser**: Firefox 88

**Steps to reproduce**
1. Have a button/select to be able to dynamically switch between `date` and `month`
2. Show datepicker `inline`
3. Start on `date`
4. Switch from `date` to `month`

**Reproduction Link or Source Code**
This codepen says it all:

https://codepen.io/caspersmits/pen/bGqLwBO

https://user-images.githubusercontent.com/5594436/120453588-783ffb80-c393-11eb-95f9-2be46eca959c.mov

**Expected behavior**
I expect the inline datepicker to switch from `date` panel to `month` panel

**Actual behavior**
The panel does not change; it stays on `date`

## Side note
This also works the other way around:
1. Start on `month`
2. Switch to `date` 

The panel does not switch

**Comment by mengxiong10** [comment]
You can add a key to update it. 
```html
  <date-picker
      ref="datepicker"
      v-model="pickedDateTime"
      v-bind="configInline"
      :key="dateRangeType"
  />
```

**Comment by cmitz** [comment]
Oh that was an easy fix. Thank you! ❤️
