### ISSUE TITLE
[Question] Is it possible to listen to events emitted by the child components

### ISSUE THREAD

**Issue by weisinlakd** [mengxiong10/vue2-datepicker#614]
Hi, great project.
I was checking your demo and saw the example of toggling the timepicker dinamically with a slotted button.
![image](https://user-images.githubusercontent.com/48336674/120518090-91eb3e00-c3a7-11eb-9400-97ca67f4343f.png)
However, clicking on the title of said timepicker emits an event (clicktitle) on a <TimePanel> component, and i would like to listen to that event on the DatePicker component in order to mantain the functionality of the regular datetime datepicker (as in, going back to the calendar picker).

Is this currently possible?

Thanks!

**Comment by mengxiong10** [comment]
OK, It has a bug to prevent it.
You can add `sync` to listen it.
```html
      <date-picker
        v-model="value1"
        type="datetime"
        placeholder="Select datetime"
        :show-time-panel.sync="showTimePanel"
        @close="handleOpenChange"
      >

```
