### ISSUE TITLE
[Bug] datepicker is out of viewport, when size changes

### ISSUE THREAD

**Issue by dartcafe** [mengxiong10/vue2-datepicker#615]
**Vue2-datepicker version**: 3.9.0
**Vue version**: 2.6.13
**Browser**: independend

**Steps to reproduce**
The datepicker popup opens at the most right position of the browser's window (triggered from a button inside a sidebar)
![grafik](https://user-images.githubusercontent.com/26707476/120818730-2cd44b80-c553-11eb-9f0c-cc6af8a8164c.png)

When selecting range the new panel opens to the right and is out of the viewport
![grafik](https://user-images.githubusercontent.com/26707476/120818762-352c8680-c553-11eb-9987-4c3d34a5ea3f.png)

**Reproduction Link or Source Code**
https://github.com/nextcloud/polls/tree/master/src/js/components/Options

**Expected behavior**
The panel should react to the width change and position the popup inside the viewport

**Actual behavior**
see screenshots

**Comment by mengxiong10** [comment]
When you change the `range`, you should update the component key, then it can forceupdate.
```html
<date-picker  :range="range" :key="range ? 1: 0" />
```

**Comment by dartcafe** [comment]
Thanks for the hint to the key attribute. That works! 👍
