### ISSUE TITLE
How to change the order of the calendar panel?

### ISSUE THREAD

**Issue by AlexanderBV** [mengxiong10/vue2-datepicker#621]
I am using datepicker range and I need the current month to load to the right side and the left panel to be from the previous month as I only query past dates, not future dates.

Make it look like this
![image](https://user-images.githubusercontent.com/20906718/123531495-b26a9780-d6ca-11eb-8018-f47b046df90e.png)

It looks like this
![image](https://user-images.githubusercontent.com/20906718/123531527-dcbc5500-d6ca-11eb-9040-95db566a2bee.png)

**Comment by mengxiong10** [comment]
You can rewrite the `updateCalendars`
```js
import DatePicker from 'vue2-datepicker'

const { updateCalendars } = DatePicker.CalendarRange.methods

DatePicker.CalendarRange.methods.updateCalendars = function(calendars, adjustIndex = 0) {
  updateCalendars.call(this, calendars, adjustIndex)
}



```
