### ISSUE TITLE
[Bug] Date value isn't loaded / displayed in the date picker

### ISSUE THREAD

**Issue by Coreusa** [mengxiong10/vue2-datepicker#623]
**Vue2-datepicker version**: 3.9.1
**Vue version**: 2.6.12
**Browser**: Vivaldi

**Steps to reproduce**
Have an existing object with a date value like "2021-07-07T22:00:00+00:00". This used to work in in 2.10.1.

**Reproduction Link or Source Code**
This code is screenshot further down.
```
<strong>Value of start date:</strong>{{ surveyData.queryDto.startDate }}
 <date-picker
          v-model="surveyData.queryDto.startDate"
          :lang="lang"
          :minute-step="10"
          :first-day-of-week="1"
          :class="[{ 'border-red': $v.surveyData.queryDto.startDate.$invalid === true }, 'w-100']"
          :placeholder="$t('startDate')"
          :disabled="surveyIsActive"
          confirm
>
</date-picker>
```

**Expected behavior**
The value should be loaded into the calendar input when it 's served a date value

**Actual behavior**
The value isn't displayed

Screenshot of the example code above:
## Here's how it looks in 3.9.1
![image](https://user-images.githubusercontent.com/706874/124780348-cf149400-df42-11eb-935d-c5bad957a1b0.png)

## Here's how it looks in 2.10.1
Edit: Here's the _EXACT_ same object, variable and value (not changed since the last example) in 2.10.1:
![image](https://user-images.githubusercontent.com/706874/124781859-09cafc00-df44-11eb-8e27-330d68adaa68.png)

**Comment by mengxiong10** [comment]
You need check the type of `surveyData.queryDto.startDate`. If it is a `String`. You need use `new Date` to transform  to`Date`

**Comment by nguyenduc308** [comment]
I got the same issue

**Comment by mengxiong10** [comment]
> I got the same issue
