### ISSUE TITLE
Validation on first date selection in date range picker

### ISSUE THREAD

**Issue by Meet132** [mengxiong10/vue2-datepicker#625]
In my project, I want to add validation in the date range picker.

I have added a date range picker and want to set validation on the second date when the user selects the first date. The second date should be in the range of 30 days. When the user sets the first date only the next 30 days should be visible for the user to select.

Here is the code which I tried. but not works as it requires. 
1. Datepicker 
            <date-picker 
                    v-model="dateRange"
                    range
                    class="custome-datepiker"
                    :clearable="false"
                    :disabled-date="disabledBeforeTodayAndAfterAWeek"
                    @pick="selectedCurrentDate"
                ></date-picker>

2. Below method for disable dates
methods: {
       disabledBeforeTodayAndAfterAWeek(date) {
            if(this.dateRange.length > 0) {
                const today = new Date(this.dateRange[0]);
                today.setHours(0, 0, 0, 0);
                return date < new Date(today.getTime() - 30 * 24 * 3600 * 1000) || date > new Date(today.getTime() + 30 * 24 * 3600 * 
               1000);
            }
        },
}

**Comment by mengxiong10** [comment]
https://github.com/mengxiong10/vue2-datepicker/issues/592#issuecomment-810985604
