### ISSUE TITLE
[Bug] wrong format view

### ISSUE THREAD

**Issue by egormanakin** [mengxiong10/vue2-datepicker#626]
When I try to enter date 1984-04-01 in input or pick it with datepicker date turns to 1984-03-31 with ValueType (https://mengxiong10.github.io/vue2-datepicker/index.html#ValueType).

**Vue2-datepicker version**: 3.9.1
**Browser**: Safari

**Comment by mengxiong10** [comment]
![image](https://user-images.githubusercontent.com/14135808/126614525-5a1b288d-faa9-412f-9eec-1d3954ff1c23.png)

**Comment by egormanakin** [comment]
https://user-images.githubusercontent.com/56153693/126614880-e88f13dc-1453-4288-866c-b4588496f5d0.mov

**Comment by mengxiong10** [comment]
@egormanakin Is it right on Chrome? And What's your timezone.
![image](https://user-images.githubusercontent.com/14135808/126627031-7e174b27-d6de-4a96-82b5-c19748ad0126.png)

**Comment by egormanakin** [comment]
@mengxiong10 the same error on Chrome. timezone offset is -180

**Comment by mengxiong10** [comment]
Can you help me debug the value of `this.$refs.datepicker.parseDate('1984-04-01', 'YYYY-MM-DD');`

```html
      <date-picker
        ref="datepicker"
        v-model="value2"
        value-type="format"
        format="YYYY-MM-DD"
      ></date-picker>
```
```js
export default {
  name: 'ValueType',
  data() {
    return {
      value2: '1984-04-01',
    };
  },
  mounted() {
    const date = this.$refs.datepicker.parseDate('1984-04-01', 'YYYY-MM-DD');
    console.log(date, this.$refs.datepicker.innerValue);
  },
};

```

**Comment by mengxiong10** [comment]
@egormanakin v3.9.3 maybe fix it. 
If not, please visit this link(https://codesandbox.io/s/vue2-datepicker-value-type-bug-b9sih?file=/src/App.vue) and send me a screenshot

**Comment by egormanakin** [comment]
@mengxiong10 yes, problem solved, thank you!
