### ISSUE TITLE
[Bug] Click event should not change default open state when datepicker disabled

### ISSUE THREAD

**Issue by Billiam** [mengxiong10/vue2-datepicker#630]
**Vue2-datepicker version**: 3.9.1
**Vue version**: 2.6.14
**Browser**: Chrome 92

**Steps to reproduce** 

1. Disable datepicker by setting `:disabled="true"` prop
2. Click datepicker element, which changes its internal defaultOpen value
3. Enable datepicker by setting `:disabled="false"` prop

**Expected behavior**

Datepicker remains closed

**Actual behavior**

Datepicker opens immediately when disabled prop changes to false or is removed.

**Comment by mengxiong10** [comment]
fixed in v.3.9.2
