### ISSUE TITLE
Time Range picker with only current month(instead of current and next month)

### ISSUE THREAD

**Issue by pavankumar886** [mengxiong10/vue2-datepicker#631]
Time Range picker with only current month(instead of current and next month), because future dates will be disabled in my project. and opening current month and next month(with disabled dates) is useless.
![Screenshot from 2021-08-10 14-52-12](https://user-images.githubusercontent.com/12639616/128842402-9ccc3661-0be2-4c53-8544-961a4bd90ed4.png)

**Comment by mengxiong10** [comment]
#612

**Comment by bio0z** [comment]
Same question, how to show only 1 month in popup if you using range?
Example in #612 issue doesnt  fits me

Thanks for help and for all datapicker component

**Comment by mengxiong10** [comment]
@bio0z https://codesandbox.io/s/range-in-datepicker2x-mode-hlzrg?file=/src/App.vue

**Comment by bio0z** [comment]
@mengxiong10 i think it is complicated, not intuitively and not user-friendly for those how would like to choose dates.

**Comment by mengxiong10** [comment]
@bio0z The default mode is that the dates can be displayed on the same panel.
The second mode is that the first panel displays the start date and the second panel displays the end date. (Maybe I can build in this feature)
And you can use one panel to show range: https://codesandbox.io/s/range-picker-with-one-calendar-jvv5s?file=/src/App.vue

**Comment by maximkompaneev** [comment]
@mengxiong10 is it possible to set months which will be shown when u open datepicker range? 
what happens now: when I open it it shows current month on left and next month on right 
what i want: it shows current month on right and previous month on left (ideally option to set which month is exactly on left/right panel)

**Comment by mengxiong10** [comment]
https://github.com/mengxiong10/vue2-datepicker/issues/584#issuecomment-814928160
