### ISSUE TITLE
[Bug]  How to set month format as Full month name (August instead of Aug ) along with dynamic language ?

### ISSUE THREAD

**Issue by shilpa-MI** [mengxiong10/vue2-datepicker#633]
### **How to set month format as Full month name (August instead of Aug ) along with dynamic language ?**

if I used lang like 

`lang = {
    days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    yearFormat: 'YYYY',
    monthFormat: 'MMMM'
  }
  `
  
  then it's working fine but,  but how can I set language to es  (As per API response , I have to set labguage )
  
  I want to change the language dynamically as well,  like [(see here)](https://github.com/mengxiong10/vue2-datepicker/issues/488#issuecomment-648659343)  but is not working

lang = 'es'
  
  is there anyway, that I can use both language (dynamic language) and monthFormat , yearFormat options together

**Comment by mengxiong10** [comment]
import  en from 'vue2-datepicker/locale/zh-cn';
import  es from 'vue2-datepicker/locale/es';

const defaultLang = { days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], yearFormat: 'YYYY', monthFormat: 'MMMM' }

Object.assign(en, defaultLang)
Object.assign(es, defaultLang)

**Comment by shilpa-MI** [comment]
Hi, Thanks  @mengxiong10 

yes, it's working, import  creating  types issues with Typescript, but not a big deal we use with Require statement
