### ISSUE TITLE
Problem changing language

### ISSUE THREAD

**Issue by alexv96** [mengxiong10/vue2-datepicker#634]
Hello, I have a problem when implementing the datepicker with ranges in Spanish, if I analyze the component in the browser it appears in Spanish but when executing the input I get it in English.

![image](https://user-images.githubusercontent.com/33232796/130094468-48984891-0432-4878-a324-f2e22eff4311.png)

Another thing is it possible to change the format to DD-MM-YYYYYY and not the default YYYY-MM-DD.

```
<date-picker 
   type="date" 
   :lang="lang" 
   placeholder="Seleccione rango de fecha" 
   v-model="dateRange"
   range
></date-picker>

<script>
import DatePicker from 'vue2-datepicker';
import 'vue2-datepicker/index.css';
import es from 'date-format-parse/lib/locale/es';

export default{
  components: {
    DatePicker
  },
  data() {
    return {
      lang: es,
      dateRange: [],
    };
  },
}
</script>

```

**Comment by mengxiong10** [comment]
You need import the lang from `vue2-datepicker` instead of `date-format-parse`.
```js
import es from  'vue2-datepicker/locale/es';

```
You can use prop `format`

```html
<date-picker format="DD-MM-YYYY" />
```
