### ISSUE TITLE
How to force Minutes to be always 00?

### ISSUE THREAD

**Issue by christopheSeeka** [mengxiong10/vue2-datepicker#636]
**Vue2-datepicker version**: 3.9.2
**Vue version**: 2
**Browser**: Chrome

**Steps to reproduce**
I have the following datepicker component:

`<date-picker v-model="sale.datePicked" valueType="timestamp" type="datetime" format="YYYY-MM-DD HH:mm" :disabledDate="disableDate" :time-picker-options="{start: '00:00', step: '01:00', end: '23:00'}" :show-minute="false" :show-second="false" :default-value="new Date()" :min="new Date()" class="d-block"></date-picker>`

**Expected behavior**
I only want allow to pick hour time with 00 minutes.

**Actual behavior**
If i pick a date but skip the click to pick time, then it use current time minutes:

![datepicker](https://user-images.githubusercontent.com/50763365/130584681-e35f600e-7f90-4bde-b6aa-bec24f060452.png)

Any way to force the minutes to 00 after i pick the date regardless if i picked time already or not?

Thank you in advance.

**Comment by mengxiong10** [comment]
You can remove `:default-value="new Date()"` or set `:default-value="new Date().setMinutes0, 0, 0)"`

**Comment by christopheSeeka** [comment]
Thank you very much!
