### ISSUE TITLE
DisableTime is 1h ahead

### ISSUE THREAD

**Issue by christopheSeeka** [mengxiong10/vue2-datepicker#637]
**Vue2-datepicker version**: 3.9.2
**Vue version**: 2
**Browser**: Chrome

**Reproduction Link or Source Code**
I have this datepicker component:

`<date-picker v-model="sale.datePicked" valueType="timestamp" type="datetime" format="YYYY-MM-DD HH:mm" :editable="false" :disabledDate="disableDate" :disabledTime="disableTime" :show-second="false" :default-value="new Date()" :min="new Date()" class="d-block"></date-picker>`

with these disable methods:

```
    disableDate: function(date){
      return date < new Date(new Date().setHours(0, 0, 0, 0));
    },
    disableTime: function(date){
      return date <  new Date();
    }
```

**Expected behavior**
I expect to allow selection of date / time only higher than now

**Actual behavior**
I can only pick one hour up later than now and i don't understand why, for example if it's 18h25 hour start at 19 already.

**Comment by christopheSeeka** [comment]
Came out doing this:

```
disableTime: function(date){
      return date < new Date().getTime() - 60000;
    },
```

but not sure it's the proper way though?

**Comment by mengxiong10** [comment]
https://github.com/mengxiong10/vue2-datepicker/issues/478
