### ISSUE TITLE
[Bug] Disable-Time can't do sparse time correctly

### ISSUE THREAD

**Issue by hqpwca** [mengxiong10/vue2-datepicker#638]
**Vue2-datepicker version**:^3.9.1
**Vue version**:^2.6.14
**Browser**:Chrome

**Reproduction Link or Source Code**
`<date-picker                    
    v-model="time"              
    type="datetime"             
    @close="timeChanged"        
    @input="partialtimeChanged" 
    :clearable="false"          
    :editable="pdisable"
    :disabled-time="Vdisabled"  
    :show-second="false"        
    :minute-step="10"           
    partial-update/>`

and

Vdisabled() {

       for(let dt of this.vdate) {
           const a = new Date(dt.st)
           const b = new Date(dt.ed)
           if(x >= a && x < b)
               return false
       }
       return true
}

**Expected behavior**
Want to only enable sparse time. Like 10:20, 10:30, 11:40, 13:10, 17:50, something like that.

**Actual behavior**
Won't check all the time points properly, most of the hours are disabled.

**Comment by mengxiong10** [comment]
use `time-picker-options`
https://mengxiong10.github.io/vue2-datepicker/index.html#FixedTimeList
