### ISSUE TITLE
Time is being shown when type=date or not specified

### ISSUE THREAD

**Issue by vexsolutions** [mengxiong10/vue2-datepicker#64]
`<date-picker type="date" v-model="input.actual_complete_date" format="mm-dd-yyyy"
                             lang="en" name="action_by_date">
</date-picker>`

![datepicker](https://user-images.githubusercontent.com/33415075/37093083-aefcf5e8-21d3-11e8-881d-1259f6b2e3ae.PNG)

Any way to force it to adhere to the type and format specified?

**Comment by mengxiong10** [comment]
The result is the input.actual_complete_date.
You can format it by yourself if you don't use the default input UI.
```JavaScript
import DatePicker from 'vue2-datepicker'

DatePicker.formatDate(input.actual_complete_date, 'mm-dd-yyyy')

```

**Comment by mengxiong10** [comment]
change the format to 'MM-DD-YYYY'
