### ISSUE TITLE
[Bug] Input value and selection showed are not always synchronized

### ISSUE THREAD

**Issue by polosson** [mengxiong10/vue2-datepicker#640]
**Vue2-datepicker version**: 3.9.1
**Vue version**: 2.6.14
**Browser**: Firefox / Chrome

**Steps to reproduce**

Using a Datepicker with a confirm button:

- Open the date picker by clicking on the input
- Click on a date (or range of dates if prop `range` is `true`)
- Do NOT click on the confirm button, but click outside the date picker
- Open the date picker again: the date (or range) is still highlighted, but the input is empty.

**Expected behavior**

I can see 2 solutions for this UX problem, by either:
- removing the selection date (or range) from the datepicker when we close it by clicking outside,
- or filling the input field with the selected date (or range), even if we have not clicked the confirm button.

I think the first solution is more user friendly because when we don't click on the confirm button, there is no reason to have the input filled.

**Actual behavior**

The input field does not reflect the selection of date(s) that is present inside the datepicker when not using the confirm button.

Thanks!

**Comment by mengxiong10** [comment]
Thanks for feedback, I will improve it

**Comment by mengxiong10** [comment]
v3.10.2  fixed it.
