### ISSUE TITLE
[Feature request] Get the text of the selected shortcut

### ISSUE THREAD

**Issue by totalhack** [mengxiong10/vue2-datepicker#644]
**What problem does this feature solve?**

If a user selects a range shortcut such as "Last 7 Days" I don't see a way to later distinguish between the shortcut being used vs. the user just selecting that date range manually. 

As an example of where knowing this is important, consider an analytics UI that saves report definitions -- reloading a report where the user selected "Last 7 Days" should always load the last 7 days as of the time the report is loaded, not a specific saved date range. If I could inspect the datepicker component to figure out that the current values came from a certain shortcut, on reload of the component I could then make sure that shortcut is applied instead of a fixed range.

**What does the proposed API look like?**

Perhaps there is already some way to do this that I am missing. the `onClick` functions for the shortcuts needs to return a date (or range / two dates) so I don't think I can just return some different object there with more information such as the text of the selected shortcut. Otherwise it seems like the component would need to store some state which tells what shortcut the last input came from, if any, or null if the last input did not come from a shortcut (manual selection of a date or date range).

**Comment by mengxiong10** [comment]
```html
      <date-picker
        v-model="date"
        range
        :shortcuts="shortcuts"
        placeholder="Select date"
      ></date-picker>

```
```js
export default {
  data() {
    return {
      value: null,
      shortcuts: [
        {
          text: 'Last 7 Days',
          getDate() {
            const start = new Date();
            const end = new Date();
            start.setTime(start.getTime() - 7 * 24 * 3600 * 1000);
            const date = [start, end];
            // return a Date
            return date;
          },
          onClick: () => this.handleShortcutClick('Last 7 Days'),
        },
      ],
    };
  },
  computed: {
    date: {
      get() {
        const shortcut = this.shortcuts.find(v => v.text === this.value);
        if (shortcut) {
          return shortcut.getDate();
        }
        return this.value;
      },
      set(val) {
        this.value = val;
      },
    },
  },
  methods: {
    handleShortcutClick(text) {
      this.value = text;
    },
  },
};

```
When the `value` is a String for the shortcut or a Date for the fixed range.

**Comment by totalhack** [comment]
Thanks, I get what you are aiming for there, but I'm not sure if I can do that in my situation. I'm setting the value of the component through a property (and using vue class component), so my attempts to adapt what you did there have not worked. How would you accomplish the above when the value is set with a prop in a parent?

```
<template>
  <date-picker
    :value="syncedValue"
    value-type="YYYY-MM-DD"
    format="YYYY-MM-DD"
    type="date"
    placeholder="Select Date Range"
    :shortcuts="rangeShortcuts"
    @input="onInput"
    range
  ></date-picker>
</template>
```

And in the parent:

```
  @PropSync('value') syncedValue: any;

  onInput(newValue) {
    this.syncedValue = newValue;
  }
```

So I don't have the computed property the way you do, and therefore I'm not sure if I can rely on the reactivity of setting a local data value to get the component to update to a date. I may just be doing something wrong of course. Because the onClick handlers lead to onInput getting called again, but non-shortcut based selections just call onInput directly, I still have no way to distinguish whether the selection came from a shortcut or not with this approach.

**Comment by totalhack** [comment]
While I mostly got this working, there is still a shortcoming of this approach. If you select a shortcut, such as "Today", it will show the current date values in the date picker UI rather than just saying "Today" and computing the date values on read. This is fine for that day, but if you leave the window open and come back to it the next day, it doesn't always make sense or match the user's intentions (there are cases where you want a selection of "Today" to always mean the current day, not just shortcut to an absolute/static value). 

It would be great if this plugin could support true relative date ranges rather than just shortcuts to static values. Any selection of a shortcut could just show the name of that shortcut in the UI, and then upon read of the value from the component it could compute the date values from the shortcut.
