### ISSUE TITLE
[Bug] Change default time

### ISSUE THREAD

**Issue by nasuhikeskin** [mengxiong10/vue2-datepicker#647]
![image](https://user-images.githubusercontent.com/75370396/135098917-9690b287-2a1f-46b5-b2b4-cd00116e7ac3.png)

Hi,

I want to change 12:00 am value with 11:59 pm. How can i change?

**Comment by mengxiong10** [comment]
```html
<date-picker  :default-value="defaultValue" />
```
```js
data() {
  return {
    const defaultValue = new Date()
    defaultValue.setHours(23, 59, 0)
    return { defaultValue }
  }
}

```

**Comment by nasuhikeskin** [comment]
What if first option 12:00 AM and second option 11:59 PM?

**Comment by mengxiong10** [comment]
> What if first option 12:00 AM and second option 11:59 PM?

`defaultValue=[new Date(), new Date(new Date().setHours(23, 59, 0))]`

**Comment by sebsobseb** [comment]
If you want to set the start time to 00:00:00 and end time to 23:59:59 (in range):
`:default-value="[new Date().setHours(0, 0, 0), new Date().setHours(23, 59, 59)]"`
