### ISSUE TITLE
[Bug] Cannot use default value with custom formatter

### ISSUE THREAD

**Issue by Bambalazs** [mengxiong10/vue2-datepicker#654]
**Vue2-datepicker version**: 3.10.2
**Vue version**: 2.6.14
**Browser**: Safari 15.0

**Description**

I'm using a custom formatter with moment.js. If I would like to set a default value, it will be ignored by the custom formatter. Is this a bug, or am I using the custom formatter wrong? Thank you in advance.

Formatter:
```typescript
export const customTimeFormat = {
  stringify: (date: Date): string|null => {
    return date ? moment(date).utc(true).format('YYYY-MM-DD HH:mm:ss') : null
  },
  parse: (value: number): Date|null => {
    return value ? moment(value, 'YYYY-MM-DD HH:mm:ssZ').toDate() : null
  }
}
```

Default values for three kind of inputs:
```typescript
export const defaultStartTime = (): number => {
  return new Date().setHours(0, 0, 0)
}

export const defaultEndTime = (): number => {
  return new Date().setHours(23, 59, 59)
}

export const defaultIntervalTime = (): number[] => {
  return [defaultStartTime(), defaultEndTime()]
}
```

(All functions are used in a helper.ts file and they are imported to the given vue component.)

Edit: as a workaround, I'm setting the formatter to null if v-model has no initial value from the vuex getter:
```vue
<date-picker v-model="item.available.from"
                           :disabled="!editing"
                           :default-value="defaultStartTime"
                           :formatter="!createMode ? customTimeFormat : null"
                           :input-class="['input form-control', { 'border-danger': errors[0]}]"
                           :state="errors[0] && !item.available.from && editing ? false : null"
                           class="w-100"
                           prefix-class="xmx"
                           type="datetime"
                           value-type="format"/>
```

**Comment by mengxiong10** [comment]
The type of `default-value` should be `Date` not `Function`

**Comment by movstox** [comment]
@mengxiong10 I've created a snippet here I guess it is related. I pass default value, but current date is still highlighted in blue. am i doing something wrong? https://jsfiddle.net/4acw1dz3/1/

**Comment by mengxiong10** [comment]
@movstox 
![image](https://user-images.githubusercontent.com/14135808/145504448-ccbb7ae9-e138-4be1-a033-13adea5a9b44.png)
The default value is only for which the calendar month is showing when value is null. If you want highlight date you should set the value. and the current date is highlighted because of the class `today`, you can use css to custom it.
