### ISSUE TITLE
[Feature Request] Option to declare a date range that the user can select. Disable the rest.

### ISSUE THREAD

**Issue by LimaEduardo** [mengxiong10/vue2-datepicker#657]
Hello everyone! 

Currently, we can declare which dates we want to disable via the "disabled-date" prop. I find it interesting that we have a feature that is the "inverse" of "disabled-data", a prop that I can declare a list of enabled dates. Something like the "time-picker-options" prop, but for dates. 

**What problem does this feature solve?**
As a developer, I want to only enable a date range and prevent my user from selecting a date outside that range. A feature like "enabled-dates" would allow me to easily state which dates my user can select.

**What does the proposed API look like?**
We could have a prop "enable-dates" to pass a list of dates that would be activated. Or a function that returns the range of activated dates.

**Comment by mengxiong10** [comment]
I think this is redundant api, just use `disabled-date`.
```js
enableDates() {
   return !this.disabledDate()
}

```

**Comment by LimaEduardo** [comment]
You are right. I wasn't thinking clearly yesterday 😀

Thanks for the answer!
