### ISSUE TITLE
[Bug]Return timestamp

### ISSUE THREAD

**Issue by VictorPulzz** [mengxiong10/vue2-datepicker#665]
**Vue2-datepicker version**: 3.4.1
**Vue version**: 2.6.12
**Browser**: Chrome

When I use timestamp, returns timestamp in milliseconds, how I can return timestamp only seconds?

**Steps to reproduce**
![image](https://user-images.githubusercontent.com/23406402/144996744-70faf2b2-8f3e-48f8-99ea-0d4319dab4d0.png)

**Comment by mengxiong10** [comment]
use a computed value.
```html
<date-time-picker v-model="value" />
```
```js
  computed: {
    value: {
      get() {
        if (typeof form.planning_date === 'number') {
          return form.planning_date * 1000
        }
        return form.planning_date
      },
      set(val) {
        if (typeof val === 'number') {
          form.planning_date = Math.floor(val / 1000)
        }
        form.planning_date = val
      }
    }
  }


```
