### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by VictorPulzz** [mengxiong10/vue2-datepicker#666]
**Vue2-datepicker version**:3.4.1
**Vue version**: 2.6.12
**Browser**: Chrome

Hello! Thanks for you cool plugin.
But I faced with problem. 
In my service, the user can select his timezone, which will differ from the local one.
And I would like the selected date or for example in the parameter: disabled-date. The time zone was taken into account. Could you add property 
```:timezone="Europe / Berlin"```

Thanks A lot!

**Comment by mengxiong10** [comment]
You can use a computed value to transform timezone.
```html
<date-picker v-model="date" />
```
```js
data() {
  return { value: new Date() }
},
computed: {
  date: {
    get() {
      if (this.value) {
        return new Date(this.value.getTime() + this.timezoneOffset * 60 * 1000)
      }
      return this.value
    },
    set(val) {
      if (val) {
        this.value = new Date(this.value.getTime() - this.timezoneOffset * 60 * 1000)
      }
      this.value = val
    }
  }
}

```

**Comment by VictorPulzz** [comment]
Hmmm, how this work in ```disabled-date``` ?

**Comment by mengxiong10** [comment]
use `disabled-date` as usual.
```js
disabledDate(date) {
   return date < new Date()
}

```
