### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by StensenE** [mengxiong10/vue2-datepicker#667]
**vue2-datepicker: 3.10.4**
**vue: 2.6.6**
**chrome**:

Good evening!

I'm having an issue with date format to datepicker.

When i set valueType="YYYY-DD-MM"
The MM is updating, instead of DD.

If I set valueType="DD-MM-YYYY" the input is empty on render, and date value is not set to this format.

![image](https://user-images.githubusercontent.com/22217945/145602612-0f5a60a9-70d3-4558-8a2c-cab50bd33cf5.png)

Reference image above; how can I change DD on date format YYYY-DD-MM  and on format DD-MM-YYYY ?

**Comment by mengxiong10** [comment]
Can you show your code? what's the problem?
https://codesandbox.io/s/vue2-datepicker-test-iq5eq?file=/src/App.vue

**Comment by mengxiong10** [comment]
You should set `format`not  `value-type`. The `value-type` should be the type of `v-model`.
```html
<date-picker format="YYYY-DD-MM" />

```
