### ISSUE TITLE
[Feature request] Change month/year programmatically 

### ISSUE THREAD

**Issue by CavalcanteLeo** [mengxiong10/vue2-datepicker#675]
Using inline mode, I have to change next/prev month by clicking on a custom button.

Is that possible?

Also I had to hide the `mx-calendar-header`

```css
::v-deep .mx-calendar-header {
  display: none;
} 
```

All of that because i have to create a custom header that looks like this (green circle):

<img width="466" alt="Screen Shot 2022-01-05 at 01 13 07" src="https://user-images.githubusercontent.com/1735944/148159836-bfb64b19-a295-4eba-a74e-a765d5d52562.png">

and now i have to change the months with those pink arrows

Thanks

**Comment by mengxiong10** [comment]
use `CalendarPanel` repalce `DatePicker`

```html
<calendar-panel
  :value="value"
  @select="handleSelect"
  :calendar.sync="calendar"
></calendar-panel>

```
```js
import DatePicker from 'vue2-datepicker';

const { CalendarPanel } = DatePicker;

export default {
  name: 'Basic',
  components: { CalendarPanel },
  data() {
    return {
      calendar: new Date(),
      value: new Date()
    };
  },
  methods: {
    handleSelect(val) {
      this.value = val;
    },
    handleNextMonth() {
      const nextMonth = new Date(this.calendar);
      nextMonth.setMonth(nextMonth.getMonth() + 1);
    },
  },
};



```

**Comment by CavalcanteLeo** [comment]
thanks
