### ISSUE TITLE
[Bug] Date from the object property is not being filled in the input field

### ISSUE THREAD

**Issue by felzend** [mengxiong10/vue2-datepicker#676]
**Vue2-datepicker version**: v3.10.4
**Vue version**: v2.6.14
**Browser**: Chrome / Firefox

**Reproduction Link or Source Code**

![image](https://user-images.githubusercontent.com/10427954/148449757-0d0ad0cd-37a2-4d16-90ac-e5e7153c5af2.png)

![image](https://user-images.githubusercontent.com/10427954/148449916-fa1d3ec9-919b-4baa-86e0-4d66d1398ffa.png)

**Expected behavior**  

- Date on the object property to be filled into the input field.

**Actual behavior**

- Date on the object isn't being filled into the input field (v-model and :value are not working)

**Comment by mengxiong10** [comment]
The type of session.data is a String. You can set `value-type`.

```html
<date-picker value-type="YYYY-MM-DD" />
```
https://mengxiong10.github.io/vue2-datepicker/index.html#ValueType
