### ISSUE TITLE
[Feature request] Possible to set the day interval for range datepicker?

### ISSUE THREAD

**Issue by lilyhoctint** [mengxiong10/vue2-datepicker#677]
**What problem does this feature solve?**
For a reservation system, users are allowed to reserve an item for max 7 days. If this function is available, it's more convenient for user to select the correct day interval

**What does the proposed API look like?**
When user dragged more than the max day interval, there should be no blue background effect on datpicker, and no click event on the date
![image](https://user-images.githubusercontent.com/97651801/149263247-2c96ab0a-8bde-42bc-9baa-3611ae09ef54.png)

**Comment by mengxiong10** [comment]
https://github.com/mengxiong10/vue2-datepicker/issues/430#issuecomment-648713825

**Comment by lilyhoctint** [comment]
working fine thanks for ur help 
I changed like this:

let dayInterval = 7;
      if (currentValues.length === 1) {
        return (
          date < currentValues[0] ||
          date >
            new Date(currentValues[0].getTime() + dayInterval * 24 * 3600 * 1000)
        );
      }
