### ISSUE TITLE
Custom css class or titles for disabled dates

### ISSUE THREAD

**Issue by Matvej17** [mengxiong10/vue2-datepicker#683]
Hi guys,

I use your datepicker, it is great. Thank you.

I have one guestion, maybe idea for next feature.

Is posibble in disabled-date function somehow add for individual days custom class and custom title ?
I was looking for something like that, but I couldn't find it.

It's good, for example, to be able to distinguish between types of reservations.

Have a nice day guys and thanks for your reply.

**Comment by mengxiong10** [comment]
```html
<date-picker :get-classes="getClasses" />
```
```js
{
  methods: {
    disabledDate(date) {}
    getClasses (date) {}
  }
}

```
