### ISSUE TITLE
Default time value through v-model is not updating

### ISSUE THREAD

**Issue by sathiyad** [mengxiong10/vue2-datepicker#685]
I tried to set time on load but it's not. 

```JS
<date-picker
    type="time" id="start"
    :time-picker-options="startTimeOptions"
    v-model="start"
    value-type="time"
    format="hh:mm A"
></date-picker>
```

here's the start and startTimeOptions,
```JS
startTimeOptions:{start: '00:00',step: '00:15',end: '23:45',format: 'hh:mm A'},
start:'12:00' //(also tried with start:'12:00 AM' & start:{hh:'12',mm:'00',A : 'AM'})
```

But none of the above helps to update the value. At the same time after selecting time on the input, I could see the below value.
![Screenshot from 2022-01-26 13-13-39](https://user-images.githubusercontent.com/25609136/151157946-b3f435fd-d379-4eb4-8672-d276c11ed59c.png)

However, it helps `new Date()` but after removing value-type!

**Comment by mengxiong10** [comment]
`value-type="HH:mm"`
