### ISSUE TITLE
Cannot set the dynamic value for the date

### ISSUE THREAD

**Issue by jjllppp** [mengxiong10/vue2-datepicker#687]
It does not show the date that has been save into the database. (for edit)

<label>Time</label>
 <date-picker class="wide-date" v-model="time"  type="datetime" format="YYYY-MM-DD HH:mm"  @input="selecttime" ></date-picker>

export default {
data(){
time:new Date(this.data.time),
},
created(){
this.getData();
},
methods:{
getData(){
        this.sendHttp(`/api/data/${this.data}`)
        .then((response) => {
          this.data = response.data;
          this.time =  moment(this.data.time).format("YYYY-MM-DD HH:mm");
        }) .catch((error) => {
          console.log(error);
        })
    },
},
}
the image show the time saved in the database
<img width="104" alt="image" src="https://user-images.githubusercontent.com/99226891/152898324-d0f071c0-884e-4cc1-880e-f21de4e038e0.png">
it does not highlighted the date selected in the panel. For example, it should be  highlighted the the date 2022-02-11 00:00 that had been saved in the database. 
<img width="188" alt="image" src="https://user-images.githubusercontent.com/99226891/152898685-b72546b3-b1f5-47a4-bfcf-2a2b0d05191f.png">

**Comment by mengxiong10** [comment]
`this.time` should be a `Date` not `String`.
```js
// this.time = moment(this.data.time).format("YYYY-MM-DD HH:mm")
// replace
this.time = new Date(this.data.time)
```
