### ISSUE TITLE
Date and Time Picker won't show the time

### ISSUE THREAD

**Issue by SimetriaStudio** [mengxiong10/vue2-datepicker#69]
In version 1.9.1 when you have a date and time datepicker, the time never shows once you selected the date. Even in your example here - https://mengxiong10.github.io/vue2-datepicker/  - in the middle section where you give examples of the date time functionality, it does not work. 

Or am I missing something?

**Comment by mengxiong10** [comment]
Thanks for reminding.
I've fixed it in v1.9.2.
