### ISSUE TITLE
Upgrade posstcss-cli[Feature request]

### ISSUE THREAD

**Issue by VictorPulzz** [mengxiong10/vue2-datepicker#690]
Hello!
Can you upgrade postcss.cli, because when I tryed connect tailwind to vue project.
And got this error:
![image](https://user-images.githubusercontent.com/23406402/153774548-9660fa8a-9933-4c1d-9034-a923b1da0fbb.png)
Please upgrade :)

**Comment by mengxiong10** [comment]
You can copy the css to other place.

**Comment by VictorPulzz** [comment]
Or just update version)

**Comment by mengxiong10** [comment]
@VictorPulzz I'll update it when the next version is released
