### ISSUE TITLE
[Feature request] Add custom text in the week type component

### ISSUE THREAD

**Issue by csteri** [mengxiong10/vue2-datepicker#691]
How do I add custom text and start and end date here?
![Screenshot_5](https://user-images.githubusercontent.com/32652225/154487289-22096340-e43d-40e8-bc62-67f33e26f83a.png)

```
<div id='app'>
  <date-picker v-model="time1" type="week" placeholder="select week" value-type="ww"></date-picker>
</div>

<script>
  new Vue({
    el: "#app",
    components: {
      DatePicker
    },
    data: {
      time1: null
      }
  });
</script>
```

**Comment by csteri** [comment]
@mengxiong10 not working with `value-type="w"`, but your code does not display exactly what is required.
![image](https://user-images.githubusercontent.com/32652225/154691595-05a13630-6af9-45f7-bd66-61b75a03f69f.png)

Here is an example: https://codepen.io/csteri/pen/vYWWxda

**Comment by mengxiong10** [comment]
@csteri Because if the `value-type` is 'w', `this.value6` is a String not Date, Then you should modify the `weekRangeText ` and adjust the css by yourself.
