### ISSUE TITLE
Wrong date when saving

### ISSUE THREAD

**Issue by Ixxi478** [mengxiong10/vue2-datepicker#694]
When I try to save my date, I end up saving the previous date and not the date I had selected. I'm not sure if there is an option for this or how to solve it.

I'm also not sure what other code to add here.

This is how my date input looks like
`<date-picker v-model="startDate" type="date" format="MM-DD-YYYY" placeholder="mm-dd-yyyy"></date-picker>`

**Comment by mengxiong10** [comment]
There is no problem with this component. You can log the `startDate`
There may be a problem with where it is saved
