### ISSUE TITLE
[Feature request] Custom time interval at opening time-range

### ISSUE THREAD

**Issue by VTshk** [mengxiong10/vue2-datepicker#698]
I don't need to select future dates so when I open I want to show the previous month and the current one

**Expected behavior at opening**
![image](https://user-images.githubusercontent.com/46195996/159015531-ec5a0575-8497-4c8f-a656-df06931ac32a.png)

**Actual behavior at opening**
![image](https://user-images.githubusercontent.com/46195996/159015631-2116ddb5-a265-4480-bdfd-6e510a2dbdb7.png)

**Comment by mengxiong10** [comment]
#584
