### ISSUE TITLE
[Bug] 组件的销毁会导致页面body标签重新渲染

### ISSUE THREAD

**Issue by Dengzygx** [mengxiong10/vue2-datepicker#699]
单页面项目切换左侧菜单，改变路由后，正常情况下页面只会重新渲染右侧内容区。但每次从引用了此组件的路由切换成其他路由时，整个页面body会重新渲染一次。怀疑是组件销毁时对body内容做了修改？看源码好像也有类似逻辑
![image](https://user-images.githubusercontent.com/40979896/159888132-cbdc5b39-0b49-4e9a-9d1b-2293da414893.png)

**Comment by mengxiong10** [comment]
body会重新渲染一次是指什么?
这里的逻辑是把这个组件的根元素从body删除.
