### ISSUE TITLE
[Feature request] British locale

### ISSUE THREAD

**Issue by tomastan** [mengxiong10/vue2-datepicker#700]
Currently English locale is US only, with week starting on Sunday. 

Could you please add en-gb locale, with week starting on Monday.

As many instances of the component are used, it would be much more convenient to have this setting globally, to avoid overriding `:lang="..."` every time.

Unfortunately the attempt to rewrite setting globally (code below) doesn't work and the week starts on Sunday anyway:

```
import DatePicker from 'vue2-datepicker'
import en from 'vue2-datepicker/locale/en'
en.formatLocale.firstDayOfWeek = 1
DatePicker.locale('en')
Vue.use(DatePicker) 
```

**Comment by mengxiong10** [comment]
You should update `locale`
```js
....
// DatePicker.locale('en')
DatePicker.locale('en', en)

```

**Comment by tomastan** [comment]
Thanks, this was it! Somehow didn't find in docs how to set this setting.
