### ISSUE TITLE
clear to given date

### ISSUE THREAD

**Issue by gurupetach** [mengxiong10/vue2-datepicker#701]
When clearing(the x button), how can i set it to particular `from` and `to` instead of null?

**Comment by mengxiong10** [comment]
```html
<date-picker  v-model="value" @clear="handleClear"/>
```
```js
handleClear() {
   this.value = [from, to]
}

```

**Comment by gurupetach** [comment]
Thanks. Also this works..
``<date-picker
              v-model="params.range"
              type="date"
              value-type="format"
              format="YYYY-MM-DD"
              range
              placeholder="Filter by date range"
              @clear="
                (clear) => {
                  params.range = [(from = '2021-01-01'), (to = '')];
                }
              "
            />``
