### ISSUE TITLE
[QUESTION] Time-picker issue with end-date value.

### ISSUE THREAD

**Issue by fickezapad** [mengxiong10/vue2-datepicker#705]
![datepicker](https://user-images.githubusercontent.com/61761195/168030163-704b291f-019c-4934-8483-6103919effd0.png)
When you select from the 'ranges' tab on the left side of the panel, the pre-selected value of end-date is 11;59 and its giving false data back because the time should be going to 23;59 so it calculates only half of the day. Here's the code for time-picker and how I'm getting end-date.
![2022-05-12_10-49](https://user-images.githubusercontent.com/61761195/168031261-bb283c88-4525-4761-a2c2-71ab9ebf0dea.png)
![2022-05-12_10-50](https://user-images.githubusercontent.com/61761195/168031566-ba8eb4e3-0203-4d1c-ac22-105bc7473f2f.png)

I tried setting :ranges="false" and :show-dropdowns="true" to eliminate that issue, but then other problem occur. When you select a month form the dropdown menu it only allows you to select dates from within 1 month range. For example:
![2022-05-12_10-47](https://user-images.githubusercontent.com/61761195/168030810-31181f32-8cc8-48dc-9a24-261970fa7683.png)
If i tried to select march on the start date select it will only allow me to select april as end date and so on. I can't select for example startdate january and end date december.

So help with either one of the changes will mean a lot.

**Comment by mengxiong10** [comment]
Maybe  you should replace 'hh' with 'HH'

**Comment by mengxiong10** [comment]
@fickezapad I guess.
Can you show more detail?

**Comment by fickezapad** [comment]
![2022-05-16_09-36](https://user-images.githubusercontent.com/61761195/168542289-710b6c65-fc88-4cb4-a639-33c10dd50b26.png)

This is the exact usage of the component.

**Comment by mengxiong10** [comment]
what's the `picker.startDate`?

**Comment by mengxiong10** [comment]
Whick version do you use?

**Comment by fickezapad** [comment]
![start](https://user-images.githubusercontent.com/61761195/168546092-fdb52967-44b1-4331-91bc-4d60ed5529ca.png)

![timeType](https://user-images.githubusercontent.com/61761195/168546228-aa0247ef-6937-4219-a307-8d42a881a4ff.png)

![created()](https://user-images.githubusercontent.com/61761195/168546164-f80ea793-70c3-4c24-89be-e6804986d433.png)
![2022-05-16_09-57](https://user-images.githubusercontent.com/61761195/168546300-81ea1c96-d518-4d3c-b2ed-4e66363d4af1.png)

**Comment by fickezapad** [comment]
> Whick version do you use?

I use the version for Vue2

**Comment by fickezapad** [comment]
![2022-05-16_10-06](https://user-images.githubusercontent.com/61761195/168547468-6e0d6513-63c2-48c2-a433-65cc8fdb68f6.png)

**Comment by fickezapad** [comment]
i am using different componenat, am i?

**Comment by mengxiong10** [comment]
> i am using different componenat, am i?

Yes, It's another component not this.
