### ISSUE TITLE
I am unable to use input-error event 

### ISSUE THREAD

**Issue by ShikshaInfotechPvtLtd** [mengxiong10/vue2-datepicker#708]
Hi, 
I am unable to use the input-error events.
<date-picker @input-error="chkDate()" v-model="date"></date-picker>
I have a couple of questions regarding this date picker
whenever a user types the wrong date it is automatically converted into a valid date. is it possible to stop this feature?

**Comment by mengxiong10** [comment]
```html
<date-picker @input-error="handleInputError" v-model="date">
```
```js
methods: {
   handleInputError() {
     this.date = new Date()
    }
}

```
