### ISSUE TITLE
show start date and end date when choose range datapicker

### ISSUE THREAD

**Issue by cylace** [mengxiong10/vue2-datepicker#709]
Hallo,

 i would add on two inputs **start date and end date,** have you an idea for help me ??? i see start date and end date but not possible for me to add this on an **input**.
an input for start date and an other input for end date.
thank you for help

**Comment by mengxiong10** [comment]
@cylace 
https://codesandbox.io/s/date-range-optional-range-z06gv?file=/src/App.vue

**Comment by cylace** [comment]
Hallo thank you so much :)
