### ISSUE TITLE
mx-datepicker width is not changeable

### ISSUE THREAD

**Issue by komalpangam** [mengxiong10/vue2-datepicker#71]
I am trying to change the width of the datepicker to 100% as per requirement of our web page, but seems like width is set to by default to 210 px for date picker. And hence i am unable to change the width. 

Can i expect any help from this? I wanted to manipulate the width for mx-datepicker class of div tag from index.vue of this package, but no luck.

Please advice.

**Comment by mengxiong10** [comment]
Just set the width='100%'

**Comment by sureshjoshi** [comment]
When in doubt, use !important

    width: 100% !important;

**Comment by ObSeSSeN** [comment]
Setting the width prop to 100% doesn't work. If you set just a number (eg. 500) it will set the width to 500px but if you set it to a number and unit (eg. 100%) it is ignored.

Not working:
`<date-picker v-model="date1" lang="en" width="100%"></date-picker>`

Working (sets 500px):
`<date-picker v-model="date1" lang="en" width="500"></date-picker>`

**Comment by sureshjoshi** [comment]
You can manually set the stylesheet and it works, I'd never tried setting the prop - but looking in the code, it explicitly adds a "px" suffix to whatever you send in:

    :style="{'width': width + 'px','min-width':range ? (type === 'datetime' ? '320px' : '210px') : '140px'}"

Setting the stylesheet works fine, but you might need to use the !important attrib.

Works:

    <date-picker style="width: 100%;" lang="en" v-model="date"></date-picker>

Or

    <date-picker class="wide-date-example" lang="en" v-model="date"></date-picker>
    .wide-date-example {
        width: 100% !important;
    }

Doesn't work:

    <date-picker class="wide-date-example" lang="en" v-model="date"></date-picker>
    .wide-date-example {
        width: 100%;
    }

**Comment by mengxiong10** [comment]
Now the css units are allowed. tks
