### ISSUE TITLE
Change the name of the header title

### ISSUE THREAD

**Issue by cylace** [mengxiong10/vue2-datepicker#710]
Hi, how can i change the 'mx-calendar-title-label' ?? I would change the title jun to juni for exemple (complète word not the three first letters). And wat is the method for translations for this ?? i've a website with 3 translations. 
For moment, i've that: 
![image](https://user-images.githubusercontent.com/57703077/176470113-12bf2c9e-a563-4ee6-94f5-84037b0d4108.png)

i would that: 
![image](https://user-images.githubusercontent.com/57703077/176470361-b3833697-f4f9-4d99-b1fc-3441af5feefd.png)

THank you so much for your help :)

**Comment by mengxiong10** [comment]
```html
<date-picker  :lang="lang"/>
```
```js
data() {
  return {
        lang: {
          monthFormat: 'MMMM',
        },
  }
}

```
https://github.com/mengxiong10/vue2-datepicker/blob/master/locale.md

**Comment by cylace** [comment]
@mengxiong10 thank you so much.
One question, for multi languages it doesn't work on my website. it's always on the same language. 
i add this : 
![image](https://user-images.githubusercontent.com/57703077/176648029-6828927e-d6ec-4798-8c20-34b9ba4daece.png)

and add this on datepicker : 

![image](https://user-images.githubusercontent.com/57703077/176648181-f4e114e4-45b7-41b8-bbbc-8f2d57c3cff4.png)

**Comment by mengxiong10** [comment]
You can change the global object.
```html
<date-picker lang="en" />

```

```js
import zh from 'vue2-datepicker/locale/zh-cn'
import en from 'vue2-datepicker/locale/en'

zh.monthFormat = 'MMMM'
en.monthFormat = 'MMMM'

```

**Comment by cylace** [comment]
I tried this but it's not correct it's strange. i've three languages

**Comment by mengxiong10** [comment]
Can you show your code ?

**Comment by cylace** [comment]
![image](https://user-images.githubusercontent.com/57703077/176661439-6e9ba568-7397-4f44-916f-50ba7f05a854.png)
It's my code, i've tried with method above but not correct. i search for moment :)

**Comment by cylace** [comment]
i tried with this method too : 
![image](https://user-images.githubusercontent.com/57703077/176661934-5108d323-6782-4c62-85f8-93c51de23d8b.png)

**Comment by mengxiong10** [comment]
<date-picker :lang="lang" />

```js
import DatePicker from "vue2-datepicker";
import "vue2-datepicker/index.css";
import en from "vue2-datepicker/locale/en";
import fr from 'vue2-datepicker/locale/fr';

en.monthFormat = "MMMM";
fr.monthFormat = 'MMMM';
DatePicker.locale("en", en);
DatePicker.locale("fr", fr);

export default {
  data() {
    return { lang: 'en'}
  },
methods: {
    changeLang () {
       this.lang = this.lang === 'en ' ? 'fr' : 'en'
    }
 }
}
```

**Comment by cylace** [comment]
Hi, i don't know why but i think that changeLang don't work. i try this and
it's not working.
[image: image.png]
and it's my method for that. maybe add changeLang on <Date-picker
:lang=lang ... />   .????


Op vr 1 jul. 2022 om 04:35 schreef 也无风雨 ***@***.***>:

**Comment by mengxiong10** [comment]
Add a key for the component
```html
<date-picker :lang="lang" :key="lang" />
```

**Comment by cylace** [comment]
Hi, unfortunately it's not working for me i don't know why. Maybe because other modules like vuei18n for translations ?

**Comment by cylace** [comment]
ok thank you for your help. You're great ! And Very reactif. Thanks.
