### ISSUE TITLE
[Bug] While using looping date picker object change his value but not display on datepicker it's work without loop only

### ISSUE THREAD

**Issue by vishalmicrolevel** [mengxiong10/vue2-datepicker#715]
While using looping date picker object change his value but not display on datepicker it's work without loop only
I m using datepicker with type time only
like 
<div class="row mb-1" v-for="(item, index) in finalTiming" :key="index">
 <date-picker
                v-model="item.opentime"
                :minute-step="30"
                :hour-options="hours"
                format="HH:mm"
                value-type="format"
                type="time"
                placeholder="HH:mm"
            >
            </date-picker>
</div>
finaltiming object with opentime is working perfect. the only problem with display.

**Comment by mengxiong10** [comment]
https://v2.vuejs.org/v2/guide/list.html#Array-Change-Detection
You can change `v-model` to `:value` and `onChange`.
```html
<date-picker :value="array[0]" @change="(date) => handleChange(0, date)" />
```
```script
handleChange(index, date) {
   this.$set(this.array, index, date)
}
```
