### ISSUE TITLE
[Bug] Unknown custom element: <datepicker> use Vue 2.7.0

### ISSUE THREAD

**Issue by csteri** [mengxiong10/vue2-datepicker#717]
**Vue2-datepicker version**: 3.11.0
**Vue version**: 2.7.0
**Browser**: Chrome V. 105.0.5195.127
**Laravel**: 9.19

1. I downloaded the library from here: https://www.jsdelivr.com/package/npm/vue2-datepicker
2. In **app.blade**
``` html
<head>
...
<script src="{{ asset('assets/vuejs/vue.js') }}"></script>

<link rel="stylesheet" href="{{ asset('assets/vue2-datepicker/index.css') }}"/>
<script src="{{ asset('assets/vue2-datepicker/index.js') }}"></script>
</head>

<body>
   <div id='appVue'>
     <datepicker></datepicker>
  </div>
  <script>
      let vueApp = new Vue ({
           el: '#appVue'
      })
  </script>
</body>
```
3. Error in console:
`vue.js:588 [Vue warn]: Unknown custom element: <datepicker> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by mengxiong10** [comment]
change `<datepicker>` to `<date-picker>`
