### ISSUE TITLE
In range datepicker need both calender with same month.

### ISSUE THREAD

**Issue by nazim1quadri** [mengxiong10/vue2-datepicker#720]
I have a datepicker to select from date and to date from range picker, this works but my requirement is quite different.
Actually i need both calendar with same month. My requirement is i want to select from date by clicking on first calendar and to date by clicking on second calendar.

I ave attached a screenshot which i need to achieve.

![image](https://user-images.githubusercontent.com/5894768/195007839-a6186659-afbe-4af9-a662-61e76c00fff6.png)

**Comment by mengxiong10** [comment]
https://codesandbox.io/s/range-in-datepicker2x-mode-hlzrg?file=/src/App.vue

**Comment by nazim1quadri** [comment]
Than you so much for your instant reply.

I m using below codepen.
https://codepen.io/OlegF/pen/XWdPrjb

Can i implement in this codepen
