### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by nazim1quadri** [mengxiong10/vue2-datepicker#721]
I have a datepicker to select from date and to date from range picker, this works but my requirement is quite different.
Actually i need both calendar with same month. My requirement is i want to select from date by clicking on first calendar and to date by clicking on second calendar.

I need codepen like below with above functionality.
https://codepen.io/OlegF/pen/XWdPrjb

I want to use cdn in my HTML

I ave attached a screenshot which i need to achieve.

![image](https://user-images.githubusercontent.com/5894768/195168776-0d8ed8ac-91e2-451e-8ec9-09163b5a3af5.png)

**Comment by mengxiong10** [comment]
https://codepen.io/mengxiong10/pen/VwxqrZM
