### ISSUE TITLE
Icon-calendar slot didnt change [Bug]

### ISSUE THREAD

**Issue by ihda06** [mengxiong10/vue2-datepicker#722]
im trying use this code and nothing change

`<i slot="icon-calendar">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                        <path id="clock" d="M16,8a8,8,0,0,0-8,8,8.256,8.256,0,0,0,1.53,4.707A7.818,7.818,0,0,0,16,24,8,8,0,0,0,16,8Zm0,14.452A6.452,6.452,0,1,1,22.452,16,6.45,6.45,0,0,1,16,22.452Zm1.994-3.368-2.739-1.99a.39.39,0,0,1-.158-.313v-5.3a.388.388,0,0,1,.387-.387h1.032a.388.388,0,0,1,.387.387v4.571l2.155,1.568a.387.387,0,0,1,.084.542L18.535,19a.39.39,0,0,1-.542.084Z" transform="translate(-8 -8)"/>
                    </svg>
                </i>`

im using vue2 and nuxt js

**Comment by mengxiong10** [comment]
If you use the version of vue > 2.6.
```html
  <template v-slot:icon-calendar>
      <svg></svg>
  </template>

```

**Comment by ihda06** [comment]
@mengxiong10 still didnt change anyting

let me drop my real code

![image](https://user-images.githubusercontent.com/63222229/199709833-f6cc569f-5e91-44d9-b6c5-2835b53c5bb5.png)

result
![image](https://user-images.githubusercontent.com/63222229/199709958-eccd67ab-cff8-4226-a854-a6dda2460e16.png)

my vue version 2.6.11

**Comment by mengxiong10** [comment]
If you use the 2.x version of `vue2-datepicker`, you should change the `icon-calendar` to `calendar-icon`

**Comment by ihda06** [comment]
@mengxiong10 thank you so much, now its works
