### ISSUE TITLE
[Bug] The first click of the time picker in the mobile version fails to respond in time

### ISSUE THREAD

**Issue by Xu-Li-Min** [mengxiong10/vue2-datepicker#725]
**Vue2-datepicker version**:^3.9.1
**Vue version**:^2.6.8
**Browser**:Google Chrome、Safari

**Steps to reproduce**
When using the phone with the time picker the first selection didn't work, but the second time did work

**Reproduction Link or Source Code**
<date-picker v-model="time" type="time" placeholder="select time"/>

**Expected behavior**
Immediate response to selected time

**Actual behavior**
It takes two clicks to work

**Comment by mengxiong10** [comment]
You can update to latest version

**Comment by Xu-Li-Min** [comment]
> You can update to latest version
HiHi, I updated the latest version but the problem still exists, and I have the same problem when I use my mobile phone to view the official website demo

**Comment by mengxiong10** [comment]
Is there the problem with all demos or only time picker?

**Comment by Xu-Li-Min** [comment]
only time picker has this problem, date picker works fine

**Comment by Xu-Li-Min** [comment]
Does anyone have a solution, I tried it but it didn't work so far

**Comment by mengxiong10** [comment]
v3.11.1 fixed it, thanks

**Comment by Xu-Li-Min** [comment]
I’m really sorry, I’ve updated the version but it still doesn’t seem to work. The click time in the screen doesn’t work. I need to double-click to work. Is there a way to make it work when I click once?

**Comment by mengxiong10** [comment]
You can copy the 'vue2-datepicker/index.css' to 'datepicker-mobile.css', then remove all the style with ':hover'.
![image](https://user-images.githubusercontent.com/14135808/205200577-500980d4-cd31-4695-8e0c-bd6bf405786a.png)


~~import 'vue2-datepicker/index.css'~~
import './datepicker-mobile.css'

**Comment by Xu-Li-Min** [comment]
Ok I'll try again, thank you very much

**Comment by Xu-Li-Min** [comment]
Hello, I finally found the problem. It is the hover of the scrollbar that causes the value of the time to not respond immediately.
Thanks for your help let me find the problem.
![image](https://user-images.githubusercontent.com/31185266/209487166-f42d0c77-6a8f-4914-b8be-45d1374e5349.png)
