### ISSUE TITLE
[Feature request] - An option to open one panel only for ranges

### ISSUE THREAD

**Issue by smplyjr** [mengxiong10/vue2-datepicker#737]
Hi! Thank you for this awesome plugin. It packs a lot features while maintaining being lightweight. As the title suggest - although I can hide the second panel of the date range either using CSS or JavaScript, I think it would still be helpful if we support it natively. 🤔

**Comment by mengxiong10** [comment]
https://codesandbox.io/s/range-picker-with-one-calendar-jvv5s

**Comment by kozubov** [comment]
@mengxiong10  Not working autoClose after selection.
