### ISSUE TITLE
[Feature request]: Disable choosing of a date in the coming month from the current month

### ISSUE THREAD

**Issue by Boluwatife2904** [mengxiong10/vue2-datepicker#738]
**What problem does this feature solve?**
I want to be able to prevent users from selecting a date that is in the next month but is currently being shown in the current month. Take for instance, in the image attached below, I want to prevent from choosing dates that are in February which are 1, 2, 3 and 4 but they are currently visible.

<img width="866" alt="Screenshot 2023-01-23 at 21 55 38" src="https://user-images.githubusercontent.com/49585353/214148175-5b61f0dc-2329-4346-a28b-1740034a1673.png">

**What does the proposed API look like?**

**Comment by mengxiong10** [comment]
css 
```
.not-current-month {
  pointer-events: none;
}

```

**Comment by Boluwatife2904** [comment]
> css
> 
> ```
> .not-current-month {
>   pointer-events: none;
> }
> ```

Thank You.
