### ISSUE TITLE
[Bug] When i click any Btn in v-dialog why modal scroll to top

### ISSUE THREAD

**Issue by DimensionRoom** [mengxiong10/vue2-datepicker#747]
[https://drive.google.com/file/d/13_H4hdFRarYFQ4lcN54z6ZGnAKJDNeS5/view?usp=sharing](url)
I record issue video for easy to help me solve problem.
btw this issue been only in v-dialog

**Comment by mengxiong10** [comment]
You can try to set `append-to-body = false`
