### ISSUE TITLE
Custom format function

### ISSUE THREAD

**Issue by saintplay** [mengxiong10/vue2-datepicker#75]
Sometimes you need more control when formatting the Dates.

```html
<date-picker v-model="time" :format="customFormatter"></date-picker>
```

```js
methods: {
  customFormatter(date) {
    return moment(date).format('MMMM Do YYYY, h:mm:ss a');
  }
}
```

This functionality will be supported somehow? **are PRs welcome**?

**Comment by dougstjohn** [comment]
Did you find another solution for formatting the output date?

**Comment by saintplay** [comment]
No, I didn't. I checked the source code, this needs a PR.

Personally I'm using other solution like **vuejs-datepicker**, in the meantime

**Comment by dougstjohn** [comment]
Agreed. I ended up using @change and calling a method to do the formatting.

```html
<date-picker v-model="endDate" @change="dateChange('endDate')"></date-picker>
```

```javascript
methods: {
    dateChange(variable) {
        this[variable] = moment(this[variable]).format('MM-DD-YYYY');
    }
}
```

**Comment by mengxiong10** [comment]
PRs welcome

**Comment by mengxiong10** [comment]
V1.9.5 Added.
Since this prop 'format' affects the input function , I added the prop 'custom-formatter'.
```html
<date-picker v-model="time" :custom-formatter="customFormatter"></date-picker>
```

```js
methods: {
  customFormatter(date) {
    return moment(date).format('MMMM Do YYYY, h:mm:ss a');
  }
}
```

**Comment by dougstjohn** [comment]
Is this assigning the customFormatter() return value to the model?

**Comment by mengxiong10** [comment]
return a String to dispaly

**Comment by lan8086** [comment]
hello there,
I'm new to vue, need to bind a date object to this so that it sends to server as ISO date string-YYYY-MM-DD, but display format in local culture. could you please suggest the best way to achieve this? i tried to use the custom-formatter, doesn't seem to work.
thanks,

**Comment by mengxiong10** [comment]
@lan8086 The default bind value is a Date Object. You can set format (YYYY/MM/DD) to format the display.

**Comment by mgreenw** [comment]
@mengxiong10 Is there currently a way to provide a custom format function since the `custom-formatter` prop was removed in v2?

**Comment by mengxiong10** [comment]
Pass to `format` an object.
```html
<date-picker v-model="value" :format="myFormat" />

```

```js
  data () {
    return {
      myFormat: {
        stringify: (date) => {
          return date ? moment(date).format('LL') : null
        },
        parse: (value) => {
          return value ? moment(value, 'LL').toDate() : null
        }
      }
    }
  }

```

**Comment by mgreenw** [comment]
@mengxiong10 thanks!

**Comment by hikayatz** [comment]
> V1.9.5 Added.
> Since this prop 'format' affects the input function , I added the prop 'custom-formatter'.
> 
> ```
> <date-picker v-model="time" :custom-formatter="customFormatter"></date-picker>
> ```
> 
> ```js
> methods: {
>   customFormatter(date) {
>     return moment(date).format('MMMM Do YYYY, h:mm:ss a');
>   }
> }
> ```

I 
try using version `3.8.2` this props not working

**Comment by mengxiong10** [comment]
@hikayatz the lastest version is `formatter`

**Comment by Sivkay25** [comment]
Hello @mengxiong10 
<date-picker v-model="value" format="DD-MMM-YYYY" />
I want the value to format like 'DD-MMM-YYYY'. However, I want date-picker to accept any format from manually input (exp: 'DD-MM-YYYY', 'YYYY-MM-DD'). How can I achieve that?
