### ISSUE TITLE
Ability to set or override locales

### ISSUE THREAD

**Issue by andreasvirkus** [mengxiong10/vue2-datepicker#77]
A simple feature request where the user can set a custom locale or override an existing one (for example if different translations are desired).
Would you be open to a PR about this?

Sidenote: do you accept PRs to populate the current locale pool? I'd be willing to add some:
- Lithuanian
- Latvian
- Swedish
- Finnish
- Dutch
- Estonian
(the company I work for operates in those countries so the translations would be legitimate and from native speakers)

**Comment by mengxiong10** [comment]
Yes, I can add a prop to customize the language.
Thanks for the remind.

**Comment by mengxiong10** [comment]
v1.9.3 released
