### ISSUE TITLE
How to use this datepicker via CDN?

### ISSUE THREAD

**Issue by zhiyong80** [mengxiong10/vue2-datepicker#83]
I tried to load it via CDN:
```
  <script src="https://cdn.jsdelivr.net/npm/vue2-datepicker@1.9.6/dist/build.min.js"></script>
  <script type="text/javascript">
    Vue.use(DatePicker);
    var vm = new Vue({
      el: '#app',
      components: { DatePicker },
      data: {
        startDate: '',
      },
      computed: {

      },
      mounted() {

      },
      methods: {

      }
    });
  </script>
```
Then add the following to html:
```
<date-picker v-model="criteriaStartDate" lang="en" type="datetime" format="yyyy-MM-dd hh:mm:ss" confirm></date-picker>
```
When I tried to load the page, I saw error message in console:

[Vue warn]: Failed to mount component: template or render function not defined.
found in
---> <DatePicker>
       <Root>

I really like this tool, but would much appreciate if there is way to use it via CDN.

**Comment by mengxiong10** [comment]
Vue.use(DatePicker.default);

**Comment by zhiyong80** [comment]
It works now.Please consider close the issue.
