### ISSUE TITLE
How to change default date range options

### ISSUE THREAD

**Issue by malikali86** [mengxiong10/vue2-datepicker#84]
I was wondering if there is any way to customize the default date range options?

For example: next 7 days - next 30 days - previous 7 days - previous 30 days

Maybe I would like  Today - Yesterday - Last 7 Days - Last Month - Last 3 Months

Please advice. I do appreciate an excellent quality of work you have put into the development of this tool.

**Comment by mengxiong10** [comment]
The prop shortcuts.
```html
<script>
export default {
  data() {
    return {
      time: '',
      shortcuts: [
        {
          text: 'Today',
          start: new Date(),
          end: new Date()
        }
      ]
    }
  }
}
</script>

<template>
    <date-picker v-model="time" range :shortcuts="shortcuts"></date-picker>
</template>
```

**Comment by malikali86** [comment]
@mengxiong10 Many thanks! A perfect solution now for my project. 

Keep up the great work.
