### ISSUE TITLE
Not able to change Name attribute

### ISSUE THREAD

**Issue by akshay-kh** [mengxiong10/vue2-datepicker#85]
i want to change name attribute of this component but not able to do the same am using this component as a child component i think it would be better to add name to v-bind to change it.

**Comment by mengxiong10** [comment]
Do you mean you want to change the input element's name attribute?

**Comment by akshay-kh** [comment]
yes

**Comment by akshay-kh** [comment]
i have submitted a PR for the same please review https://github.com/mengxiong10/vue2-datepicker/pull/86

**Comment by akshay-kh** [comment]
I think its not updated to npm yet but thank you for merging my PR .

**Comment by akshay-kh** [comment]
can you please update npm

**Comment by mengxiong10** [comment]
```html
<date-picker ref="datepicker"></date-picker>
```
```js
this.$refs.datepicker.$refs.input.name = 'time'

```
You can temporarily change it.
I'll publish it next time.

**Comment by akshay-kh** [comment]
oh ok thank you.
