### ISSUE TITLE
Enable / Disable selection of hours in the timepicker

### ISSUE THREAD

**Issue by munerf** [mengxiong10/vue2-datepicker#88]
Hi,
I want to allow the user to select a date and time e.g. 01.05.2018  21H15M, but some slots are already booked. Is there a way to disable the selection of custom hours?

Something like
`pickerOptions: { start: '09:00', step: '00:15', end: '20:45', enabler: customHandler },`

If not can you point me where to extend it? I'll do a clone.

Thanks

**Comment by mengxiong10** [comment]
I published v1.9.7 
the 'time-picker-options' supports custom function. Return the array link this.
```html
<date-picker v-model="value4" lang="en" type="datetime" format="yyyy-MM-dd hh:mm:ss a"
          :time-picker-options="customPickerOption"></date-picker>
```

```JavaScript
customPickerOption () {
  const results = [
    {
      label: '21:15',
      value: {
        hours: 21,
        minutes: 15
      }
    },
    {
      label: '22:15',
      value: {
        hours: 22,
        minutes: 15
      }
    }
  ]
  return results
}
```

**Comment by munerf** [comment]
Not working!

vue.esm.js?efeb:591 [Vue warn]: Invalid prop: type check failed for prop "timePickerOptions". Expected Object, Function, got Array.

**Comment by mengxiong10** [comment]
@munerf you need a funciton
```JavaScript
methods: {
  customPickerOption () {
    const results = [
      {
        label: '21:15',
        value: {
          hours: 21,
          minutes: 15
        }
      },
      {
        label: '22:15',
        value: {
          hours: 22,
          minutes: 15
        }
      }
    ]
    return results
  }
}

```
