### ISSUE TITLE
Shortcuts don't work when using :value

### ISSUE THREAD

**Issue by funkybob** [mengxiong10/vue2-datepicker#90]
When using:

        <date-picker lang="en" range confirm
          v-model="filters.dateRange"
          @confirm="onDateSelect"
          :shortcuts="shortcuts"
          v-show="showDateFilter"
        />
The code works, however since "filters" is a vuex getter, this is incorrect.  It also makes the @confirm trigger moot, as it updates the value immediately.

However, if I correct this to:

        <date-picker lang="en" range confirm
          :value="filters.dateRange"
          @confirm="onDateSelect"
          :shortcuts="shortcuts"
          v-show="showDateFilter"
        />

It behaves correctly [vuex doesn't complain, and the confirm trigger fires correctly] but the custom shortcuts stop working.

Have updated to 1.9.7 and it persists.

Could it be related to the text() method referencing this.value directly, instead of this.currentValue ?

**Comment by mengxiong10** [comment]
the shortcuts emit 'change and input' event. You can change 'confirm' to 'change'.
```html
    <date-picker lang="en" range confirm
      :value="filters.dateRange"
      @change="onDateSelect"
      :shortcuts="shortcuts"
      v-show="showDateFilter"
    />

```

**Comment by funkybob** [comment]
I only want to update my vuex state when the user clicks OK.

I expect the shortcuts to change the selection. e.g. currentValue
They don't.

When using v-model clicking a shortcut does update the selection, and leaves the pop-up open. I want this behavior to continue.

**Comment by Julia-Lavrova** [comment]
Try to use `v-model="filters.dateRange"` and event `@confirm`. The `input` event also will call. It has array with range: startDate and endDate .
```
methods: {
  handleInput(range) {
    console.log(range[0], range[1]);
  }
}
```

**Comment by funkybob** [comment]
But won't using v-model mean it will try to update the v-model target when the selection is changed?

**Comment by mengxiong10** [comment]
upgrade V2.0.
If you use vuex, you can't use v-model. Listen the 'change' event.
``` html
    <date-picker lang="en" range confirm
      :value="filters.dateRange"
      @change="onDateSelect"
      :shortcuts="shortcuts"
      v-show="showDateFilter"/>

```

**Comment by funkybob** [comment]
Appears to be working perfectly now.

Many thanks!
