### ISSUE TITLE
masking for editable datepicker?

### ISSUE THREAD

**Issue by Ramya-Palaniswami** [mengxiong10/vue2-datepicker#91]
Is it possible to have mask for the editable input field in the datepicker?

**Comment by mengxiong10** [comment]
Sorry, I didn't understand what you mean

**Comment by gigioSouza** [comment]
@mengxiong10 @Ramya-Palaniswami wants a mask for user input when `editable` prop is `false`. Something like [text-mask](https://github.com/text-mask/text-mask)

**Comment by mengxiong10** [comment]
v3.1.x. 
FYI: https://codesandbox.io/s/masking-for-datepicker-input-36mh8?fontsize=14&hidenavigation=1&theme=dark

**Comment by lokkomokko** [comment]
@mengxiong10 this doesnt work now, why?

slot - input. no way to edit it
v3.1.1
